dashpay/platform

packages/dashmate/configs/system/index.js
packages/dashmate/configs/system/mainnet.js
packages/dashmate/src/constants.js
packages/dashmate/src/listr/tasks/setup/setupRegularPresetTaskFactory.js
packages/dashmate/templates/core/dash.conf.dot

Masternode owners have expressed interest in testing dashmate on mainnet.
- Add mainnet config with platform disabled
- Disable tenderdash init on mainnet
- Tested locally
- Ongoing testnet on VPS
None

feat: enable mainnet for dashmate

---

.github/semantic.yml
CODEOWNERS

Define scopes and types for sematic pull requests check
- Added semantic pull requests configuration file
None
None

build: setup semantic pull requests

---

packages/js-dash-sdk/src/SDK/Client/Platform/methods/names/register.ts

fix(sdk): dpp hash function import

---

packages/js-grpc-common/.mocharc.yml
packages/js-grpc-common/test/mocha.opts

Mocha bootstrap not working due to updated version of mocha
Updated mocha config to the latest standard
Run tests 

test(dpp): grpc common bootstrap not working

---

packages/wallet-lib/src/test/mocks/TransportMock.js

Fatal error during unit tests
Fixed SDK tests
with tests
No

fix(sdk): this is undefined during unit tests

---

packages/dashmate/src/commands/group/reset.js
packages/dashmate/src/commands/group/restart.js
packages/dashmate/src/commands/group/start.js
packages/dashmate/src/commands/group/stop.js
packages/dashmate/src/commands/reset.js
packages/dashmate/src/commands/restart.js
packages/dashmate/src/commands/setup.js
packages/dashmate/src/commands/start.js
packages/dashmate/src/commands/stop.js
packages/dashmate/src/commands/update.js
packages/dashmate/src/docker/DockerCompose.js
packages/dashmate/src/listr/tasks/buildServicesTaskFactory.js

It's complicated to debug the services build process in dashmate since it doesn't provide any output for developer.
- Output docker build output on verbose mode
None

feat(dashmate): provide docker build logs for verbose mode

---

packages/js-dapi-client/test/integration/SMLProvider/SimplifiedMasternodeListProvider.spec.js

Error in SML provider test
Made call interval higher than the update interval, so mock gets called a proper amount of times without race conditions
Run the tests multiple times
None

fix(dapi-client): expect 100 but got 122 in SML provider test

---

.github/workflows/all-packages.yml
.github/workflows/release.yml
package-lock.json
package.json

Packages should use the same version of dependencies
- Check mismatch versions in CI
With CI
None

ci: check mismatch dependencies

---

packages/js-dpp/test/integration/stateTransition/AbstractStateTransitionIdentitySigned.spec.js
packages/js-dpp/test/integration/stateTransition/StateTransitionFacade.spec.js

Tests are failing with "invalid network" error from time to time.
privateKet.toBuffer replaced with privateKet.toWIF
Tests
No

test(dpp): invalid network

---

packages/platform-test-suite/lib/test/createClientWithFundedWallet.js

Test suite fails with error if we use SKIP_SYNC_BEFORE_HEIGHT parameter.
Fixed wallet contructor params
Tests
No

test(test-suite): `skipSynchronizationBeforeHeight` option with new wallet

---

LICENSE.md
README.md
packages/README.md

No README.md file in the repo
Add README.md for the repo and README.md for packages dir with brief packages description
-
None

docs: add README.md for the whole platform as a project

---

.github/workflows/all-packages.yml
.github/workflows/cron.yml
.github/workflows/test.yml

To ease GitHub Action runs debugging, we need to see docker container logs in case of failure
- Show Docker logs in GitHub Action workflows in case of failure
WIth CI
None

ci: show docker logs on failure

---

package.json
packages/dapi/package.json
packages/dashpay-contract/test/unit/schema.spec.js
packages/dpns-contract/test/unit/dpnsContract.spec.js
packages/feature-flags-contract/test/unit/featureFlagsContract.spec.js
packages/js-dapi-client/.mocharc.yml
packages/js-dapi-client/package.json
packages/js-dapi-client/test/integration/SMLProvider/SimplifiedMasternodeListProvider.spec.js
packages/js-dash-sdk/.mocharc.yml
packages/js-dash-sdk/karma.conf.js
packages/js-dash-sdk/package.json
packages/js-dpp/.mocharc.yml
packages/js-dpp/package.json
packages/js-drive/.mocharc.yml
packages/wallet-lib/.mocharc.yml
packages/wallet-lib/package.json
packages/wallet-lib/src/types/Wallet/Wallet.spec.js

Some tests are failing randomly due to timeouts
- Add additional timeout settings to different packages
Running locally many times
None

test: adjust timeouts

---

packages/js-dash-sdk/docs/README.md
packages/js-dash-sdk/docs/_sidebar.md
packages/js-dash-sdk/docs/examples/pay-to-another-address.md
packages/js-dash-sdk/docs/examples/publishing-a-new-contract.md
packages/js-dash-sdk/docs/examples/receive-money-and-check-balance.md
packages/js-dash-sdk/docs/getting-started/core-concepts.md
packages/js-dash-sdk/docs/getting-started/dash-platform-applications.md
packages/js-dash-sdk/docs/getting-started/quickstart.md
packages/js-dash-sdk/docs/platform/contracts/about-contracts.md
packages/js-dash-sdk/docs/platform/contracts/broadcast.md
packages/js-dash-sdk/docs/platform/contracts/create.md
packages/js-dash-sdk/docs/platform/documents/broadcast.md
packages/js-dash-sdk/docs/platform/documents/create.md
packages/js-dash-sdk/docs/platform/identities/about-identity.md
packages/js-dash-sdk/docs/platform/identities/register.md
packages/js-dash-sdk/docs/platform/identities/topUp.md
packages/js-dash-sdk/docs/platform/names/register.md
packages/js-dpp/docs/usage/DashPlatformProtocol.md
packages/js-dpp/docs/usage/dataContract.md
packages/js-dpp/docs/usage/document.md
packages/js-dpp/docs/usage/identity.md
packages/wallet-lib/docs/account/Account.md
packages/wallet-lib/docs/account/broadcastTransaction.md
packages/wallet-lib/docs/account/createTransaction.md
packages/wallet-lib/docs/getting-started/core-concepts.md
packages/wallet-lib/docs/getting-started/quickstart.md
packages/wallet-lib/docs/identities/Identities.md
packages/wallet-lib/docs/usage/coinSelection.md
packages/wallet-lib/docs/wallet/createAccount.md
packages/wallet-lib/docs/wallet/getAccount.md

I discovered a number of linking issues in our markdown files that broke navigation.
Fixed the links.
Clicked links
N/A

docs: markdown link fixes

---

.github/workflows/release.yml

DAPI and Test Suite docker build actions have incorrect tag outputs set.
- Set correct docker tag outputs to docker build actions
None
None

ci: set correct docker tag outputs in release workflow

---

package-lock.json
packages/dapi/package.json
packages/dashmate/package.json
packages/js-dapi-client/package.json
packages/js-dash-sdk/package.json
packages/js-dpp/package.json
packages/js-drive/package.json
packages/platform-test-suite/package.json
packages/wallet-lib/package.json

New instant lock is not compatible with Core 0.17
dashcore-lib updated to 0.19.28
With tests
No

fix: new instant lock is not compatible with DashCore 0.17

---

.github/workflows/release.yml

Test suite docker build is using DAPI's dockerfile in release workflow
- Use tests suite dockerfile
None
None

ci: use correct Dockerfile in test suite release

---

packages/dashmate/src/commands/group/reset.js
packages/dashmate/src/listr/tasks/setup/local/initializePlatformTaskFactory.js
packages/dashmate/src/listr/tasks/stopNodeTaskFactory.js
scripts/configure_dashmate.sh
scripts/configure_dotenv.sh
scripts/configure_test_suite.sh
scripts/setup_local_network.sh

There are RPC errors when stopping node that is not running.
- Check node is running before stop and show error if not running
- Remove unnecessary stop from `configure_test_suite.sh` script
- Use yarn to run dashmate in scripts
- Use `stopNodeTask` everywhere
- Exit from scripts on error
Manually
None

fix(dashmate): RPC error on stopping node

---

packages/wallet-lib/webpack.config.js

Fixes an error running wallet-lib in the browser
Adds buffer and process to the webpack config
Build of the wallet-lib

fix(wallet-lib): "Failure: Type not convertible to Uint8Array"

---

packages/wallet-lib/tests/integration/plugins/Workers/TransactionSyncStreamWorker.spec.js

test(wallet-lib): enable skipped test after the fix for grpc-js lib

---

packages/dashpay-contract/schema/dashpay.schema.json
packages/dpns-contract/schema/dpns-contract-documents.json
packages/feature-flags-contract/schema/feature-flags-documents.json
packages/js-dash-sdk/examples/schema.json
packages/js-dash-sdk/tests/fixtures/contracts.json
packages/js-dash-sdk/tests/fixtures/dp1.schema.json
packages/js-dash-sdk/tests/fixtures/ratePlatform.schema.json
packages/js-dpp/lib/dataContract/validation/validateDataContractFactory.js
packages/js-dpp/lib/errors/consensus/basic/dataContract/DuplicateIndexNameError.js
packages/js-dpp/lib/errors/consensus/codes.js
packages/js-dpp/lib/test/fixtures/getDataContractFixture.js
packages/js-dpp/schema/dataContract/dataContractMeta.json
packages/js-dpp/test/integration/dataContract/validation/validateDataContractFactory.spec.js
packages/js-dpp/test/unit/document/stateTransition/DocumetsBatchTransition/validation/basic/findDuplicatesByIndices.spec.js
packages/js-drive/test/unit/document/query/getIndexedFieldsFromDocumentSchema.spec.js
packages/platform-test-suite/test/e2e/contacts.spec.js
packages/platform-test-suite/test/functional/platform/DataContract.spec.js

Adding a required `name` field to index definition in order to have a unique key for the index tree in GroveDB.
- added `name` property to data contract schema
- `name` uniqueness validation
Unit tests.
- all indices should have `name` property from now on

feat!: add required `name` property to index definition

---

package.json

test:drive command in package.json is broken
Fixed test:drive command in package.json
Manual
No

chore: fix `test:drive` script

---

scripts/configure_test_suite.sh

Configure test suite script must exit with error if the were errors during setup
Exit with error if some env variables cannot be set during setup
Manual
No

chore: exit if some env variables are empty during setup

---

scripts/release/release.sh

Fixed release script
Manual
No

build: fix bash syntax issue in release script

---

.github/workflows/release.yml

Publish NPM packages erroring with "No authentication configured for request"
- Configure NPM auth token
None
None

ci: configure NPM auth token

---

scripts/release/release.sh

Release PR contains previous version instead of the new one
Fixed release script
Manual
No

chore: fix wrong version in PR title

---

.pnp.cjs
packages/js-drive/package.json
packages/platform-test-suite/package.json
yarn.lock

Pre-build binary merk darwin x64  was missed
Updated node-merk dependency
Tests
No

chore: missed merk darwin x64 pre-build binary

---

CHANGELOG.md
package.json
packages/dapi-grpc/package.json
packages/dapi/package.json
packages/dashmate/package.json
packages/dashpay-contract/package.json
packages/dpns-contract/package.json
packages/feature-flags-contract/package.json
packages/js-dapi-client/package.json
packages/js-dash-sdk/package.json
packages/js-dpp/package.json
packages/js-drive/package.json
packages/js-grpc-common/package.json
packages/platform-test-suite/package.json
packages/wallet-lib/package.json

chore(release): update changelog and bump version to v0.22.0-dev.3

---

.github/workflows/release.yml
.yarnrc.yml

NPM release tasks doesn't work anymore:
```
Not found
193
➤ YN0000: ➤ YN0035:   Response Code: 404 (Not Found)
194
➤ YN0000: ➤ YN0035:   Request Method: PUT
195
➤ YN0000: ➤ YN0035:   Request URL: https://registry.yarnpkg.com/@dashevo%2fdapi-client
```
- Set NPM publish registry to yarnrc
None
None

chore: configure NPM publish registry

---

.github/workflows/release.yml

#149 didn't help to authorize in NPM registry. Probably we should add the token to `.npmrc` too
- Set the token to `setup-node` action
None
None

ci: set NPM token to `setup-node` action

---

CHANGELOG.md
package.json
packages/dapi-grpc/package.json
packages/dapi/package.json
packages/dashmate/package.json
packages/dashpay-contract/package.json
packages/dpns-contract/package.json
packages/feature-flags-contract/package.json
packages/js-dapi-client/package.json
packages/js-dash-sdk/package.json
packages/js-dpp/package.json
packages/js-drive/package.json
packages/js-grpc-common/package.json
packages/platform-test-suite/package.json
packages/wallet-lib/package.json

chore(release): update changelog and bump version to 0.22.0-dev.4

---

.github/workflows/release.yml

#151, #150 need to be reverted since the problem was with token itself (expired?)
- Revert #151, #150
None
None

revert: passing NPM tokens all around

---

packages/js-dpp/lib/dataContract/validation/validateDataContractFactory.js
packages/js-dpp/lib/test/fixtures/getDataContractFixture.js
packages/js-dpp/package.json
packages/js-dpp/test/integration/dataContract/validation/validateDataContractFactory.spec.js

Indexed properties must have a size constraint
- Introduced constraints for indexed strings
- Introduced constraints for indexed byte arrays
- Introduced constraints for indexed string array items
With integration test
Indexed properties now require size constraints

feat(dpp)!: size constraints for indexed properties

---

CHANGELOG.md
package.json
packages/dapi-grpc/package.json
packages/dapi/package.json
packages/dashmate/package.json
packages/dashpay-contract/package.json
packages/dpns-contract/package.json
packages/feature-flags-contract/package.json
packages/js-dapi-client/package.json
packages/js-dash-sdk/package.json
packages/js-dpp/package.json
packages/js-drive/package.json
packages/js-grpc-common/package.json
packages/masternode-reward-shares-contract/package.json
packages/platform-test-suite/package.json
packages/wallet-lib/package.json

chore(release): update changelog and bump version to 0.22.0-dev.5

---

packages/dapi/package.json
packages/dapi/scripts/core-streams.js
packages/dashmate/docker-compose.platform.yml

refactor(dapi): rename `tx-filter-stream.js` to `core-streams.js`

---

docs/README.md

A basically empty `docs` folder can be confusing for someone looking for information.
Added a [README](https://github.com/dashevo/platform/blob/docs-readme/docs/README.md) to explain the function of the folder.
Tested locally
N/A

docs: add readme to docs folder

---

packages/wallet-lib/tests/functional/wallet.js

Fixing hanging functional test case
Check whether the wallet already has a relevant transaction. If so, do not wait for BLOCK_HEADER event.
`yarn ultra -r --filter "packages/wallet-lib" test`

test(wallet-lib): fix hanging functional test

---

packages/dashmate/configs/system/base.js
packages/dashmate/templates/platform/drive/tenderdash/config.toml.dot

Need to update Tenderdash to 0.7.0-dev
Updated tenderdash image
Introduced new `create_proof_block_range` value in tenderdash config
With tests
No

chore(dashmate): update tenderdash to 0.7.0-dev

---

CHANGELOG.md
package.json
packages/dapi-grpc/package.json
packages/dapi/package.json
packages/dashmate/package.json
packages/dashpay-contract/package.json
packages/dpns-contract/package.json
packages/feature-flags-contract/package.json
packages/js-dapi-client/package.json
packages/js-dash-sdk/package.json
packages/js-dpp/package.json
packages/js-drive/package.json
packages/js-grpc-common/package.json
packages/platform-test-suite/package.json
packages/wallet-lib/package.json

chore(release): update changelog and bump version to 0.21.7

---

packages/platform-test-suite/package.json

Abort the test suite on very first error test case. Previously, some failed test cases were waiting other tasks to finishes that were hanging on our CI
Added `mocha -b` flag that abort on first error is caught
In CI, together with @markin-io 
No breaking changes

test: abort on first error in platform test suite

---

packages/js-dash-sdk/src/SDK/Client/Platform/methods/contracts/update.ts

If we update contract which was already cached as an application  in SDK, validation fails due to comparing versions of the same contract instance.
- Clone contract before incrementing version and update cache after contract is updated
With CI
None

fix(sdk): can't update cached data contract

---

packages/wallet-lib/src/types/Account/methods/getTransactionHistory.js

fixes #205 
The unconfirmed tx timestamp was changed from `-1` to `9999999999`.
Green CI tests
None

fix: uncofirmed tx sort as oldest

---

packages/wallet-lib/src/utils/filterTransactions.js
packages/wallet-lib/src/utils/filterTransactions.spec.js

Fixes a bug with `getTransactionHistory` function not returning a complete set of transactions
Fixed lookup inside internal addresses
Improved relevant unit test

fix(wallet-lib): get transaction history missing txs

---

CHANGELOG.md
package.json
packages/dapi-grpc/package.json
packages/dapi/package.json
packages/dashmate/package.json
packages/dashpay-contract/package.json
packages/dpns-contract/package.json
packages/feature-flags-contract/package.json
packages/js-dapi-client/package.json
packages/js-dash-sdk/package.json
packages/js-dpp/package.json
packages/js-drive/package.json
packages/js-grpc-common/package.json
packages/platform-test-suite/package.json
packages/wallet-lib/package.json

chore(release): update changelog and bump version to 0.21.8

---

packages/js-drive/lib/identity/masternode/synchronizeMasternodeIdentitiesFactory.js
packages/js-drive/test/integration/core/updateSimplifiedMasternodeListFactory.spec.js

Drive crashes with fatal error `Unable  to reconstruct SML at height 4061`
Fixed bug in synchronizeMasternodeIdentities
With tests
No

fix(drive): unable to reconstruct SML

---

.pnp.cjs
packages/js-drive/lib/document/DocumentRepository.js
packages/js-drive/lib/document/query/errors/StartDocumentNotFoundError.js
packages/js-drive/package.json
packages/js-drive/test/integration/document/DocumentRepository.spec.js
yarn.lock

Incorrectly constructed document queries are fatal Drive runtime and lead to crashes.
- Handle invalid query error type from RS Drive and respond with InvalidQueryError to user.
With integration test
None

fix(drive): invalid query errors are fatal

---

packages/wallet-lib/src/types/Account/Account.d.ts

fixes #202
Added missing `getTransactionHistory()` method to `Account` type.
Ran tests
Built platform and linked build to a project, type definition now works.
none

fix: `TransactionHistory` type is not defined

---

packages/dashmate/configs/system/base.js

Update Core to the latest beta version
- Updated Core docker image to 0.18.0.0-beta4
None
None

chore(dashmate): update Core to 0.18.0.0-beta4

---

packages/js-dash-sdk/src/SDK/Client/Client.spec.ts
packages/js-dash-sdk/src/SDK/Client/Platform/methods/identities/internal/createIdentityCreateTransition.ts
packages/js-dash-sdk/src/SDK/Client/Platform/methods/identities/internal/createIdnetityTopUpTransition.ts
packages/js-dpp/lib/bls/blsPrivateKeyFactory.js
packages/js-dpp/lib/bls/blsPublicKeyFactory.js
packages/js-dpp/lib/stateTransition/AbstractStateTransition.js
packages/js-dpp/lib/stateTransition/AbstractStateTransitionIdentitySigned.js
packages/js-dpp/lib/stateTransition/validation/validateStateTransitionIdentitySignatureFactory.js
packages/js-dpp/test/integration/identity/stateTransition/IdentityCreateTransition/validation/basic/validateIdentityCreateTransitionBasicFactory.spec.js
packages/js-dpp/test/integration/identity/stateTransition/IdentityTopUpTransition/validation/basic/validateIdentityTopUpTransitionBasicFactory.spec.js
packages/js-dpp/test/integration/stateTransition/AbstractStateTransitionIdentitySigned.spec.js
packages/js-dpp/test/integration/stateTransition/StateTransitionFacade.spec.js
packages/js-dpp/test/integration/stateTransition/calculateStateTransitionFee.spec.js
packages/js-dpp/test/unit/identity/stateTransition/IdentityCreateTransition/validation/state/validateIdentityCreateTransitionStateFactory.spec.js
packages/js-dpp/test/unit/stateTransition/validation/validateStateTransitionBasicFactory.spec.js
packages/platform-test-suite/test/functional/platform/Identity.spec.js

Allow using BLS key to sign state transitions
Added BLS signing support to DPP
With
No

feat(dpp): allow using BLS key to sign state transitions

---

packages/js-dash-sdk/docs/platform/identities/topUp.md

docs(sdk): update topup identity doc

---

CHANGELOG.md
package.json
packages/dapi-grpc/package.json
packages/dapi/package.json
packages/dashmate/package.json
packages/dashpay-contract/package.json
packages/dpns-contract/package.json
packages/feature-flags-contract/package.json
packages/js-dapi-client/package.json
packages/js-dash-sdk/package.json
packages/js-dpp/package.json
packages/js-drive/package.json
packages/js-grpc-common/package.json
packages/masternode-reward-shares-contract/package.json
packages/platform-test-suite/package.json
packages/wallet-lib/package.json

chore(release): update changelog and bump version to 0.22.0-dev.8

---

CHANGELOG.md
package.json
packages/dapi-grpc/package.json
packages/dapi/package.json
packages/dashmate/package.json
packages/dashpay-contract/package.json
packages/dpns-contract/package.json
packages/feature-flags-contract/package.json
packages/js-dapi-client/package.json
packages/js-dash-sdk/package.json
packages/js-dpp/package.json
packages/js-drive/package.json
packages/js-grpc-common/package.json
packages/masternode-reward-shares-contract/package.json
packages/platform-test-suite/package.json
packages/wallet-lib/package.json

chore(release): update changelog and bump version to 0.22.0-dev.9

---

CHANGELOG.md
package.json
packages/dapi-grpc/package.json
packages/dapi/package.json
packages/dashmate/package.json
packages/dashpay-contract/package.json
packages/dpns-contract/package.json
packages/feature-flags-contract/package.json
packages/js-dapi-client/package.json
packages/js-dash-sdk/package.json
packages/js-dpp/package.json
packages/js-drive/package.json
packages/js-grpc-common/package.json
packages/masternode-reward-shares-contract/package.json
packages/platform-test-suite/package.json
packages/wallet-lib/package.json

chore(release): update changelog and bump version to 0.22.0-dev.10

---

CHANGELOG.md
package.json
packages/dapi-grpc/package.json
packages/dapi/package.json
packages/dashmate/package.json
packages/dashpay-contract/package.json
packages/dpns-contract/package.json
packages/feature-flags-contract/package.json
packages/js-dapi-client/package.json
packages/js-dash-sdk/package.json
packages/js-dpp/package.json
packages/js-drive/package.json
packages/js-grpc-common/package.json
packages/masternode-reward-shares-contract/package.json
packages/platform-test-suite/package.json
packages/wallet-lib/package.json

chore(release): update changelog and bump version to 0.22.0-dev.11

---

packages/js-drive/lib/identity/masternode/synchronizeMasternodeIdentitiesFactory.js
packages/js-drive/test/unit/identity/masternode/synchronizeMasternodeIdentitiesFactory.spec.js

```
[2022-03-08 14:34:56.222 +0000] FATAL (36 on f15ba21a0cf2): Documents have mixed owner ids
drive_abci_1             |     driveVersion: "0.22.0-dev.11"
drive_abci_1             |     err: {
drive_abci_1             |       "type": "MismatchOwnerIdsError",
drive_abci_1             |       "message": "Documents have mixed owner ids",
drive_abci_1             |       "stack":
drive_abci_1             |           MismatchOwnerIdsError: Documents have mixed owner ids
drive_abci_1             |               at DocumentFactory.createStateTransition (/platform/packages/js-dpp/lib/document/DocumentFactory.js:231:13)
drive_abci_1             |               at DocumentFacade.createStateTransition (/platform/packages/js-dpp/lib/document/DocumentFacade.js:112:25)
drive_abci_1             | …
```

fix(drive): documents have mixed owner ids

---

CHANGELOG.md
package.json
packages/dapi-grpc/package.json
packages/dapi/package.json
packages/dashmate/package.json
packages/dashpay-contract/package.json
packages/dpns-contract/package.json
packages/feature-flags-contract/package.json
packages/js-dapi-client/package.json
packages/js-dash-sdk/package.json
packages/js-dpp/package.json
packages/js-drive/package.json
packages/js-grpc-common/package.json
packages/masternode-reward-shares-contract/package.json
packages/platform-test-suite/package.json
packages/wallet-lib/package.json

chore(release): update changelog and bump version to 0.22.0-dev.12

---

packages/js-drive/lib/validator/ValidatorSet.js

```
[2022-03-09 03:02:15.068 +0000] FATAL (36 on ff8ed933109d): Cannot read properties of undefined (reading 'getIp')
driveVersion: "0.22.0-dev.12"
err: {
"type": "TypeError",
"message": "Cannot read properties of undefined (reading 'getIp')",
"stack":
TypeError: Cannot read properties of undefined (reading 'getIp')
at /platform/packages/js-drive/lib/validator/ValidatorSet.js:151:65
at Array.map (<anonymous>)
at ValidatorSet.switchToRandomQuorum (/platform/packages/js-drive/lib/validator/ValidatorSet.js:147:8)
at async ValidatorSet.initialize (/platform/packages/js-drive/lib/validator/ValidatorSet.js:44:5)
at async Object.initChainHandler [as initChain] (/platform/packages/js-drive/lib/abci/handlers/initChainHandlerFactory.js:74:5)
at async Connection.handleRequest …
```

fix: cannot read properties of undefined (reading 'getIp')

---

CHANGELOG.md
package.json
packages/dapi-grpc/package.json
packages/dapi/package.json
packages/dashmate/package.json
packages/dashpay-contract/package.json
packages/dpns-contract/package.json
packages/feature-flags-contract/package.json
packages/js-dapi-client/package.json
packages/js-dash-sdk/package.json
packages/js-dpp/package.json
packages/js-drive/package.json
packages/js-grpc-common/package.json
packages/masternode-reward-shares-contract/package.json
packages/platform-test-suite/package.json
packages/wallet-lib/package.json

chore(release): update changelog and bump version to 0.22.0-dev.13

---

CHANGELOG.md
package.json
packages/dapi-grpc/package.json
packages/dapi/package.json
packages/dashmate/package.json
packages/dashpay-contract/package.json
packages/dpns-contract/package.json
packages/feature-flags-contract/package.json
packages/js-dapi-client/package.json
packages/js-dash-sdk/package.json
packages/js-dpp/package.json
packages/js-drive/package.json
packages/js-grpc-common/package.json
packages/masternode-reward-shares-contract/package.json
packages/platform-test-suite/package.json
packages/wallet-lib/package.json

chore(release): update changelog and bump version to 0.22.0-dev.14

---

packages/js-dash-sdk/src/SDK/Client/Platform/methods/identities/internal/createAssetLockProof.ts
packages/js-dpp/lib/identity/stateTransition/assetLockProof/instant/validateInstantAssetLockProofStructureFactory.js
packages/js-dpp/test/integration/identity/stateTransition/assetLockProof/instant/validateInstantAssetLockProofStructureFactory.spec.js
packages/platform-test-suite/test/functional/platform/Identity.spec.js

```
InstantLock waiting period for transaction ce5685d67f64267c4b76d0105da4780b08581fea13f7ec94e2cf6fd648ad41b1 timed out
```
If a block appears before IS lock, it won't be sent. It's a temporary solution.
- Sent fake instant lock in case of timeout
- Ignored instant lock signature
Not tested at all
None

fix: InstantLock waiting period for transaction..

---

CHANGELOG.md
package.json
packages/dapi-grpc/package.json
packages/dapi/package.json
packages/dashmate/package.json
packages/dashpay-contract/package.json
packages/dpns-contract/package.json
packages/feature-flags-contract/package.json
packages/js-dapi-client/package.json
packages/js-dash-sdk/package.json
packages/js-dpp/package.json
packages/js-drive/package.json
packages/js-grpc-common/package.json
packages/masternode-reward-shares-contract/package.json
packages/platform-test-suite/package.json
packages/wallet-lib/package.json

chore(release): update changelog and bump version to 0.22.0-dev.15

---

packages/js-drive/lib/dpp/DriveStateRepository.js
packages/js-drive/test/unit/dpp/DriveStateRepository.spec.js

`Cannot destructure property 'coreChainLockedHeight' of 'header' as it is null.`
Fixed verifyInstantLock method
With tests
No

fix(drive): internal error on verify instant lock

---

.pnp.cjs
packages/js-drive/lib/dataContract/DataContractStoreRepository.js
packages/js-drive/lib/document/DocumentRepository.js
packages/js-drive/package.json
packages/js-drive/test/integration/dataContract/DataContractStoreRepository.spec.js
packages/js-drive/test/unit/document/DocumentRepository.spec.js
packages/platform-test-suite/test/functional/platform/Document.spec.js
yarn.lock

- https://github.com/dashevo/rs-drive/pull/90
- https://github.com/dashevo/rs-drive/pull/88
- https://github.com/dashevo/rs-drive/issues/85
- https://github.com/dashevo/rs-drive/pull/93
- Updates RS Drive
With tests
Previously created data might not be compatible 

fix(drive)!: document query and delete issues

---

CHANGELOG.md
package.json
packages/dapi-grpc/package.json
packages/dapi/package.json
packages/dashmate/package.json
packages/dashpay-contract/package.json
packages/dpns-contract/package.json
packages/feature-flags-contract/package.json
packages/js-dapi-client/package.json
packages/js-dash-sdk/package.json
packages/js-dpp/package.json
packages/js-drive/package.json
packages/js-grpc-common/package.json
packages/masternode-reward-shares-contract/package.json
packages/platform-test-suite/package.json
packages/wallet-lib/package.json

chore(release): update changelog and bump version to 0.22.0-dev.16

---

CHANGELOG.md
package.json
packages/dapi-grpc/package.json
packages/dapi/package.json
packages/dashmate/package.json
packages/dashpay-contract/package.json
packages/dpns-contract/package.json
packages/feature-flags-contract/package.json
packages/js-dapi-client/package.json
packages/js-dash-sdk/package.json
packages/js-dpp/package.json
packages/js-drive/package.json
packages/js-grpc-common/package.json
packages/masternode-reward-shares-contract/package.json
packages/platform-test-suite/package.json
packages/wallet-lib/package.json

chore(release): update changelog and bump version to 0.22.0

---

packages/dashmate/src/listr/tasks/setup/setupLocalPresetTaskFactory.js

Now, when I run `dashmate setup local --verbose`, I get this error:
```
[STARTED] Create local_1 config
[FAILED] config/core/miner must have required property 'interval'
[FAILED] config/core/miner must have required property 'interval'
[FAILED] config/core/miner must have required property 'interval'
```
- Check for correct default flag value
None

fix(dashmate): config/core/miner must have required property 'interval'

---

CHANGELOG.md
package.json
packages/dapi-grpc/package.json
packages/dapi/package.json
packages/dashmate/package.json
packages/dashpay-contract/package.json
packages/dpns-contract/package.json
packages/feature-flags-contract/package.json
packages/js-dapi-client/package.json
packages/js-dash-sdk/package.json
packages/js-dpp/package.json
packages/js-drive/package.json
packages/js-grpc-common/package.json
packages/masternode-reward-shares-contract/package.json
packages/platform-test-suite/package.json
packages/wallet-lib/package.json

chore(release): update changelog and bump version to 0.22.1

---

packages/js-dpp/lib/dataTrigger/rewardShareDataTriggers/createMasternodeRewardSharesDataTrigger.js
packages/js-dpp/test/unit/dataTrigger/rewardShareDataTriggers/createMasternodeRewardSharesDataTrigger.spec.js
packages/js-drive/lib/identity/masternode/handleNewMasternodeFactory.js
packages/js-drive/lib/identity/masternode/handleUpdatedPubKeyOperatorFactory.js
packages/js-drive/lib/identity/masternode/synchronizeMasternodeIdentitiesFactory.js
packages/js-drive/test/integration/identity/masternode/synchronizeMasternodeIdentitiesFactory.spec.js
packages/platform-test-suite/test/e2e/masternodeRewardShares.spec.js
packages/platform-test-suite/test/functional/platform/Identity.spec.js

don't need to hash proRegTx for masternode identifier
removed proRegTx hashing for masternode identifier
With tests
Will not work with previously created masternode identities

fix!: do not hash proRegTx for masternode identifier

---

packages/js-dpp/test/integration/identity/validation/validateIdentityFactory.spec.js

Identity validation tests having some absolutely identical tests
Fix the test to match its description
None

test(dpp): double test in identity validation

---

.pnp.cjs
packages/bench-suite/README.md
packages/bench-suite/benchmarks/basicValidation.js
packages/bench-suite/benchmarks/documents/100string.js
packages/bench-suite/benchmarks/documents/dpns.js
packages/bench-suite/benchmarks/documents/indices.js
packages/bench-suite/benchmarks/index.js
packages/bench-suite/lib/Runner.js
packages/bench-suite/lib/benchmarks/AbstractBenchmark.js
packages/bench-suite/lib/benchmarks/DocumentsBenchmark.js
packages/bench-suite/lib/benchmarks/FunctionBenchmark.js
packages/bench-suite/lib/benchmarks/index.js
packages/bench-suite/lib/benchmarks/types.js
packages/bench-suite/lib/setupContext.js
packages/bench-suite/lib/util/createIndices.js
packages/bench-suite/package.json
yarn.lock

To proceed computational fee investigation bench suite required additional functionality. Also, some things didn't work properly.
- Fixed documents benchmark
- Connect client only if benchmarks require it
- Changed "mean" to "median"
- Introduced function benchmark
None

feat(bench-suite): function benchmark and other improvements

---

packages/wallet-lib/src/types/Storage/methods/configure.js
packages/wallet-lib/src/types/Storage/methods/rehydrateState.js

Optimize verison schema version check comparement
Fixed if condition
CI
-

fix(wallet-lib): optimize storage version check

---

CHANGELOG.md
package.json
packages/dapi-grpc/package.json
packages/dapi/package.json
packages/dashmate/package.json
packages/dashpay-contract/package.json
packages/dpns-contract/package.json
packages/feature-flags-contract/package.json
packages/js-dapi-client/package.json
packages/js-dash-sdk/package.json
packages/js-dpp/package.json
packages/js-drive/package.json
packages/js-grpc-common/package.json
packages/masternode-reward-shares-contract/package.json
packages/platform-test-suite/package.json
packages/wallet-lib/package.json

chore(release): update changelog and bump version to 0.22.2

---

packages/js-dpp/lib/identity/IdentityPublicKey.js
packages/js-dpp/schema/identity/publicKey.json
packages/js-dpp/test/integration/identity/validation/validatePublicKeysFactory.spec.js
packages/js-dpp/test/unit/identity/IdentityPublicKey.spec.js
packages/js-dpp/test/unit/stateTransition/validation/validateStateTransitionIdentitySignatureFactory.spec.js

Introduced new Identity Public Key type BIP13_SCRIPT_HASH (3) (without ST singing and verification)
Unit tests
No

feat(dpp): BIP13_SCRIPT_HASH identity public key type

---

packages/js-dpp/lib/identity/IdentityPublicKey.js

Withdrawal purpose allowed security level must be only Critical
Changed withdrawal purpose allowed security level to Critical
Tests
No

fix(dpp): change allowed security level for withdrawal purpose to critical

---

packages/dashmate/configs/migrations.js

Migrations for versions 0.22.0 an 0.22.2 are broken
Fixed migrations for versions 0.22.0 and 0.22.2
By running migrations
No

fix(dashmate): broken migrations

---

CHANGELOG.md
package.json
packages/dapi-grpc/package.json
packages/dapi/package.json
packages/dashmate/package.json
packages/dashpay-contract/package.json
packages/dpns-contract/package.json
packages/feature-flags-contract/package.json
packages/js-dapi-client/package.json
packages/js-dash-sdk/package.json
packages/js-dpp/package.json
packages/js-drive/package.json
packages/js-grpc-common/package.json
packages/masternode-reward-shares-contract/package.json
packages/platform-test-suite/package.json
packages/wallet-lib/package.json

- CI
- running platform-test-suite against the testnet
None

chore(release): update changelog and bump version to 0.22.3

---

CHANGELOG.md
package.json
packages/dapi-grpc/package.json
packages/dapi/package.json
packages/dashmate/package.json
packages/dashpay-contract/package.json
packages/dpns-contract/package.json
packages/feature-flags-contract/package.json
packages/js-dapi-client/package.json
packages/js-dash-sdk/package.json
packages/js-dpp/package.json
packages/js-drive/package.json
packages/js-grpc-common/package.json
packages/masternode-reward-shares-contract/package.json
packages/platform-test-suite/package.json
packages/wallet-lib/package.json

chore(release): update changelog and bump version to 0.22.5

---

CHANGELOG.md
package.json
packages/dapi-grpc/package.json
packages/dapi/package.json
packages/dashmate/package.json
packages/dashpay-contract/package.json
packages/dpns-contract/package.json
packages/feature-flags-contract/package.json
packages/js-dapi-client/package.json
packages/js-dash-sdk/package.json
packages/js-dpp/package.json
packages/js-drive/package.json
packages/js-grpc-common/package.json
packages/masternode-reward-shares-contract/package.json
packages/platform-test-suite/package.json
packages/wallet-lib/package.json

chore(release): update changelog and bump version to 0.22.6

---

CHANGELOG.md
package.json
packages/dapi-grpc/package.json
packages/dapi/package.json
packages/dashmate/package.json
packages/dashpay-contract/package.json
packages/dpns-contract/package.json
packages/feature-flags-contract/package.json
packages/js-dapi-client/package.json
packages/js-dash-sdk/package.json
packages/js-dpp/package.json
packages/js-drive/package.json
packages/js-grpc-common/package.json
packages/masternode-reward-shares-contract/package.json
packages/platform-test-suite/package.json
packages/wallet-lib/package.json

chore(release): update changelog and bump version to 0.22.7

---

packages/dashmate/configs/system/base.js

Dashmate still uses dev versions of `Drive` and `DAPI`
Changed drive and dapi versions in dashmate 
Via CI
No

fix(dashmate): switch `drive` and `dapi` to stable versions

---

CHANGELOG.md
package.json
packages/dapi-grpc/package.json
packages/dapi/package.json
packages/dashmate/package.json
packages/dashpay-contract/package.json
packages/dpns-contract/package.json
packages/feature-flags-contract/package.json
packages/js-dapi-client/package.json
packages/js-dash-sdk/package.json
packages/js-dpp/package.json
packages/js-drive/package.json
packages/js-grpc-common/package.json
packages/masternode-reward-shares-contract/package.json
packages/platform-test-suite/package.json
packages/wallet-lib/package.json

chore(release): update changelog and bump version to 0.22.8

---

CHANGELOG.md
package.json
packages/dapi-grpc/package.json
packages/dapi/package.json
packages/dashmate/package.json
packages/dashpay-contract/package.json
packages/dpns-contract/package.json
packages/feature-flags-contract/package.json
packages/js-dapi-client/package.json
packages/js-dash-sdk/package.json
packages/js-dpp/package.json
packages/js-drive/package.json
packages/js-grpc-common/package.json
packages/masternode-reward-shares-contract/package.json
packages/platform-test-suite/package.json
packages/wallet-lib/package.json

chore(release): update changelog and bump version to 0.22.9

---

.github/workflows/release.yml

Devs need to be able to build custom tagged docker images without pushing a release
- Add `workflow_dispatch` action trigger
- Make NPM and Docker release run in parallel
Tested on `strophy/platform`
None

ci: dispatch trigger and parallelization

---

CHANGELOG.md
package.json
packages/dapi-grpc/package.json
packages/dapi/package.json
packages/dashmate/package.json
packages/dashpay-contract/package.json
packages/dpns-contract/package.json
packages/feature-flags-contract/package.json
packages/js-dapi-client/package.json
packages/js-dash-sdk/package.json
packages/js-dpp/package.json
packages/js-drive/package.json
packages/js-grpc-common/package.json
packages/masternode-reward-shares-contract/package.json
packages/platform-test-suite/package.json
packages/wallet-lib/package.json

chore(release): update changelog and bump version to 0.22.10

---

packages/js-drive/test/integration/fee/checkFeePrediction.spec.js

test(drive): check fee prediction

---

packages/dashmate/configs/system/base.js
packages/dashmate/configs/system/mainnet.js
packages/dashmate/configs/system/testnet.js

Dashmate does not work on testnet due to incorrect presets in the config. 
- Update image versions to what is currently deployed
- Update genesis
- Add contract pubkeys
Locally by running dashmate
None, these are fixing changes ;)

fix: incorrect image versions and variables for testnet config

---

packages/bench-suite/benchmarks/documents/100string.js
packages/bench-suite/benchmarks/documents/dpns.js
packages/bench-suite/benchmarks/documents/indices.js
packages/bench-suite/benchmarks/fees/dataContractCreate.js
packages/bench-suite/benchmarks/index.js
packages/bench-suite/lib/Runner.js
packages/bench-suite/lib/benchmarks/DocumentsBenchmark.js
packages/bench-suite/lib/benchmarks/StateTransitionsBenchmark.js
packages/bench-suite/lib/benchmarks/index.js
packages/bench-suite/lib/benchmarks/types.js
packages/bench-suite/lib/metrics/drive/createStateTransitionMatch.js
packages/bench-suite/lib/metrics/drive/printMetrics.js

To benchmark state transition execution time and fees we need a benchmark to create and broadcast different types of state transitions.
- Introduced State Transitions benchmark
- Improved config for Documents benchmark
None

feat(bench): state transition benchmark

---

packages/js-dash-sdk/src/SDK/Client/Platform/methods/identities/update.ts

identity update publicKeys can be unsigned because of the parallel signing process
Fixed identity update method
With tests
No

fix(sdk): identity update method can't sign publicKeys in some cases

---

packages/wallet-lib/src/CONSTANTS.js
packages/wallet-lib/src/types/Account/Account.js
packages/wallet-lib/src/types/Storage/methods/configure.js
packages/wallet-lib/src/types/Storage/methods/rehydrateState.js
packages/wallet-lib/src/types/Storage/methods/saveState.js
packages/wallet-lib/tests/integration/types/Wallet.spec.js

chore(wallet-lib): cherry-pick storage fix

---

CHANGELOG.md
package.json
packages/dapi-grpc/package.json
packages/dapi/package.json
packages/dashmate/package.json
packages/dashpay-contract/package.json
packages/dpns-contract/package.json
packages/feature-flags-contract/package.json
packages/js-dapi-client/package.json
packages/js-dash-sdk/package.json
packages/js-dpp/package.json
packages/js-drive/package.json
packages/js-grpc-common/package.json
packages/masternode-reward-shares-contract/package.json
packages/platform-test-suite/package.json
packages/wallet-lib/package.json

chore(release): update changelog and bump version to 0.22.12

---

packages/js-dpp/lib/dataTrigger/rewardShareDataTriggers/createMasternodeRewardSharesDataTrigger.js
packages/js-dpp/test/unit/dataTrigger/rewardShareDataTriggers/createMasternodeRewardSharesDataTrigger.spec.js
packages/js-drive/lib/identity/masternode/createRewardShareDocumentFactory.js
packages/js-drive/lib/identity/masternode/handleRemovedMasternodeFactory.js
packages/js-drive/test/integration/document/DocumentRepository.spec.js

The number of shares for masternode was limited by 16 identities
With tests
No

feat: limit the number of shares for masternode by 16

---

CHANGELOG.md
package.json
packages/dapi-grpc/package.json
packages/dapi/package.json
packages/dashmate/package.json
packages/dashpay-contract/package.json
packages/dpns-contract/package.json
packages/feature-flags-contract/package.json
packages/js-dapi-client/package.json
packages/js-dash-sdk/package.json
packages/js-dpp/package.json
packages/js-drive/package.json
packages/js-grpc-common/package.json
packages/masternode-reward-shares-contract/package.json
packages/platform-test-suite/package.json
packages/wallet-lib/package.json

chore(release): update changelog and bump version to 0.22.13

---

packages/js-dpp/test/unit/document/stateTransition/DocumetsBatchTransition/validation/basic/findDuplicatesByIndices.spec.js

findIndexDuplicates test in DPP contains invalid indices definitions
Fixed invalid indices in findIndexDuplicates test
No

test(dpp): fix invalid findIndexDuplicates test in DPP

---

packages/js-drive/lib/abci/handlers/beginBlockHandlerFactory.js

Due to untested block execution context logic in real conditions, transaction could not be rolled back 
Move transaction is started check from block context height condition to the top level
With tests
No

fix(drive): uncertain transaction rollback

---

packages/dashmate/templates/platform/drive/tenderdash/config.toml.dot

Tenderdash's config.toml must be updated to be used with the latest version
In tenderdash's config.toms `seeds` property was replaced by `bootstrap-peers`
Manually
No

fix(dashmate): replace `seeds` by `bootstrap-peers` in config.toml

---

CHANGELOG.md
package.json
packages/bench-suite/package.json
packages/dapi-grpc/package.json
packages/dapi/package.json
packages/dash-spv/package.json
packages/dashmate/package.json
packages/dashpay-contract/package.json
packages/dpns-contract/package.json
packages/feature-flags-contract/package.json
packages/js-dapi-client/package.json
packages/js-dash-sdk/package.json
packages/js-dpp/package.json
packages/js-drive/package.json
packages/js-grpc-common/package.json
packages/masternode-reward-shares-contract/package.json
packages/platform-test-suite/package.json
packages/wallet-lib/package.json

chore(release): update changelog and bump version to 0.23.0-dev.4

---

packages/js-drive/lib/createDIContainer.js
packages/js-drive/lib/identity/masternode/createVotingIdentifier.js
packages/js-drive/lib/identity/masternode/handleNewMasternodeFactory.js
packages/js-drive/lib/identity/masternode/handleUpdatedVotingAddressFactory.js
packages/js-drive/lib/identity/masternode/synchronizeMasternodeIdentitiesFactory.js
packages/js-drive/test/integration/identity/masternode/synchronizeMasternodeIdentitiesFactory.spec.js
packages/js-drive/test/unit/identity/masternode/createVotingIdentifier.spec.js
packages/js-drive/test/unit/identity/masternode/handleNewMasternodeFactory.spec.js
packages/js-drive/test/unit/identity/masternode/handleUpdatedVotingAddressFactory.spec.js
packages/platform-test-suite/test/functional/platform/Identity.spec.js

Need to implement masternode voting identities in the same way such as operator identity
Implemented masternode voting identities
With tests
No

feat: implement masternode voting identities

---

CHANGELOG.md
package.json
packages/bench-suite/package.json
packages/dapi-grpc/package.json
packages/dapi/package.json
packages/dash-spv/package.json
packages/dashmate/package.json
packages/dashpay-contract/package.json
packages/dpns-contract/package.json
packages/feature-flags-contract/package.json
packages/js-dapi-client/package.json
packages/js-dash-sdk/package.json
packages/js-dpp/package.json
packages/js-drive/package.json
packages/js-grpc-common/package.json
packages/masternode-reward-shares-contract/package.json
packages/platform-test-suite/package.json
packages/wallet-lib/package.json

chore(release): update changelog and bump version to 0.23.0-dev.5

---

CHANGELOG.md
package.json
packages/bench-suite/package.json
packages/dapi-grpc/package.json
packages/dapi/package.json
packages/dash-spv/package.json
packages/dashmate/package.json
packages/dashpay-contract/package.json
packages/dpns-contract/package.json
packages/feature-flags-contract/package.json
packages/js-dapi-client/package.json
packages/js-dash-sdk/package.json
packages/js-dpp/package.json
packages/js-drive/package.json
packages/js-grpc-common/package.json
packages/masternode-reward-shares-contract/package.json
packages/platform-test-suite/package.json
packages/wallet-lib/package.json

chore(release): update changelog and bump version to 0.23.0-dev.6

---

packages/dashmate/docker-compose.platform.yml
packages/js-dapi-client/lib/dapiAddressProvider/ListDAPIAddressProvider.js
packages/wallet-lib/src/types/Account/Account.js
packages/wallet-lib/src/types/Account/methods/broadcastTransaction.js

DAPI client requests one local single node only.
DAPI client will request a random node from the list.
With tests
No

fix: DAPI client requests one local single node only

---

packages/dashmate/configs/system/base.js
packages/dashmate/templates/platform/dapi/envoy/envoy.yaml.dot

gRPC streams disconnect every 5 seconds
- Updated Envoy to 0.22 (v0.23 doesn't work on arm)
- Added `grpc_timeout_header_max`
- Updated cors settings
- Refactored envoy config
Locally
None

fix(dashmate): gRPC stream timeout

---

packages/dashmate/src/docker/errors/DockerComposeError.js

Dashmate throws Docker undefined error from time to time
Fixed Dashmate error reporting
With tests
No

fix(dashmate): docker undefined error

---

packages/platform-test-suite/test/functional/core/broadcastTransaction.spec.js
packages/platform-test-suite/test/functional/dapi/subscribeToBlockHeadersWithChainLocksHandlerFactory.spec.js
packages/platform-test-suite/test/functional/platform/Identity.spec.js

Some tests in test suite using dapi client directly instead of using `Account#broadcastTransaction` updated in #479.
- Use `Account#broadcastTransaction`
Running tests
None

fix(test-suite): invalid transaction: missing inputs

---

CHANGELOG.md
package.json
packages/bench-suite/package.json
packages/dapi-grpc/package.json
packages/dapi/package.json
packages/dash-spv/package.json
packages/dashmate/package.json
packages/dashpay-contract/package.json
packages/dpns-contract/package.json
packages/feature-flags-contract/package.json
packages/js-dapi-client/package.json
packages/js-dash-sdk/package.json
packages/js-dpp/package.json
packages/js-drive/package.json
packages/js-grpc-common/package.json
packages/masternode-reward-shares-contract/package.json
packages/platform-test-suite/package.json
packages/wallet-lib/package.json

chore(release): update changelog and bump version to 0.23.0-dev.7

---

CHANGELOG.md
package.json
packages/bench-suite/package.json
packages/dapi-grpc/package.json
packages/dapi/package.json
packages/dash-spv/package.json
packages/dashmate/package.json
packages/dashpay-contract/package.json
packages/dpns-contract/package.json
packages/feature-flags-contract/package.json
packages/js-dapi-client/package.json
packages/js-dash-sdk/package.json
packages/js-dpp/package.json
packages/js-drive/package.json
packages/js-grpc-common/package.json
packages/masternode-reward-shares-contract/package.json
packages/platform-test-suite/package.json
packages/wallet-lib/package.json

chore(release): update changelog and bump version to 0.23.0-dev.8

---

packages/platform-test-suite/test/e2e/dpns.spec.js
packages/platform-test-suite/test/e2e/masternodeRewardShares.spec.js
packages/platform-test-suite/test/functional/platform/Document.spec.js
packages/platform-test-suite/test/functional/platform/Identity.spec.js

```
expected { Object (dataContract, entropy, ...) } to not exist
```
and other cases
- add wait for st propagated interval
None
None

fix(test-suite): failing assertions due to replication lag

---

packages/dashmate/configs/system/base.js

Update dashcore and sentinel versions to the latest
Updated docker images versions in dashmate templates (base.js)
Locally
No breaking changes

chore(dashmate): bump dashcore and sentinel versions

---

CHANGELOG.md
package.json
packages/dapi-grpc/package.json
packages/dapi/package.json
packages/dash-spv/package.json
packages/dashmate/package.json
packages/dashpay-contract/package.json
packages/dpns-contract/package.json
packages/feature-flags-contract/package.json
packages/js-dapi-client/package.json
packages/js-dash-sdk/package.json
packages/js-dpp/package.json
packages/js-drive/package.json
packages/js-grpc-common/package.json
packages/masternode-reward-shares-contract/package.json
packages/platform-test-suite/package.json
packages/wallet-lib/package.json

chore(release): update changelog and bump version to 0.22.14

---

packages/dashmate/src/config/convertObjectToEnvs.js

From time to time undefined Docker Compose error happened during local network setup.
- Escape [unexpected chars](https://www.baeldung.com/linux/allowed-characters-variable-names) in env variable name
Locally
None

fix(dashmate): DockerComposeError undefined

---

CHANGELOG.md
package.json
packages/dapi-grpc/package.json
packages/dapi/package.json
packages/dash-spv/package.json
packages/dashmate/configs/system/mainnet.js
packages/dashmate/package.json
packages/dashpay-contract/package.json
packages/dpns-contract/package.json
packages/feature-flags-contract/package.json
packages/js-dapi-client/package.json
packages/js-dash-sdk/package.json
packages/js-dpp/package.json
packages/js-drive/package.json
packages/js-grpc-common/package.json
packages/masternode-reward-shares-contract/package.json
packages/platform-test-suite/package.json
packages/wallet-lib/package.json

chore(release): update changelog and bump version to 0.22.15

---

CHANGELOG.md
package.json
packages/dapi-grpc/package.json
packages/dapi/package.json
packages/dash-spv/package.json
packages/dashmate/package.json
packages/dashpay-contract/package.json
packages/dpns-contract/package.json
packages/feature-flags-contract/package.json
packages/js-dapi-client/package.json
packages/js-dash-sdk/package.json
packages/js-dpp/package.json
packages/js-drive/package.json
packages/js-grpc-common/package.json
packages/masternode-reward-shares-contract/package.json
packages/platform-test-suite/package.json
packages/wallet-lib/package.json

chore(release): update changelog and bump version to 0.22.16

---

packages/dashmate/configs/system/base.js

Using tenderdash version was updated up to `0.9.0-dev.1 `
With tests
No

feat(dashmate): update tenderdash to 0.9.0-dev.1

---

packages/js-dapi-client/lib/transport/GrpcTransport/createGrpcTransportError.js

`metadata.get is not a function` in browser tests
Changed the way the stack is obtained from the internal error
None

fix(dapi-client): metadata.get is not a function

---

packages/dashmate/configs/system/base.js
packages/dashmate/configs/system/mainnet.js
packages/js-drive/lib/abci/handlers/query/response/createQueryResponseFactory.js
packages/js-drive/lib/test/bootstrap.js
packages/js-drive/test/integration/core/updateSimplifiedMasternodeListFactory.spec.js

Update Core to the latest 18.1.0 build
- Updated Core image in dashmate and tests
Running test suite
None

feat: update Core to 18.1.0-rc.1

---

packages/js-drive/lib/core/waitForCoreChainLockSyncFactory.js

Typo in debug message
Corrected typeo
N/A
No

chore(drive): correct typo in debug message

---

.pnp.cjs
packages/js-drive/lib/validator/ValidatorSet.js
packages/platform-test-suite/package.json
packages/platform-test-suite/test/functional/platform/proofs.spec.js
packages/platform-test-suite/test/functional/platform/waitForStateTransitionResult.spec.js
yarn.lock

Merk package is not using anymore in platform
- Removed merk from dependecies
With linter
None

chore(test-suite): remove unused merk dependency

---

scripts/setup_local_network.sh

Due to `dashmate update` call during local network setup, we can't set docker images that do not exist yet but will be built with this commit via CI. See #548. This call unnecessary for local development as well since Platform images are building from sources anywas.
- Remove `dashmate update` form the setup script
None
None

chore(scripts): remove dashmate update

---

CHANGELOG.md
package.json
packages/bench-suite/package.json
packages/dapi-grpc/package.json
packages/dapi/package.json
packages/dash-spv/package.json
packages/dashmate/configs/migrations.js
packages/dashmate/configs/system/base.js
packages/dashmate/configs/system/testnet.js
packages/dashmate/package.json
packages/dashpay-contract/package.json
packages/dpns-contract/package.json
packages/feature-flags-contract/package.json
packages/js-dapi-client/package.json
packages/js-dash-sdk/package.json
packages/js-dpp/package.json
packages/js-drive/package.json
packages/js-grpc-common/package.json
packages/masternode-reward-shares-contract/package.json
packages/platform-test-suite/package.json
packages/wallet-lib/package.json

chore(release): update changelog and bump version to 0.23.0-alpha.1

---

packages/dashmate/configs/migrations.js
packages/js-dash-sdk/src/SDK/Client/Platform/methods/identities/internal/createAssetLockProof.ts

PR fixes a bug with the call of `waitForCoreChainLockedHeight` with a wrong platform argument

fix(sdk): platform.initialize is not a function

---

scripts/release/bump_version.js
scripts/release/release.sh

Alpha releases support for CI release script
Manual
No

fix(ci): support alpha prereleases

---

CHANGELOG.md
package.json
packages/bench-suite/package.json
packages/dapi-grpc/package.json
packages/dapi/package.json
packages/dash-spv/package.json
packages/dashmate/package.json
packages/dashpay-contract/package.json
packages/dpns-contract/package.json
packages/feature-flags-contract/package.json
packages/js-dapi-client/package.json
packages/js-dash-sdk/package.json
packages/js-dpp/package.json
packages/js-drive/package.json
packages/js-grpc-common/package.json
packages/masternode-reward-shares-contract/package.json
packages/platform-test-suite/package.json
packages/wallet-lib/package.json
packages/wasm-dpp/package.json

chore(release): update changelog and bump version to 0.24.0-dev.1

---

scripts/release/release.sh

Wrong parameter names in release script
Fixed release script wrong parameter names
Manual
No

build: fix release script wrong param names

---

packages/dashmate/configs/system/base.js

We should use the latest alpha versions of DAPI and Drive
- Updated dashmate base config
None
None

chore(dashmate): use latest DAPI and Drive 0.23.0-alpha

---

CHANGELOG.md
package.json
packages/bench-suite/package.json
packages/dapi-grpc/package.json
packages/dapi/package.json
packages/dash-spv/package.json
packages/dashmate/package.json
packages/dashpay-contract/package.json
packages/dpns-contract/package.json
packages/feature-flags-contract/package.json
packages/js-dapi-client/package.json
packages/js-dash-sdk/package.json
packages/js-dpp/package.json
packages/js-drive/package.json
packages/js-grpc-common/package.json
packages/masternode-reward-shares-contract/package.json
packages/platform-test-suite/package.json
packages/wallet-lib/package.json

chore(release): update changelog and bump version to 0.23.0-alpha.3

---

CHANGELOG.md
package.json
packages/bench-suite/package.json
packages/dapi-grpc/package.json
packages/dapi/package.json
packages/dash-spv/package.json
packages/dashmate/package.json
packages/dashpay-contract/package.json
packages/dpns-contract/package.json
packages/feature-flags-contract/package.json
packages/js-dapi-client/package.json
packages/js-dash-sdk/package.json
packages/js-dpp/package.json
packages/js-drive/package.json
packages/js-grpc-common/package.json
packages/masternode-reward-shares-contract/package.json
packages/platform-test-suite/package.json
packages/wallet-lib/package.json

chore(release): update changelog and bump version to 0.23.0-alpha.4

---

.github/workflows/dashmate.yml
.github/workflows/platform-test-suite.yml

Dashmate and platform test suite workflow are not running when corresponding packages are changed
- Add dashmate and platform test suite paths
None
None

ci: run dashmate and test suite workflow

---

CHANGELOG.md
package.json
packages/bench-suite/package.json
packages/dapi-grpc/package.json
packages/dapi/package.json
packages/dash-spv/package.json
packages/dashmate/package.json
packages/dashpay-contract/package.json
packages/dpns-contract/package.json
packages/feature-flags-contract/package.json
packages/js-dapi-client/package.json
packages/js-dash-sdk/package.json
packages/js-dpp/package.json
packages/js-drive/package.json
packages/js-grpc-common/package.json
packages/masternode-reward-shares-contract/package.json
packages/platform-test-suite/package.json
packages/wallet-lib/package.json

chore(release): update changelog and version to 0.23.0-alpha.5

---

CHANGELOG.md
package.json
packages/bench-suite/package.json
packages/dapi-grpc/package.json
packages/dapi/package.json
packages/dash-spv/package.json
packages/dashmate/package.json
packages/dashpay-contract/package.json
packages/dpns-contract/package.json
packages/feature-flags-contract/package.json
packages/js-dapi-client/package.json
packages/js-dash-sdk/package.json
packages/js-dpp/package.json
packages/js-drive/package.json
packages/js-grpc-common/package.json
packages/masternode-reward-shares-contract/package.json
packages/platform-test-suite/package.json
packages/wallet-lib/package.json

chore(release): update changelog and bump version to 0.23.0-alpha.6

---

packages/js-drive/test/integration/identity/masternode/synchronizeMasternodeIdentitiesFactory.spec.js

`synchronizeMasternodeIdentitiesFactory ` test is broken
Fixed `synzhronizeMasternodeIdentitiesFactory ` integration test
With tests
No

test(drive): synchronizeMasternodeIdentitiesFactory

---

CHANGELOG.md
package.json
packages/bench-suite/package.json
packages/dapi-grpc/package.json
packages/dapi/package.json
packages/dash-spv/package.json
packages/dashmate/package.json
packages/dashpay-contract/package.json
packages/dpns-contract/package.json
packages/feature-flags-contract/package.json
packages/js-dapi-client/package.json
packages/js-dash-sdk/package.json
packages/js-dpp/package.json
packages/js-drive/package.json
packages/js-grpc-common/package.json
packages/masternode-reward-shares-contract/package.json
packages/platform-test-suite/package.json
packages/wallet-lib/package.json
packages/wasm-dpp/package.json

chore(release): update changelog and bump version to 0.24.0-dev.2

---

.github/workflows/all-packages.yml
.github/workflows/cron.yml
.github/workflows/js-dapi-client.yml
.github/workflows/js-dash-sdk.yml
.github/workflows/js-dpp.yml
.github/workflows/platform-test-suite.yml
.github/workflows/release.yml
.github/workflows/test.yml
.github/workflows/wallet-lib.yml
.pnp.cjs
packages/js-dapi-client/webpack.config.js
packages/js-drive/lib/abci/handlers/beginBlockHandlerFactory.js
packages/js-drive/lib/storage/GroveDBStore.js
packages/js-drive/package.json
packages/js-drive/test/integration/fee/pools.spec.js
packages/js-drive/test/integration/identity/masternode/synchronizeMasternodeIdentitiesFactory.spec.js
packages/js-drive/test/unit/abci/handlers/beginBlockHandlerFactory.spec.js
yarn.lock

To apply the fix https://github.com/dashpay/rs-platform/pull/165 we need to update to the latest RS Drive v0.23.0-dev.9
- Updated CI base image to support RS Drive built with gcc 11
- Updated JS Drive to the latest RS Drive
With CI
Previous data is not compatible with new Drive

chore(drive)!: update RS Drive to 0.23.0-dev.9

---

CHANGELOG.md
package.json
packages/bench-suite/package.json
packages/dapi-grpc/package.json
packages/dapi/package.json
packages/dash-spv/package.json
packages/dashmate/package.json
packages/dashpay-contract/package.json
packages/dpns-contract/package.json
packages/feature-flags-contract/package.json
packages/js-dapi-client/package.json
packages/js-dash-sdk/package.json
packages/js-dpp/package.json
packages/js-drive/package.json
packages/js-grpc-common/package.json
packages/masternode-reward-shares-contract/package.json
packages/platform-test-suite/package.json
packages/wallet-lib/package.json

chore(release): update changelog and bump version to 0.23.0-alpha.7

---

.github/workflows/all-packages.yml
.github/workflows/cron.yml
.github/workflows/release.yml
.github/workflows/test.yml

Many action deps have been updated in preparation of the Node 12 deprecation, and we were beginning to see other warnings:
- https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/
- https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
We need to update many of these actions in platform and other repos soon, so I would like to test them here first for any obvious changes.
Update deps
Tested on `dashpay/dash-network-deploy` which uses very similar actions. Test and release succeeded without any issues, and I don't expect this will cause major issues either.
Probably none

ci: update deps

---

README.md
docs/index.md
packages/bench-suite/README.md
packages/dapi-grpc/README.md
packages/dapi/README.md
packages/dashmate/README.md
packages/dashpay-contract/README.md
packages/dpns-contract/README.md
packages/feature-flags-contract/README.md
packages/js-dapi-client/README.md
packages/js-dash-sdk/README.md
packages/js-dash-sdk/docs/README.md
packages/js-dash-sdk/docs/usage/dashcorelib-primitives.md
packages/js-dpp/README.md
packages/js-drive/README.md
packages/platform-test-suite/README.md
packages/wallet-lib/README.md
packages/wallet-lib/docs/README.md
packages/wallet-lib/docs/plugins/writing-a-new-plugin.md
packages/wallet-lib/docs/storage/searchBlockHeader.md
packages/wallet-lib/docs/usage/coinSelection.md
packages/wallet-lib/docs/usage/examples.md

Clean up some more places where we refer to `dashevo`
Updated `dashevo` to `dashpay` for a number of links/badges.
Previewed updated files to check badges
N/A

docs: GitHub org change updates

---

.github/workflows/release.yml
packages/dashmate/Dockerfile

New Envoy and Dashmate helper docker images must be published on release
release.yml GitHub script was modified to release new Docker images
Manual
No

build: publish envoy and dashmate-helper docker images after release

---

CHANGELOG.md
package.json
packages/bench-suite/package.json
packages/dapi-grpc/package.json
packages/dapi/package.json
packages/dash-spv/package.json
packages/dashmate/package.json
packages/dashpay-contract/package.json
packages/dpns-contract/package.json
packages/feature-flags-contract/package.json
packages/js-dapi-client/package.json
packages/js-dash-sdk/package.json
packages/js-dpp/package.json
packages/js-drive/package.json
packages/js-grpc-common/package.json
packages/masternode-reward-shares-contract/package.json
packages/platform-test-suite/package.json
packages/wallet-lib/package.json
packages/wasm-dpp/package.json

chore(release): update changelog and bump version to 0.24.0-dev.4

---

.github/workflows/release.yml

`release.yml` had wrong indentation for `envoy` and `dashmate-helper`
- updated `release.yml`
- [xI have commented my code, particularly in hard-to-understand areas

fix: `release.yml` contained wrong indentation

---

CHANGELOG.md
package.json
packages/bench-suite/package.json
packages/dapi-grpc/package.json
packages/dapi/package.json
packages/dash-spv/package.json
packages/dashmate/package.json
packages/dashpay-contract/package.json
packages/dpns-contract/package.json
packages/feature-flags-contract/package.json
packages/js-dapi-client/package.json
packages/js-dash-sdk/package.json
packages/js-dpp/package.json
packages/js-drive/package.json
packages/js-grpc-common/package.json
packages/masternode-reward-shares-contract/package.json
packages/platform-test-suite/package.json
packages/wallet-lib/package.json
packages/wasm-dpp/package.json

chore(release): update changelog and bump version to 0.24.0-dev.5

---

.github/workflows/release.yml
packages/dashmate/configs/system/base.js
packages/dashmate/docker-compose.platform.build.yml
packages/dashmate/docker-compose.platform.yml

Typo `dash-amte` was preventing publishing of the image
- fixed typo

fix: typo `dash-amte` to `dashmate`

---

CHANGELOG.md
package.json
packages/bench-suite/package.json
packages/dapi-grpc/package.json
packages/dapi/package.json
packages/dash-spv/package.json
packages/dashmate/package.json
packages/dashpay-contract/package.json
packages/dpns-contract/package.json
packages/feature-flags-contract/package.json
packages/js-dapi-client/package.json
packages/js-dash-sdk/package.json
packages/js-dpp/package.json
packages/js-drive/package.json
packages/js-grpc-common/package.json
packages/masternode-reward-shares-contract/package.json
packages/platform-test-suite/package.json
packages/wallet-lib/package.json
packages/wasm-dpp/package.json

chore(release): update changelog and bump version to 0.24.0-dev.6

---

packages/platform-test-suite/test/functional/platform/featureFlags.spec.js

Feature flags test was awaiting blocks that may have been produced or not (well, in 3 minutes).
- propagated documents in different broadcasts, plus created an unnecessary transition to create 2 more blocks
- devnet testing 
None

fix(test-suite): `featureFlags` test was awaiting blocks that have not been produced

---

packages/js-dpp/lib/dataContract/validation/validateDataContractFactory.js
packages/js-dpp/lib/test/fixtures/getDataContractFixture.js
packages/js-dpp/test/integration/dataContract/validation/validateDataContractFactory.spec.js

`validateDataContract` function have been validating all indices for partially available properties 
- updated `validateDataContract` function
Unit tests
- previously valid data contracts are now invalid

fix!(dpp): required properties of unique indices were validated falsely

---

packages/dashmate/src/listr/tasks/ssl/VerificationServer.js

SSL verification server cannot be started
Fixed dashmate
Manually
No

fix(dashmate): SSL verification server cannot be started

---

CHANGELOG.md
package.json
packages/bench-suite/package.json
packages/dapi-grpc/package.json
packages/dapi/package.json
packages/dash-spv/package.json
packages/dashmate/package.json
packages/dashpay-contract/package.json
packages/dpns-contract/package.json
packages/feature-flags-contract/package.json
packages/js-dapi-client/package.json
packages/js-dash-sdk/package.json
packages/js-dpp/package.json
packages/js-drive/package.json
packages/js-grpc-common/package.json
packages/masternode-reward-shares-contract/package.json
packages/platform-test-suite/package.json
packages/wallet-lib/package.json

chore(release): update changelog and bump version to 0.23.0-alpha.8

---

packages/wasm-dpp/scripts/build.sh

wasm-dpp build failed with error
Fixed wasm-dpp build script
With tests
No

build(dpp): build script failed with unknown mkdipr command

---

packages/dapi/lib/grpcServer/handlers/core/getStatusHandlerFactory.js

Cannot read properties of undefined (reading 'PoSePenalty')
Fixed DAPI method
With tests
No

fix(dapi): Cannot read properties of undefined (reading 'PoSePenalty')

---

packages/js-drive/lib/core/getRandomQuorum.js
packages/js-drive/test/unit/core/getRandomQuorum.spec.js

Do not switch validator set to the quorum which has not enough active members
Changed Drive's validator rotation logic
With tests
No

feat(drive): select the most vital validator set quorums

---

packages/js-dpp/lib/dataTrigger/dashpayDataTriggers/createContactRequestDataTrigger.js
packages/js-dpp/test/unit/dataTrigger/dashpayDataTriggers/createContactRequestDataTrigger.spec.js

Dashpay contract can have toUserId which is not exists or equals ownerId
Fixed dashpay datatrigger
With tests
No

feat(dpp): dashpay datatrigger toUserIds better validation

---

packages/wasm-dpp/src/identity.rs

A fix to accommodate corresponding change from rs-platfrom
Renamed method the same way it was renamed in rs-platform
Run tests
None

fix: rename method from rs-dpp

---

packages/wasm-dpp/Cargo.toml
packages/wasm-dpp/src/data_contract/data_contract.rs
packages/wasm-dpp/src/data_contract/errors/invalid_document_type.rs
packages/wasm-dpp/src/data_contract/errors/mod.rs
packages/wasm-dpp/src/document/mod.rs
packages/wasm-dpp/src/errors/from.rs
packages/wasm-dpp/src/identifier.rs
packages/wasm-dpp/src/identity.rs
packages/wasm-dpp/src/metadata.rs
packages/wasm-dpp/test/unit/dataContract/DataContract.spec.js

Make tests in DataContract.spec.js in wasm-dpp package actually check wasm-dpp behavior.
Adaptation of tests and required fixes to wasm bindings.
Setting expectations and verifying results, also comparing to js-dpp results.

fix: DataContract.spec.js in wasm-dpp

---

CHANGELOG.md
package.json
packages/bench-suite/package.json
packages/dapi-grpc/package.json
packages/dapi/package.json
packages/dash-spv/package.json
packages/dashmate/package.json
packages/dashpay-contract/package.json
packages/dpns-contract/package.json
packages/feature-flags-contract/package.json
packages/js-dapi-client/package.json
packages/js-dash-sdk/package.json
packages/js-dpp/package.json
packages/js-drive/package.json
packages/js-grpc-common/package.json
packages/masternode-reward-shares-contract/package.json
packages/platform-test-suite/package.json
packages/wallet-lib/package.json
packages/wasm-dpp/package.json
packages/withdrawals-contract/package.json

chore(release): update changelog and bump version to 0.24.0-dev.8

---

packages/dashmate/src/listr/tasks/ssl/zerossl/renewZeroSSLCertificateTaskFactory.js

ZeroSSL certificate renewal processs fails with error
Fixed ZeroSSL certificate renewal processs
Manual
No

fix(dashmate): ZeroSSL certificate renewal doesn't work

---

CHANGELOG.md
package.json
packages/bench-suite/package.json
packages/dapi-grpc/package.json
packages/dapi/package.json
packages/dash-spv/package.json
packages/dashmate/package.json
packages/dashpay-contract/package.json
packages/dpns-contract/package.json
packages/feature-flags-contract/package.json
packages/js-dapi-client/package.json
packages/js-dash-sdk/package.json
packages/js-dpp/package.json
packages/js-drive/package.json
packages/js-grpc-common/package.json
packages/masternode-reward-shares-contract/package.json
packages/platform-test-suite/package.json
packages/wallet-lib/package.json

chore(release): update changelog and bump version to 0.23.0-alpha.9

---

CHANGELOG.md
package.json
packages/bench-suite/package.json
packages/dapi-grpc/package.json
packages/dapi/package.json
packages/dash-spv/package.json
packages/dashmate/package.json
packages/dashpay-contract/package.json
packages/dpns-contract/package.json
packages/feature-flags-contract/package.json
packages/js-dapi-client/package.json
packages/js-dash-sdk/package.json
packages/js-dpp/package.json
packages/js-drive/package.json
packages/js-grpc-common/package.json
packages/masternode-reward-shares-contract/package.json
packages/platform-test-suite/package.json
packages/wallet-lib/package.json

chore(release): update changelog and bump version to 0.23.0

---

.github/workflows/release.yml

Release failed due to wrong entrypoint path
- Fixed entrypoint path
None
None

ci: fix entrypoint path in release workflow

---

CHANGELOG.md
package.json
packages/bench-suite/package.json
packages/dapi-grpc/package.json
packages/dapi/package.json
packages/dash-spv/package.json
packages/dashmate/package.json
packages/dashpay-contract/package.json
packages/dpns-contract/package.json
packages/feature-flags-contract/package.json
packages/js-dapi-client/package.json
packages/js-dash-sdk/package.json
packages/js-dpp/package.json
packages/js-drive/package.json
packages/js-grpc-common/package.json
packages/masternode-reward-shares-contract/package.json
packages/platform-test-suite/package.json
packages/rs-drive-nodejs/package.json
packages/wallet-lib/package.json
packages/wasm-dpp/package.json
packages/withdrawals-contract/package.json

chore(release): update changelog and bump version to 0.24.0-dev.10

---

.github/workflows/all-packages.yml
.github/workflows/docs.yml
.github/workflows/js-checks.yml
.github/workflows/release.yml
.github/workflows/rs-checks.yml
.github/workflows/wasm-dpp.yml

Several actions were outdated, and `actions-rs/toolchain` in particular is [unmaintained](https://github.com/actions-rs/toolchain/issues/216)
- Update GitHub Action deps
- Pin some versions and update matrix conditions
- Switch to alternative actions to set up Rust
Two unmaintained `actions-rs` actions remain, possible alternatives if/when they break can be found [here](https://github.com/starship/starship/issues/4725)
In CI
None

ci: bump action versions

---

packages/dashmate/src/listr/tasks/ssl/saveCertificateTask.js
packages/dashmate/src/listr/tasks/ssl/zerossl/obtainZeroSSLCertificateTaskFactory.js
packages/dashmate/src/listr/tasks/ssl/zerossl/renewZeroSSLCertificateTaskFactory.js
packages/dashmate/src/ssl/zerossl/downloadCertificate.js

ZeroSSL certificates couldn't be saved to disk in WSL
Fixed dasmate tasks
Manual
No

fix(dashmate): ZeroSSL certificates are not saved in WSL

---

packages/dashmate/src/helper/scheduleRenewZeroSslCertificateFactory.js

Dashamte helper fails with `setDay is not a function`
Fixed dashamte helper
Manual
No

fix(dashmate): setDay is not a function

---

CHANGELOG.md
package.json
packages/bench-suite/package.json
packages/dapi-grpc/package.json
packages/dapi/package.json
packages/dash-spv/package.json
packages/dashmate/package.json
packages/dashpay-contract/package.json
packages/dpns-contract/package.json
packages/feature-flags-contract/package.json
packages/js-dapi-client/package.json
packages/js-dash-sdk/package.json
packages/js-dpp/package.json
packages/js-drive/package.json
packages/js-grpc-common/package.json
packages/masternode-reward-shares-contract/package.json
packages/platform-test-suite/package.json
packages/rs-drive-nodejs/package.json
packages/wallet-lib/package.json
packages/wasm-dpp/package.json
packages/withdrawals-contract/package.json

chore(release): update changelog and bump version to 0.24.0-dev.11

---

.github/workflows/release.yml

No packages were uploaded, and oclif runs with the warning ` Warning: pack {{ matrix.package_type }} is not a oclif command.`
Fix GitHub Actions templating syntax
This is for testing
None

ci: fix incorrect github actions templating syntax

---

Cargo.lock
packages/js-drive/lib/dataContract/DataContractStoreRepository.js
packages/js-drive/lib/identity/IdentityStoreRepository.js
packages/rs-drive-abci/src/common/helpers/fee_pools.rs
packages/rs-drive-nodejs/GroveDB.js
packages/rs-drive-nodejs/src/converter.rs
packages/rs-drive-nodejs/src/lib.rs
packages/rs-drive/Cargo.toml
packages/rs-drive/src/drive/batch/drive_op_batch.rs
packages/rs-drive/src/drive/batch/grovedb_op_batch.rs
packages/rs-drive/src/drive/contract/mod.rs
packages/rs-drive/src/drive/document/delete.rs
packages/rs-drive/src/drive/document/estimation_costs.rs
packages/rs-drive/src/drive/document/insert.rs
packages/rs-drive/src/drive/document/update.rs
packages/rs-drive/src/drive/grove_operations.rs
packages/rs-drive/src/drive/mod.rs
packages/rs-drive/src/drive/object_size_info.rs
packages/rs-drive/src/fee/op.rs
packages/rs-drive/src/query/mod.rs
packages/rs-drive/tests/deterministic_root_hash.rs
packages/rs-drive/tests/query_tests.rs
packages/rs-drive/tests/query_tests_history.rs
packages/rs-drive/tests/supporting_files/contract/family/family-contract-only-age-index.json
packages/rs-drive/tests/supporting_files/contract/family/person0-older.json
packages/rs-drive/tests/supporting_files/contract/family/person3-older.json
packages/rs-drive/tests/supporting_files/contract/family/person3.json

Before this PR it was not possible to have multiple document inserts or updates per batch, now it is.
Support for GroveDB 9 was also included in this PR.

feat: multiple documents changes per batch and support for GroveDB 0.9

---

packages/rs-dpp/src/document/state_transition/documents_batch_transition/validation/basic/find_duplicates_by_id.rs

find_duplicates_by_id.rs test compilation error
Updated test method signature
Run tests
None

fix: find_duplicates_by_id.rs not compiling

---

packages/rs-drive/src/drive/contract/mod.rs

test: additional test to prove the fix

---

packages/dashmate/src/ssl/zerossl/downloadCertificate.js

ZeroSSL certificate cannot be downloaded after migration to fecth
Fixed downloadCertificate function
By issuing ZeroSSL certificate
No

fix(dashmate): ZeroSSL certificate cannot be downloaded

---

packages/dashmate/configs/system/base.js

Core version needs to be set to 18.1.1
Set core to 18.1.1
In testint
None

chore: set core in base config to v18.1.1

---

packages/rs-dpp/src/document/state_transition/documents_batch_transition/validation/basic/find_duplicates_by_id.rs

DPP tests are failing:
```
---- document::state_transition::documents_batch_transition::validation::basic::find_duplicates_by_id::test::test_duplicates stdout ----
thread 'document::state_transition::documents_batch_transition::validation::basic::find_duplicates_by_id::test::test_duplicates' panicked at 'called `Result::unwrap()` on an `Err` value: Can't create fingerprint from a document transition', packages/rs-dpp/src/document/state_transition/documents_batch_transition/validation/basic/find_duplicates_by_id.rs:83:62
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
---- tests::data_contract::state_transition::data_contract_update_transition::validation::basic::validate_indices_are_backward_compatible_spec::should_return_invalid_result_if_some_of_unique_indic …
```

fix(dpp): can’t create fingerprint from a document transition

---

packages/dashmate/configs/system/testnet.js

Platform chain id needs updating
Update platform chain id
On testnet

chore: update platform chain id

---

CHANGELOG.md
package.json
packages/bench-suite/package.json
packages/dapi-grpc/package.json
packages/dapi/package.json
packages/dash-spv/package.json
packages/dashmate/package.json
packages/dashpay-contract/package.json
packages/dpns-contract/package.json
packages/feature-flags-contract/package.json
packages/js-dapi-client/package.json
packages/js-dash-sdk/package.json
packages/js-dpp/package.json
packages/js-drive/package.json
packages/js-grpc-common/package.json
packages/masternode-reward-shares-contract/package.json
packages/platform-test-suite/package.json
packages/wallet-lib/package.json

chore(release): update changelog and bump version to 0.23.1

---

packages/rs-drive-abci/src/execution/engine.rs
packages/rs-drive/src/drive/batch/drive_op_batch/identity.rs
packages/rs-drive/src/drive/identity/balance/update.rs
packages/rs-drive/src/drive/identity/insert.rs
packages/rs-drive/src/drive/identity/mod.rs
packages/rs-drive/src/fee/result/mod.rs

Identity v8 fixes

---

packages/rs-drive-abci/src/execution/fee_pools/distribute_storage_pool.rs
packages/rs-drive-abci/src/execution/fee_pools/process_block_fees.rs
packages/rs-drive/src/drive/fee_pools/mod.rs
packages/rs-drive/src/drive/fee_pools/pending_epoch_refunds.rs
packages/rs-drive/src/fee/credits.rs
packages/rs-drive/src/fee_pools/epochs_root_tree_key_constants.rs
packages/rs-drive/src/fee_pools/mod.rs

refactor(drive): rename pending updates

---

packages/dashmate/configs/system/base.js

Need to update Core
Core updated up to the 18.2.0
With tests
No

feat(dashmate): update Core to 18.2.0

---

packages/js-drive/lib/abci/handlers/proposal/deliverTxFactory.js

Add contractId to document logs in deliverTx handler
Additional field was added to logs
With tests
No

feat(drive): log contractId in deliverTx handler

---

packages/rs-drive/src/fee/epoch/mod.rs
packages/rs-drive/src/fee/result/refunds.rs

feat(drive): ignore dust refunds

---

packages/dashmate/configs/migrations.js

Overlooked migration does not count configs without platform (mainnet, local_seed, etc...)
Migrate tenderdash logging only if platform is presented in the config
Locally
No

fix(dashmate): fix migration for configs without platform

---

packages/js-dapi-client/package.json

fix(dapi-client): missing fetch-polyfill in npm installation

---

packages/rs-dpp/src/data_contract/data_contract.rs
packages/rs-dpp/src/identity/identity.rs
packages/rs-dpp/src/util/cbor_value/cbor_map.rs

We had a few redundant methods to get integer from a map.
Used a trait instead.

refactor: use a trait to remove the need for some functions

---

CHANGELOG.md
package.json
packages/bench-suite/package.json
packages/dapi-grpc/package.json
packages/dapi/package.json
packages/dash-spv/package.json
packages/dashmate/package.json
packages/dashpay-contract/package.json
packages/dpns-contract/package.json
packages/feature-flags-contract/package.json
packages/js-dapi-client/package.json
packages/js-dash-sdk/package.json
packages/js-dpp/package.json
packages/js-drive/package.json
packages/js-grpc-common/package.json
packages/masternode-reward-shares-contract/package.json
packages/platform-test-suite/package.json
packages/wallet-lib/package.json

chore(release): update changelog and bump version to 0.23.2

---

packages/dashmate/templates/platform/drive/tenderdash/config.toml.dot

Tenderdash config file in Dashmate is outdated.
Synchronized Tenderdash config template in Dashmate with fresh one generated by Tenderdash v0.10.0-dev.8
Created local environment using Dashmate.
None

chore(dashmate): sync Tenderdash config template with Tenderdash v0.10.0-dev.8

---

packages/dashmate/configs/migrations.js

Migration fixes for pulls #752 and #755
* Added missing migration for dapi envoy grpc port
* Fixed invalid config name pointer
Locally + devnet, by manipulating local and dashmate versions and testing the result
No

fix(dashmate): migrations fixes

---

Cargo.lock
packages/rs-dpp/Cargo.toml
packages/rs-dpp/src/tests/data_contract/validation/data_contract_validator_spec.rs
packages/rs-dpp/src/validation/meta_validators.rs
packages/wasm-dpp/test/integration/dataContract/validation/validateDataContractFactory.spec.js

This PR enables data contract validation tests that require `unevaluatedProperties` feature to work.

fix(dpp): update jsonschema-rs and enable tests

---

packages/dashmate/src/commands/setup.js
packages/dashmate/src/listr/tasks/setup/setupRegularPresetTaskFactory.js

chore: some setup instruction suggestions

---

packages/rs-dpp/src/data_contract/mod.rs
packages/rs-dpp/src/data_contract/state_transition/data_contract_create_transition/validation/state/validate_data_contract_create_transition_basic.rs
packages/rs-dpp/src/validation/json_schema_validator.rs
packages/wasm-dpp/src/data_contract/state_transition/data_contract_create_transition/mod.rs
packages/wasm-dpp/src/data_contract/state_transition/data_contract_create_transition/validation.rs
packages/wasm-dpp/test/integration/dataContract/stateTransition/DataContractCreateTransition/validation/basic/validateDataContractCreateTransitionBasicFactory.spec.js

feat(wasm-dpp) integration tests validate data contract create transition

---

packages/wasm-dpp/src/decode_protocol_entity.rs
packages/wasm-dpp/src/lib.rs
packages/wasm-dpp/test/unit/decodeProtocolEntityFactory.spec.js

Missing `decodeProtocolEntity` tests for wasm-dpp
Exposed the `decodeProtocolEntity` function through the binging and changed tests to use it
Run tests
None

feat(wasm-dpp): decodeProtocolEntity test

---

packages/rs-drive/src/drive/test_utils.rs

Fixes path to entropy generator in rs-drive tests

test(rs-drive): fix path to EntropyGenerator

---

packages/dashmate/configs/migrations.js
packages/dashmate/configs/schema/configJsonSchema.js
packages/dashmate/configs/system/base.js
packages/dashmate/templates/core/dash.conf.dot

Some of core options are applied only for devnet and having them into the main core section is confusing
- Move devnet-only core options to the `devnet` subsection.
- Implement config migration 
None
None

refactor(dashmate): move core devnet options to subsection

---

packages/dashmate/configs/schema/configJsonSchema.js
packages/dashmate/src/constants.js
packages/dashmate/src/listr/tasks/setup/regular/configureNodeTaskFactory.js
packages/dashmate/src/listr/tasks/setup/regular/configureSSLCertificateTaskFactory.js
packages/dashmate/src/listr/tasks/setup/setupLocalPresetTaskFactory.js
packages/dashmate/src/listr/tasks/ssl/selfSigned/obtainSelfSignedCertificateTaskFactory.js
packages/dashmate/src/listr/tasks/ssl/zerossl/obtainZeroSSLCertificateTaskFactory.js
packages/dashmate/templates/platform/dapi/envoy/envoy.yaml.dot

Need to generate self-signed certificates for testnet in dashmate setup
Added ability to generate self-signed certificates for testnet
Manual
No

feat(dashmate): generate self-signed certificates in the `setup` command

---

packages/dashmate/src/listr/tasks/setup/regular/configureSSLCertificateTaskFactory.js

Dashmate shows `invalid data` error when user tries to enter certificate files paths
Fixed certificate files form
Manual
No

fix(dashmate): ambiguous validation errors for file certificates

---

packages/dashmate/src/commands/group/reset.js

```
$ yarn reset
[STARTED] Reset local nodes
[STARTED] Reset local_1 node
[FAILED] config.isPlatformEnabled is not a function
[FAILED] config.isPlatformEnabled is not a function
```
- Removed the unnecessary `config.isPlatformEnabled` check
Manually
None

fix(dashmate): config.isPlatformEnabled is not a function

---

scripts/configure.sh

Fixes operation order of `dashmate` configuration script
- updated `scripts/configure.sh`
local env
None

build: operations in configure.sh script were in a wrong order

---

packages/rs-dpp/src/data_contract/state_transition/data_contract_create_transition/apply_data_contract_create_transition_factory.rs
packages/rs-dpp/src/data_contract/state_transition/data_contract_update_transition/apply_data_contract_update_transition_factory.rs
packages/rs-dpp/src/document/state_transition/documents_batch_transition/apply_documents_batch_transition_factory.rs
packages/rs-dpp/src/identity/state_transition/asset_lock_proof/asset_lock_public_key_hash_fetcher.rs
packages/rs-dpp/src/identity/state_transition/asset_lock_proof/asset_lock_transaction_output_fetcher.rs
packages/rs-dpp/src/identity/state_transition/identity_create_transition/apply_identity_create_transition.rs
packages/rs-dpp/src/identity/state_transition/identity_topup_transition/apply_identity_topup_transition.rs
packages/rs-dpp/src/identity/state_transition/identity_update_transition/apply_identity_update_transition.rs
packages/rs-dpp/src/state_transition/apply_state_transition.rs
packages/rs-dpp/src/state_transition/mod.rs
packages/rs-dpp/src/state_transition/state_transition_facade.rs
packages/rs-dpp/src/state_transition/validation/validate_state_transition_key_signature.rs
packages/rs-dpp/src/tests/identity/state_transition/identity_update_transition/apply_identity_udpate_transition_spec.rs
packages/wasm-dpp/src/data_contract/state_transition/data_contract_create_transition/apply.rs
packages/wasm-dpp/src/data_contract/state_transition/data_contract_update_transition/apply.rs
packages/wasm-dpp/src/identity/state_transition/asset_lock_proof/mod.rs
packages/wasm-dpp/src/identity/state_transition/identity_update_transition/apply_identity_update_transition.rs
packages/wasm-dpp/src/state_transition/fee/refunds.rs
packages/wasm-dpp/src/state_transition/state_transition_facade.rs
packages/wasm-dpp/src/state_transition/validation/validate_state_transition_key_signature.rs

Missing dpp.stateTransition.apply function in the bindings
Add state transition applicator in rs-dpp and exposed `apply` function through the ST facade
There are no tests for this function in the original implementation
None

feat(dpp): state transition applicator

---

packages/dashmate/src/listr/tasks/restartNodeTaskFactory.js

If sourcePath is set, service restart leads to a huge downtime due to build process
- Build services before restarting
None
None

feat(dashmate): build services before restart

---

packages/dashmate/docker/entrypoint.sh

Dashmate helper is running with user root which breaks access rights to dashmate home dir
- Fix entrypoint to run helper using dashmate user
None
None

fix(dashmate): dashmate helper is running under root user

---

packages/js-drive/lib/abci/handlers/proposal/beginBlockFactory.js
packages/js-drive/test/unit/abci/handlers/proposal/beginBlockFactory.spec.js

Total HPMN count what we use to switch protocol version according to proposer signals. Current value includes all validators.
- Count only HPMNs
With tests
None

fix(drive): total HPMNs contains all masternodes

---

CHANGELOG.md
package.json
packages/bench-suite/package.json
packages/dapi-grpc/package.json
packages/dapi/package.json
packages/dash-spv/package.json
packages/dashmate/package.json
packages/dashpay-contract/package.json
packages/dpns-contract/package.json
packages/feature-flags-contract/package.json
packages/js-dapi-client/package.json
packages/js-dash-sdk/package.json
packages/js-dpp/package.json
packages/js-drive/package.json
packages/js-grpc-common/package.json
packages/masternode-reward-shares-contract/package.json
packages/platform-test-suite/package.json
packages/rs-drive-nodejs/package.json
packages/wallet-lib/package.json
packages/wasm-dpp/package.json
packages/withdrawals-contract/package.json

chore(release): update changelog and bump version to 0.24.0-dev.19

---

CHANGELOG.md
package.json
packages/bench-suite/package.json
packages/dapi-grpc/package.json
packages/dapi/package.json
packages/dash-spv/package.json
packages/dashmate/package.json
packages/dashpay-contract/package.json
packages/dpns-contract/package.json
packages/feature-flags-contract/package.json
packages/js-dapi-client/package.json
packages/js-dash-sdk/package.json
packages/js-dpp/package.json
packages/js-drive/package.json
packages/js-grpc-common/package.json
packages/masternode-reward-shares-contract/package.json
packages/platform-test-suite/package.json
packages/rs-drive-nodejs/package.json
packages/wallet-lib/package.json
packages/wasm-dpp/package.json
packages/withdrawals-contract/package.json

chore(release): update changelog and bump version to 0.24.0-dev.20

---

packages/dashmate/package.json

We decided that it would be better to not have docker dependencies in dashmate deb release, since there are many options for installing docker under linux
Removed deb release dasmate dependencies
Manual
No

build(dashamte): remove deb release docker dependencies

---

scripts/pack_dashmate.sh

We don't need release tarballs for Windows and MacOs, only Linux.
Additional oclif flags were added for tarball build
Manual
No

build(dashmate): build only linux tarballs

---

CHANGELOG.md
package.json
packages/bench-suite/package.json
packages/dapi-grpc/package.json
packages/dapi/package.json
packages/dash-spv/package.json
packages/dashmate/package.json
packages/dashpay-contract/package.json
packages/dpns-contract/package.json
packages/feature-flags-contract/package.json
packages/js-dapi-client/package.json
packages/js-dash-sdk/package.json
packages/js-dpp/package.json
packages/js-drive/package.json
packages/js-grpc-common/package.json
packages/masternode-reward-shares-contract/package.json
packages/platform-test-suite/package.json
packages/rs-drive-nodejs/package.json
packages/wallet-lib/package.json
packages/wasm-dpp/package.json
packages/withdrawals-contract/package.json

chore(release): update changelog and bump version to 0.24.0-dev.21

---

CHANGELOG.md
package.json
packages/bench-suite/package.json
packages/dapi-grpc/package.json
packages/dapi/package.json
packages/dash-spv/package.json
packages/dashmate/package.json
packages/dashpay-contract/package.json
packages/dpns-contract/package.json
packages/feature-flags-contract/package.json
packages/js-dapi-client/package.json
packages/js-dash-sdk/package.json
packages/js-dpp/package.json
packages/js-drive/package.json
packages/js-grpc-common/package.json
packages/masternode-reward-shares-contract/package.json
packages/platform-test-suite/package.json
packages/rs-drive-nodejs/package.json
packages/wallet-lib/package.json
packages/wasm-dpp/package.json
packages/withdrawals-contract/package.json

chore(release): update changelog and bump version to 0.24.0-dev.22

---

CHANGELOG.md
package.json
packages/bench-suite/package.json
packages/dapi-grpc/package.json
packages/dapi/package.json
packages/dash-spv/package.json
packages/dashmate/package.json
packages/dashpay-contract/package.json
packages/dpns-contract/package.json
packages/feature-flags-contract/package.json
packages/js-dapi-client/package.json
packages/js-dash-sdk/package.json
packages/js-dpp/package.json
packages/js-drive/package.json
packages/js-grpc-common/package.json
packages/masternode-reward-shares-contract/package.json
packages/platform-test-suite/package.json
packages/rs-drive-nodejs/package.json
packages/wallet-lib/package.json
packages/wasm-dpp/package.json
packages/withdrawals-contract/package.json

chore(release): update changelog and bump version to 0.24.0-dev.23

---

Cargo.lock
packages/rs-dpp/Cargo.toml
packages/rs-dpp/src/block/epoch.rs
packages/rs-dpp/src/data_contract/generate_data_contract.rs
packages/rs-dpp/src/data_contract/state_transition/data_contract_update_transition/validation/state/validate_data_contract_update_transition_state.rs
packages/rs-dpp/src/document/state_transition/documents_batch_transition/document_transition/action.rs
packages/rs-dpp/src/identity/state_transition/identity_credit_withdrawal_transition/mod.rs
packages/rs-dpp/src/identity/state_transition/identity_update_transition/identity_update_transition.rs
packages/rs-dpp/src/state_transition/serialization.rs
packages/rs-dpp/src/tests/document/state_transitions/validation/validate_documents_uniqueness_by_indices_spec.rs
packages/rs-drive-abci/src/abci/withdrawal.rs
packages/rs-drive-abci/src/execution/helpers.rs
packages/rs-drive-abci/src/execution/masternode_identities/mod.rs
packages/rs-drive-abci/tests/strategy_tests/main.rs
packages/rs-drive-abci/tests/strategy_tests/upgrade_fork_tests.rs
packages/rs-drive/src/drive/document/update.rs
packages/rs-drive/src/drive/grove_operations.rs
packages/rs-drive/src/drive/protocol_upgrade/mod.rs
packages/rs-drive/src/fee_pools/epochs/mod.rs

There are 3 tests:
* one for when quorums rotate because of core chain lock height going up.
* one for when hpmns come in.
* one for when hpmns are removed.

test: chainlock quorum rotation test

---

packages/platform-test-suite/test/functional/platform/Identity.spec.js

Masternode identities test expects identities for invalid ins
- Skip invalid mns
Manually
None

fix(test-suite): expects identities for invalid mns

---

packages/rs-drive-abci/src/abci/handlers.rs
packages/rs-platform-value/src/inner_value.rs

fix: init chain core chain lock failure

---

CHANGELOG.md
package.json
packages/bench-suite/package.json
packages/dapi-grpc/package.json
packages/dapi/package.json
packages/dash-spv/package.json
packages/dashmate/package.json
packages/dashpay-contract/package.json
packages/dpns-contract/package.json
packages/feature-flags-contract/package.json
packages/js-dapi-client/package.json
packages/js-dash-sdk/package.json
packages/js-dpp/package.json
packages/js-drive/package.json
packages/js-grpc-common/package.json
packages/masternode-reward-shares-contract/package.json
packages/platform-test-suite/package.json
packages/rs-drive-nodejs/package.json
packages/wallet-lib/package.json
packages/wasm-dpp/package.json
packages/withdrawals-contract/package.json

chore(release): update changelog and bump version to 0.24.0-dev.25

---

CHANGELOG.md
package.json
packages/bench-suite/package.json
packages/dapi-grpc/package.json
packages/dapi/package.json
packages/dash-spv/package.json
packages/dashmate/package.json
packages/dashpay-contract/package.json
packages/dpns-contract/package.json
packages/feature-flags-contract/package.json
packages/js-dapi-client/package.json
packages/js-dash-sdk/package.json
packages/js-dpp/package.json
packages/js-drive/package.json
packages/js-grpc-common/package.json
packages/masternode-reward-shares-contract/package.json
packages/platform-test-suite/package.json
packages/rs-drive-nodejs/package.json
packages/wallet-lib/package.json
packages/wasm-dpp/package.json
packages/withdrawals-contract/package.json

chore(release): update changelog and bump version to 0.24.0-dev.26

---

CHANGELOG.md
package.json
packages/bench-suite/package.json
packages/dapi-grpc/package.json
packages/dapi/package.json
packages/dash-spv/package.json
packages/dashmate/package.json
packages/dashpay-contract/package.json
packages/dpns-contract/package.json
packages/feature-flags-contract/package.json
packages/js-dapi-client/package.json
packages/js-dash-sdk/package.json
packages/js-dpp/package.json
packages/js-drive/package.json
packages/js-grpc-common/package.json
packages/masternode-reward-shares-contract/package.json
packages/platform-test-suite/package.json
packages/rs-drive-nodejs/package.json
packages/wallet-lib/package.json
packages/wasm-dpp/package.json
packages/withdrawals-contract/package.json

chore(release): update changelog and bump version to 0.24.0-dev.27

---

packages/dashmate/src/listr/tasks/resetNodeTaskFactory.js

If you run reset on already reset config it will fail with "no such volume"
- Force removing volumes
Manually
None

fix(dashmate): can't remove volumes if they not exist

---

packages/dashmate/src/status/scopes/masternode.js
packages/dashmate/test/unit/status/scopes/masternode.spec.js

`dashmate status` command shows empty masternode state while it is syncing
Fixed `dashmate status` command
Manual
No

fix(dashmate): show masternode state while it is not synced

---

CHANGELOG.md
package.json
packages/bench-suite/package.json
packages/dapi-grpc/package.json
packages/dapi/package.json
packages/dash-spv/package.json
packages/dashmate/package.json
packages/dashpay-contract/package.json
packages/dpns-contract/package.json
packages/feature-flags-contract/package.json
packages/js-dapi-client/package.json
packages/js-dash-sdk/package.json
packages/js-dpp/package.json
packages/js-drive/package.json
packages/js-grpc-common/package.json
packages/masternode-reward-shares-contract/package.json
packages/platform-test-suite/package.json
packages/rs-drive-nodejs/package.json
packages/wallet-lib/package.json
packages/wasm-dpp/package.json
packages/withdrawals-contract/package.json

chore(release): update changelog and bump version to 0.24.0-dev.28

---

packages/dashmate/src/listr/tasks/resetNodeTaskFactory.js

The reset command with `--platform` flag affects core as well
- Filter out core containers to remove
Manually
None

fix(dashmate): reset platform affects core

---

packages/js-drive/lib/abci/handlers/initChainHandlerFactory.js
packages/js-drive/test/unit/abci/handlers/initChainHandlerFactory.spec.js

Double init chain call leads to side bugs that spoil the state and complicate debugging
- Reset the state and fail with error if state is not empty on init chain
Manually
None

fix(drive): double init chain leads to side bugs

---

CHANGELOG.md
package.json
packages/bench-suite/package.json
packages/dapi-grpc/package.json
packages/dapi/package.json
packages/dash-spv/package.json
packages/dashmate/package.json
packages/dashpay-contract/package.json
packages/dpns-contract/package.json
packages/feature-flags-contract/package.json
packages/js-dapi-client/package.json
packages/js-dash-sdk/package.json
packages/js-dpp/package.json
packages/js-drive/package.json
packages/js-grpc-common/package.json
packages/masternode-reward-shares-contract/package.json
packages/platform-test-suite/package.json
packages/rs-drive-nodejs/package.json
packages/wallet-lib/package.json
packages/wasm-dpp/package.json
packages/withdrawals-contract/package.json

chore(release): update changelog and bump version to 0.24.0-dev.29

---

CHANGELOG.md
package.json
packages/bench-suite/package.json
packages/dapi-grpc/package.json
packages/dapi/package.json
packages/dash-spv/package.json
packages/dashmate/package.json
packages/dashpay-contract/package.json
packages/dpns-contract/package.json
packages/feature-flags-contract/package.json
packages/js-dapi-client/package.json
packages/js-dash-sdk/package.json
packages/js-dpp/package.json
packages/js-drive/package.json
packages/js-grpc-common/package.json
packages/masternode-reward-shares-contract/package.json
packages/platform-test-suite/package.json
packages/rs-drive-nodejs/package.json
packages/wallet-lib/package.json
packages/wasm-dpp/package.json
packages/withdrawals-contract/package.json

chore(release): update changelog and bump version to 0.24.0-dev.30

---

packages/rs-dpp/src/state_transition/mod.rs
packages/rs-platform-serialization/src/lib.rs

Platform signable worked great on structs but did not work well at all on enums, in this PR we add the ability to derive PlatformSignable to Enums.

feat: platform signable on enums

---

CHANGELOG.md
package.json
packages/bench-suite/package.json
packages/dapi-grpc/package.json
packages/dapi/package.json
packages/dash-spv/package.json
packages/dashmate/package.json
packages/dashpay-contract/package.json
packages/dpns-contract/package.json
packages/feature-flags-contract/package.json
packages/js-dapi-client/package.json
packages/js-dash-sdk/package.json
packages/js-dpp/package.json
packages/js-grpc-common/package.json
packages/masternode-reward-shares-contract/package.json
packages/platform-test-suite/package.json
packages/wallet-lib/package.json
packages/wasm-dpp/package.json
packages/withdrawals-contract/package.json

chore(release): update changelog and bump version to 0.25.0-dev.1

---

CHANGELOG.md
package.json
packages/bench-suite/package.json
packages/dapi-grpc/package.json
packages/dapi/package.json
packages/dash-spv/package.json
packages/dashmate/package.json
packages/dashpay-contract/package.json
packages/dpns-contract/package.json
packages/feature-flags-contract/package.json
packages/js-dapi-client/package.json
packages/js-dash-sdk/package.json
packages/js-dpp/package.json
packages/js-grpc-common/package.json
packages/masternode-reward-shares-contract/package.json
packages/platform-test-suite/package.json
packages/wallet-lib/package.json
packages/wasm-dpp/package.json
packages/withdrawals-contract/package.json

chore(release): update changelog and bump version to 0.25.0-dev.2

---

CHANGELOG.md
package.json
packages/bench-suite/package.json
packages/dapi-grpc/package.json
packages/dapi/package.json
packages/dash-spv/package.json
packages/dashmate/package.json
packages/dashpay-contract/package.json
packages/dpns-contract/package.json
packages/feature-flags-contract/package.json
packages/js-dapi-client/package.json
packages/js-dash-sdk/package.json
packages/js-dpp/package.json
packages/js-drive/package.json
packages/js-grpc-common/package.json
packages/masternode-reward-shares-contract/package.json
packages/platform-test-suite/package.json
packages/rs-drive-nodejs/package.json
packages/wallet-lib/package.json
packages/wasm-dpp/package.json
packages/withdrawals-contract/package.json

chore(release): update changelog and bump version to 0.24.0-dev.31

---

packages/dashmate/src/listr/tasks/setup/setupLocalPresetTaskFactory.js

If you run dashmate with `yarn dashmate setup local` command, it fails with `waitForQuorumConnections deadline of 300000 exceeded` error
Fixed getting nodes count prompt function
Manual
No

fix(dashmate): waitForQuorumConnections deadline of 300000 exceeded

---

packages/rs-drive-abci/src/abci/handlers.rs
packages/rs-drive/src/drive/identity/fetch/fetch_by_public_key_hashes.rs
packages/rs-drive/src/drive/query/mod.rs
packages/rs-platform-value/src/lib.rs
packages/rs-platform-value/src/types/bytes_20.rs

A query send to the system shouldn't cause a panic if the query is not valid.
Also implemented new methods for fetching identities by public key hashes.

fix: query error shouldn't break system

---

packages/rs-drive-abci/src/abci/handlers.rs
packages/rs-drive-abci/tests/strategy_tests/upgrade_fork_tests.rs

The protocol version signaling logic has source on non-determinsm
- Disabled for v0.24 so we can investigate and fix it in v0.25 if it's still exist
On testnet
Previous state won't be valid

chore!: disable protocol version signaling

---

.github/workflows/release.yml

Relase Drive adn Test Suite failed due to timeout https://github.com/dashpay/platform/actions/runs/4884778160/attempts/1
- Increased timeouts docker images build jobs
None
None

ci: increase release timeouts

---

CHANGELOG.md
package.json
packages/bench-suite/package.json
packages/dapi-grpc/package.json
packages/dapi/package.json
packages/dash-spv/package.json
packages/dashmate/package.json
packages/dashpay-contract/package.json
packages/dpns-contract/package.json
packages/feature-flags-contract/package.json
packages/js-dapi-client/package.json
packages/js-dash-sdk/package.json
packages/js-dpp/package.json
packages/js-drive/package.json
packages/js-grpc-common/package.json
packages/masternode-reward-shares-contract/package.json
packages/platform-test-suite/package.json
packages/rs-drive-nodejs/package.json
packages/wallet-lib/package.json
packages/wasm-dpp/package.json
packages/withdrawals-contract/package.json

chore(release): update changelog and bump version to 0.24.0-dev.33

---

packages/dapi/lib/grpcServer/handlers/platform/waitForStateTransitionResultHandlerFactory.js
packages/dapi/test/integration/grpcServer/handlers/platform/waitForStateTransitionResultHandlerFactory.spec.js
packages/dapi/test/unit/grpcServer/handlers/platform/getDataContractHandlerFactory.spec.js
packages/dapi/test/unit/grpcServer/handlers/platform/getDocumentsHandlerFactory.spec.js
packages/dapi/test/unit/grpcServer/handlers/platform/getIdentitiesByPublicKeyHashesHandlerFactory.spec.js
packages/dapi/test/unit/grpcServer/handlers/platform/getIdentityHandlerFactory.spec.js
packages/js-dapi-client/lib/methods/platform/response/Proof.js
packages/js-dapi-client/test/unit/methods/platform/getDataContract/GetDataContractResponse.spec.js
packages/js-dapi-client/test/unit/methods/platform/getDataContract/getDataContractFactory.spec.js
packages/js-dapi-client/test/unit/methods/platform/getDocuments/GetDocumentsResponse.spec.js
packages/js-dapi-client/test/unit/methods/platform/getDocuments/getDocumentsFactory.spec.js
packages/js-dapi-client/test/unit/methods/platform/getIdentitiesByPublicKeyHashes/GetIdentitiesByPublicKeyHashesResponse.spec.js
packages/js-dapi-client/test/unit/methods/platform/getIdentitiesByPublicKeyHashes/getIdentitiesByPublicKeyHashesFactory.spec.js
packages/js-dapi-client/test/unit/methods/platform/getIdentitiy/GetIdentityResponse.spec.js
packages/js-dapi-client/test/unit/methods/platform/getIdentitiy/getIdentityFactory.spec.js
packages/js-dapi-client/test/unit/methods/platform/waitForStateTransitionResult/waitForStateTransitionResultFactory.spec.js

fix: merkle proof in proto messages instead of grovedb proof

---

packages/dashmate/src/listr/tasks/resetNodeTaskFactory.js

The reset platform command hangs
- Removed docker container if platform in use
Manually
None

fix(dashmate): reset platform commands hangs

---

CHANGELOG.md
package.json
packages/bench-suite/package.json
packages/dapi-grpc/package.json
packages/dapi/package.json
packages/dash-spv/package.json
packages/dashmate/package.json
packages/dashpay-contract/package.json
packages/dpns-contract/package.json
packages/feature-flags-contract/package.json
packages/js-dapi-client/package.json
packages/js-dash-sdk/package.json
packages/js-dpp/package.json
packages/js-drive/package.json
packages/js-grpc-common/package.json
packages/masternode-reward-shares-contract/package.json
packages/platform-test-suite/package.json
packages/rs-drive-nodejs/package.json
packages/wallet-lib/package.json
packages/wasm-dpp/package.json
packages/withdrawals-contract/package.json

chore(release): update changelog and bump version to 0.24.0-dev.34

---

packages/rs-drive-abci/src/abci/handlers.rs
packages/rs-drive-abci/src/execution/engine.rs
packages/rs-drive-abci/src/execution/processor.rs

This was a small fix to make the system work.
We replaced an empty byte array with the transaction data.

fix: fix transaction results to include original transaction

---

packages/dashmate/configs/system/base.js
packages/dashmate/configs/system/testnet.js

In order to connect to the new platform network on testnet we need to update dashmate configs
- Updated genesis and other options in testnet preset
Syncing a testnet node with testnet
None

chore(dashmate): update testnet preset

---

packages/js-dapi-client/lib/methods/platform/waitForStateTransitionResult/waitForStateTransitionResultFactory.js
packages/platform-test-suite/lib/test/createClientWithFundedWallet.js
packages/platform-test-suite/lib/test/createClientWithoutWallet.js
packages/platform-test-suite/test/functional/platform/DataContract.spec.js

Block production on testnet is pretty slow 5-80 seconds
- Increase client side timeouts
Running test suite aginst testnet
None

chore: increase client side timeouts

---

packages/dashmate/configs/system/base.js
packages/dashmate/test/unit/status/scopes/masternode.spec.js

Sentinel needs to be updated to 1.7.3 to support core 19.0.0
Bump sentinel version in config and tests
Untested
None

chore: bump sentinel to 1.7.3

---

packages/dashmate/src/listr/prompts/createIpAndPortsForm.js

Detecting external IP in `dashmate setup` hangs sometimes
- Added 10 secs timeout
Manually
None

fix(dashmate): external IP detection hangs sometimes

---

CHANGELOG.md
package.json
packages/bench-suite/package.json
packages/dapi-grpc/package.json
packages/dapi/package.json
packages/dash-spv/package.json
packages/dashmate/package.json
packages/dashpay-contract/package.json
packages/dpns-contract/package.json
packages/feature-flags-contract/package.json
packages/js-dapi-client/package.json
packages/js-dash-sdk/package.json
packages/js-dpp/package.json
packages/js-drive/package.json
packages/js-grpc-common/package.json
packages/masternode-reward-shares-contract/package.json
packages/platform-test-suite/package.json
packages/rs-drive-nodejs/package.json
packages/wallet-lib/package.json
packages/wasm-dpp/package.json
packages/withdrawals-contract/package.json

chore(release): update changelog and bump version to 0.24.0

---

packages/js-dash-sdk/src/SDK/Client/Platform/methods/identities/get.ts
packages/js-drive/lib/identity/masternode/createMasternodeIdentityFactory.js
packages/js-drive/lib/identity/masternode/handleUpdatedScriptPayoutFactory.js
packages/js-drive/test/unit/identity/masternode/createMasternodeIdentityFactory.spec.js
packages/js-drive/test/unit/identity/masternode/handleUpdatedScriptPayoutFactory.spec.js
packages/platform-test-suite/test/e2e/masternodeRewardShares.spec.js
packages/platform-test-suite/test/functional/platform/Identity.spec.js

```
[2023-05-10 13:48:54.686 +0000] FATAL (35 on b77bca396627): identity: a unique key with that hash already exists: the key already exists in the unique set
driveVersion: "0.24.0-dev.34"
height: "251"
round: 2
abciMethod: "prepareProposal"
err: {
"type": "Error",
"message": "identity: a unique key with that hash already exists: the key already exists in the unique set",
"stack":
Error: identity: a unique key with that hash already exists: the key already exists in the unique set
at Object.appendStackWrapper (/platform/packages/rs-drive-nodejs/appendStack.js:10:18)
at async IdentityStoreRepository.create (/platform/packages/js-drive/lib/identity/IdentityStoreRepository.js:170:25)
at async createMasternodeIdentity (/platform/packages/js-drive/lib/identity/masternode/createMasternodeIdentit …
```

fix!: unique key with that hash already exists

---

packages/dashmate/configs/migrations.js
packages/dashmate/configs/system/base.js

Released Dashmate uses dev images.
Now the image version is taking from package.json. Added missed v0.24 migration
Manual
No

fix(dashmate): outdated docker images and missed migration 

---

packages/js-dapi-client/lib/networkConfigs.js

Tutorials on Dash Platform documentation website doesn't work
- Added port and self signed certificate flag to testnet seeds
@pshenmic please test this out
None

fix(dapi): can't connect to testnet with default seeds

---

CHANGELOG.md
package.json
packages/bench-suite/package.json
packages/dapi-grpc/package.json
packages/dapi/package.json
packages/dash-spv/package.json
packages/dashmate/package.json
packages/dashpay-contract/package.json
packages/dpns-contract/package.json
packages/feature-flags-contract/package.json
packages/js-dapi-client/package.json
packages/js-dash-sdk/package.json
packages/js-dpp/package.json
packages/js-drive/package.json
packages/js-grpc-common/package.json
packages/masternode-reward-shares-contract/package.json
packages/platform-test-suite/package.json
packages/rs-drive-nodejs/package.json
packages/wallet-lib/package.json
packages/wasm-dpp/package.json
packages/withdrawals-contract/package.json

chore(release): update changelog and bump version to 0.24.1

---

CHANGELOG.md
packages/dashmate/configs/migrations.js
packages/dashmate/configs/system/base.js
packages/dashmate/src/commands/restart.js
packages/dashmate/src/commands/setup.js
packages/dashmate/src/commands/start.js
packages/dashmate/src/commands/stop.js
packages/dashmate/src/listr/tasks/registerMasternodeTaskFactory.js
packages/dashmate/src/listr/tasks/restartNodeTaskFactory.js
packages/dashmate/src/listr/tasks/setup/nodeTypes.js
packages/dashmate/src/listr/tasks/setup/regular/configureSSLCertificateTaskFactory.js
packages/dashmate/src/listr/tasks/setup/setupRegularPresetTaskFactory.js
packages/dashmate/src/listr/tasks/startNodeTaskFactory.js
packages/dashmate/src/listr/tasks/stopNodeTaskFactory.js
packages/js-dapi-client/lib/networkConfigs.js

Incrememntal backports of valuable changes from v0.24
- Backport from v0.24.0 to v0.24.1 changes to v0.25-dev
None
None

chore: backports from v0.24.0 to v0.24.1

---

packages/rs-dpp/Cargo.toml
packages/rs-drive-abci/src/asset_lock/fetch_tx_out.rs
packages/rs-drive-abci/src/rpc/core.rs

Added a core retry capability. If core responds with an error we retry 4 times using a fibonacci increase.

feat(rs-drive-abci): added a retry capability

---

CHANGELOG.md
package.json
packages/bench-suite/package.json
packages/dapi-grpc/package.json
packages/dapi/package.json
packages/dash-spv/package.json
packages/dashmate/package.json
packages/dashpay-contract/package.json
packages/dpns-contract/package.json
packages/feature-flags-contract/package.json
packages/js-dapi-client/package.json
packages/js-dash-sdk/package.json
packages/js-dpp/package.json
packages/js-drive/package.json
packages/js-grpc-common/package.json
packages/masternode-reward-shares-contract/package.json
packages/platform-test-suite/package.json
packages/rs-drive-nodejs/package.json
packages/wallet-lib/package.json
packages/wasm-dpp/package.json
packages/withdrawals-contract/package.json

chore(release): update changelog and bump version to 0.24.2

---

CHANGELOG.md
package.json
packages/bench-suite/package.json
packages/dapi-grpc/package.json
packages/dapi/package.json
packages/dash-spv/package.json
packages/dashmate/package.json
packages/dashpay-contract/package.json
packages/dpns-contract/package.json
packages/feature-flags-contract/package.json
packages/js-dapi-client/package.json
packages/js-dash-sdk/package.json
packages/js-dpp/package.json
packages/js-drive/package.json
packages/js-grpc-common/package.json
packages/masternode-reward-shares-contract/package.json
packages/platform-test-suite/package.json
packages/rs-drive-nodejs/package.json
packages/wallet-lib/package.json
packages/wasm-dpp/package.json
packages/withdrawals-contract/package.json

chore(release): update changelog and bump version to 0.24.3

---

packages/rs-drive-abci/src/execution/check_tx.rs
packages/rs-drive-abci/src/execution/processor.rs
packages/rs-drive-abci/src/execution/types/execution_event.rs

A top up transition wasn't taking into account the top up balance before it was checking to see if there was enough balance.

fix : identity top balance issue

---

.github/workflows/pr.yml

`action-semantic-pull-request` looks not so nice in checks
- Add a name to the step
None

ci: add a name to PR linter step

---

packages/dashmate/templates/platform/dapi/envoy/envoy.yaml.dot

Android client fails to connect to testnet with an error:
```Failed ALPN negotiation: Unable to find compatible protocol```
- Added HTTP1 and HTTP2 to `alpn_protocols` in envoy config
On testnet
None

fix(dashmate): unable to find compatible protocol

---

CHANGELOG.md
package.json
packages/bench-suite/package.json
packages/dapi-grpc/package.json
packages/dapi/package.json
packages/dash-spv/package.json
packages/dashmate/package.json
packages/dashpay-contract/package.json
packages/dpns-contract/package.json
packages/feature-flags-contract/package.json
packages/js-dapi-client/package.json
packages/js-dash-sdk/package.json
packages/js-dpp/package.json
packages/js-drive/package.json
packages/js-grpc-common/package.json
packages/masternode-reward-shares-contract/package.json
packages/platform-test-suite/package.json
packages/rs-drive-nodejs/package.json
packages/wallet-lib/package.json
packages/wasm-dpp/package.json
packages/withdrawals-contract/package.json

chore(release): update changelog and bump version to 0.24.4

---

CHANGELOG.md
package.json
packages/bench-suite/package.json
packages/dapi-grpc/package.json
packages/dapi/package.json
packages/dash-spv/package.json
packages/dashmate/package.json
packages/dashpay-contract/package.json
packages/dpns-contract/package.json
packages/feature-flags-contract/package.json
packages/js-dapi-client/package.json
packages/js-dash-sdk/package.json
packages/js-dpp/package.json
packages/js-drive/package.json
packages/js-grpc-common/package.json
packages/masternode-reward-shares-contract/package.json
packages/platform-test-suite/package.json
packages/rs-drive-nodejs/package.json
packages/wallet-lib/package.json
packages/wasm-dpp/package.json
packages/withdrawals-contract/package.json

chore(release): update changelog and bump version to 0.24.5

---

packages/dashmate/src/listr/tasks/setup/local/configureCoreTaskFactory.js

`setup` command throws fatal error from time to time: `TypeError: Cannot read properties of undefined (reading 'status')`
Fixed dashmate setup command
Manual
No

fix(dashmate): cannot read properties of undefined (reading 'status')

---

packages/platform-test-suite/test/e2e/dpns.spec.js
packages/platform-test-suite/test/e2e/masternodeRewardShares.spec.js
packages/platform-test-suite/test/functional/core/getBlock.spec.js
packages/platform-test-suite/test/functional/platform/Identity.spec.js
packages/platform-test-suite/test/functional/platform/featureFlags.spec.js
packages/platform-test-suite/test/functional/platform/proofs.spec.js
packages/wasm-dpp/src/document/document_facade.rs

As a part of integration with rs-drive-abci, restored some basic platform tests and skipped ones that needs updating or further debugging
- platform test stuite with local network

test(test-suite): skip failing tests and provide details for them

---

packages/wallet-lib/src/logger/index.js
packages/wallet-lib/src/plugins/Workers/TransactionsSyncWorker/TransactionsReader.js
packages/wallet-lib/src/plugins/Workers/TransactionsSyncWorker/TransactionsReader.spec.js
packages/wallet-lib/src/plugins/Workers/TransactionsSyncWorker/TransactionsSyncWorker.js
packages/wallet-lib/src/test/mocks/dashcore/instantlock.js
packages/wallet-lib/tests/integration/plugins/Workers/TransactionsSyncWorker.spec.js

Backport of https://github.com/dashpay/platform/pull/1126

fix(wallet-lib): instant locks not arriving to HD wallets (#1126)

---

packages/rs-drive-abci/src/execution/fee_pools/distribute_storage_pool.rs
packages/rs-drive-abci/src/execution/fee_pools/epoch.rs
packages/rs-drive-abci/src/execution/fee_pools/fee_distribution.rs
packages/rs-drive-abci/src/execution/fee_pools/process_block_fees.rs
packages/rs-drive-abci/tests/strategy_tests/main.rs
packages/rs-drive/src/drive/batch/drive_op_batch/mod.rs
packages/rs-drive/src/drive/batch/grovedb_op_batch.rs
packages/rs-drive/src/drive/fee_pools/epochs/credit_distribution_pools.rs
packages/rs-drive/src/drive/fee_pools/epochs/proposers.rs
packages/rs-drive/src/drive/fee_pools/epochs/start_block.rs
packages/rs-drive/src/drive/fee_pools/pending_epoch_refunds.rs
packages/rs-drive/src/drive/genesis_time.rs
packages/rs-drive/src/fee_pools/epochs/epoch_key_constants.rs
packages/rs-drive/src/fee_pools/epochs/operations_factory.rs

This is the PR for Core Block Reward Distribution.
In this PR we add the block subsidy from Core. Parameters are still to be fined tuned but the overall approach is done.
The overall system works by counting the core blocks between two Epochs, then on epoch change paying out to proposers of the epoch based on the amount of core blocks that occurred.
Limited payout per block were removed since this logic doesn't work after total credit balance implementation.
Verified through tests that the amounts were added to proposers on Epoch End.
Platform state is modified so previous data won't be valid

feat(drive)!: core block reward distribution

---

packages/wallet-lib/src/types/Account/methods/getUTXOS.js

Fix checks maturity for all coinbase transactions 
Remove check for special transactions as a criteria of checking coinbase maturity
- CI
- Manual testing on devnet absinthe

fix(wallet-lib): spending immature coinbase transactions

---

Cargo.lock
packages/rs-drive-abci/src/core/mod.rs
packages/rs-drive-abci/src/lib.rs
packages/rs-drive-abci/src/main.rs
packages/rs-drive-abci/src/rpc/core.rs

Drive and Tenderdash rely on Core. We need to make sure that Core is synced before we start Drive and Tenderdash, otherwise various functions will fail.
- Wait for Core to sync before we start ABCI application (so Tenderdash is waiting as well)
None
None

fix(drive): wait for core to sync

---

packages/js-dapi-client/lib/transport/JsonRpcTransport/requestJsonRpc.js

A flaky failure in CI:
```
FetchError: invalid json response body at https://127.0.0.1:2443/ reason: Unexpected token u in JSON at position 0
at /opt/actions-runner/_work/platform/platform/.yarn/__virtual__/node-fetch-virtual-a3f0ba2944/0/cache/node-fetch-npm-2.6.7-777aa2a6df-8d816ffd1e.zip/node_modules/node-fetch/lib/index.js:273:32
```
- Parse JSON body after checking for response validness
- With CI

fix(dapi): invalid json response body

---

packages/rs-drive-abci/src/abci/handlers.rs
packages/rs-drive-abci/src/rpc/core.rs

revert(drive): ensure that chain lock height valid

---

packages/rs-drive/src/drive/verify/contract.rs
packages/rs-drive/src/drive/verify/document.rs
packages/rs-drive/src/drive/verify/identity.rs
packages/rs-drive/src/drive/verify/single_document.rs

Better docs for verify functions in drive.

docs: better drive verify docs

---

CHANGELOG.md
package.json
packages/bench-suite/package.json
packages/dapi-grpc/package.json
packages/dapi/package.json
packages/dash-spv/package.json
packages/dashmate/package.json
packages/dashpay-contract/package.json
packages/dpns-contract/package.json
packages/feature-flags-contract/package.json
packages/js-dapi-client/package.json
packages/js-dash-sdk/package.json
packages/js-dpp/package.json
packages/js-drive/package.json
packages/js-grpc-common/package.json
packages/masternode-reward-shares-contract/package.json
packages/platform-test-suite/package.json
packages/rs-drive-nodejs/package.json
packages/wallet-lib/package.json
packages/wasm-dpp/package.json
packages/withdrawals-contract/package.json

chore(release): update changelog and bump version to 0.24.6

---

CHANGELOG.md
package.json
packages/bench-suite/package.json
packages/dapi-grpc/package.json
packages/dapi/package.json
packages/dash-spv/package.json
packages/dashmate/package.json
packages/dashpay-contract/package.json
packages/dpns-contract/package.json
packages/feature-flags-contract/package.json
packages/js-dapi-client/package.json
packages/js-dash-sdk/package.json
packages/js-dpp/package.json
packages/js-drive/package.json
packages/js-grpc-common/package.json
packages/masternode-reward-shares-contract/package.json
packages/platform-test-suite/package.json
packages/rs-drive-nodejs/package.json
packages/wallet-lib/package.json
packages/wasm-dpp/package.json
packages/withdrawals-contract/package.json

chore(release): update changelog and bump version to 0.24.7

---

packages/dashmate/src/listr/tasks/resetNodeTaskFactory.js

Hard reset doesn't delete related configuration files like  SSL certificates 
- Delete related configuration files with the `--hard` flag
Manually
SSL certificates and other configuration files will be deleted with the hard reset command

feat(dashmate)!: hard reset deletes related files

---

packages/dashmate/src/listr/tasks/ssl/zerossl/obtainZeroSSLCertificateTaskFactory.js

Certificate download logic suppose to retry the download process if certificate is not ready but it's not
- Fixed retry logic
Manually
None

fix(dashmate): download certificate retry logic

---

.github/workflows/manage-runs.yml

https://github.com/dashpay/platform/pull/1179 code based on outdated API
- Update "cancel runs for merged PRs" job to use current Github API
None
None

ci: fix cancel runs for already merged PRs

---

CHANGELOG.md
package.json
packages/bench-suite/package.json
packages/dapi-grpc/package.json
packages/dapi/package.json
packages/dash-spv/package.json
packages/dashmate/package.json
packages/dashpay-contract/package.json
packages/dpns-contract/package.json
packages/feature-flags-contract/package.json
packages/js-dapi-client/package.json
packages/js-dash-sdk/package.json
packages/js-dpp/package.json
packages/js-drive/package.json
packages/js-grpc-common/package.json
packages/masternode-reward-shares-contract/package.json
packages/platform-test-suite/package.json
packages/rs-drive-nodejs/package.json
packages/wallet-lib/package.json
packages/wasm-dpp/package.json
packages/withdrawals-contract/package.json

chore(release): update changelog and bump version to 0.24.9

---

CHANGELOG.md
package.json
packages/bench-suite/package.json
packages/dapi-grpc/package.json
packages/dapi/package.json
packages/dash-spv/package.json
packages/dashmate/package.json
packages/dashpay-contract/package.json
packages/dpns-contract/package.json
packages/feature-flags-contract/package.json
packages/js-dapi-client/package.json
packages/js-dash-sdk/package.json
packages/js-dpp/package.json
packages/js-drive/package.json
packages/js-grpc-common/package.json
packages/masternode-reward-shares-contract/package.json
packages/platform-test-suite/package.json
packages/rs-drive-nodejs/package.json
packages/wallet-lib/package.json
packages/wasm-dpp/package.json
packages/withdrawals-contract/package.json

chore(release): update changelog and bump version to 0.24.10

---

CHANGELOG.md
package.json
packages/bench-suite/package.json
packages/dapi-grpc/package.json
packages/dapi/package.json
packages/dash-spv/package.json
packages/dashmate/package.json
packages/dashpay-contract/package.json
packages/dpns-contract/package.json
packages/feature-flags-contract/package.json
packages/js-dapi-client/package.json
packages/js-dash-sdk/package.json
packages/js-dpp/package.json
packages/js-drive/package.json
packages/js-grpc-common/package.json
packages/masternode-reward-shares-contract/package.json
packages/platform-test-suite/package.json
packages/rs-drive-nodejs/package.json
packages/wallet-lib/package.json
packages/wasm-dpp/package.json
packages/withdrawals-contract/package.json

chore(release): update changelog and bump version to 0.24.11

---

CHANGELOG.md
package.json
packages/bench-suite/package.json
packages/dapi-grpc/package.json
packages/dapi/package.json
packages/dash-spv/package.json
packages/dashmate/package.json
packages/dashpay-contract/package.json
packages/dpns-contract/package.json
packages/feature-flags-contract/package.json
packages/js-dapi-client/package.json
packages/js-dash-sdk/package.json
packages/js-dpp/package.json
packages/js-drive/package.json
packages/js-grpc-common/package.json
packages/masternode-reward-shares-contract/package.json
packages/platform-test-suite/package.json
packages/rs-drive-nodejs/package.json
packages/wallet-lib/package.json
packages/wasm-dpp/package.json
packages/withdrawals-contract/package.json

chore(release): update changelog and bump version to 0.24.12

---

packages/dashmate/configs/migrations.js

Migrations fails to apply with message
`TypeError: Cannot read properties of undefined (reading 'helper')`
* Fixed migration dashmate helper api config path
* Added check for platform check for `pprof`
Locally
No

fix(dashmate): invalid migration

---

CHANGELOG.md
package.json
packages/bench-suite/package.json
packages/dapi-grpc/package.json
packages/dapi/package.json
packages/dash-spv/package.json
packages/dashmate/package.json
packages/dashpay-contract/package.json
packages/dpns-contract/package.json
packages/feature-flags-contract/package.json
packages/js-dapi-client/package.json
packages/js-dash-sdk/package.json
packages/js-dpp/package.json
packages/js-drive/package.json
packages/js-grpc-common/package.json
packages/masternode-reward-shares-contract/package.json
packages/platform-test-suite/package.json
packages/rs-drive-nodejs/package.json
packages/wallet-lib/package.json
packages/wasm-dpp/package.json
packages/withdrawals-contract/package.json

chore(release): update changelog and bump version to 0.24.13

---

packages/dashmate/configs/migrations.js
packages/dashmate/configs/system/base.js
packages/dashmate/configs/system/mainnet.js
packages/dashmate/configs/system/testnet.js

Bump dashcore version to 19.2.0
Updated values in base, testnet and mainnet configs

chore(dashmate): bump dashcore version to 19.2.0

---

packages/dashmate/configs/schema/configJsonSchema.js
packages/dashmate/src/update/updateNodeFactory.js

Scheme missing sentinel in required and dashmate update loose variable after unclean refactor.
* Added sentinel in the required list in the config schema
* Fixed `name` variable in the `updateNodeTask`
Locally + devnet
No

fix(dashmate): invalid variable name

---

CHANGELOG.md
package.json
packages/bench-suite/package.json
packages/dapi-grpc/package.json
packages/dapi/package.json
packages/dash-spv/package.json
packages/dashmate/package.json
packages/dashpay-contract/package.json
packages/dpns-contract/package.json
packages/feature-flags-contract/package.json
packages/js-dapi-client/package.json
packages/js-dash-sdk/package.json
packages/js-dpp/package.json
packages/js-drive/package.json
packages/js-grpc-common/package.json
packages/masternode-reward-shares-contract/package.json
packages/platform-test-suite/package.json
packages/rs-drive-nodejs/package.json
packages/wallet-lib/package.json
packages/wasm-dpp/package.json
packages/withdrawals-contract/package.json

chore(release): update changelog and bump version to 0.24.14

---

.github/workflows/all-packages.yml

```
├─ @grpc/grpc-js: 1.4.4
│  ├─ ID: 1092393
│  ├─ Issue: Connection confusion in gRPC
│  ├─ URL: https://github.com/advisories/GHSA-cfgp-2977-2fmm
│  ├─ Severity: high
│  ├─ Vulnerable Versions: <1.8.8
│  ├─ Patched Versions: >=1.8.8
│  ├─ Via: @grpc/grpc-js
│  └─ Recommendation: Upgrade to version 1.8.8 or later
```
- Temporary ignored this vulnerability until long term solution is done
None
None

ci: temporary ignore gRPC JS vulnerability

---

CHANGELOG.md
package.json
packages/bench-suite/package.json
packages/dapi-grpc/package.json
packages/dapi/package.json
packages/dash-spv/package.json
packages/dashmate/package.json
packages/dashpay-contract/package.json
packages/dpns-contract/package.json
packages/feature-flags-contract/package.json
packages/js-dapi-client/package.json
packages/js-dash-sdk/package.json
packages/js-dpp/package.json
packages/js-drive/package.json
packages/js-grpc-common/package.json
packages/masternode-reward-shares-contract/package.json
packages/platform-test-suite/package.json
packages/rs-drive-nodejs/package.json
packages/wallet-lib/package.json
packages/wasm-dpp/package.json
packages/withdrawals-contract/package.json

chore(release): update changelog and bump version to 0.24.15

---

packages/rs-dpp/src/data_contract/factory/v0/mod.rs
packages/rs-dpp/src/identity/identity_public_key/v0/mod.rs
packages/rs-dpp/src/version/v0.rs
packages/rs-drive/Cargo.toml
packages/rs-drive/src/drive/batch/mod.rs
packages/rs-drive/src/drive/contract/mod.rs
packages/rs-drive/src/drive/document/insert/mod.rs
packages/rs-drive/src/drive/document/mod.rs
packages/rs-drive/src/drive/document/query/mod.rs
packages/rs-drive/src/drive/document/update/mod.rs
packages/rs-drive/src/drive/document/update/test_helpers.rs
packages/rs-drive/src/drive/mod.rs
packages/rs-drive/tests/deterministic_root_hash.rs
packages/rs-drive/tests/query_tests.rs
packages/rs-drive/tests/query_tests_history.rs

test(drive): fix tests after versioning

---

CHANGELOG.md
package.json
packages/bench-suite/package.json
packages/dapi-grpc/package.json
packages/dapi/package.json
packages/dash-spv/package.json
packages/dashmate/package.json
packages/dashpay-contract/package.json
packages/dpns-contract/package.json
packages/feature-flags-contract/package.json
packages/js-dapi-client/package.json
packages/js-dash-sdk/package.json
packages/js-dpp/package.json
packages/js-drive/package.json
packages/js-grpc-common/package.json
packages/masternode-reward-shares-contract/package.json
packages/platform-test-suite/package.json
packages/rs-drive-nodejs/package.json
packages/wallet-lib/package.json
packages/wasm-dpp/package.json
packages/withdrawals-contract/package.json

chore(release): update changelog and bump version to 0.24.16

---

packages/dashmate/src/commands/status/core.js
packages/dashmate/src/status/colors.js

https://github.com/dashpay/platform/issues/1214
Composed version string
Locally
No

fix(dashmate): version color is red

---

packages/dashmate/src/createDIContainer.js
packages/dashmate/src/listr/tasks/setup/regular/configureNodeTaskFactory.js
packages/dashmate/src/listr/tasks/setup/regular/registerMasternode/registerMasternodeWithCoreWallet.js
packages/dashmate/src/listr/tasks/setup/regular/registerMasternodeGuideTaskFactory.js

`createIpAndPortsForm` method returns a function instead of form
- Resolve `createIpAndPortsForm` factory through DI container
None
None

fix(dashmate): undefined createIpAndPortsForm factory

---

packages/dashmate/configs/defaults/getBaseConfigFactory.js
packages/dashmate/configs/getConfigFileMigrationsFactory.js
packages/dashmate/docker-compose.build.base.yml
packages/dashmate/docker-compose.build.dapi_api.yml
packages/dashmate/docker-compose.build.dapi_tx_filter_stream.yml
packages/dashmate/docker-compose.build.dashmate_helper.yml
packages/dashmate/docker-compose.build.drive_abci.yml
packages/dashmate/src/config/configJsonSchema.js
packages/dashmate/src/docker/DockerCompose.js
packages/dashmate/src/listr/tasks/buildServicesTaskFactory.js
packages/dashmate/src/listr/tasks/setup/regular/registerMasternode/registerMasternodeWithCoreWallet.js
packages/dashmate/test/unit/commands/config/set.spec.js

Multiple docker build optimization strategies (i.e., base image or multi-stage builds) required a base image to be built before building service images.
- Added `docker.baseImage` settings to configure base image build.
None
None

feat(dashmate): pre-build image

---

CHANGELOG.md
package.json
packages/bench-suite/package.json
packages/dapi-grpc/package.json
packages/dapi/package.json
packages/dash-spv/package.json
packages/dashmate/package.json
packages/dashpay-contract/package.json
packages/dpns-contract/package.json
packages/feature-flags-contract/package.json
packages/js-dapi-client/package.json
packages/js-dash-sdk/package.json
packages/js-dpp/package.json
packages/js-drive/package.json
packages/js-grpc-common/package.json
packages/masternode-reward-shares-contract/package.json
packages/platform-test-suite/package.json
packages/rs-drive-nodejs/package.json
packages/wallet-lib/package.json
packages/wasm-dpp/package.json
packages/withdrawals-contract/package.json

chore(release): update changelog and bump version to 0.24.17

---

packages/dashmate/src/config/generateEnvsFactory.js
packages/dashmate/src/constants.js
packages/dashmate/src/docker/getServiceListFactory.js

The dashmate update command still expects dashmate helper image to be configurable
- Use the hardcoded dashmate image name in the update command
None
None

fix(dashmate): the update command expects helper image option

---

CHANGELOG.md
package.json
packages/bench-suite/package.json
packages/dapi-grpc/package.json
packages/dapi/package.json
packages/dash-spv/package.json
packages/dashmate/package.json
packages/dashpay-contract/package.json
packages/dpns-contract/package.json
packages/feature-flags-contract/package.json
packages/js-dapi-client/package.json
packages/js-dash-sdk/package.json
packages/js-dpp/package.json
packages/js-drive/package.json
packages/js-grpc-common/package.json
packages/masternode-reward-shares-contract/package.json
packages/platform-test-suite/package.json
packages/rs-drive-nodejs/package.json
packages/wallet-lib/package.json
packages/wasm-dpp/package.json
packages/withdrawals-contract/package.json

chore(release): update changelog and bump version to 0.24.18

---

packages/dashmate/src/config/configJsonSchema.js

Testnet deploy using dashmate 0.24.18 and config template from this PR https://github.com/dashpay/dash-network-deploy/pull/531/files#diff-db018766d0b61607adb538a240aad8a55fa2764c353ff9bef5e896c27fa3d60f was failing with
```
TASK [dashmate : Set ZeroSSL certificate ID to dashmate config from SSM] ***********************************************************************************
fatal: [hp-masternode-1]: FAILED! => changed=false 
cmd:
- dashmate
- config
- set
- platform.dapi.envoy.ssl.providerConfigs.zerossl.id
- d266c5bc2b4a40a4728f286485ac3fe3
delta: '0:00:01.776851'
end: '2023-07-28 05:44:39.050284'
msg: non-zero return code
rc: 1
start: '2023-07-28 05:44:37.273433'
stderr: |2-
InvalidConfigFileFormatError: Invalid
'/home/dashmate/.dashmate/config.json' config format: …
```

fix(dashmate): `baseImage/build/context` invalid json schema

---

CHANGELOG.md
package.json
packages/bench-suite/package.json
packages/dapi-grpc/package.json
packages/dapi/package.json
packages/dash-spv/package.json
packages/dashmate/package.json
packages/dashpay-contract/package.json
packages/dpns-contract/package.json
packages/feature-flags-contract/package.json
packages/js-dapi-client/package.json
packages/js-dash-sdk/package.json
packages/js-dpp/package.json
packages/js-drive/package.json
packages/js-grpc-common/package.json
packages/masternode-reward-shares-contract/package.json
packages/platform-test-suite/package.json
packages/rs-drive-nodejs/package.json
packages/wallet-lib/package.json
packages/wasm-dpp/package.json
packages/withdrawals-contract/package.json

chore(release): update changelog and bump version to 0.24.19

---

packages/dashmate/configs/defaults/getBaseConfigFactory.js
packages/dashmate/configs/defaults/getMainnetConfigFactory.js
packages/dashmate/configs/defaults/getTestnetConfigFactory.js
packages/dashmate/configs/getConfigFileMigrationsFactory.js

19.3.0 dashcore already out, so we have to update it in the dashmate as well
Upgraded dashcore image in the base, testnet and mainnet configs
No
No

chore(dashmate): update Core to v19.3.0

---

Cargo.lock
packages/wasm-dpp/Cargo.toml
packages/wasm-dpp/scripts/build-wasm.sh
packages/wasm-dpp/src/utils.rs

Mismatch wasm-bindgen and wasm-bindgen-cli versions
- Upgraded to 0.2.86
None
None

build: update `wasm-bindgen-cli` to 0.2.86

---

packages/dashmate/src/commands/status/index.js
packages/dashmate/src/status/scopes/masternode.js

* `dashmate status` incorrectly shows lastPaidTime for a freshly registered nodes
* `dashmate status` incorrectly shows PoSe score
* defaulted lastPaidTime to null in masternode status scope
* Copied lastPaidTime and PosE score from the `status masternode` so it will have the same ui behaviour
Locally

fix(dashmate): masternode dashmate status ui typos

---

packages/dashmate/src/status/providers.js

In the dashmate status command, all errors from the rpc's and endpoints should be hidden until `DEBUG` environment variable is set
Added missing check on env variable
Locally
No

fix(dashmate): some status errors is visible without DEBUG env

---

CHANGELOG.md
package.json
packages/bench-suite/package.json
packages/dapi-grpc/package.json
packages/dapi/package.json
packages/dash-spv/package.json
packages/dashmate/package.json
packages/dashpay-contract/package.json
packages/dpns-contract/package.json
packages/feature-flags-contract/package.json
packages/js-dapi-client/package.json
packages/js-dash-sdk/package.json
packages/js-dpp/package.json
packages/js-drive/package.json
packages/js-grpc-common/package.json
packages/masternode-reward-shares-contract/package.json
packages/platform-test-suite/package.json
packages/rs-drive-nodejs/package.json
packages/wallet-lib/package.json
packages/wasm-dpp/package.json
packages/withdrawals-contract/package.json

chore(release): update changelog and bump version to 0.24.20

---

Cargo.lock
packages/dapi/lib/externalApis/drive/DriveClient.js
packages/dapi/lib/grpcServer/handlers/platform/getDataContractsHandlerFactory.js
packages/dapi/lib/grpcServer/handlers/platform/getIdentitiesHandlerFactory.js
packages/dapi/lib/grpcServer/handlers/platform/getIdentityBalanceAndRevisionHandlerFactory.js
packages/dapi/lib/grpcServer/handlers/platform/getIdentityBalanceHandlerFactory.js
packages/dapi/lib/grpcServer/handlers/platform/getIdentityByPublicKeyHashesHandlerFactory.js
packages/dapi/lib/grpcServer/handlers/platform/getIdentityKeysHandlerFactory.js
packages/dapi/lib/grpcServer/handlers/platform/getProofsHandlerFactory.js
packages/dapi/lib/grpcServer/handlers/platform/platformHandlersFactory.js
packages/dapi/test/unit/grpcServer/handlers/platform/getDataContractsHandlerFactory.spec.js
packages/dapi/test/unit/grpcServer/handlers/platform/getIdentitiesHandlerFactory.spec.js
packages/dapi/test/unit/grpcServer/handlers/platform/getIdentityBalanceAndRevisionHandlerFactory.spec.js
packages/dapi/test/unit/grpcServer/handlers/platform/getIdentityBalanceHandlerFactory.spec.js
packages/dapi/test/unit/grpcServer/handlers/platform/getIdentityByPublicKeyHashesHandlerFactory.spec.js
packages/dapi/test/unit/grpcServer/handlers/platform/getIdentityKeysHandlerFactory.spec.js
packages/dapi/test/unit/grpcServer/handlers/platform/getProofsHandlerFactory.spec.js
packages/dashmate/configs/system/base.js
packages/rs-drive-abci/src/mimic/mod.rs
packages/rs-drive-abci/src/platform_types/commit/v0/mod.rs
packages/rs-drive-abci/tests/strategy_tests/execution.rs
packages/rs-drive-abci/tests/strategy_tests/main.rs
packages/rs-drive-abci/tests/strategy_tests/query.rs

Added missing gRPC endpoints for `rust-light-client` PoC
- added several endpoints
- unit tests
- gRPC UI
None

feat(dapi): add missing gRPC endpoints

---

CHANGELOG.md
package.json
packages/bench-suite/package.json
packages/dapi-grpc/package.json
packages/dapi/package.json
packages/dash-spv/package.json
packages/dashmate/package.json
packages/dashpay-contract/package.json
packages/dpns-contract/package.json
packages/feature-flags-contract/package.json
packages/js-dapi-client/package.json
packages/js-dash-sdk/package.json
packages/js-dpp/package.json
packages/js-drive/package.json
packages/js-grpc-common/package.json
packages/masternode-reward-shares-contract/package.json
packages/platform-test-suite/package.json
packages/rs-drive-nodejs/package.json
packages/wallet-lib/package.json
packages/wasm-dpp/package.json
packages/withdrawals-contract/package.json
scripts/release/release.sh

chore(release): update changelog and bump version to 0.24.21

---

packages/dashmate/configs/defaults/getBaseConfigFactory.js
packages/dashmate/configs/getConfigFileMigrationsFactory.js
packages/dashmate/src/config/configJsonSchema.js
packages/dashmate/src/listr/tasks/setup/setupLocalPresetTaskFactory.js
packages/dashmate/src/listr/tasks/setup/setupRegularPresetTaskFactory.js
packages/dashmate/templates/platform/drive/tenderdash/config.toml.dot

For a https://github.com/dashpay/dash-network-deploy/pull/535 task I need a way to set custom tenderdash mode, that is hardcoded at now.
* Replaced hardcoded mode with config variable in config.toml.dot
* Added mode set according node types in the setup phase
Devnet
No

feat(dashmate): tenderdash mode configuration

---

CHANGELOG.md
package.json
packages/bench-suite/package.json
packages/dapi-grpc/package.json
packages/dapi/package.json
packages/dash-spv/package.json
packages/dashmate/package.json
packages/dashpay-contract/package.json
packages/dpns-contract/package.json
packages/feature-flags-contract/package.json
packages/js-dapi-client/package.json
packages/js-dash-sdk/package.json
packages/js-dpp/package.json
packages/js-drive/package.json
packages/js-grpc-common/package.json
packages/masternode-reward-shares-contract/package.json
packages/platform-test-suite/package.json
packages/rs-drive-nodejs/package.json
packages/wallet-lib/package.json
packages/wasm-dpp/package.json
packages/withdrawals-contract/package.json

chore(release): update changelog and version to 0.24.22

---

.github/actions/nodejs/action.yaml
.github/actions/rust/action.yaml

Release runs were failing when attempting to run the sub-action to install NodeJS, which starts out with a GHA/AWS OIDC login step in order to access the cache bucket in S3. This step fails with:
```
Run aws-actions/configure-aws-credentials@v2
with:
aws-region: eu-west-1
audience: sts.amazonaws.com
(node:1885) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.
Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check the migration guide at https://a.co/7PzMCcy
(Use `node --trace-warnings ...` to show where the warning was created)
Error: Credentials could not be loaded, please check your action inputs: Could not load credentials from any providers
```
It should not be necessary to use OIDC to obtain AWS …

ci: fix credentials could not be loaded error

---

CHANGELOG.md
package.json
packages/bench-suite/package.json
packages/dapi-grpc/package.json
packages/dapi/package.json
packages/dash-spv/package.json
packages/dashmate/package.json
packages/dashpay-contract/package.json
packages/dpns-contract/package.json
packages/feature-flags-contract/package.json
packages/js-dapi-client/package.json
packages/js-dash-sdk/package.json
packages/js-dpp/package.json
packages/js-drive/package.json
packages/js-grpc-common/package.json
packages/masternode-reward-shares-contract/package.json
packages/platform-test-suite/package.json
packages/rs-drive-nodejs/package.json
packages/wallet-lib/package.json
packages/wasm-dpp/package.json
packages/withdrawals-contract/package.json
scripts/release/release.sh

chore(release): update changelog and bump version to 0.24.23

---

packages/rs-dpp/src/dash_platform_protocol.rs
packages/rs-dpp/src/identity/identity_facade.rs
packages/wasm-dpp/src/dash_platform_protocol.rs
packages/wasm-dpp/src/identity/identity_facade.rs
packages/wasm-dpp/src/identity/identity_factory.rs
packages/wasm-dpp/src/identity/mod.rs
packages/wasm-dpp/src/lib.rs
packages/wasm-dpp/test/integration/identity/IdentityFacade.spec.js

fix(dpp): identity facade

---

packages/rs-dpp/src/data_contract/accessors/mod.rs
packages/rs-dpp/src/data_contract/accessors/v0/mod.rs
packages/rs-dpp/src/data_contract/mod.rs
packages/rs-dpp/src/data_contract/v0/accessors/mod.rs
packages/rs-dpp/src/data_contract/v0/methods/schema.rs
packages/wasm-dpp/Cargo.toml
packages/wasm-dpp/src/data_contract/data_contract.rs
packages/wasm-dpp/src/data_contract/errors/mod.rs
packages/wasm-dpp/src/data_contract/mod.rs
packages/wasm-dpp/src/data_contract/state_transition/data_contract_create_transition/mod.rs
packages/wasm-dpp/src/data_contract/state_transition/data_contract_update_transition/mod.rs
packages/wasm-dpp/src/errors/consensus/consensus_error.rs
packages/wasm-dpp/src/errors/from.rs
packages/wasm-dpp/src/errors/mod.rs
packages/wasm-dpp/src/lib.rs
packages/wasm-dpp/src/metadata.rs
packages/wasm-dpp/test/unit/dataContract/DataContract.spec.js

After versioning PR we need to update WASM biding for DataContract
- Updated DataContract struct and corresponding tests
With tests
- DataContract methods are renamed.
- Raw data contract structure is changed.

fix(dpp)!: wasm binding for DataContract

---

packages/rs-dpp/src/old/document_tests/state_transitions/validation/validate_documents_batch_transition_state_spec.rs
packages/rs-dpp/src/state_transition/state_transitions/document/documents_batch_transition/document_transition/mod.rs
packages/rs-drive-abci/src/execution/validation/state_transition/state_transitions/data_contract_create/structure/v0/mod.rs
packages/rs-drive-abci/src/execution/validation/state_transition/state_transitions/documents_batch/action_validation/document_create_transition_action/state_v0/mod.rs
packages/rs-drive-abci/src/execution/validation/state_transition/state_transitions/documents_batch/action_validation/document_create_transition_action/structure_v0/mod.rs
packages/rs-drive-abci/src/execution/validation/state_transition/state_transitions/documents_batch/action_validation/document_delete_transition_action/state_v0/mod.rs
packages/rs-drive-abci/src/execution/validation/state_transition/state_transitions/documents_batch/action_validation/document_replace_transition_action/state_v0/mod.rs
packages/rs-drive-abci/src/execution/validation/state_transition/state_transitions/documents_batch/action_validation/document_replace_transition_action/structure_v0/mod.rs
packages/rs-drive-abci/src/execution/validation/state_transition/state_transitions/documents_batch/state/v0/mod.rs
packages/rs-drive-abci/src/execution/validation/state_transition/state_transitions/documents_batch/transformer/v0/mod.rs
packages/rs-drive-abci/tests/strategy_tests/verify_state_transitions.rs

Comments in #1334
- Fixes and comments according to the #1334 review comments
None
None

fix: various fixes and todos for #1334

---

packages/platform-test-suite/test/functional/platform/Identity.spec.js
packages/rs-dpp/src/state_transition/mod.rs
packages/wasm-dpp/src/identity/state_transition/identity_create_transition/identity_create_transition.rs
packages/wasm-dpp/src/identity/state_transition/identity_credit_transfer_transition/transition.rs
packages/wasm-dpp/src/identity/state_transition/identity_topup_transition/identity_topup_transition.rs
packages/wasm-dpp/src/identity/state_transition/identity_update_transition/identity_update_transition.rs

test: restore identity create

---

packages/rs-dpp/src/errors/consensus/basic/json_schema_error/json_schema_error.rs
packages/rs-dpp/src/errors/consensus/basic/json_schema_error/json_schema_error_data.rs
packages/rs-drive/src/drive/document/estimation_costs/stateless_delete_of_non_tree_for_costs/mod.rs
packages/rs-drive/src/drive/document/estimation_costs/stateless_delete_of_non_tree_for_costs/v0/mod.rs
packages/rs-drive/src/drive/document/index_uniqueness/internal/validate_uniqueness_of_data/mod.rs
packages/rs-drive/src/drive/document/index_uniqueness/internal/validate_uniqueness_of_data/v0/mod.rs
packages/rs-drive/src/drive/document/query/mod.rs
packages/rs-drive/src/drive/document/query/query_documents/mod.rs
packages/rs-drive/src/drive/document/query/query_documents/v0/mod.rs
packages/rs-drive/src/drive/fee/mod.rs
packages/rs-drive/src/drive/grove_operations/mod.rs
packages/rs-drive/src/drive/identity/contract_info/insert.rs
packages/rs-drive/src/drive/identity/estimation_costs/for_authentication_keys_security_level_in_key_reference_tree/v0/mod.rs
packages/rs-drive/src/drive/identity/estimation_costs/for_balances/v0/mod.rs
packages/rs-drive/src/drive/identity/estimation_costs/for_keys_for_identity_id/v0/mod.rs
packages/rs-drive/src/drive/identity/estimation_costs/for_negative_credit/v0/mod.rs
packages/rs-drive/src/drive/identity/estimation_costs/for_purpose_in_key_reference_tree/v0/mod.rs
packages/rs-drive/src/drive/identity/estimation_costs/for_root_key_reference_tree/v0/mod.rs
packages/rs-drive/src/drive/identity/estimation_costs/for_update_revision/v0/mod.rs
packages/rs-drive/src/drive/identity/fetch/balance/fetch_identity_negative_balance/v0/mod.rs
packages/rs-drive/src/drive/identity/key/insert/create_key_tree_with_keys/v0/mod.rs
packages/rs-drive/src/drive/identity/key/insert/insert_key_searchable_references/v0/mod.rs
packages/rs-drive/src/drive/identity/key/insert/insert_key_to_storage/v0/mod.rs
packages/rs-drive/src/drive/identity/mod.rs

Error messages for a JSON schema error are made more descriptive and concise.
**Example**:
Now: `JsonSchemaError: "*food" does not match "^[a-zA-Z0-9-_]{1,64}$", Path: /documents/order/properties`
Before: `JsonSchemaError: keyword: propertyNames, instance_path: /documents/order/properties, schema_path:/properties/documents/additionalProperties/allOf/1/properties/properties/propertyNames/pattern`
Add an error_message field to JsonSchemaErrorData struct which holds an error message from the json library. Changed the default error message for JsonSchemaError struct and included the error_message.
I've been using this in dashpay.io Data Contract Creator for validations.
- [ x] I have performed a self-review of my own code
- [ x] I have commented my code, particularly in hard-to-understand …

feat: add better JsonSchemaError messages

---

Cargo.lock
packages/dashmate/configs/defaults/getBaseConfigFactory.js
packages/dashmate/src/core/wallet/registerMasternode.js
packages/dashmate/src/listr/tasks/setup/local/configureCoreTaskFactory.js
packages/dashmate/src/listr/tasks/setup/regular/registerMasternode/registerMasternodeWithCoreWallet.js
packages/platform-test-suite/test/functional/platform/Identity.spec.js
packages/rs-drive-abci/Cargo.toml
packages/rs-drive-abci/src/execution/platform_events/core_based_updates/update_masternode_list/update_state_masternode_list/v0/mod.rs
packages/rs-drive-abci/src/execution/platform_events/initialization/initial_core_height/v0/mod.rs
packages/rs-drive-abci/src/execution/validation/state_transition/state_transitions/documents_batch/data_triggers/triggers/reward_share/v0/mod.rs
packages/rs-drive-abci/src/rpc/core.rs
packages/rs-drive-abci/tests/strategy_tests/execution.rs
packages/rs-drive-abci/tests/strategy_tests/masternodes.rs

Update platform to support core v20-alpha.4

chore: support Core v0.20.0-alpha.4

---

CHANGELOG.md
package.json
packages/bench-suite/package.json
packages/dapi-grpc/package.json
packages/dapi/package.json
packages/dash-spv/package.json
packages/dashmate/package.json
packages/dashpay-contract/package.json
packages/dpns-contract/package.json
packages/feature-flags-contract/package.json
packages/js-dapi-client/package.json
packages/js-dash-sdk/package.json
packages/js-dpp/package.json
packages/js-grpc-common/package.json
packages/masternode-reward-shares-contract/package.json
packages/platform-test-suite/package.json
packages/wallet-lib/package.json
packages/wasm-dpp/package.json
packages/withdrawals-contract/package.json

chore(release): update changelog and bump version to 0.25.0-dev.17

---

packages/dashmate/configs/defaults/getBaseConfigFactory.js
packages/dashmate/configs/defaults/getTestnetConfigFactory.js
packages/dashmate/configs/getConfigFileMigrationsFactory.js

Core 20.0.0-alpha.6 was released
Bump base core version
In CI
None

chore(dashmate): bump core to 20.0.0-alpha.6

---

Dockerfile
packages/dashmate/docker/entrypoint.sh

Dashmate helper container is restarting
- Reverted entrypoint and dockerfile to v0.24
None
None

fix(dashmate): helper container is restarting

---

CHANGELOG.md
package.json
packages/bench-suite/package.json
packages/dapi-grpc/package.json
packages/dapi/package.json
packages/dash-spv/package.json
packages/dashmate/package.json
packages/dashpay-contract/package.json
packages/dpns-contract/package.json
packages/feature-flags-contract/package.json
packages/js-dapi-client/package.json
packages/js-dash-sdk/package.json
packages/js-dpp/package.json
packages/js-grpc-common/package.json
packages/masternode-reward-shares-contract/package.json
packages/platform-test-suite/package.json
packages/wallet-lib/package.json
packages/wasm-dpp/package.json
packages/withdrawals-contract/package.json

chore(release): update changelog and bump version to 0.25.0-dev.18

---

packages/rs-dpp/src/data_contract/config/methods/validate_config_update/v0/mod.rs
packages/rs-drive-abci/src/execution/validation/state_transition/state_transitions/data_contract_update/state/v0/mod.rs

A few contract configuration checks were not being verified as not updated on data contract update state transition, now they are.

fix(dpp): some contract options are updatable

---

CHANGELOG.md
package.json
packages/bench-suite/package.json
packages/dapi-grpc/package.json
packages/dapi/package.json
packages/dash-spv/package.json
packages/dashmate/package.json
packages/dashpay-contract/package.json
packages/dpns-contract/package.json
packages/feature-flags-contract/package.json
packages/js-dapi-client/package.json
packages/js-dash-sdk/package.json
packages/js-dpp/package.json
packages/js-grpc-common/package.json
packages/masternode-reward-shares-contract/package.json
packages/platform-test-suite/package.json
packages/wallet-lib/package.json
packages/wasm-dpp/package.json
packages/withdrawals-contract/package.json

chore(release): update changelog and bump version to 0.25.0-dev.19

---

packages/rs-drive-abci/src/execution/check_tx/v0/mod.rs
packages/rs-drive/src/drive/identity/fetch/balance/fetch_identity_balance/v0/mod.rs
packages/rs-drive/src/drive/identity/fetch/revision/fetch_identity_revision/v0/mod.rs

Two issues existed in check_tx:
*the first was that an invalid state transition could be deserialized and report a non consensus error.
*the second was that if the identity didn't exist it would error instead of saying that no identity existed.

fix(drive): deserialization and identity not existing on check_tx

---

packages/rs-drive-abci/src/abci/handlers.rs

Internal error on `check_tx` is reporting with code 1 (CANCELED) without any information about the error
- Changed error code to 13 (Internal error)
- Logged the error
None
None

feat(drive): better error handling on check_tx

---

CHANGELOG.md
package.json
packages/bench-suite/package.json
packages/dapi-grpc/package.json
packages/dapi/package.json
packages/dash-spv/package.json
packages/dashmate/package.json
packages/dashpay-contract/package.json
packages/dpns-contract/package.json
packages/feature-flags-contract/package.json
packages/js-dapi-client/package.json
packages/js-dash-sdk/package.json
packages/js-dpp/package.json
packages/js-grpc-common/package.json
packages/masternode-reward-shares-contract/package.json
packages/platform-test-suite/package.json
packages/wallet-lib/package.json
packages/wasm-dpp/package.json
packages/withdrawals-contract/package.json

chore(release): update changelog and bump version to 0.25.0-dev.20

---

CHANGELOG.md
package.json
packages/bench-suite/package.json
packages/dapi-grpc/package.json
packages/dapi/package.json
packages/dash-spv/package.json
packages/dashmate/package.json
packages/dashpay-contract/package.json
packages/dpns-contract/package.json
packages/feature-flags-contract/package.json
packages/js-dapi-client/package.json
packages/js-dash-sdk/package.json
packages/js-dpp/package.json
packages/js-grpc-common/package.json
packages/masternode-reward-shares-contract/package.json
packages/platform-test-suite/package.json
packages/wallet-lib/package.json
packages/wasm-dpp/package.json
packages/withdrawals-contract/package.json

chore(release): update changelog and bump version to 0.25.0-dev.21

---

Cargo.lock
packages/rs-drive-abci/src/query/v0/mod.rs
packages/rs-drive/Cargo.toml
packages/rs-drive/src/drive/test_utils.rs
packages/rs-drive/src/query/mod.rs

We were only returning 1 (now we return up to limit if limit is defined). (Most likely the value was altered to 1 for a test and was forgotten to be reverted). We can also now handle no where clause.

fix(drive): query fix for 1 value and no where clause

---

Cargo.lock
packages/rs-drive-abci/Cargo.toml
packages/rs-drive-abci/src/abci/handlers.rs
packages/rs-drive-abci/src/execution/check_tx/v0/mod.rs
packages/rs-drive-abci/src/logging.rs
packages/rs-drive-abci/tests/strategy_tests/main.rs
packages/rs-drive/Cargo.toml
packages/rs-drive/src/drive/grove_operations/grove_apply_batch_with_add_costs/v0/mod.rs

Logs in Drive don\t include necessary information about ABCI request.
Updated rs-tenderdash-abci to the most recent version which adds tracing spans to requests.
Cleaned up code a bit to improve logs.
Using local devnet.
None

feat(drive): improve ABCI logging

---

CHANGELOG.md
package.json
packages/bench-suite/package.json
packages/dapi-grpc/package.json
packages/dapi/package.json
packages/dash-spv/package.json
packages/dashmate/package.json
packages/dashpay-contract/package.json
packages/dpns-contract/package.json
packages/feature-flags-contract/package.json
packages/js-dapi-client/package.json
packages/js-dash-sdk/package.json
packages/js-dpp/package.json
packages/js-grpc-common/package.json
packages/masternode-reward-shares-contract/package.json
packages/platform-test-suite/package.json
packages/wallet-lib/package.json
packages/wasm-dpp/package.json
packages/withdrawals-contract/package.json

chore(release): update changelog and bump version to 0.25.0-dev.23

---

.github/workflows/all-packages.yml
.github/workflows/js-checks.yml
.github/workflows/release.yml
Dockerfile

Cache was returning dirty hits, resulting in corrupted builds
Ensure that mtime is maintained when checking out repo so that cargo mtime-based caching works correctly
Make sure to merge https://github.com/dcginfra/buildkit-cache-dance/pull/3 first
In CI
None

ci: fix cache mtime

---

.github/actions/rust/action.yaml
.github/workflows/release.yml

This PR reverts prematurely merged #1374 which is most likely no longer necessary now that we are being assigned runners with version `20230901.1` which [purportedly fixes](https://github.com/actions/runner-images/issues/8104#issuecomment-1709648189) the underlying issue.
We also encountered a new error while running a release with the above fix in place:
```
Run sudo apt update -qq
The operation couldn’t be completed. Unable to locate a Java Runtime that supports apt.
Please visit http://www.java.com/ for information on installing Java.
```
- Disable use of `apt` Linux package manager on macOS. Clang and LLVM should already be installed on the macOS runner at this point.
Will be tested on next release
None

ci: disable apt install step on macos release job

---

CHANGELOG.md
package.json
packages/bench-suite/package.json
packages/dapi-grpc/package.json
packages/dapi/package.json
packages/dash-spv/package.json
packages/dashmate/package.json
packages/dashpay-contract/package.json
packages/dpns-contract/package.json
packages/feature-flags-contract/package.json
packages/js-dapi-client/package.json
packages/js-dash-sdk/package.json
packages/js-dpp/package.json
packages/js-grpc-common/package.json
packages/masternode-reward-shares-contract/package.json
packages/platform-test-suite/package.json
packages/wallet-lib/package.json
packages/wasm-dpp/package.json
packages/withdrawals-contract/package.json

chore(release): update changelog and bump version to 0.25.0-dev.24

---

.github/actions/nodejs/action.yaml
.github/actions/rust/action.yaml

Reverting #1391 - This workflow runs for everything including stuff not in AWS, causing failures.
Revert #1391 
None, the PR was to address non-fatal errors

fix: revert #1391

---

CHANGELOG.md
package.json
packages/bench-suite/package.json
packages/dapi-grpc/package.json
packages/dapi/package.json
packages/dash-spv/package.json
packages/dashmate/package.json
packages/dashpay-contract/package.json
packages/dpns-contract/package.json
packages/feature-flags-contract/package.json
packages/js-dapi-client/package.json
packages/js-dash-sdk/package.json
packages/js-dpp/package.json
packages/js-grpc-common/package.json
packages/masternode-reward-shares-contract/package.json
packages/platform-test-suite/package.json
packages/wallet-lib/package.json
packages/wasm-dpp/package.json
packages/withdrawals-contract/package.json

chore(release): update changelog and bump version to 0.25.0-dev.25

---

CHANGELOG.md
package.json
packages/bench-suite/package.json
packages/dapi-grpc/package.json
packages/dapi/package.json
packages/dash-spv/package.json
packages/dashmate/package.json
packages/dashpay-contract/package.json
packages/dpns-contract/package.json
packages/feature-flags-contract/package.json
packages/js-dapi-client/package.json
packages/js-dash-sdk/package.json
packages/js-dpp/package.json
packages/js-grpc-common/package.json
packages/masternode-reward-shares-contract/package.json
packages/platform-test-suite/package.json
packages/wallet-lib/package.json
packages/wasm-dpp/package.json
packages/withdrawals-contract/package.json

chore(release): update changelog and bump version to 0.25.0-dev.26

---

CHANGELOG.md
package.json
packages/bench-suite/package.json
packages/dapi-grpc/package.json
packages/dapi/package.json
packages/dash-spv/package.json
packages/dashmate/package.json
packages/dashpay-contract/package.json
packages/dpns-contract/package.json
packages/feature-flags-contract/package.json
packages/js-dapi-client/package.json
packages/js-dash-sdk/package.json
packages/js-dpp/package.json
packages/js-grpc-common/package.json
packages/masternode-reward-shares-contract/package.json
packages/platform-test-suite/package.json
packages/wallet-lib/package.json
packages/wasm-dpp/package.json
packages/withdrawals-contract/package.json

chore(release): update changelog and bump version to 0.25.0-dev.27

---

CHANGELOG.md
package.json
packages/bench-suite/package.json
packages/dapi-grpc/package.json
packages/dapi/package.json
packages/dash-spv/package.json
packages/dashmate/package.json
packages/dashpay-contract/package.json
packages/dpns-contract/package.json
packages/feature-flags-contract/package.json
packages/js-dapi-client/package.json
packages/js-dash-sdk/package.json
packages/js-dpp/package.json
packages/js-grpc-common/package.json
packages/masternode-reward-shares-contract/package.json
packages/platform-test-suite/package.json
packages/wallet-lib/package.json
packages/wasm-dpp/package.json
packages/withdrawals-contract/package.json

chore(release): update changelog and bump version to 0.25.0-dev.28

---

packages/dashmate/src/listr/tasks/resetNodeTaskFactory.js

https://github.com/dashpay/platform/issues/1414
Reset command with platform only flag is broken
* Pass profiles to to the `isNodeRunning`
Locally on my macbook
No

fix(dashmate): platform reset failure

---

.github/actions/docker/action.yaml
.github/actions/nodejs/action.yaml
.github/actions/rust/action.yaml
.github/actions/s3-layer-cache-settings/action.yaml
.github/workflows/all-packages.yml
.github/workflows/js-checks.yml

The CI stack was redeployed, which includes creating a cache bucket with a new name
Update cache bucket name
In CI
None

ci: update cache target bucket

---

packages/dashmate/configs/defaults/getBaseConfigFactory.js
packages/dashmate/configs/defaults/getLocalConfigFactory.js
packages/dashmate/configs/defaults/getTestnetConfigFactory.js
packages/dashmate/configs/getConfigFileMigrationsFactory.js
packages/dashmate/docker-compose.yml
packages/dashmate/src/config/configJsonSchema.js
packages/dashmate/src/listr/tasks/setup/setupLocalPresetTaskFactory.js
packages/dashmate/templates/platform/drive/tenderdash/config.toml.dot

We should be able to get tenderdash metrics using dashmate
- Configure tenderdash's prometheus client
Manually
None

feat(dashmate): expose tenderdash metics

---

CHANGELOG.md
package.json
packages/bench-suite/package.json
packages/dapi-grpc/package.json
packages/dapi/package.json
packages/dash-spv/package.json
packages/dashmate/package.json
packages/dashpay-contract/package.json
packages/dpns-contract/package.json
packages/feature-flags-contract/package.json
packages/js-dapi-client/package.json
packages/js-dash-sdk/package.json
packages/js-dpp/package.json
packages/js-grpc-common/package.json
packages/masternode-reward-shares-contract/package.json
packages/platform-test-suite/package.json
packages/wallet-lib/package.json
packages/wasm-dpp/package.json
packages/withdrawals-contract/package.json

chore(release): update changelog and bump version to 0.25.0-dev.29

---

packages/dashmate/configs/defaults/getTestnetConfigFactory.js
packages/dashmate/configs/getConfigFileMigrationsFactory.js

Testnet seed nodes were redeployed, forcing an IP address change
Update IP addresses in dashmate config
Untested
None

chore: update seed ip addresses

---

.github/actions/docker/action.yaml
.github/actions/nodejs/action.yaml
.github/actions/rust/action.yaml
.github/actions/s3-layer-cache-settings/action.yaml
.github/workflows/all-packages.yml
.github/workflows/js-checks.yml

Update s3 bucket for platform runners
Update s3 bucket for platform runners

chore: update s3 bucket

---

CHANGELOG.md
package.json
packages/bench-suite/package.json
packages/dapi-grpc/package.json
packages/dapi/package.json
packages/dash-spv/package.json
packages/dashmate/package.json
packages/dashpay-contract/package.json
packages/dpns-contract/package.json
packages/feature-flags-contract/package.json
packages/js-dapi-client/package.json
packages/js-dash-sdk/package.json
packages/js-dpp/package.json
packages/js-grpc-common/package.json
packages/masternode-reward-shares-contract/package.json
packages/platform-test-suite/package.json
packages/wallet-lib/package.json
packages/wasm-dpp/package.json
packages/withdrawals-contract/package.json

chore(release): update changelog and bump version to 0.25.0-dev.31

---

packages/dashmate/configs/defaults/getTestnetConfigFactory.js
packages/dashmate/configs/getConfigFileMigrationsFactory.js

Testnet was reset due to breaking changes
Update config and migrations
Currently testing locally
None

chore: update config and migrations for testnet-25

---

CHANGELOG.md
package.json
packages/bench-suite/package.json
packages/dapi-grpc/package.json
packages/dapi/package.json
packages/dash-spv/package.json
packages/dashmate/package.json
packages/dashpay-contract/package.json
packages/dpns-contract/package.json
packages/feature-flags-contract/package.json
packages/js-dapi-client/package.json
packages/js-dash-sdk/package.json
packages/js-dpp/package.json
packages/js-grpc-common/package.json
packages/masternode-reward-shares-contract/package.json
packages/platform-test-suite/package.json
packages/wallet-lib/package.json
packages/wasm-dpp/package.json
packages/withdrawals-contract/package.json

chore(release): update changelog and bump version to 0.25.0-dev.32

---

packages/dashmate/configs/defaults/getBaseConfigFactory.js
packages/dashmate/configs/defaults/getTestnetConfigFactory.js
packages/dashmate/configs/getConfigFileMigrationsFactory.js

Upgrade dashmate to the recent dashcore version
Upgraded core image in base, testnet and migration
no
no

feat(dashmate): upgrade core to v20.0.0-beta.2

---

CHANGELOG.md
package.json
packages/bench-suite/package.json
packages/dapi-grpc/package.json
packages/dapi/package.json
packages/dash-spv/package.json
packages/dashmate/package.json
packages/dashpay-contract/package.json
packages/dpns-contract/package.json
packages/feature-flags-contract/package.json
packages/js-dapi-client/package.json
packages/js-dash-sdk/package.json
packages/js-dpp/package.json
packages/js-grpc-common/package.json
packages/masternode-reward-shares-contract/package.json
packages/platform-test-suite/package.json
packages/wallet-lib/package.json
packages/wasm-dpp/package.json
packages/withdrawals-contract/package.json

chore(release): update changelog and bump version to 0.25.0-dev.33

---

.github/PULL_REQUEST_TEMPLATE.md

We need people to think twice if they mark a PR as a breaking change
- Added a breaking changes checkbox in the PR template
None
None

chore: add a breaking changes checkbox to the PR template

---

.github/workflows/rs-drive-abci.yml
.github/workflows/rs-drive.yml
packages/rs-drive/tests/deterministic_root_hash.rs

We have missed Drive workflow that's why we committed a broken tests recently.
- Added Drive workflow
- Added triggers for dependencies
- Fixed app hash in Drive tests
Running tests manually
None

ci: add missing Drive workflow

---

.github/actions/docker/action.yaml
.github/workflows/all-packages.yml
.github/workflows/docs.yml
.github/workflows/js-checks.yml
.github/workflows/release.yml
.github/workflows/rs-checks.yml
.github/workflows/wasm-dpp.yml

CI was throwing warnings for several actions we depend on similar to the following:
```
The following actions uses node12 which is deprecated and will be forced to run on node16: actions/checkout@v2
The following actions uses node12 which is deprecated and will be forced to run on node16: actions-rs/clippy-check@v1
```
- Update action versions
- Replace abandoned actions with maintained forks
In CI
None

ci: update action dependency versions

---

packages/dashmate/configs/defaults/getBaseConfigFactory.js
packages/rs-drive-abci/Cargo.toml

https://github.com/dashpay/rs-tenderdash-abci/pull/41
- Bump rs-tenderdash-abci to 0.13.1 to address deadlock on multiple msgs received  https://github.com/dashpay/rs-tenderdash-abci/pull/41
Run Github Actions
None

fix(drive): deadlock in tenderdash abci client

---

packages/dashmate/configs/defaults/getBaseConfigFactory.js
packages/dashmate/configs/getConfigFileMigrationsFactory.js

Updated core image to v20-beta.4
CI

chore(dashmate): update core image

---

.github/workflows/rs-features.yml

This is recreated #1450 
When using only subset of features provided by our crates, it is quite often these crates don't build or work.
We need a way to detect such issues early.
Implemented a github job `rs-features` that can be triggered manually or from other workflow. 
It runs cargo test for each individual feature, with default features disabled.
The job IS NOT included in normal CI runs yet, **needs to be started manually** for now.
Run on rs-drive-abci, it failed ;-).
None

ci: test individual features

---

CHANGELOG.md
Cargo.lock
package.json
packages/bench-suite/package.json
packages/dapi-grpc/package.json
packages/dapi/package.json
packages/dash-spv/package.json
packages/dashmate/package.json
packages/dashpay-contract/package.json
packages/dpns-contract/package.json
packages/feature-flags-contract/package.json
packages/js-dapi-client/package.json
packages/js-dash-sdk/package.json
packages/js-dpp/package.json
packages/js-grpc-common/package.json
packages/masternode-reward-shares-contract/package.json
packages/platform-test-suite/package.json
packages/wallet-lib/package.json
packages/wasm-dpp/package.json
packages/withdrawals-contract/package.json

chore(release): update changelog and bump version to 0.25.1

---

Cargo.lock
packages/dashmate/src/commands/start.js

We need to start all stopped services and recreate containers if images are updated.
- Added the `--force` flag to the `start` command to skip the started services check
None
None

feat(dashmate): force start

---

CHANGELOG.md
package.json
packages/bench-suite/package.json
packages/dapi-grpc/package.json
packages/dapi/package.json
packages/dash-spv/package.json
packages/dashmate/package.json
packages/dashpay-contract/package.json
packages/dpns-contract/package.json
packages/feature-flags-contract/package.json
packages/js-dapi-client/package.json
packages/js-dash-sdk/package.json
packages/js-dpp/package.json
packages/js-grpc-common/package.json
packages/masternode-reward-shares-contract/package.json
packages/platform-test-suite/package.json
packages/wallet-lib/package.json
packages/wasm-dpp/package.json
packages/withdrawals-contract/package.json

chore(release): update changelog and bump version to 0.25.2

---

CHANGELOG.md
package.json
packages/bench-suite/package.json
packages/dapi-grpc/package.json
packages/dapi/package.json
packages/dash-spv/package.json
packages/dashmate/package.json
packages/dashpay-contract/package.json
packages/dpns-contract/package.json
packages/feature-flags-contract/package.json
packages/js-dapi-client/package.json
packages/js-dash-sdk/package.json
packages/js-dpp/package.json
packages/js-grpc-common/package.json
packages/masternode-reward-shares-contract/package.json
packages/platform-test-suite/package.json
packages/wallet-lib/package.json
packages/wasm-dpp/package.json
packages/withdrawals-contract/package.json

chore(release): update changelog and bump version to 0.25.3

---

packages/rs-sdk/tests/fetch/common.rs
packages/rs-sdk/tests/fetch/data_contract.rs
packages/rs-sdk/tests/fetch/document.rs
packages/rs-sdk/tests/fetch/main.rs
packages/rs-sdk/tests/fetch/mock_fetch.rs
packages/rs-sdk/tests/fetch/mock_list.rs

added files without import to allow IDE to work better

---

package.json
packages/bench-suite/package.json
packages/dapi-grpc/package.json
packages/dapi/package.json
packages/dash-spv/package.json
packages/dashmate/package.json
packages/dashpay-contract/package.json
packages/dpns-contract/package.json
packages/feature-flags-contract/package.json
packages/js-dapi-client/package.json
packages/js-dash-sdk/package.json
packages/js-dpp/package.json
packages/js-grpc-common/package.json
packages/masternode-reward-shares-contract/package.json
packages/platform-test-suite/package.json
packages/rs-drive-abci/src/abci/handler/mod.rs
packages/rs-drive-abci/src/execution/engine/run_block_proposal/v0/mod.rs
packages/rs-drive-abci/src/execution/platform_events/core_based_updates/update_masternode_list/v0/mod.rs
packages/rs-drive-abci/src/execution/platform_events/core_based_updates/update_quorum_info/v0/mod.rs
packages/rs-drive-abci/src/platform_types/block_proposal/v0.rs
packages/rs-drive-abci/src/platform_types/platform_state/mod.rs
packages/wallet-lib/package.json
packages/wasm-dpp/package.json
packages/withdrawals-contract/package.json

Add even more logs to be able to catch non determinism issues.

test: add more logs in process proposal with state fingerprint

---

packages/rs-drive-abci/src/execution/engine/run_block_proposal/v0/mod.rs
packages/rs-drive-abci/src/execution/platform_events/core_based_updates/update_masternode_list/v0/mod.rs
packages/rs-drive-abci/src/execution/platform_events/core_based_updates/update_quorum_info/v0/mod.rs
packages/rs-drive-abci/src/platform_types/block_proposal/v0.rs
packages/rs-drive-abci/src/platform_types/masternode/v0/mod.rs
packages/rs-drive-abci/src/platform_types/platform_state/v0/mod.rs
packages/rs-drive-abci/src/platform_types/validator/v0/mod.rs
packages/rs-drive-abci/src/platform_types/validator_set/v0/mod.rs
packages/rs-platform-value/src/string_encoding.rs

We now log hex strings instead of arrays of numbers for various hashes.

chore: logging hex strings

---

CHANGELOG.md
package.json
packages/bench-suite/package.json
packages/dapi-grpc/package.json
packages/dapi/package.json
packages/dash-spv/package.json
packages/dashmate/package.json
packages/dashpay-contract/package.json
packages/dpns-contract/package.json
packages/feature-flags-contract/package.json
packages/js-dapi-client/package.json
packages/js-dash-sdk/package.json
packages/js-dpp/package.json
packages/js-grpc-common/package.json
packages/masternode-reward-shares-contract/package.json
packages/platform-test-suite/package.json
packages/wallet-lib/package.json
packages/wasm-dpp/package.json
packages/withdrawals-contract/package.json

chore(release): update changelog and bump version to 0.25.6

---

packages/rs-drive-abci/src/abci/handler/mod.rs
packages/rs-drive-abci/src/execution/engine/initialization/init_chain/v0/mod.rs
packages/rs-drive-abci/src/execution/engine/run_block_proposal/v0/mod.rs
packages/rs-drive-abci/src/execution/platform_events/core_based_updates/update_masternode_list/v0/mod.rs
packages/rs-drive-abci/src/execution/platform_events/core_based_updates/update_quorum_info/v0/mod.rs
packages/rs-drive/src/drive/grove_operations/grove_apply_batch_with_add_costs/v0/mod.rs
packages/rs-drive/src/drive/grove_operations/grove_clear/v0/mod.rs

We need more logs for testing 
- Added more params and logs
None
None

chore(drive): add more logs

---

CHANGELOG.md
package.json
packages/bench-suite/package.json
packages/dapi-grpc/package.json
packages/dapi/package.json
packages/dash-spv/package.json
packages/dashmate/package.json
packages/dashpay-contract/package.json
packages/dpns-contract/package.json
packages/feature-flags-contract/package.json
packages/js-dapi-client/package.json
packages/js-dash-sdk/package.json
packages/js-dpp/package.json
packages/js-grpc-common/package.json
packages/masternode-reward-shares-contract/package.json
packages/platform-test-suite/package.json
packages/wallet-lib/package.json
packages/wasm-dpp/package.json
packages/withdrawals-contract/package.json

chore(release): update changelog and bump version to 0.25.7

---

packages/rs-drive-abci/src/execution/engine/initialization/init_chain/v0/mod.rs
packages/rs-drive-abci/src/execution/engine/run_block_proposal/v0/mod.rs
packages/rs-drive-abci/src/execution/platform_events/core_based_updates/update_masternode_list/v0/mod.rs
packages/rs-drive-abci/src/execution/platform_events/core_based_updates/update_quorum_info/v0/mod.rs
packages/rs-drive-abci/src/execution/platform_events/state_transition_processing/process_raw_state_transitions/v0/mod.rs

The source of non-determinism is identified in this platform runtime 
- Removed state print
None
None

chore(drive): remove runtime state logging

---

.github/actions/docker/action.yaml
.github/workflows/release.yml

Releasing drive was very slow, needing 1.5-2h in most cases
https://github.com/dcginfra/tf-aws-gh-runner/pull/18 provides a new set of `c6id.8xlarge` runners for particularly slow actions.
With workflow_dispatch
None

ci: c6id.8xlarge runners

---

CHANGELOG.md
package.json
packages/bench-suite/package.json
packages/dapi-grpc/package.json
packages/dapi/package.json
packages/dash-spv/package.json
packages/dashmate/package.json
packages/dashpay-contract/package.json
packages/dpns-contract/package.json
packages/feature-flags-contract/package.json
packages/js-dapi-client/package.json
packages/js-dash-sdk/package.json
packages/js-dpp/package.json
packages/js-grpc-common/package.json
packages/masternode-reward-shares-contract/package.json
packages/platform-test-suite/package.json
packages/wallet-lib/package.json
packages/wasm-dpp/package.json
packages/withdrawals-contract/package.json

chore(release): update changelog and bump version to 0.25.8

---

packages/dashmate/src/commands/build.js
packages/dashmate/src/commands/docker/build.js

Sometimes we need to only build docker images from sources without starting a node
- Introduced the `dashmate docker build` command to build docker images for configured services
Manually
None

feat(dashmate): docker build command

---

README.md

docs: Update README.md to give information about correctly adding to correct Shell $PATH

---

CHANGELOG.md
package.json
packages/bench-suite/package.json
packages/dapi-grpc/package.json
packages/dapi/package.json
packages/dash-spv/package.json
packages/dashmate/package.json
packages/dashpay-contract/package.json
packages/dpns-contract/package.json
packages/feature-flags-contract/package.json
packages/js-dapi-client/package.json
packages/js-dash-sdk/package.json
packages/js-grpc-common/package.json
packages/masternode-reward-shares-contract/package.json
packages/platform-test-suite/package.json
packages/wallet-lib/package.json
packages/wasm-dpp/package.json
packages/withdrawals-contract/package.json

chore(release): update changelog and bump version to 0.25.9

---

CHANGELOG.md
package.json
packages/bench-suite/package.json
packages/dapi-grpc/package.json
packages/dapi/package.json
packages/dash-spv/package.json
packages/dashmate/package.json
packages/dashpay-contract/package.json
packages/dpns-contract/package.json
packages/feature-flags-contract/package.json
packages/js-dapi-client/package.json
packages/js-dash-sdk/package.json
packages/js-grpc-common/package.json
packages/masternode-reward-shares-contract/package.json
packages/platform-test-suite/package.json
packages/wallet-lib/package.json
packages/wasm-dpp/package.json
packages/withdrawals-contract/package.json

chore(release): update changelog and bump version to 0.25.10

---

CHANGELOG.md
package.json
packages/bench-suite/package.json
packages/dapi-grpc/package.json
packages/dapi/package.json
packages/dash-spv/package.json
packages/dashmate/package.json
packages/dashpay-contract/package.json
packages/dpns-contract/package.json
packages/feature-flags-contract/package.json
packages/js-dapi-client/package.json
packages/js-dash-sdk/package.json
packages/js-grpc-common/package.json
packages/masternode-reward-shares-contract/package.json
packages/platform-test-suite/package.json
packages/wallet-lib/package.json
packages/wasm-dpp/package.json
packages/withdrawals-contract/package.json

chore(release): update changelog and bump version to 0.25.11

---

packages/dashmate/configs/defaults/getTestnetConfigFactory.js
packages/dashmate/configs/getConfigFileMigrationsFactory.js
packages/platform-test-suite/test/functional/platform/Epoch.spec.js
packages/platform-test-suite/test/functional/platform/ProtocolVersion.spec.js

Add new dash-testnet-35 support for testnet nodes
* Set new genesis for dash-testnet-35
* Bump core fore testnet to dashpay/dashd:20.0.0-rc.2
CI
No

chore(dashmate): testnet-35 support

---

CHANGELOG.md
package.json
packages/bench-suite/package.json
packages/dapi-grpc/package.json
packages/dapi/package.json
packages/dash-spv/package.json
packages/dashmate/package.json
packages/dashpay-contract/package.json
packages/dpns-contract/package.json
packages/feature-flags-contract/package.json
packages/js-dapi-client/package.json
packages/js-dash-sdk/package.json
packages/js-grpc-common/package.json
packages/masternode-reward-shares-contract/package.json
packages/platform-test-suite/package.json
packages/wallet-lib/package.json
packages/wasm-dpp/package.json
packages/withdrawals-contract/package.json

chore(release): update changelog and bump version to 0.25.12

---

CHANGELOG.md
package.json
packages/bench-suite/package.json
packages/dapi-grpc/package.json
packages/dapi/package.json
packages/dash-spv/package.json
packages/dashmate/package.json
packages/dashpay-contract/package.json
packages/dpns-contract/package.json
packages/feature-flags-contract/package.json
packages/js-dapi-client/package.json
packages/js-dash-sdk/package.json
packages/js-grpc-common/package.json
packages/masternode-reward-shares-contract/package.json
packages/platform-test-suite/package.json
packages/wallet-lib/package.json
packages/wasm-dpp/package.json
packages/withdrawals-contract/package.json

chore(release): update changelog and bump version to 0.25.13

---

Cargo.lock
packages/dapi-grpc/Cargo.toml
packages/dashpay-contract/Cargo.toml
packages/rs-dpp/Cargo.toml
packages/rs-drive-abci/Cargo.toml
packages/rs-drive-proof-verifier/Cargo.toml
packages/rs-drive/Cargo.toml
packages/rs-platform-serialization/Cargo.toml
packages/rs-platform-value-convertible/Cargo.toml
packages/rs-platform-value/Cargo.toml
packages/rs-platform-version/Cargo.toml
packages/strategy-tests/Cargo.toml
packages/wasm-dpp/Cargo.toml
packages/withdrawals-contract/Cargo.toml

Build process 
Used cargo-machete to identify and remove unused dependencies
* built each crate with `cargo build`
* checked github workflows
Some features might stop working

chore: remove unused dependencies of rust crates

---

packages/dashmate/configs/defaults/getBaseConfigFactory.js
packages/dashmate/configs/getConfigFileMigrationsFactory.js
packages/dashmate/docker-compose.insight_api.yml
packages/dashmate/docker-compose.insight_ui.yml
packages/dashmate/src/config/configJsonSchema.js
packages/dashmate/src/config/generateEnvsFactory.js
packages/dashmate/src/config/getConfigProfilesFactory.js
packages/dashmate/templates/core/insight/dashcore-node.json.dot
scripts/setup_local_network.sh

[The platform explorer](https://github.com/dashpay/rs-platform-explorer/tree/feat/identityRegistration) requires insight to obtain utxos for simple wallet. To enable platfrom explorer for dashmate local network we need insight to be started
- Added insight API and UI to dashmate
- Enable insight api with `yarn setup`
`core.insight.enabled` to enable API, and `core.insight.ui.enabled` to UI (API must be enabled too)
Use API:
```
curl http://127.0.0.1:3001/insight-api/block-index/0
```
Open UI:
```
open http://127.0.0.1:3001/insight/
```

feat(dashmate): insight, core block explorer

---

packages/dashmate/src/listr/prompts/createIpAndPortsForm.js
packages/dashmate/src/printers/printObject.js
packages/dashmate/src/status/colors.js
packages/dashmate/src/status/scopes/host.js
packages/dashmate/test/unit/status/colors.spec.js

Fix few bugs found by @strophy and Node.JS v20 leftover
* Fixed imports for `table` dependency
* Fixed imports for `public-ip` dependency
* Corrected `dashmate status core` block height color when remoteBlockHeight is null
Locally
No

fix(dashmate): publicIp.v4 function is undefined

---

packages/dashmate/configs/defaults/getBaseConfigFactory.js
packages/dashmate/configs/defaults/getMainnetConfigFactory.js
packages/dashmate/configs/defaults/getTestnetConfigFactory.js
packages/dashmate/configs/getConfigFileMigrationsFactory.js

Upgrade core version to 20.0.1 and update genesis to dash-testnet-26
* Updated core version
* Updated testnet platform genesis to dash-testnet-26
Locally
No

feat(dashmate): update core version to 20.0.1

---

Cargo.lock
packages/rs-dpp/src/errors/consensus/consensus_error.rs
packages/rs-dpp/src/state_transition/mod.rs
packages/rs-drive-abci/src/abci/handler/mod.rs
packages/rs-drive-abci/src/execution/engine/run_block_proposal/v0/mod.rs
packages/rs-drive-abci/src/execution/platform_events/core_based_updates/update_masternode_list/v0/mod.rs
packages/rs-drive-abci/src/execution/platform_events/core_based_updates/update_quorum_info/v0/mod.rs
packages/rs-drive-abci/src/execution/platform_events/state_transition_processing/process_raw_state_transitions/v0/mod.rs
packages/rs-drive-abci/src/logging/level.rs
packages/rs-drive-abci/src/main.rs
packages/rs-drive-abci/src/platform_types/platform/mod.rs
packages/rs-drive/Cargo.toml
packages/rs-drive/src/drive/balances/mod.rs
packages/rs-drive/src/drive/batch/drive_op_batch/mod.rs
packages/rs-drive/src/drive/cache.rs
packages/rs-drive/src/drive/contract/mod.rs
packages/rs-drive/src/drive/document/delete/mod.rs
packages/rs-drive/src/drive/document/insert/mod.rs
packages/rs-drive/src/drive/document/mod.rs
packages/rs-drive/src/drive/document/update/mod.rs
packages/rs-drive/src/drive/identity/insert/add_new_identity/v0/mod.rs
packages/rs-drive/src/drive/initialization/v0/mod.rs
packages/rs-drive/src/drive/open/mod.rs
packages/rs-drive/src/drive/protocol_upgrade/fetch_versions_with_counter/v0/mod.rs
packages/rs-drive/src/query/mod.rs
packages/rs-drive/src/tests/helpers/setup.rs
packages/rs-drive/tests/deterministic_root_hash.rs
packages/rs-drive/tests/query_tests.rs

Drive produces wrong app hash after resart.
- Fixed protocol version vote counter deserialzation 
- Improved logging in Drive ABCI
- Removed grovedb operations logs from trace level
- Passed the latest protocol version on Info to propose a correct version
Synced a local testnet node and then restat it
None

fix: drive produces wrong app hash after restart

---

packages/dashmate/configs/defaults/getTestnetConfigFactory.js
packages/dashmate/configs/getConfigFileMigrationsFactory.js

Dashmate should be able to connect to the latest testnet-37 network
Added new genesis and migration script
No
No

chore(dashmate): add platform testnet-37 support

---

packages/dashmate/configs/defaults/getBaseConfigFactory.js
packages/dashmate/configs/getConfigFileMigrationsFactory.js

Update tenderdash to recent version
- Updated tenderdash to 0.13.4
None
None

chore(dashmate): update tenderdash to 0.13.4

---

Cargo.lock
packages/platform-test-suite/test/functional/platform/Identity.spec.js
packages/rs-drive-abci/src/execution/check_tx/v0/mod.rs

Blocks are falling on testnet when we are getting credit transfer transitions:
```
2023-12-12T09:50:09.402439Z ERROR tenderdash_abci::server::generic: error processing request, error: "execution: corrupted credits not balanced error: credits are not balanced after block execution TotalCreditsBalance { total_credits_in_platform: 4857755289070950, total_in_pools: 56026273044, total_identity_balances: 4857699272797906 } off by 10000000", request: Request { value: Some(PrepareProposal(RequestPrepareProposal { max_tx_bytes: 22018983, txs: [[7, 0, 59, 103, 131, 253, 131, 2, 255, 161, 81, 35, 31, 43, 64, 115, 244, 37, 129, 164, 73, 60, 175, 35, 36, 93, 127, 48, 249, 8, 61, 176, 25, 207, 59, 103, 131, 253, 131, 2, 255, 161, 81, 35, 31, 43, 64, 115, 244, 37, 129, 164, 73, 60, 175, 35, 36, 93, 127, …
```

chore(drive): temporary disable credit transfer transitions

---

packages/dashmate/README.md
packages/dashmate/src/commands/config/render.js
packages/dashmate/test/unit/commands/config/render.spec.js

Add `dashmate config render` command that allow you to forcibly render all config's service configs (dashd.conf, config.toml, etc.)
* Added `dashmate config render` command
* Added unit test
* Updated README.md
Checked locally via testnet fullnode + unit test
No

feat(dashmate): add config render command

---

Cargo.lock
packages/platform-test-suite/test/functional/platform/Identity.spec.js
packages/rs-drive-abci/src/execution/check_tx/v0/mod.rs

revert: temporary disable credit transfer transitions

---

Cargo.lock
packages/rs-drive-abci/src/abci/handler/mod.rs
packages/rs-drive-abci/src/mimic/mod.rs

There was a rare situation where the network could loose information about previous rounds, but then find them again after the prepare proposal. This PR aims to fix this, we will drop the internal cache and rerun the block.

fix(drive-abci): rare process proposal when we prepared tx change

---

packages/dapi/lib/grpcServer/handlers/platform/broadcastStateTransitionHandlerFactory.js
packages/rs-drive-abci/src/abci/handler/mod.rs
packages/rs-drive-abci/src/execution/platform_events/state_transition_processing/process_raw_state_transitions/v0/mod.rs
packages/rs-drive-abci/src/metrics.rs

We need block processing time in logs
- Log block processing time
- Fixed tx counters logging
- Decrease the level for annoying info message
- Add error logging to the DAPI's broadcast state transition endpoint
None
None

chore: various logging improvements

---

packages/rs-dpp/src/state_transition/proof_result.rs
packages/rs-drive-proof-verifier/src/proof.rs
packages/rs-drive/src/drive/verify/identity/verify_identity_keys_by_identity_id/mod.rs
packages/rs-drive/src/drive/verify/identity/verify_identity_keys_by_identity_id/v0/mod.rs
packages/rs-drive/src/drive/verify/state_transition/verify_state_transition_was_executed_with_proof/v0/mod.rs

Expanded a method indirectly used by SDK to verify state transition results
Along with keys it also may request for balance and revision, the data that was actually provided by drive-abci as a proof of identity update state transition success, but that wasn't requested for verification

fix: identity update transition verification

---

Cargo.lock
packages/dapi-grpc/Cargo.toml
packages/dashmate/configs/defaults/getBaseConfigFactory.js
packages/rs-drive-abci/Cargo.toml
packages/rs-drive-abci/src/abci/handler/mod.rs
packages/rs-drive-abci/src/execution/engine/finalize_block_proposal/v0/mod.rs
packages/rs-drive-abci/src/mimic/mod.rs
packages/rs-drive-abci/src/platform_types/commit/v0/mod.rs
packages/rs-drive-abci/src/platform_types/withdrawal/withdrawal_txs/v0/mod.rs
packages/rs-drive-abci/tests/strategy_tests/query.rs
packages/rs-drive-proof-verifier/Cargo.toml
packages/rs-drive-proof-verifier/src/verify.rs

This adapts Platform to changes introduced in https://github.com/dashpay/rs-tenderdash-abci/pull/43 
Updated dependencies, renamed some fields
GHA
None

chore: update rs-tenderdash-abci to v0.14.0-dev.6 and tenderdash to v0.14.0-dev.2

---

packages/rs-sdk/Cargo.toml
packages/rs-sdk/src/core_client.rs
packages/rs-sdk/src/mock.rs
packages/rs-sdk/src/platform/fetch_many.rs
packages/rs-sdk/src/platform/transition/withdraw_from_identity.rs
packages/rs-sdk/src/sdk.rs
packages/rs-sdk/tests/fetch/broadcast.rs
packages/rs-sdk/tests/fetch/data_contract.rs
packages/rs-sdk/tests/fetch/document.rs
packages/rs-sdk/tests/fetch/epoch.rs
packages/rs-sdk/tests/fetch/identity.rs
packages/rs-sdk/tests/fetch/mock_fetch.rs
packages/rs-sdk/tests/fetch/mock_fetch_many.rs
packages/rs-sdk/tests/fetch/mod.rs
packages/rs-sdk/tests/fetch/protocol_version_vote_count.rs
packages/rs-sdk/tests/fetch/protocol_version_votes.rs
packages/rs-sdk/tests/main.rs

rs-sdk --no-default-features does not build
fixed features flags
built locally
None

fix(sdk): rs-sdk --no-default-features does not build

---

packages/js-dash-sdk/src/SDK/Client/Platform/methods/identities/creditWithdrawal.ts
packages/rs-dpp/src/state_transition/state_transitions/identity/identity_credit_withdrawal_transition/v0/mod.rs
packages/rs-drive-abci/src/execution/validation/state_transition/state_transitions/identity_credit_withdrawal/structure/v0/mod.rs

Removes minimal core fee per byte validation since it's minimum is 1 duff/byte and it's covered by fibonacci check

refactor(drive): remove min core fee per byte check

---

packages/strategy-tests/src/lib.rs

This is a one-line PR that just adds ContractUpdate transitions to the used_contract_ids function for strategy tests.
This is a one-line PR that just adds ContractUpdate transitions to the used_contract_ids function for strategy tests.
In Platform TUI strategy tests

feat: add ContractUpdate to used_contract_ids function

---

packages/rs-drive/src/lib.rs

refactor(drive): expose more groveDB internals

---

packages/rs-platform-serialization/src/features/impl_alloc.rs
packages/rs-platform-value/src/inner_value.rs
packages/rs-platform-value/src/inner_value_at_path.rs
packages/rs-platform-value/src/value_serialization/de.rs
packages/rs-platform-value/src/value_serialization/ser.rs

Clippy warnings resolved
`Cargo t` in root
None

refactor: resolve a few clippy warnings in rs-platform-serializaation and rs-platform-value

---

packages/rs-dpp/src/data_contract/document_type/class_methods/try_from_schema/v0/mod.rs
packages/rs-dpp/src/document/extended_document/mod.rs
packages/rs-dpp/src/document/extended_document/v0/mod.rs
packages/rs-dpp/src/identity/identity_factory.rs
packages/rs-dpp/src/identity/identity_nonce.rs
packages/rs-dpp/src/state_transition/mod.rs
packages/rs-dpp/src/state_transition/state_transitions/document/documents_batch_transition/document_transition/document_base_transition/mod.rs
packages/rs-dpp/src/state_transition/state_transitions/document/documents_batch_transition/document_transition/document_base_transition/v0/mod.rs
packages/rs-dpp/src/state_transition/state_transitions/document/documents_batch_transition/document_transition/document_create_transition/convertible.rs
packages/rs-dpp/src/state_transition/state_transitions/identity/public_key_in_creation/methods/hash/v0/mod.rs
packages/rs-drive/src/drive/identity/contract_info/identity_contract_nonce/fetch_identity_contract_nonce/v0/mod.rs
packages/rs-drive/src/drive/identity/contract_info/identity_contract_nonce/merge_identity_contract_nonce/v0/mod.rs
packages/rs-drive/src/drive/identity/fetch/queries/mod.rs
packages/rs-platform-value/src/inner_value_at_path.rs
packages/rs-platform-value/src/value_serialization/ser.rs
packages/strategy-tests/src/lib.rs

Seems like we had merged without a fmt, this should fix things.

chore: fmt

---

packages/wasm-dpp/src/data_contract/data_contract.rs
packages/wasm-dpp/src/data_contract/data_contract_facade.rs
packages/wasm-dpp/src/data_contract/state_transition/data_contract_update_transition/mod.rs
packages/wasm-dpp/src/data_contract_factory/data_contract_factory.rs
packages/wasm-dpp/src/document/document_facade.rs
packages/wasm-dpp/src/document/extended_document.rs
packages/wasm-dpp/src/document/factory.rs
packages/wasm-dpp/src/document/mod.rs
packages/wasm-dpp/src/document/state_transition/document_batch_transition/document_transition/mod.rs
packages/wasm-dpp/src/document/state_transition/document_batch_transition/mod.rs
packages/wasm-dpp/src/errors/consensus/basic/mod.rs
packages/wasm-dpp/src/errors/consensus/state/identity/invalid_identity_contract_nonce_error.rs
packages/wasm-dpp/src/identifier/mod.rs
packages/wasm-dpp/src/identity/errors/mod.rs
packages/wasm-dpp/src/identity/identity_facade.rs
packages/wasm-dpp/src/identity/identity_factory.rs
packages/wasm-dpp/src/identity/identity_public_key/mod.rs
packages/wasm-dpp/src/identity/state_transition/identity_create_transition/identity_create_transition.rs
packages/wasm-dpp/src/identity/state_transition/identity_credit_transfer_transition/transition.rs
packages/wasm-dpp/src/identity/state_transition/identity_credit_withdrawal_transition/to_object.rs
packages/wasm-dpp/src/identity/state_transition/identity_credit_withdrawal_transition/transition.rs
packages/wasm-dpp/src/identity/state_transition/identity_topup_transition/identity_topup_transition.rs
packages/wasm-dpp/src/identity/state_transition/identity_update_transition/identity_update_transition.rs
packages/wasm-dpp/src/metadata.rs
packages/wasm-dpp/src/state_transition/state_transition_factory.rs
packages/wasm-dpp/src/utils.rs

Resolve clippy warnings in wasm-dpp
repo wide clippy warnings 326 -> 288
cargo t in root
None

refactor: resolve clippy warnings in wasm-dpp

---

packages/dashmate/configs/defaults/getLocalConfigFactory.js
packages/dashmate/configs/defaults/getTestnetConfigFactory.js
packages/dashmate/configs/getConfigFileMigrationsFactory.js

We need to align dashmate to recent testnet settings
- Updated testnet genesis
- Updated Core to 20.1.0-nightly.2024.02.15
None
Previous testnet was destroyed so there is no breaking change 

chore: update testnet genesis and core nightly

---

packages/dashmate/configs/defaults/getLocalConfigFactory.js
packages/dashmate/configs/defaults/getTestnetConfigFactory.js
packages/dashmate/configs/getConfigFileMigrationsFactory.js

Update Platform to recent version of Core
- Updated dashmate to Core 20.1
None
None

chore(dashmate): upgrade to Core 20.1

---

packages/rs-drive-abci/tests/strategy_tests/execution.rs
packages/rs-drive-abci/tests/strategy_tests/strategy.rs
packages/strategy-tests/README.md
packages/strategy-tests/src/lib.rs

The descriptions for functions, Strategy struct, and the file were all outdated. So were the function names.
Updated them all and added a readme file.
cargo test

feat: updated descriptions and function names in strategy tests plus readme file

---

packages/rs-drive-abci/tests/strategy_tests/main.rs
packages/rs-drive-abci/tests/strategy_tests/strategy.rs
packages/strategy-tests/src/lib.rs

Added a test registering 30 random contracts with 10 indexes for 30 blocks

test: added a test registering many random contracts in strategy tests

---

packages/rs-sdk/src/lib.rs

Exports various sub libraries in rs-sdk to make things easier for users of the sdk.

chore(sdk): export various libraries in rs-sdk

---

Cargo.lock
packages/dapi-grpc/Cargo.toml
packages/dapi-grpc/src/core/proto/org.dash.platform.dapi.v0.rs
packages/dapi-grpc/src/platform/proto/org.dash.platform.dapi.v0.rs
packages/dashpay-contract/Cargo.toml
packages/data-contracts/Cargo.toml
packages/dpns-contract/Cargo.toml
packages/feature-flags-contract/Cargo.toml
packages/masternode-reward-shares-contract/Cargo.toml
packages/rs-dapi-client/Cargo.toml
packages/rs-dapi-grpc-macros/Cargo.toml
packages/rs-dpp/Cargo.toml
packages/rs-drive-abci/Cargo.toml
packages/rs-drive-proof-verifier/Cargo.toml
packages/rs-drive/Cargo.toml
packages/rs-drive/src/query/mod.rs
packages/rs-platform-version/Cargo.toml
packages/rs-sdk/Cargo.toml
packages/wasm-dpp/Cargo.toml
packages/withdrawals-contract/Cargo.toml

Some dependencies are causing issues for mobile, in this version we updated a few dependencies to see if this would solve the issues.

refactor: reduce dependencies and update ring sub dependency

---

packages/rs-drive-abci/src/execution/engine/initialization/init_chain/v0/mod.rs

Just added a few comments explaining the initial core chain locked height and how quorums are selected based on it.

docs(drive-abci): added some comments on the initial core height and quorums

---

packages/rs-dpp/src/voting/contender_structs/contender/mod.rs
packages/rs-dpp/src/voting/contender_structs/contender/v0/mod.rs
packages/rs-dpp/src/voting/contender_structs/mod.rs
packages/rs-dpp/src/voting/vote_info_storage/contested_document_vote_poll_stored_info/v0/mod.rs
packages/rs-drive-abci/src/execution/validation/state_transition/state_transitions/documents_batch/mod.rs
packages/rs-drive-abci/src/execution/validation/state_transition/state_transitions/masternode_vote/mod.rs
packages/rs-drive-abci/src/execution/validation/state_transition/state_transitions/mod.rs
packages/rs-drive-abci/src/query/voting/contested_resource_vote_state/v0/mod.rs
packages/rs-drive/src/drive/verify/voting/verify_vote_poll_vote_state_proof/v0/mod.rs
packages/rs-drive/src/query/vote_poll_vote_state_query.rs

Adds contender serialization and versioning.

feat: contender serialization

---

Cargo.lock
packages/rs-dapi-client/Cargo.toml
packages/rs-dpp/src/errors/consensus/codes.rs
packages/rs-platform-version/src/version/mocks/v2_test.rs
packages/rs-platform-version/src/version/mocks/v3_test.rs
packages/rs-platform-version/src/version/v1.rs
packages/wasm-dpp/src/errors/consensus/basic/data_contract/index_error/unique_indices_limit_reached_error.rs
packages/wasm-dpp/src/errors/consensus/consensus_error.rs

Merge of #1891 broke build.
Fixed issues.
GHA

fix: build broken after merge of contested unique indexes validation

---

Cargo.lock
packages/dapi-grpc/Cargo.toml
packages/dashmate/configs/defaults/getBaseConfigFactory.js
packages/dashmate/configs/getConfigFileMigrationsFactory.js
packages/rs-drive-abci/Cargo.toml
packages/rs-drive-proof-verifier/Cargo.toml

New version of Tenderdash was released.
Updated rs-tenderdash-abci dependency to 1.0.0-dev.1
Updated Tenderdash image to 1.0.0-dev.2
GHA
None

build: update rs-tenderdash-abci to 1.0.0-dev.1

---

packages/rs-dpp/schema/meta_schemas/document/v0/document-meta.json

`dependentSchemas` could lead to validation errors and misparsing of document type. We don't support conditions in JSON Schema atm
- Removed `dependentSchemas` from document meta schema
None
Previous contracts might become invalid.

chore(dpp)!: do not allow `dependentSchemas`

---

Cargo.lock
packages/rs-drive-abci/src/execution/validation/state_transition/state_transitions/masternode_vote/mod.rs
packages/rs-drive-proof-verifier/src/proof.rs
packages/rs-drive/Cargo.toml
packages/rs-drive/src/drive/document/insert_contested/add_contested_indices_for_contract_operations/v0/mod.rs
packages/rs-drive/src/drive/verify/voting/verify_identity_votes_given_proof/mod.rs
packages/rs-drive/src/drive/verify/voting/verify_identity_votes_given_proof/v0/mod.rs
packages/rs-drive/src/drive/verify/voting/verify_vote_poll_vote_state_proof/v0/mod.rs
packages/rs-drive/src/drive/verify/voting/verify_vote_polls_end_date_query/mod.rs
packages/rs-drive/src/drive/verify/voting/verify_vote_polls_end_date_query/v0/mod.rs
packages/rs-drive/src/drive/votes/fetch/fetch_contested_document_vote_poll_stored_info/v0/mod.rs
packages/rs-drive/src/drive/votes/fetch/fetch_identities_voting_for_contenders/v0/mod.rs
packages/rs-drive/src/drive/votes/insert/contested_resource/insert_stored_info_for_contested_resource_vote_poll/v0/mod.rs
packages/rs-drive/src/drive/votes/mod.rs
packages/rs-drive/src/drive/votes/paths.rs
packages/rs-drive/src/drive/votes/storage_form/contested_document_resource_storage_form/mod.rs
packages/rs-drive/src/query/vote_poll_vote_state_query.rs

Changed some queries to use generics.
Added additional tests.
Abstain and Lock trees for votes are now always first.

fix: Abstain and Lock trees for votes are now always first and fixed some limits

---

README.md

On Ubuntu, I had to install llvm to get `yarn setup` to work
Added `llvm` to the list of packages to install
Installed locally and then was able to run yarn setup
N/A

docs: add llvm to README.md

---

packages/rs-drive-abci/src/abci/handler/prepare_proposal.rs
packages/rs-drive-abci/src/abci/handler/process_proposal.rs
packages/rs-drive-abci/src/execution/engine/run_block_proposal/v0/mod.rs
packages/rs-drive-abci/src/execution/platform_events/fee_pool_outwards_distribution/add_epoch_pool_to_proposers_payout_operations/v0/mod.rs
packages/rs-drive-abci/src/execution/platform_events/protocol_upgrade/check_for_desired_protocol_upgrade/v0/mod.rs
packages/rs-drive-abci/src/execution/platform_events/protocol_upgrade/upgrade_protocol_version/v0/mod.rs

chore: better logging for devnet upgrade protocol test

---

.github/actions/local-network/action.yaml
.github/workflows/tests-dashmate.yml
packages/dashmate/src/docker/DockerCompose.js
packages/dashpay-contract/test/unit/schema.spec.js
packages/withdrawals-contract/test/unit/withdrawalsContract.spec.js

Sometimes dashmate fails with:
```
Invalid version. Must be a string. Got type "object".
```
- Added debug output in case if docker version check fails
None
None

chore(dashmate): provide debug information if version check fails

---

packages/dashmate/src/listr/tasks/setup/regular/importCoreDataTaskFactory.js

An error on import:
```
✔ Configuration preset
› testnet
✔ Node type
› masternode
✔ System requirements
✖ Cannot read properties of null (reading '1')
```
- Handle absent Core configuration options 
None
None

fix(dashmate): cannot read properties of null (reading '1')

---

Cargo.lock
packages/rs-drive/Cargo.toml
packages/rs-platform-version/Cargo.toml

Updating grovedb to release version
Nothing should be breaking

chore: update to latest grovedb 1.0.0-rc.2

---

packages/rs-dpp/src/block/epoch/mod.rs

Very small change here, before we were serializing Epoch's as 4 bytes, instead of 2 bytes.
Updated Epoch serialization.
Not breaking.

refactor: changed Epoch serialization to make it slightly more efficient

---

packages/rs-dpp/src/errors/consensus/basic/basic_error.rs
packages/rs-dpp/src/errors/consensus/basic/mod.rs
packages/rs-dpp/src/errors/consensus/basic/unsupported_feature_error.rs
packages/rs-dpp/src/errors/consensus/codes.rs
packages/rs-dpp/src/state_transition/state_transitions/identity/identity_credit_withdrawal_transition/methods/mod.rs
packages/rs-dpp/src/state_transition/state_transitions/identity/identity_credit_withdrawal_transition/methods/v0/mod.rs
packages/rs-dpp/src/state_transition/state_transitions/identity/identity_credit_withdrawal_transition/v0/v0_methods.rs
packages/rs-drive-abci/src/execution/validation/state_transition/state_transitions/identity_credit_withdrawal/mod.rs
packages/rs-drive-abci/src/execution/validation/state_transition/state_transitions/identity_credit_withdrawal/structure/mod.rs
packages/rs-drive-abci/src/execution/validation/state_transition/state_transitions/identity_credit_withdrawal/structure/v0/mod.rs
packages/rs-drive-abci/src/execution/validation/state_transition/state_transitions/identity_credit_withdrawal/structure/v1/mod.rs
packages/rs-drive-abci/src/execution/validation/state_transition/state_transitions/mod.rs
packages/rs-drive-abci/tests/strategy_tests/main.rs
packages/rs-drive/src/drive/balances/remove_from_system_credits_operations/v0/mod.rs
packages/rs-platform-version/src/version/v1.rs
packages/rs-sdk/src/platform/transition/withdraw_from_identity.rs
packages/wasm-dpp/src/errors/consensus/consensus_error.rs

Platform hasn't been tested enough for withdrawals, hence we and the network with a vote decided to go an accelerated release that would see withdrawals disabled for the first version.
Disabled withdrawals.
Unit test

chore(platform)!: disable credit withdrawals in V1

---

.github/workflows/release-docker-image.yml

https://github.com/dashpay/platform/actions/runs/9960069760
- Passed AWS creds to docker build
None
None

ci: fix docker build for release

---

.github/workflows/release-docker-image.yml

We were using /tmp which is wiped at the end of a job
Use ./digest for now
Locally
None

fix(ci): Fix issue with empty dir in release process

---

.github/workflows/release-docker-image.yml

The build and publish docker image workflow is not working
- Increased timeout
- Cleanup digest directory before storing a new digest
Ran release workflow https://github.com/dashpay/platform/actions/runs/9967883200/job/27542324920
None

ci: fix release docker images

---

packages/rs-drive-abci/src/execution/check_tx/v0/mod.rs
packages/rs-drive-abci/src/execution/validation/state_transition/state_transitions/documents_batch/mod.rs
packages/rs-drive-abci/src/execution/validation/state_transition/state_transitions/identity_create/mod.rs
packages/rs-drive-abci/src/execution/validation/state_transition/state_transitions/identity_top_up/mod.rs
packages/rs-drive-abci/tests/strategy_tests/main.rs
packages/rs-drive/src/drive/contract/get_fetch/get_contract_with_fetch_info/mod.rs
packages/rs-drive/src/drive/document/delete/mod.rs
packages/rs-drive/src/drive/document/insert/mod.rs
packages/rs-drive/src/drive/identity/balance/update.rs
packages/rs-drive/src/drive/identity/update/mod.rs
packages/rs-platform-version/src/version/fee/hashing/v1.rs
packages/rs-platform-version/src/version/fee/signature/v1.rs
packages/rs-platform-version/src/version/fee/storage/v1.rs

@pauldelucia worked on finding slightly better fee costs. 
We updated some processing fees.
CI
This is a breaking change as fees have changed.

chore(platform)!: updated fees

---

packages/dashmate/configs/defaults/getBaseConfigFactory.js

Due to Tenderdash bug, some validators might not have connectivity to other validators, and not receive consensus messages (votes, etc.).
Update Tenderdash to 1.1.0-dev.2 which contains a fix.
Deployed on devnet and ensured that consensus works there.
None

build: update tenderdash to 1.1.0-dev.2

---

packages/dashmate/configs/defaults/getTestnetConfigFactory.js
packages/dashmate/configs/getConfigFileMigrationsFactory.js

We want other people to start own testnet nodes
- Updated testnet genesis config
None
None

chore(dashmate): update genesis config to the latest testnet

---

packages/js-dash-sdk/docs/platform/names/register.md
packages/js-dash-sdk/docs/platform/names/resolveByRecord.md
packages/js-dash-sdk/src/SDK/Client/Platform/methods/names/register.spec.ts
packages/js-dash-sdk/src/SDK/Client/Platform/methods/names/resolveByRecord.ts

More DPNS fixes for JS SDK
None

fix: more dpns related js sdk fixes

---

packages/rs-drive/src/error/document.rs
packages/rs-drive/src/error/identity.rs

two error messages had typos
fixed them
n/a

fix: two error messages had typos

---

packages/rs-drive-abci/src/execution/platform_events/block_fee_processing/add_process_epoch_change_operations/v0/mod.rs
packages/rs-drive-abci/src/execution/platform_events/fee_pool_inwards_distribution/add_distribute_block_fees_into_pools_operations/v0/mod.rs
packages/rs-drive-abci/src/execution/platform_events/fee_pool_outwards_distribution/add_distribute_fees_from_oldest_unpaid_epoch_pool_to_proposers_operations/v0/mod.rs
packages/rs-drive-abci/src/execution/platform_events/fee_pool_outwards_distribution/add_epoch_pool_to_proposers_payout_operations/v0/mod.rs
packages/rs-drive/src/drive/credit_pools/epochs/credit_distribution_pools/get_epoch_fee_multiplier/v0/mod.rs
packages/rs-drive/src/drive/credit_pools/epochs/operations_factory.rs
packages/rs-drive/src/drive/system/genesis_time/mod.rs

If an epoch was skipped we would not set the epoch protocol version for the first epoch after the skip.

fix: epoch protocol version setting

---

Cargo.lock
packages/rs-drive/Cargo.toml

Updated to GroveDB V1 which is production ready.

chore: update to GroveDB Version 1.0.0

---

Cargo.lock
packages/dapi-grpc/Cargo.toml
packages/dashmate/configs/defaults/getBaseConfigFactory.js
packages/rs-drive-abci/Cargo.toml
packages/rs-drive-proof-verifier/Cargo.toml

tenderdash 1.1.0 was released
Updated rs-tenderdash-abci and tenderdash image to 1.1.0
GHA
None

build: update tenderdash to 1.1.0

---

.yarnrc.yml

```
❯ yarn npm audit --environment production --all --recursive
├─ elliptic
│  ├─ ID: 1098397
│  ├─ Issue: Elliptic's ECDSA missing check for whether leading bit of r and s is zero
│  ├─ URL: https://github.com/advisories/GHSA-977x-g7h5-7qgw
│  ├─ Severity: low
│  ├─ Vulnerable Versions: >=2.0.0 <=6.5.6
│  │ 
│  ├─ Tree Versions
│  │  └─ 6.5.6
│  │ 
│  └─ Dependents
│     └─ @dashevo/dashcore-lib@npm:0.21.3
│
├─ elliptic
│  ├─ ID: 1098398
│  ├─ Issue: Elliptic's EDDSA missing signature length check
│  ├─ URL: https://github.com/advisories/GHSA-f7q4-pwc6-w24p
│  ├─ Severity: low
│  ├─ Vulnerable Versions: >=4.0.0 <=6.5.6
│  │ 
│  ├─ Tree Versions
│  │  └─ 6.5.6
│  │ 
│  └─ Dependents
│     └─ @dashevo/dashcore-lib@npm:0.21.3
│
└─ elliptic
├─ ID: 1098560
├─ Issue: Elliptic allows …
```

chore: ignore security vulnerability 1098397

---

packages/dashmate/configs/defaults/getBaseConfigFactory.js
packages/dashmate/configs/getConfigFileMigrationsFactory.js

Current consensus params aren't optimal for network near mainnet size. During testing on the taomeo devnet, we figure out "working" numbers.
- Updated consensus params.
None
Previously created networks won't be supported since this PR changes genesis configuration.

chore(dashmate)!: update consensus params

---

packages/dashmate/configs/defaults/getBaseConfigFactory.js
packages/dashmate/configs/getConfigFileMigrationsFactory.js
packages/dashmate/src/config/configJsonSchema.js
packages/dashmate/templates/platform/drive/tenderdash/config.toml.dot

We want to tune tenderdash connection settings
- Added `platform.drive.tenderdash.p2p.maxConnections` and `platform.drive.tenderdash.p2p.maxOutgoingConnections` options
- The max outgoing connections setting set to 30
None
None

feat(dashmate): configure tenderdash connections

---

packages/dashmate/src/listr/tasks/resetNodeTaskFactory.js

When the reset command is running with the platform flag it doesn't remove volumes. 
- Fixed the reset command
None

fix(dashmate): the reset platform command doesn't remove data

---

packages/dashmate/configs/defaults/getBaseConfigFactory.js
packages/dashmate/configs/getConfigFileMigrationsFactory.js

Tenderdash development version 1.2.0-dev.3 is specified in dashmate config
- Updated tenderdash to stable version v1.2.0
None
None

chore(dashmate): update tenderdash version to 1.2.0

---

packages/dashmate/configs/defaults/getBaseConfigFactory.js
packages/dashmate/configs/defaults/getTestnetConfigFactory.js
packages/dashmate/configs/getConfigFileMigrationsFactory.js

https://github.com/dashpay/platform/releases/tag/v1.1.0 contains breaking changes and testnet was wiped. This PR updates default testnet settings for a dashmate so user could connect to it
* Updated base tenderdash version to 1.2.0
* Updated chain id to testnet-51
Locally with dashmate by connecting to testnet
No

feat(dashmate): update testnet config

---

packages/dashmate/configs/defaults/getBaseConfigFactory.js
packages/dashmate/configs/defaults/getMainnetConfigFactory.js
packages/dashmate/configs/getConfigFileMigrationsFactory.js

We need to bump tenderdash version
- Specify only major tenderdash version so users can easily get updates
- Update network name
- Update migration
None
None

chore(dashmate): update tenderdash version

---

packages/rs-drive-abci/src/execution/platform_events/voting/check_for_ended_vote_polls/v0/mod.rs

fix(drive-abci): cleanup of later contests on testnet only

---

Cargo.lock
packages/rs-drive-abci/Cargo.toml
packages/rs-drive-abci/src/abci/handler/prepare_proposal.rs
packages/rs-drive-abci/src/abci/handler/process_proposal.rs
packages/rs-drive-abci/src/execution/engine/consensus_params_update/mod.rs
packages/rs-drive-abci/src/execution/engine/consensus_params_update/v0/mod.rs
packages/rs-drive-abci/src/execution/engine/mod.rs
packages/rs-drive-abci/src/platform_types/cleaned_abci_messages/request_init_chain_cleaned_params/v0/mod.rs
packages/rs-drive-abci/src/test/fixture/abci.rs
packages/rs-platform-version/src/version/consensus_versions.rs
packages/rs-platform-version/src/version/drive_abci_versions.rs
packages/rs-platform-version/src/version/mocks/v2_test.rs
packages/rs-platform-version/src/version/mocks/v3_test.rs
packages/rs-platform-version/src/version/mod.rs
packages/rs-platform-version/src/version/protocol_version.rs
packages/rs-platform-version/src/version/v2.rs
packages/rs-platform-version/src/version/v3.rs

We needed a new version to support Tenderdash new consensus rules.
Introduced a version 3 and supported Tenderdash upgrade.

feat(platform): support Tenderdash upgrade

---

packages/rs-drive-abci/src/execution/engine/consensus_params_update/v0/mod.rs

chore: change upgrade on testnet 1 epoch later

---

packages/dashmate/templates/core/dash.conf.dot

Invalid debug log path in dash.conf:
```
Tor control credentials not provided
Error: Could not open debug log file /var/log/dash/debug.log }}
```
- Fixed core file path in dash.conf
None

fix(dashmate): invalid debug core log path

---

packages/rs-drive-abci/src/execution/engine/consensus_params_update/v0/mod.rs

chore: change Upgrade 4 Epochs Later

---

packages/rs-drive-abci/src/config.rs
packages/rs-drive-abci/src/execution/engine/consensus_params_update/v0/mod.rs

chore: disable config from testnet propogates network test

---

packages/dashmate/src/update/updateNodeFactory.js

#2150 
- Set updated status is error if another wasn't parsed.
None

fix(dashmate): colors[updated] is not a function

---

packages/js-dash-sdk/src/SDK/Client/Client.spec.ts
packages/js-dash-sdk/src/SDK/Client/Client.ts

If network is not specified, by default JS SDK connects to testnet. Since Platform is already deployed to mainnet we should change this.
- Updated JS SDK to connect to mainnet by default.
None
Now if network is not specified, JS SDK will connect to mainnet.

feat(sdk)!: change default network to mainnet

---

packages/rs-drive-abci/src/execution/platform_events/protocol_upgrade/perform_events_on_first_block_of_protocol_change/v0/mod.rs
packages/rs-platform-version/src/version/v4.rs

We had put 4 instead of 0 for the version of the function, fixed this.

fix(drive-abci): fix network upgrade to version 4

---

packages/rs-drive-abci/src/execution/storage/fetch_platform_state/v0/mod.rs

We are getting deserialization error but to debug it when need to see actual bytes
- Added trace log with platform execution state bytes 
None
None

chore(drive): log invalid state on deserialisation

---

packages/rs-sdk/src/platform/document_query.rs

chore: add partial eq to document query 

---

packages/rs-sdk/src/lib.rs

Proof verifier errors were not exposed in sdk, here we expose them as public

chore(sdk): expose proof verifier errors

---

.yarnrc.yml

```
yarn npm audit -A -R --environment production
├─ abstract-leveldown
│  ├─ ID: abstract-leveldown (deprecation)
│  ├─ Issue: Superseded by abstract-level (https://github.com/Level/community#faq)
│  ├─ Severity: moderate
│  ├─ Vulnerable Versions: 6.2.3
│  │ 
│  ├─ Tree Versions
│  │  └─ 6.2.3
│  │ 
│  └─ Dependents
│     └─ memdown@npm:5.1.0
│
├─ deferred-leveldown
│  ├─ ID: deferred-leveldown (deprecation)
│  ├─ Issue: Superseded by abstract-level (https://github.com/Level/community#faq)
│  ├─ Severity: moderate
│  ├─ Vulnerable Versions: 5.3.0
│  │ 
│  ├─ Tree Versions
│  │  └─ 5.3.0
│  │ 
│  └─ Dependents
│     └─ levelup@npm:4.4.0
│
├─ levelup
│  ├─ ID: levelup (deprecation)
│  ├─ Issue: Superseded by abstract-level (https://github.com/Level/community#faq)
│  ├─ Severity: moderate …
```

chore: ignore leveldb deprecation warnings

---

packages/dashmate/templates/core/dash.conf.dot

Devnet with Core 22 doesn't have enough funds to register masternodes
- Set `highsubsidyfactor` to `100`
None
None

chore(dashmate): increase subsidy for devnet

---

Cargo.lock
packages/rs-dpp/Cargo.toml
packages/rs-drive-abci/Cargo.toml
packages/rs-sdk/Cargo.toml
packages/simple-signer/Cargo.toml

Update bls library to the recent version
- updated dashcore and dashcore-rpc to update blsful
None
None

chore: update bls library

---

packages/rs-dpp/src/state_transition/state_transitions/document/batch_transition/v1/v0_methods.rs

Drive ABCI is not compiling due to wrong feature flag instructions in DPP
- Remove unnecessary instructions to add missing imports
Compiling Drive ABCI and building Drive docker image
None

fix(dpp): invalid feature flag instructions

---

packages/rs-dpp/src/errors/consensus/state/token/unauthorized_token_action_error.rs

Action and Token ID needed to be switched
I switched them and put them inline as well for clarity.

fix: wrong order of parameters in UnauthorizedTokenActionError

---

packages/rs-dpp/src/state_transition/state_transitions/contract/data_contract_create_transition/mod.rs
packages/rs-drive-abci/src/execution/validation/state_transition/state_transitions/data_contract_create/mod.rs
packages/rs-platform-version/src/version/drive_abci_versions/drive_abci_validation_versions/v1.rs
packages/rs-platform-version/src/version/drive_abci_versions/drive_abci_validation_versions/v2.rs
packages/rs-platform-version/src/version/drive_abci_versions/drive_abci_validation_versions/v3.rs
packages/rs-platform-version/src/version/drive_abci_versions/drive_abci_validation_versions/v4.rs
packages/rs-platform-version/src/version/drive_abci_versions/drive_abci_validation_versions/v5.rs
packages/rs-platform-version/src/version/v9.rs

We had made a mistake and in the versioning system we had used basic structure version instead of advanced version. This was just an oversight, so we can swap the two and everything should continue to work well.
Tests should continue passing.
None

fix(drive-abci): data contract create transition advanced structure version

---

packages/dapi-grpc/build.rs

Added GetTokenPerpetualDistributionLastClaim to versioned requests

fix(dapi-grpc): add GetTokenPerpetualDistributionLastClaim to versioned requests

---

packages/rs-drive/src/drive/tokens/distribution/queries.rs

Just needed to set the limit to 1 to being to use the query to verify.

fix(drive): limit in perpetual_distribution_last_paid_moment_query

---

package.json

This PR addresses the need for a more descriptive package name for clarity and consistency within the project.
The package name "search-contract" was renamed to "token-search-contract" in the `package.json` file to better reflect its purpose and to align with the naming conventions of other packages.
The change was verified by running the project locally to ensure that the renaming does not affect the build or runtime behavior. No additional tests were necessary as this is a straightforward renaming.
None

refactor: rename search-contract to token-search-contract

---

.pnp.cjs
yarn.lock

This PR introduces the integration of the `@dashevo/keyword-search-contract` package into the project. This addition is aimed at enhancing the project's functionality with keyword search capabilities.
- Added `@dashevo/keyword-search-contract` to the `.pnp.cjs` and `yarn.lock` files.
- Specified dependencies for the `keyword-search-contract` package, including `@dashevo/wasm-dpp`, `chai`, `mocha`, and others for testing and linting purposes.
The integration has been verified by ensuring that the package dependencies are correctly listed and resolved in the project. Unit tests associated with the `keyword-search-contract` have been executed to confirm functionality.
None

chore: integrate keyword-search-contract into yarn lock
