packages/wallet-lib/docs/account/getTransactionHistory.md
packages/wallet-lib/src/types/Account/Account.d.ts
packages/wallet-lib/src/types/Account/methods/getTransactionHistory.js
packages/wallet-lib/src/types/types.d.ts

This PR improve the documentation for getTransactionHistory method.
- doc: update Account.ts JSDoc
- feat: remove async on getTransactionHistory
- doc: update docsify with getTransactionHistory

docs: provide getTransactionHistory

---

packages/wallet-lib/src/plugins/Workers/TransactionSyncStreamWorker/TransactionSyncStreamWorker.js
packages/wallet-lib/src/types/Wallet/Wallet.js

This change eliminates unnecessary synchronization of transactions in case wallet has been generated from the new mnemonic
Check if the wallet has been generated from the new mnemonic and sync transactions from the best block (instead of block 1 or the one provided via `unsafeOptions: { skipSynchronizationBeforeHeight: <n> }`)
- Passed no mnemonic to the Wallet initialization arguments
- Ensured quick initialization time
- Hooked on account events and ensured that synchronization of the new blocks works properly

feat(wallet-lib): do not sync transactions if mnemonic is absent

---

packages/wallet-lib/docs/_sidebar.md
packages/wallet-lib/docs/wallet/dumpStorage.md
packages/wallet-lib/src/types/Wallet/Wallet.d.ts
packages/wallet-lib/src/types/Wallet/Wallet.js
packages/wallet-lib/src/types/Wallet/methods/dumpStorage.js

The change allows wallet users to dump storage on demand for debugging purposes
Created a new function `dumpStorage` which returns storage JSON string and logs it to the console if not specified otherwise
Tested function during different phases of the wallet lifecycle (initialized/disconnected/crashed)

feat(wallet-lib): dump wallet storage

---

packages/dashmate/src/commands/group/reset.js
packages/dashmate/src/listr/tasks/setup/setupLocalPresetTaskFactory.js

Reset command doesn't work properly if setup command failed
- Store configs  and default config on very end of setup
- Remove generated configs on hard reset
Running manually
None

fix(dashmate): reset command doesn't work if setup failed

---

.github/workflows/all-packages.yml
packages/dapi/lib/externalApis/drive/DriveClient.js
packages/dapi/lib/externalApis/drive/fetchProofForStateTransitionFactory.js
packages/dapi/lib/grpcServer/handlers/platform/getDataContractHandlerFactory.js
packages/dapi/lib/grpcServer/handlers/platform/getDocumentsHandlerFactory.js
packages/dapi/lib/grpcServer/handlers/platform/getIdentitiesByPublicKeyHashesHandlerFactory.js
packages/dapi/lib/grpcServer/handlers/platform/getIdentityHandlerFactory.js
packages/dapi/lib/grpcServer/handlers/platform/getIdentityIdsByPublicKeyHashesHandlerFactory.js
packages/dapi/test/integration/grpcServer/handlers/platform/waitForStateTransitionResultHandlerFactory.js
packages/dapi/test/unit/grpcServer/handlers/platform/getDataContractHandlerFactory.js
packages/dapi/test/unit/grpcServer/handlers/platform/getDocumentsHandlerFactory.js
packages/dapi/test/unit/grpcServer/handlers/platform/getIdentitiesByPublicKeyHashesHandlerFactory.js
packages/dapi/test/unit/grpcServer/handlers/platform/getIdentityHandlerFactory.js
packages/dapi/test/unit/grpcServer/handlers/platform/getIdentityIdsByPublicKeyHashesHandlerFactory.js

CBOR v.4 used to convert Uint8Array values to Buffer on encoding. Since we migrated to CBOR v.8, which doesnt convert them anymore, we need to convert them manually.
Convert Uint8Array to Buffer
With platform test suite
No

fix(dapi): Identifier expects Buffer

---

package.json
packages/dashmate/src/commands/group/reset.js
packages/dashmate/src/listr/tasks/resetNodeTaskFactory.js

When a node is running but some of the containers are stuck or restarting, there is not way to reset.
- Introduce `force` option to `group:reset` command to skip the "service running" check
- Added the `force` flag to `npm run reset`
Manually
None

feat(dashmate): force option for `group:stop` command

---

packages/js-dapi-client/lib/transport/JsonRpcTransport/createJsonTransportError.js
packages/js-dapi-client/lib/transport/JsonRpcTransport/errors/WrongHttpCodeError.js
packages/js-dapi-client/lib/transport/JsonRpcTransport/requestJsonRpc.js
packages/js-dapi-client/test/unit/transport/JsonRpcTransport/requestJsonRpc.spec.js

Dapi-client doesn't retry on 502 errors
Fixed JsonTransport in Dapi-client
Platform test suite
No

fix(dapi-client): retry doesn’t work with 502 errors

---

packages/dashmate/configs/system/mainnet.js
packages/dashmate/src/commands/group/reset.js
packages/dashmate/src/config/Config.js

`Cannot read properties of undefined (reading 'dpns')` error is thrown on `group:reset` command
- Avoid modification of CommonJS module exported object
- Clone value on `Config#set` to avoid future problems
- Use `systemConfigs` from DI container
Running command
None

fix(dashmate): `cannot read properties` error on `group:reset`

---

.github/workflows/release.yml

NPM publish doesn't work in release workflow due to lack of auth information.
- Pass `NODE_AUTH_TOKEN` env to `npm publish` command
None
None

ci: enable NPM login on for release workflow

---

packages/js-dash-sdk/package.json
packages/js-dash-sdk/src/test/mocks/createAndAttachTransportMocksToClient.ts
packages/wallet-lib/src/types/Account/Account.js
packages/wallet-lib/src/types/Account/methods/broadcastTransaction.js
packages/wallet-lib/src/types/Account/methods/getUnusedAddress.js
packages/wallet-lib/src/types/Account/methods/getUnusedAddress.spec.js
packages/wallet-lib/src/types/Storage/methods/importTransaction.js
packages/wallet-lib/tests/functional/wallet.js

The feature allows calling `broadcastTransaction` function in sequence one after another without the risk of hitting mempool conflict error or reusing the same output in case there's only one UTXO
In case of multiple invocations of `broadcastTransaction` call, the library puts a subsequent call to DAPI on hold until the previous TX acquires the instant lock.
- Wrote a relevant functional test
- Tested manually with 1 or multiple UTXOs

fix(wallet-lib): tx chaining mempool conflict errors 

---

packages/js-dash-sdk/package.json
packages/wallet-lib/src/plugins/Workers/TransactionSyncStreamWorker/methods/handleTransactionFromStream.js
packages/wallet-lib/src/transport/AbstractTransport.js
packages/wallet-lib/src/types/Account/Account.js

The wallet was hooking on lots of redundant event listeners during the processing raw transactions from the stream.
Remove event listeners right after they'd became not needed
- Manually broadcast 10 transactions one by one to ensure that the warning does not appear anymore
- Ensure that the warning is not present in the logs of the test suites

fix(wallet-lib): eventemitter memory leak

---

packages/wallet-lib/src/test/mocks/TransportMock.js
packages/wallet-lib/src/types/Storage/methods/rehydrateState.js
packages/wallet-lib/src/types/Storage/methods/rehydrateState.spec.js

The fix ensures proper data types casting for serialized items in the persistent storage at the moment of wallet initialization:
- Read data from persistent storage
- Deserialize to JSON objects
- Cast certain objects to correct data types (Transaction, BlockHeader, InstantLock, Output, UnspentOutput)
Described storage types schema and wrote a function to validate storage against the schema and cast to correct types
- Created relevant unit test
- Tested manually by starting wallet from persistent storage and broadcasting a transaction

fix(wallet-lib): invalid deserialization of persistent storage

---

CHANGELOG.md
package.json
packages/dapi-grpc/package.json
packages/dapi/package.json
packages/dashmate/package.json
packages/dashpay-contract/package.json
packages/dpns-contract/package.json
packages/feature-flags-contract/package.json
packages/js-dapi-client/package.json
packages/js-dash-sdk/package.json
packages/js-dpp/package.json
packages/js-drive/package.json
packages/js-grpc-common/package.json
packages/platform-test-suite/package.json
packages/wallet-lib/package.json

chore(release): update changelog and bump version to 0.21.6

---

package.json

`Error: Unexpected argument: -w` on `yarn restart`. `dashmate group:restart` doesn't accept `-w` flag
- Remove undefined flag
Running this command manually
None

chore: undefined "-w" argument in restart script

---

CHANGELOG.md
package.json
packages/dapi-grpc/package.json
packages/dapi/package.json
packages/dashmate/package.json
packages/dashpay-contract/package.json
packages/dpns-contract/package.json
packages/feature-flags-contract/package.json
packages/js-dapi-client/package.json
packages/js-dash-sdk/package.json
packages/js-dpp/package.json
packages/js-drive/package.json
packages/js-grpc-common/package.json
packages/platform-test-suite/package.json
packages/wallet-lib/package.json

chore(release): update changelog and bump version to 0.22.0-dev.1

---

packages/js-dpp/lib/identity/IdentityPublicKey.js
packages/js-dpp/lib/stateTransition/AbstractStateTransition.js
packages/js-dpp/lib/stateTransition/AbstractStateTransitionIdentitySigned.js
packages/js-dpp/lib/stateTransition/validation/validateStateTransitionIdentitySignatureFactory.js
packages/js-dpp/schema/identity/publicKey.json
packages/js-dpp/test/integration/stateTransition/AbstractStateTransitionIdentitySigned.spec.js
packages/js-dpp/test/unit/identity/IdentityPublicKey.spec.js
packages/js-dpp/test/unit/stateTransition/validation/validateStateTransitionIdentitySignatureFactory.spec.js

In order to support masternode owner key which hash160 of ECDSA we need to introduce a new identity public key type 2 and support it for singing and verification of State Transitions
Added new key type 2.
With tests
No

feat(dpp): implement hashed ECDSA key type

---

.github/workflows/release.yml

#149  and #150 didn't help. We can try to pass token as env variable
- Set NODE_AUTH_TOKEN env to `npm publish`  command
None
None

ci: pass NPM token to `npm publish` command

---

packages/dapi-grpc/README.md
packages/dapi/README.md
packages/dashmate/README.md
packages/dashpay-contract/README.md
packages/dpns-contract/README.md
packages/feature-flags-contract/README.md
packages/js-dapi-client/README.md
packages/js-dash-sdk/README.md
packages/js-dash-sdk/docs/examples/sign-and-verify-messages.md
packages/js-dash-sdk/docs/wallet/about-wallet-lib.md
packages/js-dpp/README.md
packages/js-drive/README.md
packages/platform-test-suite/README.md
packages/wallet-lib/README.md
packages/wallet-lib/docs/account/createTransaction.md
packages/wallet-lib/docs/plugins/writing-a-new-plugin.md
packages/wallet-lib/docs/usage/coinSelection.md
packages/wallet-lib/docs/usage/dapi.md
packages/wallet-lib/docs/usage/examples.md

Links to open issues were still pointing to the old repositories so someone opening a new issue via the Readme would have opened it in the wrong location. There were also some other obvious link issues noticed while making those changes.
Fixed the Readme links to open issues in this repository instead of the old ones. Also fixed a few other broken links I noticed.

docs: minor Readme fixes

---

packages/dashmate/configs/system/base.js

Most recent dash core release (dashd:0.18.0.0-beta1 at the time) comes without arm64 support. This lead to segfault crashes on Apple Silicon devices. Solution is to downgrade to v0.17 until arm64 dash core images is provided.
Set up dashd v0.17 in the dashmate. After this fix you can successfully run `yarn setup` on Apple Silicon devices 
Tested locally on my laptop.

fix: downgrade dash-core image to v0.17

---

packages/wallet-lib/docs/storage/Storage.md

Table formatting was off. Now it's fixed. Should be obvious.

docs: escape literal '|' in table

---

packages/js-dpp/lib/dataContract/getPropertyDefinitionByPath.js
packages/js-dpp/lib/dataContract/validation/validateDataContractFactory.js
packages/js-dpp/lib/errors/consensus/basic/dataContract/SystemPropertyIndexAlreadyPresentError.js
packages/js-dpp/lib/test/fixtures/getDataContractFixture.js
packages/js-dpp/test/integration/dataContract/validation/validateDataContractFactory.spec.js

There is no practical benefits of using `$id` property as a part of secondary indices so we should do not allow do that and optimize GroveDB internal structure
- Do not allow to use `$id` as a secondary indices.
With integration test
`$id` can't be used in secondary indices

feat(dpp)!: `$id` can't be used in secondary indices

---

scripts/configure_test_suite.sh

`yarn configure:test` throws "Internal error. Some of the env variables are empty. Please check logs above."
With grep 2.5.1, command `grep -A 2 -m 1  "Create a new owner addresses" ./logs/setup.log` returns 
```
[STARTED] Create a new owner addresses
```
instead of
```
[STARTED] Create a new owner addresses
[DATA] Address: "..."
[DATA] Private key: "..."
```
Changed `-m` flag's value to 2
`yarn configure:test`

build: fix configure test suite script for grep 2.5.1

---

packages/js-drive/lib/document/query/validateQueryFactory.js
packages/js-drive/test/unit/document/query/validateQueryFactory.spec.js

Allowing using `orderBy` for properties that have `in` and `startsWith` in their `where` clause. Since they are range queries as well.
- updated `validateQuery` function
Unit tests
None

fix(drive): `orderBy` for `where` clauses with `in` and `startsWith`

---

packages/wallet-lib/src/types/WalletStore/WalletStore.js
packages/wallet-lib/src/types/WalletStore/WalletStore.spec.js
packages/wallet-lib/src/types/WalletStore/methods/createPathState.js
packages/wallet-lib/src/types/WalletStore/methods/exportState.js
packages/wallet-lib/src/types/WalletStore/methods/getIdentityIdByIndex.js
packages/wallet-lib/src/types/WalletStore/methods/getIndexedIdentityIds.js
packages/wallet-lib/src/types/WalletStore/methods/getPathState.js
packages/wallet-lib/src/types/WalletStore/methods/importState.js
packages/wallet-lib/src/types/WalletStore/methods/insertIdentityIdAtIndex.js

In https://github.com/dashevo/wallet-lib/pull/351, we introduced multiple features that couldn't be managed as is due to its size. 
This PR is the least minimal of them concerning WalletStore (excluding the connection to Wallet-lib) itself.
- feat: introduced WalletStore

feat(wallet-lib): added WalletStore

---

scripts/prepare_docs.sh

This is an alternative to #189. 
There's a section on the docs site for walkthroughs (e.g. https://dashevo.github.io/platform/SDK/walkthroughs/automatically-consolidate-UTXO/automatically-consolidate-UTXO/), but they're empty files - confusing, not helpful.
Updated the doc build prep script so it ignores the folder containing the empty docs. This way the files remain in the repo as placeholders but don't appear on the built documentation.
Tested locally
N/A

docs: ignore folder with empty docs during build

---

packages/js-dpp/lib/dataContract/validation/validateDataContractFactory.js
packages/js-dpp/lib/test/fixtures/getDataContractFixture.js
packages/js-dpp/test/integration/dataContract/validation/validateDataContractFactory.spec.js

In order to be consistent with current rs-drive implementation we need to forbid using indexes for array properties
Removed array index support from validateDataContract
With tests
Array properties cannot be indexed anymore

feat(dpp)!: do not allow to index array properties

---

packages/js-dash-sdk/src/SDK/Client/Platform/methods/documents/get.spec.ts
packages/js-dash-sdk/src/SDK/Client/Platform/methods/documents/get.ts
packages/js-drive/lib/document/query/jsonSchema.js
packages/js-drive/test/unit/document/query/validateQueryFactory.spec.js

Allowing to use `Document` and `Identifier` in document queries as a `startAt` and `startAfter` parameter. This is done to make queries easier to work with.
- updated `get` method in `SDK`
- updated query validation in `Drive`
Unit tests.
None.

feat: allow using Document and Identifier for `startAt` and `startAfter` in document query

---

packages/dashmate/configs/migrations.js
packages/dashmate/configs/schema/configJsonSchema.js
packages/dashmate/configs/system/base.js
packages/dashmate/configs/system/local.js
packages/dashmate/configs/system/mainnet.js
packages/dashmate/configs/system/testnet.js
packages/dashmate/docker-compose.yml
packages/dashmate/src/commands/setup.js
packages/dashmate/src/listr/tasks/setup/setupLocalPresetTaskFactory.js

Under linux running a VPN service network could not be created due to IPv4 address conflicts. This PR aims to add an ability to specify subnet mask for a default Docker network for each node.
- updated `docker-compose.yml` to use env variable for default network subnet
- updated config templates
Local setup
None

feat(dashmate): add an ability to configure node subnet mask

---

packages/js-dpp/lib/identity/IdentityFactory.js
packages/js-dpp/lib/test/fixtures/getIdentityFixture.js

Upon creation of `Identity` it's public keys `readOnly` flags was set to `undefined` instead of `false`
- updated `IdentityFactory`
- updated fixtures
Unit tests
None

fix(dpp): Identity public key `readOnly` is `undefined`

---

packages/dapi/lib/grpcServer/handlers/platform/getDocumentsHandlerFactory.js
packages/dapi/test/unit/grpcServer/handlers/platform/getDocumentsHandlerFactory.js
packages/js-drive/lib/abci/handlers/query/documentQueryHandlerFactory.js

Getting validation error if `startAt` or `startAfter` encoded as a byte array
```
{"errors": [{"name": "JsonSchemaValidationError", "instancePath": "/startAfter", "schemaPath": "#/properties/startAfter/instanceof", "keyword": "instanceof", "params": {}}]}
```
- Convert Uint8Array to Buffer
With tests
None

fix: `startAt` and `startAfter` invalid decoding

---

.pnp.cjs
packages/dashmate/package.json
packages/dashmate/src/templates/writeServiceConfigsFactory.js
yarn.lock

`rimraf` module could not remove non-empty directory during `start`, leading to:
`Error: ENOTEMPTY: directory not empty, rmdir '<userdir>/.dashmate/local_1/logs'
Code: ENOTEMPTY`
Partially fixes [this issue](https://github.com/dashevo/platform/issues/90)
- used `fs.rmSync` instead
local setup
None

fix(dashmate): `rimraf` module could not remove config directory

---

packages/dpns-contract/schema/dpns-contract-documents.json
packages/js-dpp/lib/dataContract/validation/validateDataContractFactory.js
packages/js-dpp/lib/test/fixtures/getDataContractFixture.js
packages/js-dpp/test/integration/dataContract/validation/validateDataContractFactory.spec.js
packages/platform-test-suite/test/functional/platform/DataContract.spec.js

Temporarily lowering constraints of indexed string properties due to the way how grovedb works internally.
- lowered constraints to `64` characters or `256` bytes
- unit tests
- old contract schemas that have indexed string properties of longer length are no longer valid
- DPNS now supports only cut versions of domain names due to lower constraints

feat(dpp)!: lower indexed string properties constraints

---

.pnp.cjs
packages/js-drive/package.json
yarn.lock

If one of the values in `in` clause not found, the query returns empty result.
Fix is done in https://github.com/dashevo/grovedb/pull/80 and https://github.com/dashevo/rs-drive/pull/81
- Updated RS Drive
None
Previous data might be incompatible due to different ST validation results (block results).

fix!: `in` query operator doesn't work with multiple values

---

packages/js-drive/lib/abci/handlers/beginBlockHandlerFactory.js
packages/js-drive/lib/abci/handlers/commitHandlerFactory.js
packages/js-drive/lib/abci/handlers/deliverTxHandlerFactory.js
packages/js-drive/lib/createDIContainer.js
packages/js-drive/lib/util/ExecutionTimer.js
packages/js-drive/test/integration/util/ExecutionTimer.spec.js
packages/js-drive/test/unit/abci/handlers/beginBlockHandlerFactory.spec.js
packages/js-drive/test/unit/abci/handlers/commitHandlerFactory.spec.js
packages/js-drive/test/unit/abci/handlers/deliverTxHandlerFactory.spec.js

Added timers for various block execution points, so we later can track bottlenecks in it.
- implemented basic execution timer using `process.hrtime`
- updated `beginBlock`, `deliverTx`, and `commit` handlers
- Integration tests
- local run
None.

feat(drive): add performance timers to measure block execution

---

packages/js-dpp/lib/test/fixtures/getDataContractFixture.js
packages/js-dpp/schema/dataContract/dataContractMeta.json
packages/js-dpp/test/integration/dataContract/validation/validateDataContractFactory.spec.js
packages/js-dpp/test/unit/dataContract/DataContractFactory.spec.js
packages/js-drive/test/unit/blockExecution/BlockExecutionContext.spec.js

As `GroveDB` not supporting $refs at the moment, they are disabled in `dpp` for now.
- removed `$ref` definition in data contract meta schema
Units and integration tests.
- `$ref` in data contract definitions are not supported for now

feat(dpp): temporarily disable $refs in data contract definitions

---

packages/js-dpp/lib/identity/IdentityPublicKey.js
packages/js-dpp/schema/identity/publicKey.json

Need to implement withdrawal purpose for identity pub key
Added new Purpose - withdraw
With tests
No

feat(dpp): add `withdraw` purpose for `IdentityPublicKey`

---

packages/platform-test-suite/karma.conf.js
packages/platform-test-suite/test/e2e/wallet.spec.js
packages/platform-test-suite/test/functional/dapi/subscribeToBlockHeadersWithChainLocksHandlerFactory.spec.js
packages/wallet-lib/src/types/Account/Account.js
packages/wallet-lib/src/types/Account/methods/broadcastTransaction.js
packages/wallet-lib/src/types/Wallet/Wallet.js

A set of fixes and optimizations facilitating platform-test-suite execution on testnet
- [Bugfix] Reworks transactions queue broadcasting. Instead of the instant lock, wallet relies on transaction info coming from the node  (Fix for `Mocha timeout of 650000ms exceeded.`)
_This fix allows subsequent broadcastTransaction calls to pass once wallet received the information about previously sent TX_
- [Bugfix] Implements retryable stream for `packages/platform-test-suite/test/functional/dapi/subscribeToBlockHeadersWithChainLocksHandlerFactory.spec.js` 
_This fix does not let test suite fail in case stream have been closed by the backend_
- [Bugfix] Increases TX metadata waiting interval from 180 to 360 seconds. Metadata needs more time to be delivered on a large-scale network. 
(`Metadata …

test: fixes of sdk and platform test suite

---

packages/js-drive/lib/abci/handlers/beginBlockHandlerFactory.js
packages/js-drive/lib/abci/handlers/commitHandlerFactory.js
packages/js-drive/lib/abci/handlers/deliverTxHandlerFactory.js
packages/js-drive/lib/abci/handlers/stateTransition/unserializeStateTransitionFactory.js
packages/js-drive/lib/abci/handlers/timers.js
packages/js-drive/lib/util/ExecutionTimer.js
packages/js-drive/test/unit/abci/handlers/beginBlockHandlerFactory.spec.js
packages/js-drive/test/unit/abci/handlers/commitHandlerFactory.spec.js
packages/js-drive/test/unit/abci/handlers/deliverTxHandlerFactory.spec.js
packages/js-drive/test/unit/util/ExecutionTimer.spec.js

We need a more precise picture of block execution performance to make the right decision on which operations we need to take into account for fee calculation.
- Add timers for all validation steps during `deliverTx`
- Unit tests
- Running test suite locally
None

chore(drive): add more block execution timers

---

packages/js-dash-sdk/src/SDK/Client/Platform/methods/identities/register.ts

When an identity is registered, the returned instance does not have any network information such as balance and metadata. 
This PR will fetch after a registration the identity by its ID from the network in order to extend such information to the returned object by updating the balance value and adding the metadata property.
- feat: correctly setBalance and setMetadata of newly registered identity.
- Relying on test-suite
N/A

feat: adds balance and metadata information from registered identity

---

packages/dashmate/templates/platform/drive/tenderdash/config.toml.dot

Tenderdash 0.8.0-dev.2 will remove `is-validator` setting in favor of `mode`. 
This PR does respective changes to `dashmate`.
Changed `is-masternode` to `mode` in tenderdash config template.
Started TD+Drive locally with `dashmate`.
None
Note: it requires https://github.com/dashevo/tenderdash/pull/353 

chore(dashmate): tenderdash requires 'mode' setting

---

packages/dapi/lib/externalApis/tenderdash/waitForTransactionToBeProvable/getExistingTransactionResult.js

Tenderdash 0.8 requires transaction hash to be provided as a hex string.
Platform sends it as a base64.
Send transaction hash as hex string.
```bash
yarn test:suite
```
none

fix(dapi): send tx id to tenderdash as hex, not base64

---

.github/workflows/release.yml

In order to run test suite against both testnet and devnets in CI from a single repo, it is necessary to use a matrix strategy to select a test suite image version to match the version running on the networks. To avoid hard coding the version for devnets, we need to add `latest-dev` to the list of Docker tags generated by the metadata action.
- Bump metadata action version
- Always emit `latest` tag and apply suffix
Tested in Github Actions from `strophy/platform` repo. Example outputs:
Input: `v0.23.0-dev.6`
```
dashpay/platform-test-suite:0-dev
dashpay/platform-test-suite:0.23-dev
dashpay/platform-test-suite:0.23.0-dev
dashpay/platform-test-suite:0.23.0-dev.6
dashpay/platform-test-suite:latest-dev
```
Input: `v0.23.1`
```
dashpay/platform-test-suite:0
dashpay/platform-test-suite:0.23 …
```

ci: add `latest-dev` docker tag

---

packages/wallet-lib/docs/account/broadcastTransaction.md
packages/wallet-lib/src/errors/MempoolPropagationTimeoutError.js
packages/wallet-lib/src/test/bootstrap.js
packages/wallet-lib/src/test/karma/bootstrap.js
packages/wallet-lib/src/types/Account/methods/broadcastTransaction.js
packages/wallet-lib/src/types/Account/methods/broadcastTransaction.spec.js

The change improves reliability of the transaction chaining mechanism and eliminates divergence between `account.getTotalBalance()` and balance impact derived from transaction history
```
const wallet = new Wallet(...);
const account = await wallet.getAccount();
const txAmount = 5;
for (let i = 0; i < txAmount; i++) {
const tx = account.createTransaction({
recipient: '...'
satoshis: 1000,
});
await account.broadcastTransaction(tx);
const transactionHistory = await account.getTransactionHistory();
const balanceImpact = transactionHistory
.reduce((acc, item) => acc + item.satoshisBalanceImpact - item.feeImpact, 0);
const balance = account.getTotalBalance();
console.log(balance, balanceImpact); // equal
}
```
Rework `broadcastTransaction.js`:
- wait for transaction data response from mempool …

fix(wallet-lib): hook tx chain broadcast on mempool response

---

packages/js-drive/lib/abci/handlers/query/verifyChainLockQueryHandlerFactory.js
packages/js-drive/lib/core/waitForCoreChainLockSyncFactory.js
packages/js-drive/test/unit/abci/handlers/query/verifyChainLockQueryHandlerFactory.spec.js

`verifyChainLock` was returning `false` instead of `ResponseQuery` in case of Core not verifying `ChainLock`
- updated `verifyChainLock`
- added more debug and trace logs
`devnet-mekhong`
None

fix: `verifyChainLock` was returning `false` instead of `ResponseQuery`

---

.github/workflows/release.yml

Docker images built with the new workflow dispatch automation were incorrectly tagged with a `v` prefix
- Specify regex capturing group when parsing tag value
Works with other tags ;)
None

ci(fix): docker images incorrectly tagged with v

---

packages/js-dpp/lib/StateRepositoryInterface.js
packages/js-dpp/lib/document/stateTransition/DocumentsBatchTransition/applyDocumentsBatchTransitionFactory.js
packages/js-dpp/test/unit/document/stateTransition/DocumetsBatchTransition/applyDocumentsBatchTransitionFactory.spec.js
packages/js-drive/lib/abci/handlers/commitHandlerFactory.js
packages/js-drive/lib/createDIContainer.js
packages/js-drive/lib/dataContract/DataContractCacheItem.js
packages/js-drive/lib/document/fetchDocumentsFactory.js
packages/js-drive/lib/dpp/CachedStateRepositoryDecorator.js
packages/js-drive/lib/dpp/DriveStateRepository.js
packages/js-drive/lib/dpp/LoggedStateRepositoryDecorator.js
packages/js-drive/lib/state/registerSystemDataContractFactory.js
packages/js-drive/test/integration/fee/feesPrediction.spec.js
packages/js-drive/test/unit/dpp/CachedStateRepositoryDecorator.spec.js
packages/js-drive/test/unit/dpp/DriveStateRepository.spec.js
packages/js-drive/test/unit/dpp/LoggedStateRepositoryDecorator.spec.js

Drive calculates different fees for a state transition depending on the data contract cache state. If a data contract is cached, then the read operation will be skipped. Since the data contract cache is not deterministic this could lead to a chain halt.
- Calculate fees for a data contract read even if the contract is already cached.
- `StateRepository#removeDocument` now accepts Data Contract to remove additional read operation.
With tests
None

fix: non-deterministic fees due to data contract cache

---

packages/js-dpp/schema/dataContract/dataContractMeta.json
packages/js-dpp/test/integration/dataContract/validation/validateDataContractFactory.spec.js

The old restrictions were dictated by mongoDB. Since we don't use it anymore - the limits have been updated. So we need to allow 1 char document type and 1 char property name. 
DataContract schema has been changed 
With tests
Previous invalid data contracts in blockchain might be valid now

feat(dpp)!: allow 1 char document type and 1 char property name

---

.pnp.cjs
packages/js-drive/lib/blockExecution/BlockExecutionContext.js
packages/js-drive/lib/document/DocumentRepository.js
packages/js-drive/lib/test/fixtures/getBlockExecutionContextObjectFixture.js
packages/js-drive/package.json
packages/js-drive/test/unit/abci/handlers/commitHandlerFactory.spec.js
packages/js-drive/test/unit/blockExecution/BlockExecutionContext.spec.js
yarn.lock

Cumulative fees for block should be reset on the next begin block but it's not.
- Reset storage and processing cumulative fees in block execution context
Unit tests
Correct cumulative fees invalidate previous blockchain data

fix(drive)!: cumulative fees are not reset between blocks

---

packages/dashmate/configs/system/base.js
packages/js-dpp/lib/errors/consensus/codes.js
packages/js-dpp/lib/errors/consensus/state/identity/IdentityPublicKeyIsDisabledError.js
packages/js-dpp/lib/identity/IdentityPublicKey.js
packages/js-dpp/lib/identity/stateTransition/IdentityUpdateTransition/validation/state/validateIdentityUpdateTransitionStateFactory.js
packages/js-dpp/test/integration/identity/stateTransition/IdentityUpdateTransition/validation/state/validateIdentityUpdateTransitionStateFactory.spec.js

It is possible to disable the already disabled identity public key and update `disabledAt` timestamp.
- Return `IdentityPublicKeyIsDisabledError` if identity key is already disabled
WIth tests
None

fix(dpp): repeated disabling of already disabled identity key

---

packages/js-dapi-client/lib/transport/JsonRpcTransport/JsonRpcTransport.js

DAPI client marks node as banned in case of invalid arguments for JSON RPC requests
- Mark as banned only on retriable error
With tests
No

fix(dapi-client): node marked as banned on retriable JSON RPC error

---

packages/dapi/Dockerfile
packages/js-drive/Dockerfile
packages/platform-test-suite/Dockerfile

Node image was updated recently https://github.com/nodejs/docker-node/commit/9e9c0ecbd938e672add198b3cbbb2ab7704f6970 that was built with updated alpine image https://github.com/alpinelinux/docker-alpine/commit/adebcfd075c83ef788b5f071678dcfb8ea118bb3
It seems alpine 3.16.2 did something bad with dependencies so NPM package builds doesn't work anymore
- Downgrade base image to `node:16.16-alpine` 
Locally
None

build: new node alpine image breaks package builds

---

packages/js-dapi-client/lib/transport/GrpcTransport/createGrpcTransportError.js

Floating error in test suite running in a browser
```
TypeError: A.metadata.get is not a function
[146](https://github.com/dashevo/platform/runs/7894472793?check_suite_focus=true#step:15:147)
at A.exports [as createGrpcTransportError] (/tmp/_karma_webpack_750351/commons.js:147688:2164070)
[147](https://github.com/dashevo/platform/runs/7894472793?check_suite_focus=true#step:15:148)
at GrpcTransport.request (/tmp/_karma_webpack_750351/commons.js:147688:2162587)
[148](https://github.com/dashevo/platform/runs/7894472793?check_suite_focus=true#step:15:149)
at async PlatformMethodsFacade.getConsensusParams (/tmp/_karma_webpack_750351/commons.js:147688:2152071)
[149](https://github.com/dashevo/platform/runs/7894472793?check_suite_focus=true#step:15:150)
at async Context.<anonymous> …
```

fix(dapi-client): A.metadata.get is not a function

---

packages/dapi/lib/config/index.js
packages/dapi/lib/grpcServer/handlers/core/getStatusHandlerFactory.js

```
TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined
at new NodeError (node:internal/errors:372:5)
at Function.from (node:buffer:323:9)
at getStatusHandler (/platform/packages/dapi/lib/grpcServer/handlers/core/getStatusHandlerFactory.js:56:36)
at runMicrotasks (<anonymous>)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
at async rpcMethodErrorHandler (/platform/packages/js-grpc-common/lib/server/error/wrapInErrorHandlerFactory.js:25:24) {
code: 'ERR_INVALID_ARG_TYPE'
}
```
In case a masternode is banned
- Do not respond with proTxHash if masternode is banned
- Propoerly parse livenet config option
None
None
**For repository code-owners and …

fix(dapi): getStatus errored if masternode is banned

---

packages/platform-test-suite/lib/waitForSTPropagated.js
packages/platform-test-suite/test/e2e/contacts.spec.js
packages/platform-test-suite/test/e2e/dpns.spec.js
packages/platform-test-suite/test/e2e/masternodeRewardShares.spec.js
packages/platform-test-suite/test/functional/platform/DataContract.spec.js
packages/platform-test-suite/test/functional/platform/Document.spec.js
packages/platform-test-suite/test/functional/platform/Identity.spec.js

Tests are failing in different places due to replication latency. Nodes have different chain tips and if one node responds with state transition results it doesn't mean that other nodes have already replicated and executed the corresponding block.
- Enabled wait logic for all networks, not just testnet. Make this interval configurable
- Replaced `toJSON` with `toObject`
Running tests
None

fix(test-suite): failing tests due to replication latency

---

packages/dapi/lib/errors/TransactionWaitPeriodExceededError.js
packages/dapi/lib/externalApis/tenderdash/waitForTransactionToBeProvable/waitForTransactionToBeProvableFactory.js
packages/dapi/lib/grpcServer/handlers/platform/platformHandlersFactory.js
packages/dapi/test/integration/grpcServer/handlers/platform/waitForStateTransitionResultHandlerFactory.js
packages/dapi/test/unit/externalApis/tenderdash/waitForTransactionToBeProvable/waitForTransactionToBeProvableFactory.spec.js
packages/js-drive/lib/abci/handlers/deliverTxHandlerFactory.js
packages/js-drive/lib/abci/handlers/query/dataContractQueryHandlerFactory.js
packages/js-drive/lib/abci/handlers/query/documentQueryHandlerFactory.js
packages/js-drive/lib/abci/handlers/query/getProofsQueryHandlerFactory.js
packages/js-drive/lib/abci/handlers/query/identitiesByPublicKeyHashesQueryHandlerFactory.js
packages/js-drive/lib/abci/handlers/query/identityQueryHandlerFactory.js
packages/js-drive/lib/abci/handlers/query/response/createQueryResponseFactory.js
packages/js-drive/test/unit/abci/handlers/query/dataContractQueryHandlerFactory.spec.js
packages/js-drive/test/unit/abci/handlers/query/documentQueryHandlerFactory.spec.js
packages/js-drive/test/unit/abci/handlers/query/getProofsQueryHandlerFactory.spec.js
packages/js-drive/test/unit/abci/handlers/query/identitiesByPublicKeyHashesQueryHandlerFactory.spec.js
packages/js-drive/test/unit/abci/handlers/query/identityQueryHandlerFactory.spec.js
packages/js-drive/test/unit/abci/handlers/query/response/createQueryResponseFactory.spec.js

After #484, `waitForStateTransitionResult` do not need to wait for next block to obtain block signature anymore. Also, Drive should respond with current block data.
- Remove the waiting for next block logic
- Updated Drive's endpoint to respond with current block data
Tests
None

fix: Drive and DAPI expect data available on H+1 block

---

packages/dapi/test/integration/grpcServer/handlers/blockheaders-stream/subscribeToNewBlockHeaders.spec.js

subscribeToNewBlockHeaders test is broken
Fixed broken test
With tests
No

test(dapi): fix froken subscribeToNewBlockHeaders test

---

packages/dashmate/configs/system/mainnet.js

Last release misses upgrading mainnet nodes. It works for local, but users cannot use run mainnet nodes, because it loads latest sentinel but with the v17 dashcore node.
Upgrade dashd version for mainnet
Issue originally discovered by community member dashfriend, fixed and tested on my laptop (m1)
Nope

feat(dashmate): update mainnet dashd version to v18

---

packages/js-dpp/lib/stateTransition/StateTransitionFacade.js
packages/js-dpp/lib/stateTransition/validation/validateStateTransitionKeySignatureFactory.js
packages/js-dpp/test/unit/stateTransition/validation/validateStateTransitionKeySignatureFactory.spec.js

DPP throw `Cannot read properties of null (reading 'getBalance')` error
`validateStateTransitionKeySignature` method now checks identity existence on topUp transitions
With tests
No

fix(dpp): cannot read properties of null (reading 'getBalance')

---

packages/js-drive/lib/identity/masternode/handleRemovedMasternodeFactory.js
packages/js-drive/test/integration/identity/masternode/synchronizeMasternodeIdentitiesFactory.spec.js

```
[2022-10-10 16:13:43.307 +0000] FATAL (36 on 605f854e1d5b): db is in readonly mode due to the active transaction. Please provide transaction or commit it
driveVersion: "0.23.0-alpha.2"
err: {
"type": "Error",
"message": "db is in readonly mode due to the active transaction. Please provide transaction or commit it",
"stack":
Error: db is in readonly mode due to the active transaction. Please provide transaction or commit it
at Object.appendStackWrapper (/platform/.yarn/unplugged/@dashevo-rs-drive-npm-0.23.0-dev.8-a11a98b062/node_modules/@dashevo/rs-drive/node/appendStack.js:10:18)
at async DocumentRepository.delete (/platform/packages/js-drive/lib/document/DocumentRepository.js:194:45)
at async handleRemovedMasternode (/platform/packages/js-drive/lib/identity/masternode/handleRemovedMas …
```

fix(drive): db is in readonly mode due to the active transaction

---

packages/dapi/lib/chainDataProvider/ChainDataProvider.js
packages/dapi/test/integration/grpcServer/handlers/blockheaders-stream/subscribeToNewBlockHeaders.spec.js
packages/dapi/test/unit/chainDataProvider/chainDataProvider.spec.js

The fix makes dapi to cache only chainlocked headers, or in the absence of the chainlock, headers with height less than current chain height - 6
- Fixed bug with wrong header heights assigned to cached items
- Tweaked cache logic to save only headers behind certain height (chain locked or latest chain height - 6)
- CI
- Manual tests with block headers sync worker on wallet 

fix(dapi): caching of headers prone to reorgs

---

docs/README.md
packages/js-dapi-client/README.md
packages/js-dash-sdk/README.md
packages/js-dash-sdk/docs/examples/pay-to-another-address.md
packages/js-dash-sdk/docs/getting-started/core-concepts.md
packages/js-dash-sdk/docs/wallet/about-wallet-lib.md
packages/js-dpp/README.md
packages/wallet-lib/README.md
packages/wallet-lib/docs/account/createTransaction.md
packages/wallet-lib/docs/usage/dapi.md

Previous gh pages url is not valid after repo rename
Updated url
Made sure link works
N/A

docs: update URL from dashevo to dashpay

---

packages/dapi/lib/grpcServer/handlers/platform/getConsensusParamsHandlerFactory.js
packages/dapi/test/unit/grpcServer/handlers/platform/getConsensusParamsHandlerFactory.spec.js

`getConsensusParamsHandler`  was handling error without a minus sign `32603` instead of `-32603`
- updated error code
None

fix(dapi): `getConsensusParamsHandler` was handling wrong Tendermint error

---

packages/dapi/lib/externalApis/tenderdash/WsClient.js

DAPI exits in case Tanderdash is not running, instead of trying to reconnect
Fixed DAPI reconnect logic
Manual
No

fix(dapi): fail to reconnect to tenderdash in case of ENOTFOUND

---

packages/wasm-dpp/Cargo.toml

Cargo build not working
Remove unused deprecated wasm-bindgen feature
Run cargo build
None

fix: build not working because of deprecated wasm-bindgen feature

---

packages/dapi-grpc/scripts/build.sh

We have been using a custom `protoc` builder image in order to enable `arm64` and `protoc-ts-gen` support. Support for these features has now been added to a stable release upstream, so we should go back to using that. 
Update protoc image to `rvolosatovs/protoc`
In CI
None

chore: update protoc builder to upstream image

---

packages/js-drive/lib/abci/handlers/initChainHandlerFactory.js
packages/js-drive/lib/abci/handlers/prepareProposalHandlerFactory.js
packages/js-drive/lib/abci/handlers/proposal/createCoreChainLockUpdateFactory.js
packages/js-drive/test/unit/abci/handlers/initChainHandlerFactory.spec.js
packages/js-drive/test/unit/abci/handlers/prepareProposalHandlerFactory.spec.js
packages/js-drive/test/unit/abci/handlers/proposal/createCoreChainLockUpdateFactory.spec.js

Need to return `nextCoreChainLockUpdate` on init chain.
`nextCoreChainLockUpdate`  param added to init chain response.
With tests
No

feat(drive): provide latest core chain lock on init chain

---

CHANGELOG.md
package.json
packages/bench-suite/package.json
packages/dapi-grpc/package.json
packages/dapi/package.json
packages/dash-spv/package.json
packages/dashmate/package.json
packages/dashpay-contract/package.json
packages/dpns-contract/package.json
packages/feature-flags-contract/package.json
packages/js-dapi-client/package.json
packages/js-dash-sdk/package.json
packages/js-dpp/package.json
packages/js-drive/package.json
packages/js-grpc-common/package.json
packages/masternode-reward-shares-contract/package.json
packages/platform-test-suite/package.json
packages/rs-drive-nodejs/package.json
packages/wallet-lib/package.json
packages/wasm-dpp/package.json
packages/withdrawals-contract/package.json

chore(release): update changelog and bump version to 0.24.0-dev.9

---

packages/dashmate/src/listr/tasks/ssl/VerificationServer.js

Under WSL environment SSL domain verification envoy config messed up in one line. 
Fixed DOT engine configuration.
Manual
No

fix(dashmate): SSL domain verification config could not be generated in WSL

---

packages/js-drive/lib/abci/handlers/initChainHandlerFactory.js

If something goes wrong in initChain command, after groveDB commit, it breaks the whole node.
GroveDB commit command was replaced to the end of initChain function
With tests
No

fix(drive): initChain handler is not idempotent

---

.github/workflows/all-packages.yml

CI builds were slow, even though cache mounts were apparently restored correctly
Both the syntax and threshold for the `cache-max-size` var were incorrect. Running a clean build on the `v0.24-dev` branch results in the following cache mounts:
```
ID:             kh4zvi2qo3wf0srh9jq6sfr2w
Created at:     2022-12-30 05:11:12.539157381 +0000 UTC
Mutable:        true
Reclaimable:    true
Shared:         false
Size:           3.748GB
Description:    cached mount /platform/target from exec /bin/sh -c yarn workspace @dashevo/rs-drive build
Usage count:    2
Last used:      21 seconds ago
Type:           exec.cachemount
ID:             myxa6zdsi3uqmjoq11xs0scct
Created at:     2022-12-30 05:11:12.804387549 +0000 UTC
Mutable:        true
Reclaimable:    true
Shared:         false
Size: …
```

ci: increase cache-max-size

---

packages/js-drive/lib/storage/GroveDBStore.js
packages/rs-drive-nodejs/GroveDB.js
packages/rs-drive-nodejs/src/lib.rs
packages/rs-drive-nodejs/test/GroveDB.spec.js
packages/rs-drive/src/drive/contract/mod.rs

test: fix test and small refactoring

---

CHANGELOG.md
package.json
packages/bench-suite/package.json
packages/dapi-grpc/package.json
packages/dapi/package.json
packages/dash-spv/package.json
packages/dashmate/package.json
packages/dashpay-contract/package.json
packages/dpns-contract/package.json
packages/feature-flags-contract/package.json
packages/js-dapi-client/package.json
packages/js-dash-sdk/package.json
packages/js-dpp/package.json
packages/js-drive/package.json
packages/js-grpc-common/package.json
packages/masternode-reward-shares-contract/package.json
packages/platform-test-suite/package.json
packages/rs-drive-nodejs/package.json
packages/wallet-lib/package.json
packages/wasm-dpp/package.json
packages/withdrawals-contract/package.json

chore(release): update changelog and bump version to 0.24.0-dev.12

---

packages/dashmate/configs/system/testnet.js

We need to use core 18.2.0 to sync to the right chain on testnet
Add testnet override, because 18.2.0 shouldn't be used on any other networks
On a VPS
None

chore: use core 18.2.0 on testnet

---

.pnp.cjs
packages/wasm-dpp/README.md
packages/wasm-dpp/package.json
packages/wasm-dpp/src/utils.rs
packages/wasm-dpp/webpack.config.js
yarn.lock

This utility function helps to produce generics from JsValue in the situations where we don't really know what is exactly passed to the function. (E.g. we can have either `InstantAssetLockProof` or `ChainAssetLockProof`)
Usage sample:
```
use wasm_bindgen::__rt::Ref;
use crate::utils::{generic_of_js_val};
struct Internal {
value: u8,
}
#[wasm_bindgen(js_name=jsValueToGeneric)]
pub async fn js_value_to_generic(
js_value: JsValue, 
) -> Result<JsValue, JsValue> {
let internal: Ref<Internal> = generic_of_js_val::<Internal>(&js_value, "Internal")?;
let internal_instance = internal.clone();
...
}
```
Applied workaround as explained here https://github.com/rustwasm/wasm-bindgen/issues/2231#issuecomment-1147260391
Locally on relevant code sample
**For repository code-owners and collaborators …

feat(wasm-dpp): implement function to produce generics from JsValue

---

packages/js-drive/lib/abci/handlers/proposal/endBlockFactory.js
packages/rs-drive-abci/src/abci/messages.rs
packages/rs-drive-abci/src/execution/fee_pools/fee_distribution.rs
packages/rs-drive-abci/src/execution/fee_pools/process_block_fees.rs
packages/rs-drive-nodejs/Drive.js
packages/rs-drive-nodejs/test/Drive.spec.js

Log number of refunded epochs in drive
Additional `refundedEpochsCount` field was added to logs
With tests
No

feat(drive): log number of refunded epochs

---

packages/rs-dpp/src/data_contract/document_type/document_type.rs
packages/rs-dpp/src/data_contract/extra/common.rs
packages/rs-drive/src/drive/contract/mod.rs

fix: remove recusion when insertin DocumentType

---

packages/dashmate/templates/core/dash.conf.dot

New merkle blocks were not propagating from Zero MQ. 
Instead, wallet-lib was obtaining them after stream reconnects when they were already accessible via Core RPC.
Added rawblock ZMQ message to core config
On local network

fix(dashmate): missing rawblock zmq message in core config

---

packages/rs-drive/src/common/helpers/setup.rs

setup_drive() comment didn't specify that it sets up a temporary directory

fix commenting

---

packages/dashmate/templates/core/dash.conf.dot

New v18 dashcore release introduces multi wallet support, and thus you have to point which wallet you want to use with dash-cli. At the same time, seed nodes are often used to send som dash in local networks. 
Added rpcwallet option to dash.conf template
Locally

fix(dashmate): undefined wallet for dash-cli

---

packages/dashmate/Dockerfile
packages/dashmate/configs/migrations.js
packages/dashmate/docker-compose.platform.yml
packages/dashmate/docker/entrypoint.sh
packages/dashmate/src/docker/DockerCompose.js

dashmate-helper container is being run as root user, and when you try to execute commands from inside the container, it re-renders the configuration with the `root:root` owner. This PR passes host user and group ids for dashmate-helper container
Made dashmate grab the current executing user uid and gid and pass it to the docker compose, allowing to execute docker commands inside container without any issues
On the devnet via dash-network-deploy tool
No

fix(dashmate): make dashmate helper run commands as host user

---

packages/rs-dpp/src/identity/state_transition/identity_create_transition/apply_identity_create_transition.rs
packages/rs-dpp/src/identity/state_transition/identity_create_transition/validation/state/mod.rs
packages/rs-dpp/src/identity/state_transition/identity_topup_transition/apply_identity_topup_transition.rs
packages/rs-dpp/src/state_repository.rs
packages/wasm-dpp/src/state_repository.rs
packages/wasm-dpp/test/unit/identity/stateTransition/IdentityCreateTransition/applyIdentityCreateTransitionFactory.spec.js
packages/wasm-dpp/test/unit/identity/stateTransition/IdentityCreateTransition/validation/state/validateIdentityCreateTransitionStateFactory.spec.js
packages/wasm-dpp/test/unit/identity/stateTransition/IdentityTopUpTransition/applyIdentityTopUpTransitionFactory.spec.js

PR ensures that identity/stateTransition logic in rs-dpp matches js-dpp
- Provided executionContext to mark_asset_lock_transaction_as_used
- Fetch identity balance instead of identity in identity create transition state validator

feat(rs-dpp): backports of identity/stateTransition from js-dpp

---

packages/rs-dpp/src/data_contract/data_contract.rs
packages/rs-dpp/src/data_contract/document_type/document_type.rs
packages/rs-dpp/src/data_contract/get_binary_properties_from_schema.rs
packages/rs-dpp/src/data_trigger/mod.rs
packages/rs-dpp/src/document/document_stub.rs
packages/rs-dpp/src/tests/identity/identity_public_key_spec.rs
packages/rs-dpp/src/tests/identity/identity_spec.rs
packages/rs-drive-abci/src/state/genesis.rs
packages/rs-drive-abci/tests/strategy_tests/main.rs
packages/rs-drive-abci/tests/strategy_tests/upgrade_fork_tests.rs
packages/rs-drive/src/drive/grove_operations.rs
packages/rs-drive/tests/query_tests.rs

Trying to remove Clippy warnings for easier future warnings elimination
- fixed code according to Clippy
- kept `unused variables` as this is thing of discussion
None

refactor: remove various Clippy warnings

---

packages/js-dpp/test/unit/dataContract/stateTransition/DataContractUpdateTransition/validation/basic/validateIndicesAreBackwardCompatible.spec.js
packages/rs-dpp/src/data_contract/state_transition/data_contract_update_transition/validation/basic/validate_indices_are_backward_compatible.rs
packages/rs-dpp/src/tests/data_contract/state_transition/data_contract_update_transition/validation/basic/validate_indices_are_backward_compatible_spec.rs
packages/wasm-dpp/test/unit/dataContract/stateTransition/DataContractUpdateTransition/validation/basic/validateIndicesAreBackwardCompatible.spec.js

PR ensures that validateIndicesAreBackwardCompatible logic in rs-dpp is up to date
Matched `validateIndicesAreBackwardCompatible` tests on `js-dpp` and `wasm-dpp` sides 
Fixed bug with validation on `rs-dpp` side

feat(rs-dpp): validate indices are backwards compatible backport

---

.github/workflows/release.yml

Platform release github actions workflow is currently broken, and it breaks on every pull request merge, because of syntax error.
Example: https://github.com/dashpay/platform/actions/runs/4261755175 
Put env inside run step script string
Not tested yet (there is no `Run workflow` button in the actions for this workflow)

fix(ci): fix release workflow syntax error

---

packages/rs-dpp/src/data_contract/state_transition/data_contract_update_transition/validation/basic/validate_data_contract_update_transition_basic.rs
packages/rs-dpp/src/tests/data_contract/state_transition/data_contract_update_transition/validation/basic/validate_data_contract_update_transition_basic_spec.rs
packages/wasm-dpp/src/data_contract/state_transition/data_contract_update_transition/mod.rs
packages/wasm-dpp/src/data_contract/state_transition/data_contract_update_transition/validation.rs
packages/wasm-dpp/test/integration/dataContract/stateTransition/DataContractUpdateTransition/validation/basic/validateDataContractUpdateTransitionBasicFactory.spec.js

feat(wasm-dpp): integration tests validate data contract update transition

---

scripts/pack_dashmate.sh

Fix oclif pack command in which OS parameter is hardcoded to macos.
Replace `macos` parameter for `yarn oclif pack` command in pack_dashmate.sh file to relevant variable.
Run pack_dashmate.sh locally on Ubuntu.

Fix oclif pack command

---

packages/rs-dpp/src/data_contract/validation/data_contract_validator.rs

Backport of the index unique validation from v24 into rs-dpp
Added one additional validation to the DataContractValidator

feat(rs-dpp): backport of index_definitions.unique validation

---

README.md
packages/dapi/README.md
packages/dashmate/README.md

As we are not supporting higher than 16 version of nodeJS, the documentation for platform is misleading. 
Dashmate reset command description is also wrongly placed and mixed with reindex command.
Update platform, DAPI and dashmate docs about currently supported nodeJS version (from v16+ to v16).
Fix incorrect description for dashmate `reset` command which was partly pasted into reindex command description.

docs: supported Node.JS version and dashmate command description

---

packages/rs-drive-abci/src/abci/handlers.rs

Rust Core RPC client fails with:
```
execution: Core PC error: could not get block hash on height: 6251, reason: JSON-RPC error: transport error: HTTP response too short: length 0, needed 12.
```
- Temporarily disable withdrawal logic which uses RPC client until it's stabilized.
None
None

chore(drive): temporary disable unstable withdrawal logic

---

packages/js-drive/lib/identity/masternode/createMasternodeIdentityFactory.js
packages/js-drive/package.json
packages/js-drive/test/integration/identity/masternode/synchronizeMasternodeIdentitiesFactory.spec.js
packages/js-drive/test/unit/identity/masternode/createMasternodeIdentityFactory.spec.js

```
[2023-03-21 04:51:46.315 +0000] FATAL (35 on 81a4ef41c2a0): identity: a unique key with that hash already exists: the key already exists in the unique set
driveVersion: "0.24.0-dev.14"
height: "1"
abciMethod: "initChain"
err: {
"type": "Error",
"message": "identity: a unique key with that hash already exists: the key already exists in the unique set",
"stack":
Error: identity: a unique key with that hash already exists: the key already exists in the unique set
at Object.appendStackWrapper (/platform/packages/rs-drive-nodejs/appendStack.js:10:18)
at async IdentityStoreRepository.create (/platform/packages/js-drive/lib/identity/IdentityStoreRepository.js:164:25)
at async createMasternodeIdentity (/platform/packages/js-drive/lib/identity/masternode/createMasternodeIdentityFactory.js:72:5) …
```

chore(drive): temporary disable payout script

---

.github/workflows/release.yml
scripts/pack_dashmate.sh

Dashmate release script contains some errors, which makes impossible to release it.
Fixed dashmate release script
No

ci: dashmate release script fix

---

packages/dashmate/configs/system/mainnet.js
packages/dashmate/configs/system/testnet.js

Bump dashcore versions
Updated dashcore images for mainnet and testnet

chore(dashmate): update production dashcore versions for mainnet and testnet

---

packages/rs-dpp/src/data_contract/data_contract_factory.rs
packages/rs-dpp/src/document/document_facade.rs
packages/rs-dpp/src/document/document_factory.rs
packages/rs-dpp/src/document/state_transition/documents_batch_transition/mod.rs
packages/rs-dpp/src/identity/state_transition/identity_credit_withdrawal_transition/apply_identity_credit_withdrawal_transition_factory.rs
packages/rs-dpp/src/tests/fixtures/get_dashpay_document_fixture.rs
packages/rs-dpp/src/tests/fixtures/get_document_transitions_fixture.rs
packages/rs-dpp/src/tests/fixtures/get_documents_fixture.rs
packages/rs-dpp/src/tests/fixtures/get_dpns_document_fixture.rs
packages/rs-dpp/src/tests/fixtures/get_masternode_reward_shares_documents_fixture.rs
packages/rs-dpp/src/util/entropy_generator.rs
packages/rs-drive/src/drive/document/update.rs
packages/wasm-dpp/lib/test/fixtures/getDataContractFixture.js
packages/wasm-dpp/lib/test/fixtures/getDocumentsFixture.js
packages/wasm-dpp/src/data_contract_factory/data_contract_factory.rs
packages/wasm-dpp/src/document/factory.rs
packages/wasm-dpp/src/entropy_generator.rs
packages/wasm-dpp/src/lib.rs

PR addresses next issues:
- Need to provide external entropy generator to Document Factory (needed for JS)
- Proper error handling for entropy generator (need to know what's going on in case external generator fails to produce entropy)
- Return Result instead of panicking in `generate()` function
- Add entropy generator as an argument to DocumentFactory
- Refactor entropy generator file structure
- Update JS fixture
- CI

feat(wasm-dpp): provide external entropy generator to document factory

---

packages/dashmate/src/config/systemConfigs/createSystemConfigsFactory.js
packages/dashmate/src/oclif/command/ConfigBaseCommand.js

Sometimes people run `dashmate start` without knowing that the node configuration is required.
- Remove base config as default
- Show a hint to run `dashmate setup` if default config is empty
Manually
None

feat(dashmate): hint to setup a node on start failure

---

packages/dashmate/configs/migrations.js
packages/dashmate/src/commands/reset.js
packages/dashmate/src/commands/status/platform.js
packages/dashmate/src/config/Config.js
packages/dashmate/src/listr/tasks/resetNodeTaskFactory.js
packages/dashmate/src/listr/tasks/setup/local/configureTenderdashTaskFactory.js
packages/dashmate/src/listr/tasks/setup/regular/configureSSLCertificateTaskFactory.js
packages/dashmate/src/listr/tasks/setup/setupLocalPresetTaskFactory.js
packages/dashmate/src/listr/tasks/setup/setupRegularPresetTaskFactory.js
packages/dashmate/src/listr/tasks/ssl/selfSigned/obtainSelfSignedCertificateTaskFactory.js
packages/dashmate/src/listr/tasks/startGroupNodesTaskFactory.js
packages/dashmate/src/listr/tasks/startNodeTaskFactory.js
packages/dashmate/src/status/scopes/overview.js
packages/dashmate/src/status/scopes/services.js
packages/dashmate/src/templates/renderServiceTemplatesFactory.js
packages/dashmate/test/unit/status/scopes/overview.spec.js
packages/dashmate/test/unit/status/scopes/platform.spec.js
packages/dashmate/test/unit/status/scopes/services.spec.js

Atm, we remove the platform config section if the platform is disabled for the specific configuration. This approach leads to different inconsistency problems and is unnecessary due to having the `platform.enable` toggle.
- Do not delete platform section from config
- Change platform assert to `Config#get('platform.enable')`
- Implement migration
None
None

refactor(dashmate): always keep platform config

---

CHANGELOG.md
package.json
packages/bench-suite/package.json
packages/dapi-grpc/package.json
packages/dapi/package.json
packages/dash-spv/package.json
packages/dashmate/package.json
packages/dashpay-contract/package.json
packages/dpns-contract/package.json
packages/feature-flags-contract/package.json
packages/js-dapi-client/package.json
packages/js-dash-sdk/package.json
packages/js-dpp/package.json
packages/js-drive/package.json
packages/js-grpc-common/package.json
packages/masternode-reward-shares-contract/package.json
packages/platform-test-suite/package.json
packages/rs-drive-nodejs/package.json
packages/wallet-lib/package.json
packages/wasm-dpp/package.json
packages/withdrawals-contract/package.json

chore(release): update changelog and bump version to 0.24.0-dev.17

---

packages/rs-dpp/src/errors/consensus/consensus_error.rs
packages/rs-dpp/src/identity/identity.rs
packages/rs-platform-value/src/types/identifier.rs
packages/wasm-dpp/src/errors/consensus/basic/decode/protocol_version_parsing_error.rs
packages/wasm-dpp/src/errors/consensus/fee/balance_is_not_enough_error.rs
packages/wasm-dpp/src/errors/consensus/signature/identity_not_found_error.rs
packages/wasm-dpp/src/errors/consensus/state/data_contract/data_contract_already_present_error.rs
packages/wasm-dpp/src/identity/mod.rs
packages/wasm-dpp/test/integration/error/consensus/deserializeConsensusError.spec.js

Identifier deserialization doesn't work for bincode
- switched to byte visitor (thanks to @QuantumExplorer )
With tests
None

fix: identifier deserialization doesn't work for bincode

---

packages/dashmate/configs/schema/configJsonSchema.js

Dashmate integration on testnet was failing due to inability to select llmqType 6, which is required on testnet.
```
fatal: [hp-masternode-3]: FAILED! => changed=false 
cmd:
- yarn
- dashmate
- restart
delta: '0:00:11.555743'
end: '2023-04-04 13:05:12.249023'
msg: non-zero return code
rc: 1
start: '2023-04-04 13:05:00.693280'
stderr: |2-
InvalidConfigFileFormatError: Invalid
'/home/dashmate/.dashmate/config.json' config format:
config/platform/drive/abci/validatorSet/llmqType must be equal to one of
the allowed values
stderr_lines: <omitted>
stdout: ''
stdout_lines: <omitted>
```
Update enum `llmqType`
In testing
None

fix: llmqType must be equal to one of the allowed values

---

packages/rs-drive-abci/src/abci/error.rs
packages/rs-drive-abci/src/abci/handlers.rs
packages/rs-drive-abci/src/abci/mod.rs
packages/rs-drive-abci/src/abci/signature_verifier.rs
packages/rs-drive-abci/src/abci/withdrawal.rs
packages/rs-drive-abci/src/block.rs
packages/rs-drive-abci/src/execution/commit_validation.rs
packages/rs-drive-abci/src/execution/engine.rs

Withdrawal transactions need to use vote extensions in their processing
1. Implemented extend_vote and verify_vote_extension hooks
2. Implemented WithdrawalTxs used in these hooks
3. Implemented SignatureVerifier  for VoteExtension (WIP)
4. Extended FinalizeBlock with withdrawal tx processing logic
Not tested at all yet

feat(rs-drive-abci): withdrawal processing using vote extensions

---

packages/dashmate/src/commands/status/index.js

The status command returns exit code 1 if nodes are not running and other errors are occurring. It prevents to handle properly  restart/start logic in the deployment tool
- Exit with code 2 if sevices are not running
None
None

feat(dashmate): exit status with 2 if it's not running

---

packages/dashmate/Dockerfile
packages/dashmate/docker/entrypoint.sh

ENV DASHMATE_HELPER=1 defined in the Dockerfile is created at root user environment, and it gets erased after we switch it to dashmate in entrypoint.sh
Moved DASHMATE_HELPER=1 from Dockerfile to entrypoint.sh
On devnet
No

fix(dashmate): dashmate logic doesn't recognize it's ran from helper

---

packages/js-dapi-client/lib/dapiAddressProvider/ListDAPIAddressProvider.js
packages/js-dapi-client/lib/dapiAddressProvider/SimplifiedMasternodeListDAPIAddressProvider.js

DAPI Client ignores platform HTTP port for node addresses received with SML
- Set correct port and certificate options for addresses received from SML
Manually
None

fix(dapi-client): platform port is ignored from SML

---

packages/js-dapi-client/lib/dapiAddressProvider/SimplifiedMasternodeListDAPIAddressProvider.js
scripts/configure_test_suite_network.sh

configure_test_suite_network script points wrong mastenode private key list and sml provider returns regular masternodes
* Fixed configure_test_suite_network.sh script
* Fixed SML provider so that it returns only hpmns
platform-test-suite
No

fix: DAPI still expected on normal masternodes

---

packages/js-drive/lib/abci/handlers/proposal/beginBlockFactory.js
packages/js-drive/lib/identity/masternode/synchronizeMasternodeIdentitiesFactory.js
packages/js-drive/test/integration/identity/masternode/synchronizeMasternodeIdentitiesFactory.spec.js
packages/js-drive/test/unit/abci/handlers/proposal/beginBlockFactory.spec.js

If some nodes were restarted or missed some rounds during consensus polka, masternode identities synchronization can be called in non-deterministic manner due to in-memory state.
- Remove in-memory state for synchronize masternode identities logic
None
None

fix(drive): non-deterministic run of mn identities sync

---

packages/js-dapi-client/test/unit/dapiAddressProvider/SimplifiedMasternodeListDAPIAddressProvider.spec.js

SimplifiedMasternodeListDAPIAddressProvider test prevents tests to be passed
Fixed broken SimplifiedMasternodeListDAPIAddressProvider test
With tests
No

test(dapi-client): fix broken SimplifiedMasternodeListDAPIAddressProvider test

---

CHANGELOG.md
package.json
packages/bench-suite/package.json
packages/dapi-grpc/package.json
packages/dapi/package.json
packages/dash-spv/package.json
packages/dashmate/package.json
packages/dashpay-contract/package.json
packages/dpns-contract/package.json
packages/feature-flags-contract/package.json
packages/js-dapi-client/package.json
packages/js-dash-sdk/package.json
packages/js-dpp/package.json
packages/js-drive/package.json
packages/js-grpc-common/package.json
packages/masternode-reward-shares-contract/package.json
packages/platform-test-suite/package.json
packages/rs-drive-nodejs/package.json
packages/wallet-lib/package.json
packages/wasm-dpp/package.json
packages/withdrawals-contract/package.json

chore(release): update changelog and bump version to 0.24.0-dev.18

---

packages/dashmate/src/commands/setup.js

There is a warning on start `DeprecationWarning: No “main” or “exports” field defined in the package.json for /usr/lib/dashmate/node_modules/begoo/ resolving the main entry point “index.js”, imported from /usr/lib/dashmate/src/commands/setup.js.` that is needed to be fixed
Fixed dashmate setup command
Manual
No

fix(dashamte): deprecation warning on start

---

.github/workflows/release.yml
packages/dashmate/src/commands/setup.js
packages/dashmate/src/docker/DockerCompose.js
packages/dashmate/src/oclif/errors/MuteOneLineError.js

Need to check if everything installed (docker, docker-cmpose, etc.) before running setup command
Setup command now check system requirements first
Manual
No

feat(dashmate): check system requirements before setup

---

README.md
packages/wasm-dpp/README.md

Added missing instructions for wasm build
- Updated root README
- Updated wasm-dpp README
On fresh Ubuntu and MacOS setups

doc: prerequisites for wasm build

---

packages/dashmate/src/listr/tasks/ssl/VerificationServer.js

Dashmate throws fatal error `"invalid input" even for valid path for existing cert` in Windows environment
Fixed error in filename parsing.
Manual
No

fix(dashamte): wrong envoy config path on windows

---

packages/js-drive/lib/identity/masternode/synchronizeMasternodeIdentitiesFactory.js

During masternode identities sync we trying to update identities for invalid SML entries
- Create and update masternode identities only for valid entries from SML 
None
Previous state might be invalid since to new sync mn identities logic

fix(drive)!: updating a masternode identity with invalid entry from SML

---

CHANGELOG.md
package.json
packages/bench-suite/package.json
packages/dapi-grpc/package.json
packages/dapi/package.json
packages/dash-spv/package.json
packages/dashmate/package.json
packages/dashpay-contract/package.json
packages/dpns-contract/package.json
packages/feature-flags-contract/package.json
packages/js-dapi-client/package.json
packages/js-dash-sdk/package.json
packages/js-dpp/package.json
packages/js-drive/package.json
packages/js-grpc-common/package.json
packages/masternode-reward-shares-contract/package.json
packages/platform-test-suite/package.json
packages/rs-drive-nodejs/package.json
packages/wallet-lib/package.json
packages/wasm-dpp/package.json
packages/withdrawals-contract/package.json

chore(release): update changelog and bump version to 0.24.0-dev.24

---

packages/dashmate/src/listr/tasks/setup/setupLocalPresetTaskFactory.js

Select number of masternodes during local setup freezes
It seems like there is a bug in Listr2 Numeral prompt implementation, which freezes the input. Thats why Numeral prompt was replaced with simple input with additional validations.
Manual
No

fix(dashmate): select number of masternodes during local setup freezes

---

packages/dashmate/src/listr/prompts/validators/validatePercentage.js

Reward shares input allows to have negative values
Fixed reward shares validation
Manual
No

fix(dashmate): reward shares can be negative during HP masternode registration

---

packages/dashmate/src/listr/tasks/setup/regular/registerMasternodeGuideTaskFactory.js

Resulting  hpmn_register multiline command doesn't have "\" at the end of string so you can't paste it the terminal
protx is missing before register_hpmn and register
Fixed the output
Manual
No

fix(dashmate): invalid mn register command in output of dashmate setup

---

packages/dashmate/src/listr/tasks/setup/regular/registerMasternodeGuideTaskFactory.js

Dashmate setup allow to input invalid BLS private key
Fixed BLS private key validation function usage
Manual
No

fix(dashmate): form accepts invalid BLS key

---

packages/dashmate/src/status/scopes/masternode.js

Dashmate status shows empty masternode status while syncing
Dashmate status now shows UNKNOWN masternode status while it is syncing
Manual
No

fix(dashmate): empty masternode status while syncing

---

Cargo.lock
packages/rs-drive-abci/src/abci/error.rs
packages/rs-drive-abci/src/abci/handlers.rs
packages/rs-drive-abci/src/abci/mimic.rs
packages/rs-drive-abci/src/execution/engine.rs
packages/rs-drive-abci/tests/strategy_tests/main.rs

fix: same block core chain lock height

---

.github/workflows/release.yml

When you try to install Dashmate MacOs installer, you'll see malicious software warning. To remove this warning we must notarize our application
Added an additional notarization step to github actions

build(dashmate): remove MacOs malicious software warning

---

packages/js-drive/lib/identity/masternode/handleNewMasternodeFactory.js
packages/js-drive/lib/identity/masternode/synchronizeMasternodeIdentitiesFactory.js
packages/js-drive/test/integration/identity/masternode/synchronizeMasternodeIdentitiesFactory.spec.js
packages/js-drive/test/unit/identity/masternode/handleNewMasternodeFactory.spec.js

Testnet uses non unque keys for owners and voting but the current implementation of syncronize masternode identities doesn't suport it 
- Disable voting keys until we have support for non-unique keys in DPP
None
Previous state won't be valid due to changes in the sync identities logic

fix(drive)!: non-unique masternode voting keys

---

packages/dashmate/docker-compose.platform.yml
packages/dashmate/src/commands/group/reset.js
packages/dashmate/src/commands/reset.js
packages/dashmate/src/config/Config.js
packages/dashmate/src/docker/DockerCompose.js
packages/dashmate/src/listr/tasks/resetNodeTaskFactory.js
packages/dashmate/src/listr/tasks/setup/local/configureCoreTaskFactory.js

The reset and group reset commands do not work with `--force` flag
- Remove containers and volumes in two steps since `docker compose rm --stop --volumes` doesn't work properly.
- Fixed group soft reset
- Refactored reset logic
- Renamed the `--platfrom-only` to `--platform` flag follow naming convention with other commands
Manually
- The `--platfrom-only` flag is renamed to `--platform`

fix(dashmate)!: multiple issues in the reset command

---

packages/dashmate/src/listr/prompts/validators/validateBLSPrivateKeyFactory.js
packages/dashmate/src/listr/prompts/validators/validateHex.js
packages/dashmate/src/listr/prompts/validators/validateTxHex.js

It is possible to add an arbitrary text after valid BLS key into the form, e.g. `2f0f410a2ad8f5e1e0eff678d5b56df2440b1792c55c7a3d71714e6f6e146e82 random text`
`validateBLSPrivateKey` function now checks that value is a valid HEX string
Manual
No

fix(dashmate): BLS private key validate accepts whitespaces

---

packages/dashmate/src/listr/tasks/resetNodeTaskFactory.js

During platform reset there are two issues happening:
``` 
(HTTP code 404) no such volume - get dash_masternode_testnet_drive_tenderdash: no such volume
```
```
(HTTP code 409) conflict - remove dash_masternode_testnet_drive_abci_data: volume is in use - [cab842c8b25f0589e80f5daad85faaf8b794489da200657d504c93e9b7039d22]
```
- Added retry logic to handle those errors
Manually
None

fix(dashmate): "volume is in use" and "no such volume"

---

.github/workflows/release.yml

Use rs-drive-abci instead of js-drive when building drive in GH actions

release: reference rs-drive-abci instead of js-drive

---

packages/dashmate/templates/core/dash.conf.dot

Dashmate failed to start core v20 with error about missing `fallbackffee` on testnet
Add `fallbackffee` on testnet
Untested
None, this has always been the fallbackfee on testnet I think

fix(dashmate): missing fallback fee on testnet with core v20

---

packages/dashmate/src/listr/tasks/resetNodeTaskFactory.js

The volume removal logic in reset command has wrong retry condition so if volume is in use it won't be removed 
- Fixed retry logic
None
None

fix(dashmate): wrong volume removal retry logic

---

packages/js-drive/lib/core/getRandomQuorumFactory.js
packages/js-drive/lib/validator/ValidatorSet.js
packages/js-drive/package.json
packages/js-drive/test/unit/core/getRandomQuorumFactory.spec.js
packages/js-drive/test/unit/validator/ValidatorSet.spec.js

We faced today with another two problem on testnet:
1. Rotation logic has a bug in v0.24: we filter out banned nodes after we select quorum so we could have one with valid nodes less than threshold
2. There are many 3rd party nodes without platform so we basically have the same issue like in the fist problem.
- Filter out banned master nodes before we choice a quorum
- Added a whitelist for testnet with DCG only nodes
- Disabled quorum expiration logic because it doesn't work properly
- Do not rotate quorum if there is not other valid candidates
On testnet
Validator rotation logic is changed. Previous blockchain data won't be compatible.

feat(drive)!: whitelist and filter banned nodes for validators

---

packages/js-drive/lib/abci/errors/VerboseInternalAbciError.js

```
[2023-05-08 10:52:39.730 +0000] FATAL (34 on d49e27521be4): Cannot read properties of undefined (reading 'toString')
driveVersion: "0.24.0-dev.33"
err: {
"type": "TypeError",
"message": "Cannot read properties of undefined (reading 'toString')",
"stack":
TypeError: Cannot read properties of undefined (reading 'toString')
at new VerboseInternalAbciError (/platform/packages/js-drive/lib/abci/errors/VerboseInternalAbciError.js:10:45)
at Object.methodErrorHandler [as checkTx] (/platform/packages/js-drive/lib/abci/errors/wrapInErrorHandlerFactory.js:49:25)
at runMicrotasks (<anonymous>)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
at async Connection.handleRequest (/platform/.yarn/cache/@dashevo-abci-https-9fb519f2ca-aaf41ab7fa.zip/node_modules/@dashevo/abci/lib/han …
```

fix(drive): cannot read properties of undefined (reading 'toString')

---

packages/dashmate/src/commands/restart.js
packages/dashmate/src/commands/start.js
packages/dashmate/src/commands/stop.js
packages/dashmate/src/listr/tasks/restartNodeTaskFactory.js
packages/dashmate/src/listr/tasks/startNodeTaskFactory.js
packages/dashmate/src/listr/tasks/stopNodeTaskFactory.js

Add `platform` flag which allows to start, stop or restart only platform
`platform` flad was added to start, stop and restart commands
Manual
No

feat(dashmate): platform flag for start, stop and restart commands

---

packages/dashmate/src/commands/restart.js
packages/dashmate/src/commands/start.js
packages/dashmate/src/commands/stop.js
packages/dashmate/src/listr/tasks/restartNodeTaskFactory.js
packages/dashmate/src/listr/tasks/startNodeTaskFactory.js
packages/dashmate/src/listr/tasks/stopNodeTaskFactory.js

We need to check if core service started or not only when we pass `--platform` flag. Now it check every time
Fixed condition for `Check core is started` task
Manual
No

fix(dashmate): check core is started checks everytime

---

Cargo.lock
packages/platform-test-suite/test/functional/platform/Identity.spec.js
packages/rs-drive-abci/Cargo.toml
packages/rs-drive-abci/src/execution/fee_pools/fee_distribution.rs
packages/rs-drive-abci/src/execution/fee_pools/process_block_fees.rs
packages/rs-drive-abci/tests/strategy_tests/main.rs

DO NOT BACKPORT TO v0.25-dev
Since synchronize masternode identity logic was partially ripped our due to the incompletion of Identity v2 in v0.24, there is no guarantee that all masternodes have corresponding identities. 
To mitigate this problem, all payouts go to the system contract owner identity.
None
None, until chain on epoch 0

chore(drive): payout fees only to single well-known Identity

---

packages/dashmate/src/commands/ssl/obtain.js
packages/dashmate/src/listr/tasks/ssl/zerossl/obtainZeroSSLCertificateTaskFactory.js

In case of using with deployment tool we don't need retry logic on the ssl obtain command
- Added `no-retry` flag to the ssl obtain command
None
None

feat(dashmate): `no-retry` flag for ssl obtain command

---

packages/dashmate/src/listr/prompts/createIpAndPortsForm.js

When users setup evolution masternode and follow setup steps, on the step “Enter IP address and ports:” they see form with `disabled` fields, which is confusing
Changed port labels for mainnet evolution node setup to non confusing ones
Manual
No

chore(dashmate): better port labels for mainnet evolution node setup 

---

Dockerfile

We have race condition here: https://github.com/dashpay/platform/actions/runs/5015722236/jobs/9002775136
Scenario I see:
```
ARM: Fri, 19 May 2023 04:47:15 GMT#35 0.508 Updating [crates.io](http://crates.io/) index
AMD: Fri, 19 May 2023 04:47:35 GMT#30 81.26 error: could not find `wasm-bindgen-cli` in registry `crates-io` with version `=0.2.84`
```
So, we try to install wasm-bindgen-cli during crates-io sync. As we share cached mounts, crates index gets broken.
Cache mounts mode changed to "private".
To be tested during release.
None

build: fix race condition in cargo cache download

---

packages/dapi/lib/externalApis/drive/DriveClient.js
packages/dapi/lib/grpcServer/handlers/createGrpcErrorFromDriveResponse.js
packages/dapi/lib/grpcServer/handlers/platform/broadcastStateTransitionHandlerFactory.js
packages/dapi/test/unit/externalApis/drive/DriveClient.spec.js
packages/js-dash-sdk/src/SDK/Client/Platform/methods/documents/get.ts
packages/rs-dpp/src/document/document_facade.rs
packages/rs-dpp/src/document/document_factory.rs
packages/rs-drive-abci/src/abci/handlers.rs
packages/rs-drive-abci/src/query/mod.rs
packages/wasm-dpp/src/document/document_facade.rs
packages/wasm-dpp/src/document/factory.rs
packages/wasm-dpp/src/state_transition/errors/invalid_state_transition_error.rs

Refactored query and consensus error handling in rs-drive-abci to comply with DAPI
Drive
- Refactored query error response (Without error codes for now)
- Provided consensus error serialization in check_tx response
- Fixed bug with decoding of empty order_by in /document query
DAPI
- Refactored some endpoint names to match rs-drive-abci handlers
SDK and Wasm-dpp
- Introduced function to create exteneded document from regular document and data contract

feat(drive): check tx and queries error handling

---

packages/data-contracts/src/lib.rs
packages/rs-dpp/src/lib.rs
packages/rs-drive-abci/src/abci/handlers.rs
packages/rs-drive-abci/src/execution/check_tx.rs
packages/rs-drive-abci/src/state/genesis.rs
packages/rs-drive-abci/src/validation/state_transition/identity_create.rs
packages/rs-drive-abci/src/validation/state_transition/identity_top_up.rs
packages/rs-drive-abci/src/validation/state_transition/identity_update.rs

We were panicking instead of giving back a validation result, this should now be fixed.
In one case we were also not testing the validation result to be errorless and instead testing a previous validation result (as they shared similar names).

fix: check tx should return validation result instead of panic

---

packages/wallet-lib/src/logger/index.js
packages/wallet-lib/src/plugins/Workers/TransactionsSyncWorker/TransactionsReader.js
packages/wallet-lib/src/plugins/Workers/TransactionsSyncWorker/TransactionsReader.spec.js
packages/wallet-lib/src/plugins/Workers/TransactionsSyncWorker/TransactionsSyncWorker.js
packages/wallet-lib/src/test/mocks/dashcore/instantlock.js
packages/wallet-lib/tests/integration/plugins/Workers/TransactionsSyncWorker.spec.js

HD wallets were never receiving instant locks because every incoming TX fills addresses gap, and TX stream restarts. Instant locks are ready to be dispatched from DAPI, but because wallet restarts stream, it was never happening.
- Expand bloom filter and restart stream after instant locks arrival.
- In case instant locks were delayed, restart stream when next set of transactions is arrived
- CI
- Platform test suite on testnet 

fix(wallet-lib): instant locks not arriving to HD wallets

---

packages/wallet-lib/src/types/Account/methods/broadcastTransaction.js

Fixed a bug where wallet was not retrying to broadcast TX in case some of the nodes didn't receive a TX in their mempool yet and alarming for missing inputs
Updated error message handler in broadcast TX logic
- CI
- Chain of 25 TXs one after another to ensure that the error appears

fix(wallet-lib): not retrying on missing inputs error

---

packages/dashmate/configs/system/base.js
packages/dashmate/configs/system/mainnet.js
packages/dashmate/configs/system/testnet.js

Dashmate has wrong dashd version for mainnet configuration
Bump up version from 18.2.2 to 19.0.0
N/A
N/A

chore: bump up dashd version for mainnet in dashmate

---

packages/rs-drive-abci/src/rpc/core.rs

Core RPC retry logic handles all types of errors, even wrong user input, internal library errors or specific errors that needs to be handled manually.
- Retry only transport errors and Core RPC errors:
- `RPC_IN_WARMUP`
- `RPC_CLIENT_NOT_CONNECTED`
- `RPC_CLIENT_IN_INITIAL_DOWNLOAD`
Running existing tests
None

fix(drive): core RPC retry all errors

---

packages/rs-drive-abci/src/abci/handlers.rs

When Tenderdash stops for some reason or another :) . It might come back and request a block proposal that has already been processed. This case is now handled.

fix: double process proposal from Tenderdash restart

---

packages/js-dash-sdk/src/SDK/Client/Platform/methods/documents/get.spec.ts
packages/js-dash-sdk/src/SDK/Client/Platform/methods/documents/get.ts

Fixes bug with identifiers conversion for `in` query condition.
[Bug reported in Discord](https://discord.com/channels/670271785974890526/670540408593448980/1118221370220884088)
- Checked if identifier propery is an array in `where` query
- CI
- Added unit tests

fix(sdk): identifier expects buffer with "in" operator in where query

---

.github/workflows/manage-runs.yml

Sometimes you merge PR without waiting for all checks passed in case if your RP couldn't affect them (release PR is agood example) but workflow runs still active. We use self-hosted runners and they are very expecive. We need to save any cost we can.
- Add a workflow to cancel runs for already merged PRs
None
None

ci: cancel runs for already merged PRs

---

packages/dashmate/src/commands/ssl/obtain.js
packages/dashmate/src/listr/tasks/ssl/saveCertificateTask.js
packages/dashmate/src/listr/tasks/ssl/zerossl/obtainZeroSSLCertificateTaskFactory.js
packages/dashmate/src/ssl/zerossl/Certificate.js
packages/dashmate/src/ssl/zerossl/cancelCertificate.js
packages/dashmate/src/ssl/zerossl/createZeroSSLCertificate.js
packages/dashmate/src/ssl/zerossl/downloadCertificate.js
packages/dashmate/src/ssl/zerossl/getCertificate.js
packages/dashmate/src/ssl/zerossl/listCertificates.js
packages/dashmate/src/ssl/zerossl/requestApi.js
packages/dashmate/src/ssl/zerossl/revokeCertificate.js
packages/dashmate/src/ssl/zerossl/verifyDomain.js

To simplify infrastructure, we want to use the same private key for ZeroSSL certificates for a given node. Current renewal logic creates and new private key and certificate request every time you run it
- Store and reuse certificate request file for renewals
- Validate ZeroSSL configuration and files
- Download certificate file only if necessary
- Remove unsafe retries from the `downloadCertificate` function
- Manually running the `dashmate ssl obtain` command
- Running with https://github.com/dashpay/dash-network-deploy/pull/516
None

feat(dashmate): re-use ZeroSSL private key

---

packages/js-drive/lib/abci/handlers/initChainHandlerFactory.js
packages/js-drive/lib/abci/handlers/proposal/beginBlockFactory.js

Issue on v0.24 testnet:
```
[2023-06-23 10:38:30.773 +0000] FATAL (35 on fabd641262cf): Cannot read properties of undefined (reading 'toJSON')
driveVersion: "0.24.10"
height: "2"
round: 0
abciMethod: "prepareProposal"
err: {
"type": "TypeError",
"message": "Cannot read properties of undefined (reading 'toJSON')",
"stack":
TypeError: Cannot read properties of undefined (reading 'toJSON')
at /platform/packages/js-drive/lib/abci/handlers/proposal/beginBlockFactory.js:213:65
at Array.map (<anonymous>)
at beginBlock (/platform/packages/js-drive/lib/abci/handlers/proposal/beginBlockFactory.js:213:46)
at async prepareProposalHandler (/platform/packages/js-drive/lib/abci/handlers/prepareProposalHandlerFactory.js:74:5)
at async Connection.handleRequest …
```

fix(drive): cannot read properties of undefined (reading 'toJSON')

---

packages/dashmate/configs/migrations.js
packages/dashmate/configs/system/base.js

Changing the basic port of Dashmate Helper to avoid binding to the print port
- updated base config
local env
Default dashmate helper port changed from 9000 to 9100

fix(dashmate)!: helper default port was bound to Windows print port

---

.pnp.cjs
packages/dash-spv/.mocharc.yml
packages/dash-spv/lib/spvchain.js
packages/dash-spv/lib/test/.eslintrc
packages/dash-spv/lib/test/bootstrap.js
packages/dash-spv/lib/x11.js
packages/dash-spv/package.json
packages/dash-spv/test/index.js
packages/dash-spv/test/spvchain.js
packages/js-dapi-client/lib/BlockHeadersProvider/BlockHeadersProvider.js
packages/js-dapi-client/test/integration/BlockHeadersProvider/BlockHeadersProvider.spec.js
packages/js-dapi-client/test/unit/BlockHeadersProvider/BlockHeadersProvider.spec.js
packages/wallet-lib/src/test/mocks/TransportMock.js
packages/wallet-lib/src/types/Account/Account.spec.js
packages/wallet-lib/src/types/Account/_initializeAccount.js
packages/wallet-lib/tests/integration/plugins/Workers/BlockHeadersSyncWorker.spec.js
yarn.lock

It is expected to use wasm-x11-hash library to calculate hashes of block headers. However, in certain situations, legacy x11-hash-js was still used.
- Refactored dash-spv initialization to support wasm-x11-hash
- Updated dapi client and block headers provider to support async initialization
- CI
- Manual testing on testnet

refactor: unwanted usage of x11-hash-js

---

packages/dashmate/configs/migrations.js
packages/dashmate/configs/schema/configJsonSchema.js
packages/dashmate/configs/system/base.js
packages/dashmate/src/util/generateEnvs.js

Dashmate helper version is persisted in config file and usually outdated or even higher than dashmate version (after `dashmate update`). It leads to different incompatibility issues. The version of helper must be always the same as dashmate code which runs it. We should always use an image with a version that is equal to the package version or build from the source together with dashmate code.
- Removed `dashmate.helper.docker.image` configuration option
- Hardcoded the helper image with the current package version. 
None
Removed `dashmate.helper.docker.image` configuration option

fix(dashmate)!: runs invalid helper version

---

.github/workflows/manage-runs.yml

Workflows were still not getting cancelled properly when the PR was closed. Adding debug output showed the change in trigger to the "Manage runs" action meant that `$GITHUB_REF` was set to the PR merge branch, i.e. `refs/pull/1247/merge`. 
Setting the `$current_branch` variable to `$GITHUB_HEAD_REF` seems to return the expected result.
In CI, see successful cancel here: https://github.com/dashpay/platform/actions/runs/5641805311/job/15280481158
None

ci: select workflow_id to cancel based on head_ref

---

packages/rs-drive/src/drive/verify/identity.rs

The operation verifying an identity-id must not return an error if the identity doesn't exist
Added handling edge case when no proof for an identity is found
Unit-Test
N/A

refactor: returns root-hash if an identity is not found

---

.github/actions/docker/action.yaml
.github/workflows/all-packages.yml
.github/workflows/js-checks.yml

Modifying https://github.com/dcginfra/tf-aws-gh-runner/ to a multi-runner config means different runners should access different buckets to store cache. 
Add the bucket input as a variable passed to the cache dance action ([corresponding PR](https://github.com/dcginfra/buildkit-cache-dance/pull/2)) to support this use case.
On https://github.com/strophy/platform with a separate runner stack
None

ci: specify docker mount cache bucket name as variable

---

.github/actions/docker/action.yaml
.github/actions/nodejs/action.yaml
.github/actions/rust/action.yaml
.github/actions/s3-layer-cache-settings/action.yaml
.github/workflows/all-packages.yml
.github/workflows/js-checks.yml
.github/workflows/release.yml
.github/workflows/rs-checks.yml
.github/workflows/wasm-dpp.yml

AWS-hosted CI runners were migrated to a multi-runner stack in https://github.com/dcginfra/tf-aws-gh-runner/pull/8
Make corresponding changes to CI to support runner selection in the new stack
In CI
None

ci: switch to multi-runner stack

---

packages/dapi/Dockerfile
packages/dashmate/Dockerfile
packages/js-drive/Dockerfile
packages/platform-test-suite/Dockerfile

Project have upgraded wasm-bindgen version to v0.2.86, but it still installs v0.2.84, because buildbase:0.0.6 does not specify exact version to install. As a result, package release breaks with error:
```
it looks like the Rust project used to create this wasm file was linked against
version of wasm-bindgen that uses a different bindgen format than this binary:
rust wasm file schema version: 0.2.86
this binary schema version: 0.2.84
```
* Upgraded strophy/buildbase to 0.0.7-wasm-0.2.85
Not yet
Idk

fix(release): upgrade buildbase with wasm-bindgen 0.2.86

---

CHANGELOG.md
package.json
packages/bench-suite/package.json
packages/dapi-grpc/package.json
packages/dapi/package.json
packages/dash-spv/package.json
packages/dashmate/package.json
packages/dashpay-contract/package.json
packages/dpns-contract/package.json
packages/feature-flags-contract/package.json
packages/js-dapi-client/package.json
packages/js-dash-sdk/package.json
packages/js-dpp/package.json
packages/js-grpc-common/package.json
packages/masternode-reward-shares-contract/package.json
packages/platform-test-suite/package.json
packages/wallet-lib/package.json
packages/wasm-dpp/package.json
packages/withdrawals-contract/package.json

chore(release): update changelog and bump version to 0.25.0-dev.16

---

Cargo.lock
packages/rs-dpp/src/identity/identity.rs
packages/rs-dpp/src/identity/identity_factory.rs
packages/rs-drive-abci/Cargo.toml
packages/rs-drive-abci/src/abci/error.rs
packages/rs-drive-abci/src/abci/mod.rs
packages/rs-drive-abci/src/lib.rs
packages/rs-drive-abci/src/platform_types/platform/mod.rs
packages/rs-drive-abci/src/rpc/core.rs
packages/rs-drive-abci/src/test/helpers/setup.rs
packages/rs-drive/Cargo.toml

1. Importing dpp with default features disabled and only  "identity-serialization" enabled as follows fails:
```
dpp = { path = "../platform/packages/rs-dpp", default-features = false, features = [ "identity-serialization" ] }
```
2. Importing drive-abci without default features and without server feature fails.
* Fixed `identity-serialization` feature in dpp
* Introduced `mocks` feature in drive-abci
* Fixed features in drive-abci
Created and built a test project with the following Cargo.toml:
```
[package]
name = "t123"
version = "0.1.0"
edition = "2021"
[dependencies]
dpp = { path = "../platform/packages/rs-dpp", default-features = false, features = [ "identity-serialization" ] }
drive-abci = { path = "../platform/packages/rs-drive-abci", default-features = false }
```
Mocks in …

fix: dpp and drive-abci fail to build without default-features

---

packages/dapi/lib/grpcServer/handlers/platform/broadcastStateTransitionHandlerFactory.js
packages/rs-drive-abci/src/abci/handlers.rs

Client DAPI Client getting -32603 instead of proper error code when we broadcast a state transition
- Send base64-encoded cbor instead of consensus error bincode
- Do not pass json rpc error code in case if state transition is already exists
Locally with test suite
None

fix(drive): -32603 error code on broadcast

---

.github/workflows/release.yml

CI was failing with
```
time="2023-09-05T08:06:14Z" level=warning msg="QEMU binary \"/Users/runner/.colima/_wrapper/4e1b408f843d1c63afbbdcf80c40e4c88d33509f/bin/qemu-system-x86_64\" is not properly signed with the \"com.apple.security.hypervisor\" entitlement" error="failed to run [codesign --verify /Users/runner/.colima/_wrapper/4e1b408f843d1c63afbbdcf80c40e4c88d33509f/bin/qemu-system-x86_64]: exit status 1 (out=\"/Users/runner/.colima/_wrapper/4e1b408f843d1c63afbbdcf80c40e4c88d33509f/bin/qemu-system-x86_64: code object is not signed at all\\nIn architecture: x86_64\\n\")"
```
Implement workaround described in https://github.com/actions/runner-images/issues/8104
Tested fixing this bug only, there may be other bugs in the actual release which we can identify as new dev releases are done. …

ci: macos dashmate build broken due to bad qemu install

---

.github/actions/nodejs/action.yaml
.github/actions/rust/action.yaml

Actions using `everpcpc/actions-cache` were experiencing non-fatal errors when trying to access S3, slowing down actions:
```
Restore s3 cache failed: Error: Unexpected (permanent) at Pager::next, context: { response: Parts { status: 301, version: HTTP/1.1, headers: {"x-amz-bucket-region": "eu-west-1", "x-amz-request-id": "3WEXC0275TW606D3", "x-amz-id-2": "BQW9Imt05kUrseOe7TpuXwChVydDLjFl+/p3tpxbZiTZVJzyp/Mnm06R3hAAXkQBFcU+9nWT008=", "content-type": "application/xml", "transfer-encoding": "chunked", "date": "Tue, 12 Sep 2023 04:32:59 GMT", "server": "AmazonS3"} }, service: s3, path: Linux-yarn-unplugged-eef79a1fefecdfa2e3d63ea004871c480d656559c004f343a5fc34f32c02cd39/ } => S3Error { code: "PermanentRedirect", message: "The bucket you are attempting to access must be addressed using the …
```

ci: make actions-cache steps access S3 using the correct region

---

Cargo.lock
packages/rs-drive-abci/Cargo.toml
packages/rs-drive-abci/src/config.rs
packages/rs-drive-abci/src/logging.rs

Logrotate should send HUP signal to a service after rotating logs.
Service is expected to close the log file and reopen (recreate) it.
Implemented rotate() for LogDestination::File. 
Local devnet
None

feat(drive): reopen log file on HUP signal

---

packages/dashmate/src/config/configFile/ConfigFileJsonRepository.js

Config doesn't have newline at the end so when we render config with deployment tool with template that has newline we getting different file. In turn, this fact trigger restart of the whole dashmate on deploy.
- Added newline to config
None
None

fix(dashmate): config format is not conventional

---

packages/rs-dpp/src/identity/identity_public_key/contract_bounds/mod.rs

CborCanonicalMap is not used anymore in the contract bounds, but still being imported in the file, making applications fail to build rs-dpp when used externally.
```
warning: `platform-serialization-derive` (lib) generated 2 warnings
Compiling dpp v0.1.0 (/Users/pshenmic/WebstormProjects/platform/packages/rs-dpp)
error[E0432]: unresolved import `crate::util::cbor_value`
--> /Users/pshenmic/WebstormProjects/platform/packages/rs-dpp/src/identity/identity_public_key/contract_bounds/mod.rs:5:18
|
5 | use crate::util::cbor_value::{CborCanonicalMap, CborMapExtension};
|                  ^^^^^^^^^^ could not find `cbor_value` in `util`
```
Removed the crashing import line
Removing this line makes rs-dpp to succesfully compile when used in external Rust project
No
**For repository code-owners and …

style(dpp): remove unused cbor import

---

.github/actions/nodejs/action.yaml
.github/actions/rust/action.yaml

#1398 reverted #1391 without resolving the original issue
Add a condition the AWS login step so it only occurs on AWS self-hosted runner infra
In CI
None

ci: make self-hosted actions-cache steps access S3 from correct region

---

packages/dapi/lib/grpcServer/handlers/core/getTransactionHandlerFactory.js

Fixes bug with serializing of `GetTransactionResponse` for DAPI `getTransaction` handler
Implemented uint32 validation for fields
- CI

fix(dapi): getTransaction google-protobuf AssertionError

---

CHANGELOG.md
package.json
packages/bench-suite/package.json
packages/dapi-grpc/package.json
packages/dapi/package.json
packages/dash-spv/package.json
packages/dashmate/package.json
packages/dashpay-contract/package.json
packages/dpns-contract/package.json
packages/feature-flags-contract/package.json
packages/js-dapi-client/package.json
packages/js-dpp/package.json
packages/js-grpc-common/package.json
packages/masternode-reward-shares-contract/package.json
packages/platform-test-suite/package.json
packages/rs-dpp/Cargo.toml
packages/rs-drive-abci/Cargo.toml
packages/rs-drive/Cargo.toml
packages/wasm-dpp/package.json
packages/withdrawals-contract/package.json

chore: update to version 0.25.0-dev.30

---

Cargo.lock
packages/rs-drive/Cargo.toml
packages/rs-drive/src/drive/grove_operations/grove_clear/mod.rs
packages/rs-drive/src/drive/grove_operations/grove_clear/v0/mod.rs
packages/rs-drive/src/drive/grove_operations/mod.rs
packages/rs-drive/src/drive/protocol_upgrade/change_to_new_version_and_clear_version_information/v0/mod.rs
packages/rs-drive/src/drive/protocol_upgrade/clear_version_information/v0/mod.rs
packages/rs-platform-version/src/version/drive_versions.rs
packages/rs-platform-version/src/version/mocks/v2_test.rs
packages/rs-platform-version/src/version/mocks/v3_test.rs
packages/rs-platform-version/src/version/v1.rs

Previously we were querying all version votes and deleting them individually, this was very much not efficient. Now after this change the tree holding this information is just cleared.
Not a breaking change.

perf(drive): clear instead of delete for previous masternode version voting

---

packages/rs-drive-abci/src/execution/platform_events/core_based_updates/update_quorum_info/v0/mod.rs
packages/rs-drive-abci/src/execution/validation/state_transition/state_transitions/documents_batch/state/v0/fetch_documents.rs
packages/rs-drive-abci/src/rpc/core.rs
packages/rs-drive-abci/tests/strategy_tests/execution.rs

Logs aren't looking the same on different nodes that complicates comparison 
- Sort deterministically the new quorum info log output
- Removed unnecessary big log data
None
None

chore(drive): improve quorum info update logs

---

docs/DOCKER.md
docs/DRIVE-ABCI.md

docs(dashmate): typos in README

---

.github/workflows/pr.yml

Not all scopes were present in CI PR title check
Added Drive-Abci, Platform and CI scopes.
When to use them:
Drive-Abci: when the fix is only in Drive-Abci we should use that as a tag. Drive now would refer to the storage crate.
Platform: often when dealing with complex features or fixes, we need to make major modifications in dpp, drive and drive-abci. In this case we should set the scope Platform.
CI: If we are just changing actions or CI, the scope should be CI.

chore: increase scopes for ci

---

packages/dashmate/configs/defaults/getTestnetConfigFactory.js
packages/dashmate/configs/getConfigFileMigrationsFactory.js

Testnet the epoch time length is currently set to 3600 seconds (1 hour). Default value in dashmate is  788400 seconds (9.5 days). This setting affects consensus logic and must be equal otherwise, a dashmate testnet node will fail with wrong app hash result.
Anther issue that platform images weren't updated with migration in existing configs.
- Update the epoch time length in dashmate's testnet config
- Update platform images in existing configs
None
None

fix(dashmate): a testnet node fails to sync

---

packages/dashmate/README.md
packages/dashmate/src/commands/core/cli.js

Add a dashmate command to execute dash-cli commands in the core container. This is very useful, when you need to do something or check something with the dash-cli of the current node, but you have to use `docker exec -it..` instead.
* Added a cli command in the core folder
Locally
No

feat(dashmate): add cli command for core service

---

packages/dashmate/src/commands/status/index.js
packages/dashmate/src/commands/status/masternode.js
packages/dashmate/src/core/calculatePaymentQueuePosition.js
packages/dashmate/src/status/colors.js
packages/dashmate/src/status/scopes/masternode.js
packages/dashmate/src/templates/writeServiceConfigsFactory.js
packages/dashmate/test/unit/core/calculatePaymentQueuePosition.spec.js
packages/dashmate/test/unit/status/colors.spec.js
packages/dashmate/test/unit/status/scopes/masternode.spec.js

https://github.com/dashpay/platform/issues/1294
Extend `status masternode` command with detailed info about enabled and total nodes and fix payment queue calculation algorithm
* Removed enabledCount in masternode status scope
* Added masternodeEnabled, masternodeTotal, evonodeEnabled, evonodeTotal in the masternode status scope
* Fixed payment queue calculation algorithm (https://github.com/dashpay/dash/issues/5528)
Locally
* Removed `scope.nodeState.enabledCount` in `status masternode` (replaced with `scope.masternodeEnabled`

fix(dashmate)!: payment queue and extend enabled count

---

.github/actions/docker/action.yaml

Docker release action for drive was [failing](https://github.com/dashpay/platform/actions/runs/6587757850/job/17898654164) with ` #58 ERROR: failed to check file presence in cache: operation error S3: HeadObject, https response error StatusCode: 403, RequestID: 9VNRXCFQ8K9RYSTQ, HostID: nts8Mzz86NQp8cuWQIQXD66YifLHv8H9M344MUNmV/trDlo14kJNzygIoAvB7tv0hFLWofcliEBJ7utdUVI7nw==, api error Forbidden: Forbidden`
Ensure correct bucket is passed to layer cache configuration step
Untested
None

ci: fix s3 layer cache access forbidden on 8x runners

---

packages/dashmate/configs/defaults/getBaseConfigFactory.js
packages/dashmate/configs/getConfigFileMigrationsFactory.js
packages/dashmate/src/listr/tasks/setup/setupLocalPresetTaskFactory.js

The debug level is too verbose for tenderdash container. Continuation of https://github.com/dashpay/tenderdash/pull/690
- Set default tenderdash logging level to info
None
None

chore(dashmate): set tenderdash logging level to info

---

packages/dashmate/src/commands/config/get.js
packages/dashmate/src/commands/group/reset.js
packages/dashmate/src/listr/tasks/resetNodeTaskFactory.js

The reset command with the hard flag doesnt persit configs are resetting
- Removed duplicated the config removal logic
- Perstit configs after resetting
- Output full config value with the config get command 
Manually
None

fix(dashmate): reset command doesn't reset configs

---

packages/rs-dpp/src/identity/state_transition/asset_lock_proof/instant/instant_asset_lock_proof.rs
packages/rs-dpp/src/identity/state_transition/asset_lock_proof/instant/methods/mod.rs
packages/rs-dpp/src/identity/state_transition/asset_lock_proof/instant/methods/validate_structure/mod.rs
packages/rs-dpp/src/identity/state_transition/asset_lock_proof/instant/methods/validate_structure/v0/mod.rs
packages/rs-dpp/src/identity/state_transition/asset_lock_proof/instant/mod.rs
packages/rs-platform-version/src/version/dpp_versions.rs
packages/rs-platform-version/src/version/mocks/v2_test.rs
packages/rs-platform-version/src/version/mocks/v3_test.rs
packages/rs-platform-version/src/version/v1.rs

Validate structure contains consensus logic and should be versioned. A todo to do so was introduced in #1510 and this PR is follow-up with the todo implemented 
- Version `InstantAssetLockProof.validate_structure` method
None
None

chore(dpp): version `InstantAssetLockProof.validate_structure`

---

packages/dashmate/src/listr/tasks/ssl/zerossl/obtainZeroSSLCertificateTaskFactory.js

The obtain command uses outdated SSL certificates path.
- Use updated SSL certificates path
None
None

fix(dashmate): invalid SSL path in the obtain command

---

packages/dashmate/src/commands/config/get.js
packages/dashmate/src/commands/config/index.js

Recently, there was a change in the config get command to print entire objects and arrays. This change has a side effect: strings are returning with quotes.
- Use colorized pretty print only for arrays and objects
- Added the format option to `config` and `config get` commands to output valid JSON. 
Manually
None

fix(dashmate): config commands output

---

packages/rs-dpp/src/errors/consensus/basic/basic_error.rs
packages/rs-dpp/src/errors/consensus/basic/document/document_transitions_are_absent_error.rs
packages/rs-dpp/src/errors/consensus/basic/document/mod.rs
packages/rs-dpp/src/errors/consensus/codes.rs
packages/rs-dpp/src/state_transition/state_transitions/document/documents_batch_transition/validation/validate_base_structure/v0/mod.rs
packages/wasm-dpp/src/errors/consensus/basic/document/document_transitions_are_absent_error.rs
packages/wasm-dpp/src/errors/consensus/basic/document/mod.rs

We potentually have an issue, processing multiple document transition in Drive ABCI
- Allow 1 document max
- Return a consenus error if there are no transitions
None
Validation rules for DocumentBatchTransition is changed so previous block result is no valid anymore

chore(dpp)!: allow only one document transition

---

packages/dashmate/configs/defaults/getBaseConfigFactory.js
packages/dashmate/configs/getConfigFileMigrationsFactory.js
packages/dashmate/scripts/helper.js
packages/dashmate/src/commands/config/create.js
packages/dashmate/src/commands/config/index.js
packages/dashmate/src/commands/config/remove.js
packages/dashmate/src/commands/config/set.js
packages/dashmate/src/config/Config.js
packages/dashmate/src/config/configFile/ConfigFile.js
packages/dashmate/src/config/configFile/ConfigFileJsonRepository.js
packages/dashmate/src/config/configFile/createConfigFileFactory.js
packages/dashmate/src/createDIContainer.js
packages/dashmate/src/helper/scheduleRenewZeroSslCertificateFactory.js
packages/dashmate/src/listr/tasks/resetNodeTaskFactory.js
packages/dashmate/src/listr/tasks/setup/local/configureCoreTaskFactory.js
packages/dashmate/src/listr/tasks/setup/local/configureTenderdashTaskFactory.js
packages/dashmate/src/listr/tasks/setup/setupLocalPresetTaskFactory.js
packages/dashmate/src/listr/tasks/setup/setupRegularPresetTaskFactory.js
packages/dashmate/src/oclif/command/BaseCommand.js
packages/dashmate/src/templates/writeConfigTemplatesFactory.js
packages/dashmate/test/e2e/localNetwork.js
packages/dashmate/test/e2e/testnetFullnode.spec.js
packages/dashmate/test/e2e/testnetHPFullnode.spec.js
packages/dashmate/test/unit/commands/config/set.spec.js

When dashmate migrate config to the new version, it should be persist back to disk, but it's not. So dashmate migrate config every command call without actual effect of this migration.
There are few commands that mutate config. It should be persisted in this case too.
- Keep status of changes for configs and config file
- Persist config file if changed
- Render templates for a config if  it was changed
None
None

fix(dashmate): config is not persisted after migration

---

packages/bench-suite/README.md
packages/dapi/README.md
packages/dashmate/README.md
packages/dashmate/src/constants.js
packages/dashmate/src/listr/prompts/formatters/formatPercentage.js
packages/dashmate/src/templates/renderServiceTemplatesFactory.js
packages/dashmate/src/update/updateNodeFactory.js

Dashmate contains import * as imports that are not working quite correctly leading to two errors:
* dashmate setup: `at SelectPrompt.reset (/home/me/.nvm/versions/node/v20.9.0/lib/node_modules/dashmate/node_modules/enquirer/lib/types/array.js:38:13)`
* dashmate update: `TypeError: _.uniqBy is not a function`
* Replaced `import * as from` in the code where its possible
* Updated few missing node.js 20 mentions in the docs
Locally + CI
No

fix(dashmate): incorrect imports 

---

Cargo.lock
packages/dashmate/configs/defaults/getBaseConfigFactory.js
packages/rs-drive-abci/Cargo.toml
packages/rs-drive-abci/src/abci/handler/mod.rs
packages/rs-drive-abci/src/mimic/mod.rs
packages/rs-drive-abci/tests/strategy_tests/core_update_tests.rs
packages/rs-drive-abci/tests/strategy_tests/execution.rs
packages/rs-drive-abci/tests/strategy_tests/failures.rs
packages/rs-drive-abci/tests/strategy_tests/main.rs
packages/rs-drive-abci/tests/strategy_tests/query.rs
packages/rs-drive-abci/tests/strategy_tests/strategy.rs
packages/rs-drive-abci/tests/strategy_tests/upgrade_fork_tests.rs
packages/strategy-tests/src/lib.rs

PR changes `prepare_proposal` logic in `rs-drive-abci` related to transactions related response:
- If amount of transactions exceeded `max_tx_bytes` setting, they never get executed but remain in `tx_records` vector
- If some of the transactions are failed during the execution, they remain in `tx_records`, but not added to `tx_results`
- Updated `prepare_proposal` logic
- Refactored `NetworkStrategy` and `Strategy` structs in strategy tests to support default value
- Added strategy test to cover max block size excession case
- Updated existing strategy test covering failure scenario for one of the state transitions
- CI

fix(drive): filtering of failed and exceeding limit transactions

---

packages/rs-dpp/src/identity/state_transition/mod.rs
packages/rs-dpp/src/state_transition/mod.rs
packages/rs-dpp/src/state_transition/state_transitions/contract/data_contract_create_transition/mod.rs
packages/rs-dpp/src/state_transition/state_transitions/contract/data_contract_update_transition/mod.rs
packages/rs-dpp/src/state_transition/state_transitions/document/documents_batch_transition/mod.rs
packages/rs-dpp/src/state_transition/state_transitions/identity/identity_create_transition/proved.rs
packages/rs-dpp/src/state_transition/state_transitions/identity/identity_create_transition/state_transition_like.rs
packages/rs-dpp/src/state_transition/state_transitions/identity/identity_create_transition/v0/state_transition_like.rs
packages/rs-dpp/src/state_transition/state_transitions/identity/identity_credit_transfer_transition/mod.rs
packages/rs-dpp/src/state_transition/state_transitions/identity/identity_credit_withdrawal_transition/mod.rs
packages/rs-dpp/src/state_transition/state_transitions/identity/identity_topup_transition/proved.rs
packages/rs-dpp/src/state_transition/state_transitions/identity/identity_topup_transition/state_transition_like.rs
packages/rs-dpp/src/state_transition/state_transitions/identity/identity_topup_transition/v0/state_transition_like.rs
packages/rs-dpp/src/state_transition/state_transitions/identity/identity_update_transition/mod.rs
packages/rs-dpp/src/state_transition/traits/state_transition_like.rs
packages/rs-drive-abci/src/execution/validation/state_transition/check_tx_verification/v0/mod.rs

refactor: move asset_lock method from StateTransitionLike trait

---

packages/dashmate/templates/platform/drive/tenderdash/config.toml.dot

There are always few transaction that was already included in a bock before and marked as invalid apperaing on other nodes after that block was finaized means they won't be removed. With a big network the number of such ghost invalid transactions in growing and ping ponging between nodes. We shouldn't allow to broadcast already invaidated txs
- Enable cache for invaid txs to prevent propagain of them
We had this setting on a month ago and we didn't notice any ghost transactions
None

fix: broadcasting already invalidated transitions

---

packages/dashmate/configs/defaults/getBaseConfigFactory.js
packages/dashmate/configs/defaults/getTestnetConfigFactory.js
packages/dashmate/configs/getConfigFileMigrationsFactory.js

We use default consensus timeouts for local and 0.24-based values for testnet. Re-check is not set so it's initializing as false. We have already more or less tested values and we need re-check to clean up mempool from unpaid invalid txs
- set consensus timeouts
- adjust some other values
- enable re-check
On devnet and locally by @lklimek 
It will be a breaking change for any network since genesis params are changed

chore(dashmate)!: adjust consensus params and enable re-check

---

packages/dapi/lib/grpcServer/handlers/platform/broadcastStateTransitionHandlerFactory.js
packages/dapi/test/unit/grpcServer/handlers/platform/broadcastStateTransitionHandlerFactory.spec.js

When Tenderdash under heavy load DAPI fails to connect to it to broadcast a state transition and fails with the `socket hang up` error. We also need to handle a new check tx timeout introduced in tenderdash.
- handle the `socket hang up` error and return the unavailable error code.
- handle `broadcast confirmation not received` error
- update tests
None
None

fix(dapi): internal errors if broadcasting failed

---

.github/actions/rust/action.yaml
Dockerfile
README.md

rs-tenderdash-abci uses "optional" field that requires quite recent version of protoc.
Updated protoc to 25.2
github actions + local Docker build
protoc 25.2+ is required to build

build: bump protoc to 25.2

---

packages/rs-drive-proof-verifier/src/proof.rs
packages/rs-sdk/src/mock/sdk.rs
packages/rs-sdk/src/platform/delegate.rs
packages/rs-sdk/src/platform/document_query.rs
packages/rs-sdk/src/platform/fetch.rs
packages/rs-sdk/src/platform/types/identity.rs
packages/rs-sdk/src/sdk.rs

When fetching through the SDK there was no way to get information about platform that exists in the response metadata such as block height.
Added a method fetch_with_metadata that also returns response metadata.
Ran tests
None

feat(sdk): fetch with metadata

---

packages/rs-drive/src/drive/batch/transitions/mod.rs
packages/rs-drive/src/drive/contract/contract_fetch_info.rs
packages/rs-drive/src/drive/contract/prove/prove_contract/v0/mod.rs
packages/rs-drive/src/drive/identity/contract_info/identity_contract_nonce/fetch_identity_contract_nonce/v0/mod.rs
packages/rs-drive/src/drive/identity/contract_info/identity_contract_nonce/merge_identity_contract_nonce/mod.rs
packages/rs-drive/src/drive/identity/contract_info/identity_contract_nonce/merge_identity_contract_nonce/v0/mod.rs
packages/rs-drive/src/drive/identity/estimation_costs/for_identity_contract_info_group/v0/mod.rs
packages/rs-drive/src/drive/identity/estimation_costs/for_identity_contract_info_group_keys/v0/mod.rs
packages/rs-drive/src/drive/identity/fetch/nonce/prove_identity_nonce/mod.rs
packages/rs-drive/src/drive/identity/fetch/queries/mod.rs
packages/rs-drive/src/drive/identity/update/methods/merge_identity_nonce/v0/mod.rs
packages/rs-drive/src/drive/identity/update/operations/initialize_identity_nonce_operation/v0/mod.rs
packages/rs-drive/src/drive/identity/update/operations/merge_identity_nonce_operations/v0/mod.rs
packages/rs-drive/src/drive/verify/identity/verify_identity_keys_by_identity_id/v0/mod.rs
packages/rs-drive/src/state_transition_action/document/documents_batch/document_transition/mod.rs
packages/rs-drive/src/state_transition_action/identity/identity_credit_transfer/mod.rs
packages/rs-drive/src/state_transition_action/identity/identity_credit_transfer/v0/mod.rs
packages/rs-drive/src/state_transition_action/identity/identity_credit_withdrawal/mod.rs
packages/rs-drive/src/state_transition_action/identity/identity_credit_withdrawal/v0/mod.rs
packages/rs-drive/src/state_transition_action/system/bump_identity_data_contract_nonce_action/mod.rs
packages/rs-drive/src/state_transition_action/system/bump_identity_data_contract_nonce_action/transformer.rs

Reduce cargo clips warnings in rs-platform
372 - 342 = 30 warnings resolved
```
Before
> $ cargo clippy 2>&1 | grep -i "warning" | wc -l
372
After
> $ cargo clippy 2>&1 | grep -i "warning" | wc -l
342
```
cargo b and cargo t in rs-drive
None

refactor: reduce cargo clippy warnings

---

packages/strategy-tests/Cargo.toml

introduced in #1729
```
> cargo t
error[E0599]: no method named `create_data_contract_create_transition` found for enum `DataContractFactory` in the current scope
--> packages/strategy-tests/src/lib.rs:1186:34
|
1185 |   ...                   let transition = match contract_factory
|  ______________________________________________-
1186 | | ...                       .create_data_contract_create_transition(created_data_contract)
| |                           -^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ method not found in `DataContractFactory`
| |___________________________|
|
```
strategy-tests relies on rs-dpp; the usage of create_data_contract_create_transition requires features "client" and "state-transitions"
these weren't present; add them to Cargo.toml
cargo t in root and strategy-tests …

fix: resolve strategy-tests test failures

---

packages/strategy-tests/src/lib.rs

Contracts registered on the first block of a strategy get a new random id, and if we want to register documents to these new contracts in the same strategy, we need to update the document transitions with the new id.
Update the document transitions from `operations` with the new contract ids from contracts_with_updates. There's a corresponding PR in rs-platform-explorer. Now we can register documents to contracts that are created within the same strategy.
Platform TUI strategy tests

fix: update strategy test document transitions with initial contract ids

---

packages/rs-drive-proof-verifier/src/verify.rs
packages/rs-drive/src/drive/grove_operations/grove_apply_batch/mod.rs
packages/rs-drive/src/drive/grove_operations/grove_apply_partial_batch/mod.rs

Fix compilation warnings
Fix them; @lklimek stated we should indeed use calculate_sign_hash
Build locally
None

refactor: drop unused includes; use calculate_sign_hash

---

Cargo.lock
packages/dapi-grpc/Cargo.toml
packages/dashmate/configs/defaults/getBaseConfigFactory.js
packages/dashmate/configs/defaults/getTestnetConfigFactory.js
packages/dashmate/configs/getConfigFileMigrationsFactory.js
packages/dashmate/src/config/configJsonSchema.js
packages/dashmate/templates/platform/drive/tenderdash/config.toml.dot
packages/rs-dpp/Cargo.toml
packages/rs-drive-abci/Cargo.toml
packages/rs-drive-abci/src/abci/app/execution_result.rs
packages/rs-drive-proof-verifier/Cargo.toml
packages/rs-drive/Cargo.toml

Update Platform to most recent Tenderdash version
- Updated Tenderdash docker image in dashmate
- Added new configuration options to dashmate:
- `platform.drive.tenderdash.mempool.timeoutCheckTx`
- `options.platform.drive.tenderdash.mempool.txEnqueueTimeout`
- `options.platform.drive.tenderdash.mempool.txSendRateLimit`
- `options.platform.drive.tenderdash.mempool.txRecvRateLimit`
- `options.platform.drive.tenderdash.rpc.timeoutBroadcastTx`
- Configured tenderdash for testnet according to load test results
- Updated Tenderdash ABCI library
None
ExecTxResult doesn't contain `gas_wanted` field anymore so it previous blockchain data most probably won't be valid

chore!: update tenderdash to 0.14-dev.4

---

packages/rs-drive-abci/src/error/execution.rs
packages/rs-drive-abci/src/execution/engine/finalize_block_proposal/v0/mod.rs
packages/rs-drive-abci/src/execution/platform_events/block_end/validator_set_update/v0/mod.rs
packages/rs-drive-abci/src/execution/platform_events/core_based_updates/update_masternode_identities/update_operator_identity/v0/mod.rs
packages/rs-drive-abci/src/execution/platform_events/core_based_updates/update_masternode_identities/update_voter_identity/v0/mod.rs
packages/rs-drive-abci/src/execution/validation/state_transition/state_transitions/identity_update/structure/v0/mod.rs
packages/rs-drive-abci/src/platform_types/platform/mod.rs
packages/rs-drive-abci/src/platform_types/platform_state/v0/mod.rs
packages/rs-drive-abci/src/platform_types/validator_set/v0/mod.rs

This PR https://github.com/dashpay/platform/pull/1733 introduced a bug that is described in this document: https://docs.google.com/document/d/10VkH30CuRmNXLGOJsdS5hvIKjtzDniPsFL3mG6ymTLw
Basically we were using updated validator sets and trying to find the current quorum by hash inside of them. But it might have been dropped.
Using the current validator sets in state instead of block state to find the current quorum by hash.

fix(platform): wrong state used to get current validator set

---

.github/workflows/tests-rs-package.yml
packages/rs-dpp/src/data_contract/document_type/class_methods/try_from_schema/v0/mod.rs
packages/rs-dpp/src/document/serialization_traits/platform_serialization_conversion/v0/mod.rs
packages/rs-dpp/src/document/v0/serialize.rs
packages/rs-dpp/src/state_transition/state_transitions/document/documents_batch_transition/methods/mod.rs
packages/rs-dpp/src/state_transition/state_transitions/document/documents_batch_transition/methods/v0/mod.rs
packages/rs-dpp/src/state_transition/state_transitions/document/documents_batch_transition/v0/v0_methods.rs
packages/rs-dpp/src/state_transition/state_transitions/identity/identity_update_transition/v0/v0_methods.rs
packages/rs-drive-abci/src/main.rs
packages/rs-drive-abci/src/utils/spawn.rs
packages/rs-drive-abci/tests/strategy_tests/strategy.rs
packages/rs-drive/src/common/mod.rs
packages/rs-drive/src/drive/batch/transitions/contract/data_contract_create_transition.rs
packages/rs-drive/src/drive/contract/contract_fetch_info.rs
packages/rs-drive/src/drive/credit_pools/mod.rs
packages/rs-drive/src/drive/document/mod.rs

Enforce warnings as errors in CI
Enforce warnings as errors; and fix a few more warnings
Running cargo check --tests locally in root; and cargo hack check
None

ci: enforce warnings as errors

---

packages/dapi/lib/grpcServer/handlers/platform/broadcastStateTransitionHandlerFactory.js
packages/dapi/test/unit/grpcServer/handlers/platform/broadcastStateTransitionHandlerFactory.spec.js

Replaced `broadcas_tx_sync` Tednerdash call with `broadcast_tx` in DAPI.
Currently, `broadcas_tx_sync` is an alias to `broadcas_tx` call in Tenderdash. 
@lklimek deprecates it. 

feat(dapi): use broadcast_tx instead of deprecated broadcast_tx_sync

---

packages/rs-dpp/src/data_contract/document_type/class_methods/try_from_schema/v0/mod.rs
packages/rs-dpp/src/data_contract/document_type/v0/random_document_type.rs
packages/rs-dpp/src/errors/consensus/basic/basic_error.rs
packages/rs-dpp/src/errors/consensus/basic/data_contract/invalid_document_type_name_error.rs
packages/rs-dpp/src/errors/consensus/basic/data_contract/mod.rs
packages/rs-dpp/src/errors/consensus/codes.rs
packages/rs-drive-abci/tests/strategy_tests/strategy.rs
packages/strategy-tests/src/lib.rs
packages/wasm-dpp/src/errors/consensus/basic/data_contract/invalid_document_type_name_error.rs
packages/wasm-dpp/src/errors/consensus/basic/data_contract/mod.rs
packages/wasm-dpp/src/errors/consensus/consensus_error.rs

Previously, when we used JSON Schema for the entire Data Contract we validated the document type name to ensure it's not empty and doesn't use special chars. When we migrated to document type-based JSON schemas this check was lost.
- Added validation to ensure the name is 1 to 64 alphanumeric chars and "_", or "-". 
With unit test
Document type name must be 1 to 64 alphanumeric chars and "_", or "-".  Previously created data might be invalid.

feat(dpp)!: validate document type name

---

Cargo.lock
packages/rs-drive/Cargo.toml
packages/rs-sdk/src/lib.rs

Full Grovedb was being built even when we were asking for only compiling the verify feature. This now fixes this.

fix(drive): no longer build full grovedb when using verify feature

---

Cargo.lock
packages/rs-dapi-client/Cargo.toml
packages/rs-dapi-client/src/address_list.rs
packages/rs-dapi-client/src/connection_pool.rs
packages/rs-dapi-client/src/dapi_client.rs
packages/rs-dapi-client/src/lib.rs
packages/rs-dapi-client/src/transport.rs
packages/rs-dapi-client/src/transport/grpc.rs

We establish new connection to DAPI for every request. This has significant impact on performance.
Implemented connection pool that allows reuse of clients.
At his point, the connection pool uses LRU (least-recently used) algorithm to evict unused peers.
1. Run rs-sdk tests in network mode.
2. Tested on testnet using `load_test` from rs-platform-explorer.
None

feat(sdk): reuse dapi connections

---

Cargo.lock
packages/dapi-grpc/Cargo.toml

When connecting to testnet (which requires https), the following happens:
```
Transport(Status { code: Unknown, message: "h2 protocol error: http2 error: connection error detected: frame with invalid size", source: Some(tonic::transport::Error(Transport, hyper::Error(Http2, Error { kind: GoAway(b"", FRAME_SIZE_ERROR, Library) 
```
Everything works fine for local networks.
Restored tonic/tls and tonic/tls-roots features, removed from dapi-grpc Cargo.toml.
Using rs-platform-explorer against testnet.
TODO: check if this is compatible with Android/iOS.

fix(sdk): cannot connect to testnet due to FRAME_SIZE_ERROR

---

Cargo.lock
packages/dapi-grpc/Cargo.toml
packages/rs-dapi-client/src/connection_pool.rs
packages/rs-dapi-client/src/transport/grpc.rs
packages/strategy-tests/src/lib.rs

Connection pool should distinguish between Core and Platform connections
Added prefix to key in connection pool, describing type of connection (Core or Platform) to use.
Tested using rs-platform-explorer strategy tests against testnet.
None

fix(sdk): dapi client pool should separate platform and core clients

---

packages/rs-drive-abci/src/error/execution.rs
packages/rs-drive-abci/src/execution/engine/finalize_block_proposal/v0/mod.rs
packages/rs-drive-abci/src/execution/platform_events/withdrawals/append_signatures_and_broadcast_withdrawal_transactions/v0/mod.rs

If a withdrawal failed, platform chain would halt.
Failed withdrawals that are already signed are saved to disk instead of causing Platform to stall.

fix(platform)!: a withdrawal failure from core should never cause platform to stop

---

Dockerfile
packages/rs-drive-abci/.env.local
packages/rs-drive-abci/.env.mainnet
packages/rs-drive-abci/.env.testnet
packages/rs-drive-abci/src/config.rs
packages/rs-drive-abci/src/execution/platform_events/withdrawals/append_signatures_and_broadcast_withdrawal_transactions/v0/mod.rs

In #1821, we store failed transactions on disk. However, the location should be configurable.
1. Added config variable, REJECTIONS_PATH, that points to directory where rejected transactions should be saved.
2. Using REJECTIONS_PATH in `store_transaction_failures()`
3. Set default `REJECTIONS_PATH=/var/log/dash/rejected` in Docker
Modified check_tx to dump every tx, then started local network and verified that files are stored in /var/log/dash/rejected
None

feat(drive-abci): configure dir to store rejected txs

---

Cargo.lock
packages/dapi-grpc/Cargo.toml

It was found that on Android, there were TLS connection errors.  After investigating this issue was found with `tonic`
https://github.com/hyperium/tonic/issues/1403.
The solution is to add the feature `tonic/tls-webpki-roots` to the `dapi-grpc` crate.  
This change was verified on Android and Mac, though in both cases using C Bindings generated by Ferment and run using Java.
None

fix: add tls-webpki-roots to support tls on mobile (Android, iOS)

---

packages/dashmate/configs/defaults/getBaseConfigFactory.js
packages/dashmate/configs/getConfigFileMigrationsFactory.js
packages/dashmate/src/config/configJsonSchema.js
packages/dashmate/templates/platform/drive/tenderdash/config.toml.dot

To protect Drive from overwhelming number of check tx ABCI calls in case of stress testing or an attack, we need limit max concurrent check tx calls in Tenderdash https://github.com/dashpay/tenderdash/pull/775
- Update tenderdash to a version that supports check tx concurrency limiting
- Add `platform.drive.tenderdash.mempool.maxConcurrentCheckTx` option to dashmate
Broadcasting transactions to local network
None

chore(dashmate): limit concurrent state transition checks

---

packages/rs-dapi-client/src/dapi_client.rs
packages/rs-sdk/examples/read_contract.rs
packages/rs-sdk/src/mock.rs
packages/rs-sdk/src/mock/provider.rs
packages/rs-sdk/src/mock/sdk.rs
packages/rs-sdk/src/platform/fetch.rs
packages/rs-sdk/src/platform/fetch_many.rs
packages/rs-sdk/src/sdk.rs
packages/rs-sdk/tests/fetch/broadcast.rs
packages/rs-sdk/tests/fetch/config.rs
packages/rs-sdk/tests/fetch/mock_fetch.rs
packages/rs-sdk/tests/fetch/mock_fetch_many.rs

Based on team's feedback, it's not a good idea to return Arc<Sdk> from SdkBuilder::build().
Refactored the code to:
* return Sdk from SdkBuilder::build()
* implement `Clone` on `Sdk` and make Sdk internally thread-safe
Accompanying PR: https://github.com/dashpay/rs-platform-explorer/pull/48
GHA
SdkBuilder::build() now returns Sdk instead of Arc<Sdk>.

refactor(sdk)!: don't return Arc in SdkBuilder

---

packages/rs-dpp/src/data_contract/config/methods/mod.rs
packages/rs-dpp/src/data_contract/config/methods/validate_update/mod.rs
packages/rs-dpp/src/data_contract/config/methods/validate_update/v0/mod.rs
packages/rs-drive-abci/src/execution/validation/state_transition/state_transitions/data_contract_update/state/v0/mod.rs

DataContract related structures has method `validate_update` to validate  compartiblity as a part of Data Contract Update transition validation. For example, `DocumentTypeRef.validate_update`. There are more introduced in https://github.com/dashpay/platform/pull/1835. To keep consistent naming and remove repetition of meaning we need to rename DataContract**Config**.validate_**config**_update
- Renamed `DataContractConfig.validate_config_update` to `DataContractConfig.validate_update`
None
None

refactor: rename `DataContractConfig.validate_config_update`

---

packages/rs-dpp/src/data_contract/document_type/random_document.rs
packages/strategy-tests/src/lib.rs

Identities would broadcast documents into the mempool successfully but the transitions would potentially fail while in the mempool if the identity put more than 24 documents for a contract in, due to nonce errors.
Pass a BTreeMap of (IdentityID, ContractID) to u64 which acts as a counter for how many documents an identity has put into the mempool for a contract. If the number is 24 or greater, we don't use that identity.

feat: implement mempool document counter in strategy tests

---

.github/actions/javy/action.yaml
.github/workflows/tests-rs-package.yml
packages/rs-dpp/src/data_contract/document_type/v0/random_document.rs

`json-schema-faker-rs` dependency of dpp, introduced in #1710 , requires `javy` and npm to build.
As our tests test each individual dependency, we need to install it whenever using that dep.
Install `javy` and `nodejs` dependency when testing/linting/checking features of `dpp`.
1. In [lint](https://github.com/dashpay/platform/actions/runs/9189663301/job/25272219164?pr=1853), [test](https://github.com/dashpay/platform/actions/runs/9189663301/job/25272219790?pr=1853) and [check each feature](https://github.com/dashpay/platform/actions/runs/9189663301/job/25272219375?pr=1853) of DPP, nodejs and javy are installed correctly:  
2. When testing other packages, nodejs and javy are skipped: https://github.com/dashpay/platform/actions/runs/9189663301/job/25272216994?pr=1853 
3. GHA pipeline is …

ci: install javy and npm for json-schema-faker-rs dependency

---

.github/actions/javy/action.yaml
.github/workflows/tests-rs-package.yml
Cargo.lock
packages/rs-dapi-grpc-macros/src/lib.rs
packages/rs-dpp/Cargo.toml
packages/rs-dpp/src/data_contract/document_type/random_document.rs
packages/rs-dpp/src/data_contract/document_type/v0/random_document.rs

Adds a method under a feature flag for `DocumentType` to generate random documents using `json-schema-faker-rs` solution
Since jsonschema taken from `DocumentType` is not fully defined at one place as a self-contained schema, this PR wraps a json-schema-faker-rs part into manual tweaks to be able to go from json-schema-faker-rs output to an actual `Document`.
There is a test.

feat(dpp): random documents based on JSON schema

---

packages/rs-sdk/src/platform/transition/put_identity.rs

put_to_platform_and_wait_for_response() doesn't return correct error when `broadcast_request_for_new_identity` fails, but it waits until timeout.
Added return when error occurs
Using rs-platform explorer, patched to use invalid asset lock private key when creating identity in `Wallet > Register identity`.
BEFORE the fix, `Wallet > Register identity` waits until timeout and then errors with:
```
|>SDK error: Dapi client error: Transport(Status { code: Cancelled, message: "Timeout expired", source:           │
│ Some(tonic::transport::Error(Transport, TimeoutExpired(()))) }, Address { ban_count: 0, banned_until: None,     │
│ uri: http://127.0.0.1:2643/ })                                                                                  │
│                                     
```
AFTER the …

fix(sdk): invalid error returned when identity create fails

---

packages/dapi/lib/chainDataProvider/ChainDataProvider.js
packages/dapi/lib/grpcServer/handlers/blockheaders-stream/subscribeToBlockHeadersWithChainLocksHandlerFactory.js
packages/dapi/lib/grpcServer/handlers/tx-filter-stream/subscribeToTransactionsWithProofsHandlerFactory.js
packages/dapi/scripts/core-streams.js
packages/dapi/test/unit/grpcServer/handlers/blockheaders-stream/subscribeToBlockHeadersWithChainLocksHandlerFactory.spec.js
packages/dapi/test/unit/grpcServer/handlers/tx-filter-stream/subscribeToTransactionsWithProofsHandlerFactory.spec.js

In order to reduce amount of Core RPC calls (which is slow), we should use already available chain height.
- Use height from `ChainDataProvider` instead of calling `getBestBlockHeight` every request in `subscribeToTransactionsWithProofs` and `subscribeToBlockHeadersWithChainLocks`
Updated tests
None

perf(dapi): use cached core height in streaming endpoints

---

packages/dapi/lib/rpcServer/commands/getBestBlockHash.js
packages/dapi/lib/rpcServer/server.js
packages/dapi/scripts/api.js
packages/dapi/test/unit/rpcServer/commands/getBestBlockHash.spec.js

Core RPC work queue has limited size. We should do as less RPC calls as possible.
- Cached `getBestBlockHash` response for one Core block
Updated tests
None

perf(dapi): cache `getBestBlockHash` endpoint

---

packages/rs-dpp/src/data_contract/mod.rs
packages/rs-dpp/src/validation/json_schema_validator/mod.rs
packages/rs-dpp/src/validation/mod.rs

DataContractFactory and JsonSchemaValidator were not public and I need them in data-contract-creator.
Made them public.
dashpay.io

chore(dpp): make data contract factory and json schema validator public

---

.yarnrc.yml

```
├─ @grpc/grpc-js
│  ├─ ID: 1097505
│  ├─ Issue: @grpc/grpc-js can allocate memory for incoming messages well above configured limits
│  ├─ URL: https://github.com/advisories/GHSA-7v5v-9h63-cj86
│  ├─ Severity: moderate
│  ├─ Vulnerable Versions: <1.8.22
│  │ 
│  ├─ Tree Versions
│  │  └─ 1.4.4
│  │ 
│  └─ Dependents
│     └─ @dashevo/dapi@workspace:packages/dapi
│
├─ @humanwhocodes/config-array
│  ├─ ID: @humanwhocodes/config-array (deprecation)
│  ├─ Issue: Use @eslint/config-array instead
│  ├─ Severity: moderate
│  ├─ Vulnerable Versions: 0.11.13
│  │ 
│  ├─ Tree Versions
│  │  └─ 0.11.13
│  │ 
│  └─ Dependents
│     └─ eslint@npm:8.53.0
│
├─ @humanwhocodes/object-schema
│  ├─ ID: @humanwhocodes/object-schema (deprecation)
│  ├─ Issue: Use @eslint/object-schema instead
│  ├─ …
```

chore: mute NPM audit warnings

---

packages/rs-dpp/src/data_contract/document_type/class_methods/try_from_schema/v0/mod.rs
packages/rs-dpp/src/errors/consensus/basic/basic_error.rs
packages/rs-dpp/src/errors/consensus/basic/data_contract/contested_unique_index_on_mutable_document_type_error.rs
packages/rs-dpp/src/errors/consensus/basic/data_contract/mod.rs
packages/rs-dpp/src/errors/consensus/basic/data_contract/unique_indices_limit_reached_error.rs
packages/rs-platform-version/src/version/dpp_versions.rs

Extra validation that there can only be one contested unique index, and that we can only have a contested unique index when the document type is non mutable.

fix: contested unique indexes can only be on non mutable document types

---

packages/rs-dpp/src/data_contract/document_type/property/mod.rs
packages/rs-drive-abci/src/execution/validation/state_transition/state_transitions/masternode_vote/mod.rs
packages/rs-drive-abci/src/query/voting/contested_resources/v0/mod.rs
packages/rs-drive/src/drive/contract/insert/insert_contract/v0/mod.rs
packages/rs-drive/src/drive/document/insert_contested/add_contested_indices_for_contract_operations/v0/mod.rs
packages/rs-drive/src/drive/document/mod.rs
packages/rs-drive/src/drive/shared_estimation_costs/add_estimation_costs_for_contested_document_tree_levels_up_to_contract/v0/mod.rs
packages/rs-drive/src/drive/votes/paths.rs
packages/rs-drive/src/drive/votes/storage_form/contested_document_resource_storage_form/mod.rs
packages/rs-drive/src/query/vote_polls_by_document_type_query.rs

Fixes a bug where empty index values would conflict with document storage.
Added indexes to a subtree for safety
Added some tests

fix: contested resources query fixes

---

packages/dashmate/src/helper/scheduleRenewZeroSslCertificateFactory.js

Dashmate helper stuck during SSL renewal in case of error due to interactive prompt.
```
Creating user dashmate (1001)
Group exist: ping 999
Adding dashmate to group ping
Starting with UID: 1001, GID: 1001, USER: dashmate, GROUP: ping
Starting dashmate helper
SSL certificate 29b6eb5a0e94592aa9d02ad113f92f24 will expire at Mon Jun 17 2024 23:59:59 GMT+0000 (Coordinated Universal Time). Schedule to obtain at Fri Jun 14 2024 23:59:59 GMT+0000 (Coordinated Universal Time).
Dashmate JSON-RPC API started on port 9000
[STARTED] Check if certificate already exists and not expiring soon
[DATA] Certificate exists but expires in less than 3 days at Mon Jun 17 2024 23:59:59 GMT+0000 (Coordinated Universal Time). Obtain a new one
[SUCCESS] Check if certificate already exists and not expiring soon …
```

fix(dashmate): background SSL renewal stuck on error

---

packages/rs-dpp/src/data_contract/document_type/class_methods/try_from_schema/v0/mod.rs
packages/rs-dpp/src/data_contract/document_type/property/mod.rs
packages/rs-dpp/src/data_contract/document_type/schema/find_identifier_and_binary_paths/v0/mod.rs
packages/rs-dpp/src/data_contract/document_type/v0/random_document_type.rs
packages/rs-dpp/src/data_contract/errors/contract.rs
packages/rs-dpp/src/tests/fixtures/identity_fixture.rs

There was a TODO to create structs for the lengths and sizes of String and ByteArray DocumentPropertyTypes.
CI

refactor(dpp): change String and ByteArray DocumentPropertyType sizes to structs

---

packages/rs-drive-proof-verifier/src/lib.rs
packages/rs-drive-proof-verifier/src/proof.rs
packages/rs-drive-proof-verifier/src/provider.rs
packages/rs-drive/src/drive/verify/state_transition/verify_state_transition_was_executed_with_proof/v0/mod.rs
packages/rs-sdk/src/platform/transition/broadcast.rs
packages/rs-sdk/src/platform/transition/put_contract.rs
packages/rs-sdk/src/platform/transition/put_identity.rs
packages/rs-sdk/src/platform/transition/top_up_identity.rs
packages/rs-sdk/src/platform/transition/vote.rs
packages/rs-sdk/src/platform/transition/withdraw_from_identity.rs
packages/rs-sdk/src/sdk.rs

Instead of providing contract provider function, some state transition broadcast logic always returned `None` (meaning the contract was not found).
* Added trait ContractProvider automatically implemented for all ContextProvider objects that makes it easy to retrieve the contract lookup fn, as required by Drive
* Added method `sdk::context_provider()` 
* fixed existing logic
In TUI, sending masternode votes
None

fix(sdk): state transition broadcast missing contract provider

---

.github/package-filters/rs-packages.yml
.github/workflows/tests-rs-package.yml
Cargo.lock
Cargo.toml
packages/rs-dpp/Cargo.toml
packages/rs-dpp/src/data_contract/document_type/random_document.rs
packages/rs-dpp/src/data_contract/document_type/v0/random_document.rs
packages/rs-random-document/Cargo.toml
packages/rs-random-document/src/lib.rs

DPP shouldn't have any external dependencies since this is a public library that is supposed to be cross-platform and cross-environment.
- Extract document faker to a separate crate 
With existing tests. Added to CI
None

refactor: extract document faker to crate

---

.github/workflows/tests-build-image.yml
.github/workflows/tests-build-js.yml
.github/workflows/tests.yml

Docker images and `drive-abci` tests are run using ubuntu-platform-4x instances that are configured to use [c7gd.4xlarge](https://instances.vantage.sh/aws/ec2/c7gd.4xlarge) aws instances. Others use [c7gd.2xlarge](https://instances.vantage.sh/aws/ec2/c7gd.2xlarge).This causes the following issues:
* pipelines don't even start for multiple hours due to low availability of c7gd.4xlarge instances on the region we use,
* 4x costs are higher than 2x
As a workaround, we use `ubuntu-platform` (c7gd.2xlarge) for all types of jobs.
Run GHA pipelines.
None

build: use ubuntu-platform github runner hardware for all github actions

---

Cargo.lock
packages/dapi-grpc/Cargo.toml
packages/dashmate/configs/defaults/getBaseConfigFactory.js
packages/dashmate/configs/getConfigFileMigrationsFactory.js
packages/rs-drive-abci/Cargo.toml
packages/rs-drive-proof-verifier/Cargo.toml

Tenderdash 1.0.0 and rs-tenderdash-abci 1.0.0 is released 
* update rs-tenderdash-abci and tenderdash dependency to 1.0.0
* use `tag` to ensure correct version of tenderdash is fetched
* add migration
GHA
None

build: upgrade rs-tenderdash-abci to v1.0.0 and tenderdash to v1.0.0

---

Cargo.lock
packages/rs-sdk/Cargo.toml
packages/rs-sdk/src/mock/provider.rs
packages/rs-sdk/src/sdk.rs
packages/wasm-dpp/src/errors/consensus/consensus_error.rs

Two related issues fixed:
1. Tokio::block_on() panics in sync fn in async context:
```
thread 'main' panicked at 'Cannot start a runtime from within a runtime. This 
happens because a function (like `block_on`) attempted to block the current 
thread while the thread is being used to drive asynchronous tasks.'
```
2. Proof verification cannot fetch contracts
```
"proof: the contract could not be retrieved during verification: cannot get data contract: Proof verification error: context provider is not set"
```
This is caused because we have cyclical dependencies: Sdk uses GrpcContextProvider, and GrpcContextProvider uses Sdk.
Unfortunately, due to the way we initialize GrpcContextProvider, it uses an invalid, not complete copy of Sdk. This issue was introduced in #1838 . 
Issue 1: …

fix(sdk): panic GrpcContextProvider on async call inside sync code

---

Cargo.lock
packages/dapi-grpc/src/mock.rs
packages/dapi-grpc/src/mock/serde_mockable.rs
packages/rs-dapi-client/Cargo.toml
packages/rs-dapi-client/src/address_list.rs
packages/rs-dapi-client/src/connection_pool.rs
packages/rs-dapi-client/src/dapi_client.rs
packages/rs-dapi-client/src/dump.rs
packages/rs-dapi-client/src/lib.rs
packages/rs-dapi-client/src/mock.rs
packages/rs-dapi-client/src/transport.rs
packages/rs-dapi-client/src/transport/grpc.rs
packages/rs-dapi-client/tests/mock_dapi_client.rs
packages/rs-dapi-grpc-macros/src/lib.rs
packages/rs-sdk/src/error.rs
packages/rs-sdk/src/mock/sdk.rs
packages/rs-sdk/tests/fetch/contested_resource_polls_by_ts.rs

We are not able to run offline tests (without network connectivity, eg. errors) as we don't support serialization of errors.
Implemented Mockable for Result<T,E> and for DapiClientError. 
Locally, generated test vectors.
None

feat(sdk): support mocking of error responses

---

packages/rs-sdk/tests/fetch/contested_resource.rs
packages/rs-sdk/tests/fetch/contested_resource_vote_state.rs
packages/rs-sdk/tests/fetch/document.rs

The following tests fail, and we decided they will be fixed in separate PRs:
*    fetch::contested_resource::contested_resources_fields::exact_match_query_returns_one_object_plan_656
*    fetch::contested_resource::contested_resources_fields::start_at_value_wrong_index_type_returns_invalidargument_plan_653
*    fetch::contested_resource::contested_resources_limit_PLAN_656
*    fetch::contested_resource_vote_state::contested_resource_vote_states_with_limit_PLAN_674
*    fetch::document::document_list_bug_value_text_decode_base58_PLAN_653
Disabled tests with comment `disabled due to bug...`
GHA: https://github.com/dashpay/platform/actions/runs/9810199925
None

test(sdk): disable failing tests for bugs scheduled for future

---

packages/dapi/test/unit/externalApis/drive/fetchProofForStateTransitionFactory.spec.js

```
1) fetchProofForStateTransition
should fetch documents proofs:
TypeError: documentTransition.hasPrefundedBalance is not a function
at /home/runner/work/platform/platform/packages/dapi/lib/externalApis/drive/fetchProofForStateTransitionFactory.js:9:1016
at Array.map (<anonymous>)
at fetchProofForStateTransition (lib/externalApis/drive/fetchProofForStateTransitionFactory.js:9:553)
at Context.it (test/unit/externalApis/drive/fetchProofForStateTransitionFactory.spec.js:92:26)
```
- Added `hasPrefundedBalance` to the state transition mock
With tests
None

test: fix documentTransition.hasPrefundedBalance is not a function

---

packages/dashmate/src/createDIContainer.js
packages/dashmate/src/listr/tasks/setup/regular/configureNodeTaskFactory.js
packages/dashmate/src/listr/tasks/setup/regular/importCoreDataTaskFactory.js
packages/dashmate/src/listr/tasks/setup/setupRegularPresetTaskFactory.js

Currently, most evo masternode owners run an evo masternode using only Core. We need a convenient method to import existing data and configuration so they don't need to sync and configure the node from scratch.
- Added a step to import Core data to `dashmate setup` for already registered masternodes.
Running `dashmate setup` locally
None

feat(dashmate): import existing Core data

---

README.md

The CI badge link was broken
Updated it to use https://github.com/dashpay/platform/actions/workflows/tests.yml
Previewed README
None

docs: badge link for CI was broken in README.md

---

Cargo.lock
packages/rs-platform-version/Cargo.toml
packages/rs-platform-version/src/version/protocol_version.rs

Moved a structure to a small external library so it could be more easily shared with GroveDB.
No effective changes.

refactor: use library for feature version

---

packages/rs-dpp/src/block/extended_block_info/mod.rs
packages/rs-dpp/src/block/extended_block_info/v0/mod.rs
packages/rs-drive-abci/src/config.rs
packages/rs-drive-abci/src/execution/engine/finalize_block_proposal/v0/mod.rs
packages/rs-drive-abci/src/execution/engine/run_block_proposal/v0/mod.rs
packages/rs-drive-abci/src/execution/platform_events/block_end/validator_set_update/mod.rs
packages/rs-drive-abci/src/execution/platform_events/block_end/validator_set_update/v0/mod.rs
packages/rs-drive-abci/src/execution/storage/store_platform_state/v0/mod.rs
packages/rs-drive-abci/src/execution/validation/state_transition/state_transitions/data_contract_update/mod.rs
packages/rs-drive-abci/src/execution/validation/state_transition/state_transitions/documents_batch/data_triggers/triggers/dashpay/v0/mod.rs
packages/rs-drive-abci/src/execution/validation/state_transition/state_transitions/masternode_vote/mod.rs
packages/rs-drive-abci/src/execution/validation/state_transition/state_transitions/mod.rs
packages/rs-drive-abci/src/platform_types/platform_state/mod.rs
packages/rs-drive-abci/src/platform_types/platform_state/v0/mod.rs
packages/rs-drive-abci/tests/strategy_tests/chain_lock_update.rs
packages/rs-drive-abci/tests/strategy_tests/core_update_tests.rs
packages/rs-drive-abci/tests/strategy_tests/execution.rs
packages/rs-drive-abci/tests/strategy_tests/failures.rs
packages/rs-drive-abci/tests/strategy_tests/main.rs
packages/rs-drive-abci/tests/strategy_tests/query.rs
packages/rs-drive-abci/tests/strategy_tests/upgrade_fork_tests.rs
packages/rs-drive-abci/tests/strategy_tests/voting_tests.rs

In the past we would rotate every 15 or 25 blocks. This caused later members of a quorum to never be paid. Now instead we rotate when all quorum members have had a chance to propose a block.
Got rid of old rotation strategy and introduced a new one. When the last proposer of a quorum proposes we rotate. If that member did not propose a block we rotate as soon as possible.
I noticed some tests were very slow, so I made state saving optional, this reduced the time needed to finish strategy tests by over 50%.
Verified that unit tests all passed.
This is a breaking change.

feat(drive-abci)!: rotate quorums when all quorums members have had a chance to propose a block

---

packages/rs-dpp/src/document/document_factory/v0/mod.rs
packages/rs-dpp/src/document/errors.rs
packages/rs-dpp/src/document/specialized_document_factory/v0/mod.rs
packages/wasm-dpp/src/document/errors/mod.rs

`DocumentFactoryV0` and `SpecializedDocumentFactoryV0` were not allowing to create delete transitions if not `document_type.documents_mutable()`, but it should have been checking `document_type.documents_can_be_deleted()`.
Changed the check and wrote a test. Also renamed the error message about not being able to delete immutable documents.
Wrote a test for deleting immutable but deletable document types.

fix(dpp): document factory wouldn't allow delete transitions for immutable document types

---

packages/check-features/src/main.rs
packages/rs-drive/src/drive/credit_pools/epochs/has_epoch_tree_exists.rs
packages/rs-drive/src/util/test_helpers/setup.rs
packages/rs-drive/tests/deterministic_root_hash.rs
packages/rs-drive/tests/query_tests_history.rs

cargo test stopped working because of some issues in imports.
They are now fixed.

fix: import fix for drive refactoring

---

.github/actions/docker/action.yaml
.github/actions/local-network/action.yaml
.github/actions/rust/action.yaml
.github/workflows/release-docker-image.yml
.github/workflows/release.yml
.github/workflows/tests-build-image.yml
.github/workflows/tests-build-js.yml
.github/workflows/tests-codeql.yml
.github/workflows/tests-dashmate.yml
.github/workflows/tests-js-package.yml
.github/workflows/tests-packges-functional.yml
.github/workflows/tests-rs-package.yml
.github/workflows/tests-test-suite.yml
Dockerfile

We need to explicitly authenticate in AWS to use static self-hosted runners since they don't support roles (`role-to-assume`). 
- Updated AWS authentication actions
- Checked if `protoc` already installed (we have it on static runners)
Running CI
None

ci: explicitly authenticate AWS

---

packages/dashmate/configs/defaults/getBaseConfigFactory.js
packages/dashmate/configs/defaults/getLocalConfigFactory.js
packages/dashmate/configs/defaults/getTestnetConfigFactory.js
packages/dashmate/templates/core/dash.conf.dot

Since #1883 whitelists were disabled since Core 21 rc.1 didn't support them for complex commands. Core rc2 is released so we can enable whitelists.
- Enabled whitelists in dash.conf
- Changed `quorumplatformsign` to `quorumsign` since we do not support in in Tenderdash v1 yet
- Updated Core to v21.0.0-devpr6115.db828177 which is basically Core rc2
None
None

chore(dashmate): enable Core RPC whitelists

---

packages/rs-dpp/src/data_contract/document_type/class_methods/try_from_schema/v0/mod.rs
packages/rs-dpp/src/data_contract/document_type/property/mod.rs
packages/rs-dpp/src/data_contract/document_type/v0/random_document_type.rs
packages/rs-drive/src/query/conditions.rs

Previously we only had an integer type in the property type for a data contract, now that has been decomposed.
Switch integer to u128, i128, u64... u8, i8
Should not be a breaking change.

feat(dpp): decomposed integer types for document type properties

---

packages/dapi-grpc/clients/platform/v0/objective-c/Platform.pbobjc.h
packages/dashmate/src/core/activateCoreSpork.js
packages/dashmate/src/listr/tasks/setup/local/configureCoreTaskFactory.js
packages/dashmate/src/listr/tasks/setup/local/configureTenderdashTaskFactory.js
packages/rs-drive-abci/src/error/execution.rs
packages/rs-drive-abci/src/execution/engine/initialization/init_chain/v0/mod.rs
packages/rs-drive-abci/src/execution/platform_events/initialization/initial_core_height/mod.rs
packages/rs-drive-abci/src/execution/platform_events/initialization/initial_core_height/v0/mod.rs
packages/rs-drive-abci/src/execution/validation/state_transition/state_transitions/documents_batch/mod.rs

Drive is using v20 fork to activate Platform but must be `mn_rr` (EHF).
Dashmate is using initial core chain locked height. We want to use EHF fork to use fork activation.
- Used `mn_rr` instead of `v20` in Drive
- Activate EHF spork in dashmate and remove initial core chain locked height
Running local network
None

chore: activate platform on EHF fork

---

packages/rs-drive-abci/src/platform_types/platform_state/mod.rs
packages/rs-drive-abci/src/platform_types/platform_state/v0/mod.rs

Using the private bound `PlatformStateV0PrivateMethods` for public the `PlatformStateV0Methods` trait is a bad idea. Not sure how it even compiles.
- Removed the `PlatformStateV0PrivateMethods` bound from the `PlatformStateV0Methods` trait 
Compile the project
None

refactor(drive): don't use private bound for public trait

---

packages/rs-drive-abci/.env.local
packages/rs-drive-abci/.env.mainnet
packages/rs-drive-abci/.env.testnet
packages/rs-drive-abci/src/config.rs

Not a good idea to use services that bind to `0.0.0.0` by default
- Set `127.0.0.1` as a default interface for drive services
None
Default bind interface for gRPC, tokio console, grovedb visualiser and others changed to `127.0.0.1`

chore(drive)!: don't use `0.0.0.0` as default listen IP

---

packages/rs-drive-abci/src/execution/engine/initialization/init_chain/v0/mod.rs

Drive and Tenderdash containers are constantly restarting until MN_RR will be activated (hours on devnet, weeks on mainnet)
- Check for initial core height in a loop every 30 seconds until we get a deterministic height.
None
None

fix(drive): drive and tenderdash are constantly restarting

---

packages/dashmate/configs/defaults/getBaseConfigFactory.js
packages/dashmate/configs/getConfigFileMigrationsFactory.js
packages/dashmate/src/config/configJsonSchema.js
packages/dashmate/src/listr/prompts/createPlatformNodeKeyInput.js
packages/dashmate/templates/core/dash.conf.dot

We need to start a big devnet to test platform that will use bigger quorums. We should be able to configure them.
- Added `core.devnet.llmq` configuration option
- Add config migration
- Small fix for node configuration
None
None

fix(dashmate): configure devnet quorums

---

packages/strategy-tests/src/transitions.rs

If extra keys were defined for identities being created in a strategy, the key ids were not being calculated correctly when inputting them into the signer in the case where there was more than one identity per block.
Fixed the calculation.
TUI strategy tests

fix(strategy-tests): key ids for new identities with extra keys were not calculated properly

---

packages/dapi/lib/MasternodeListSync.js
packages/js-dapi-client/lib/SimplifiedMasternodeListProvider/SimplifiedMasternodeListProvider.js

Can't parse masternode list diff due to wrong serialize and deserialise logic in JS dashcore-lib
- Use CBOR instead as a temporary workaround 
With CI
None

fix(dapi): can't parse masternode list diff

---

packages/js-dapi-client/lib/DAPIClient.js
packages/js-dapi-client/lib/SimplifiedMasternodeListProvider/createMasternodeListStreamFactory.js

We want to see why subscribe to masternode list stream is reconnecting all the time
- Enable logging in reconnectable stream
Locally, running test suite
None

chore(dapi): enable logger for reconnectable stream

---

packages/rs-drive/src/drive/asset_lock/estimation_costs/add_estimation_costs_for_adding_asset_lock/v0/mod.rs
packages/rs-drive/src/drive/system/estimation_costs/for_total_system_credits_update/v0/mod.rs

Small update to estimated fees of spent asset locks, and misc total credits in system

fix: spent asset lock estimated fees, and misc

---

packages/rs-drive-abci/src/main.rs
packages/rs-drive/src/config.rs

We shouldn't verify grovedb on every start since verification could take a long time on big database
- Added a flag in `DriveConfig` which enables/disables grovedb verification on startup. 
- This flag will be disabled by default.
None
None 

feat(drive): added config for grovedb verify on startup

---

packages/strategy-tests/src/transitions.rs

When we did IdentityUpdate(DisableKeys) transitions in strategies, we were sometimes disabling transfer keys, but we don't want to do that.
Prevent IdentityUpdate(DisableKeys) transitions from disabling transfer keys in strategy tests
TUI

fix(strategy-tests): transfer keys were being disabled

---

packages/rs-drive-abci/src/error/execution.rs
packages/rs-drive-abci/src/execution/engine/initialization/init_chain/v0/mod.rs
packages/rs-drive-abci/src/execution/platform_events/initialization/initial_core_height/v0/mod.rs

```
2024-07-23T18:58:32.717312Z DEBUG dashcore_rpc: JSON-RPC request: protx ["listdiff",1,5400]
at /root/.cargo/git/checkouts/rust-dashcore-rpc-474497c1dcebe04a/9e59614/client/src/client.rs:1646 on main ThreadId(1)
in tenderdash_abci::tracing_span::abci with endpoint: "InitChain", request_id: "e994bea4-b338-47b3-91cb-2721b3553294"
2024-07-23T18:58:32.717754Z DEBUG dashcore_rpc: JSON-RPC error for protx: RpcError { code: -1, message: "block must be a chain height and not 5400", data: None }
at /root/.cargo/git/checkouts/rust-dashcore-rpc-474497c1dcebe04a/9e59614/client/src/client.rs:1666 on main ThreadId(1)
in tenderdash_abci::tracing_span::abci with endpoint: "InitChain", request_id: "e994bea4-b338-47b3-91cb-2721b3553294"
```
It means the fork is active but Core doesn't have blocks for …

fix(drive): unknown mn_rr fork height

---

packages/rs-dpp/src/document/document_methods/is_equal_ignoring_timestamps/v0/mod.rs
packages/rs-dpp/src/document/document_methods/mod.rs
packages/rs-dpp/src/document/mod.rs
packages/rs-drive-abci/src/execution/validation/state_transition/state_transitions/documents_batch/mod.rs
packages/rs-drive/src/verify/state_transition/verify_state_transition_was_executed_with_proof/v0/mod.rs

We forgot to update sdk to ignore transient fields on proof verification.
Ran this afterwards in TUI and it fixed the issue.

fix: sdk should ignore transient fields when verifying proofs

---

packages/js-dash-sdk/docs/platform/names/register.md
packages/js-dash-sdk/docs/platform/names/resolveByRecord.md
packages/js-dash-sdk/src/SDK/Client/Platform/methods/names/register.spec.ts
packages/js-dash-sdk/src/SDK/Client/Platform/methods/names/register.ts
packages/js-dash-sdk/src/SDK/Client/Platform/methods/names/resolveByRecord.ts

DPNS was having an issue in the JS SDK, this should fix it.

fix: dpns js sdk fix for identity record rename

---

packages/strategy-tests/src/lib.rs

Document delete transitions were using identity callback function to get the identity for signing, which was overcomplicated for the current purposes. That method is the way to do it if we're trying to delete documents that already exist, but for now, we're just deleting documents that were also created in the current strategy. In the future, I guess it would be better to have it done the original way but for now, this is simpler.
Just get the identity from the current_identities
This means you can only delete documents that were created in the current strategy, but it's good enough for a first implementation. No other aspects of strategy tests in TUI really are compatible with previous strategy tests anyways.
TUI

fix(strategy-tests): document delete transitions were selecting identity in complicated way

---

Cargo.lock
packages/dapi-grpc/Cargo.toml
packages/dashmate/configs/defaults/getBaseConfigFactory.js
packages/dashmate/configs/getConfigFileMigrationsFactory.js
packages/rs-drive-abci/Cargo.toml
packages/rs-drive-abci/src/execution/engine/initialization/init_chain/v0/mod.rs
packages/rs-drive-proof-verifier/Cargo.toml

Updated Tenderdash dependency to 1.1, which allows setting GenesisTime  in InitChain response
Updated deps
* GHA green
* local devnet test with hardcoded timestamp in drive-abci sources generates block at height 1 containing that timestamp
None

build: update to tenderdash 1.1.0-dev.3, rs-tenderdash-abci 1.1.0-dev.1

---

packages/rs-drive-abci/src/execution/platform_events/core_based_updates/update_masternode_list/v0/mod.rs

Some masternode update information would be lost between init chain and the first block. This fixes this.
Removed a check that was no longer valid.
Tests still pass
None

fix(platform): core info is lost between genesis and first block

---

packages/rs-dpp/src/state_transition/mod.rs
packages/rs-drive-abci/src/execution/platform_events/state_transition_processing/process_raw_state_transitions/v0/mod.rs

The name() function for state transitions only returned "DocumentsBatch" but it would be nice if it was more specific.
Instead of just "DocumentsBatch" it's now "DocumentsBatch([vector_of_transition_names])". For example "DocumentsBatch(["Create", "Create", "Delete", "UpdatePrice"])".
TUI

feat: specify transition names within documents batch

---

Cargo.lock
packages/dashmate/configs/defaults/getBaseConfigFactory.js
packages/dashmate/configs/defaults/getTestnetConfigFactory.js
packages/dashmate/configs/getConfigFileMigrationsFactory.js
packages/dashmate/src/listr/tasks/setup/local/configureTenderdashTaskFactory.js
packages/rs-drive-abci/src/error/execution.rs
packages/rs-drive-abci/src/execution/engine/initialization/init_chain/v0/mod.rs
packages/rs-drive-abci/src/execution/platform_events/initialization/initial_core_height/mod.rs
packages/rs-drive-abci/src/execution/platform_events/initialization/initial_core_height/v0/mod.rs
packages/rs-drive-abci/src/rpc/core.rs
packages/rs-drive-abci/tests/strategy_tests/execution.rs
packages/rs-drive-abci/tests/strategy_tests/main.rs
packages/rs-platform-version/src/version/drive_abci_versions.rs
packages/rs-platform-version/src/version/mocks/v2_test.rs
packages/rs-platform-version/src/version/mocks/v3_test.rs
packages/rs-platform-version/src/version/v1.rs

fix(platform)!: genesis state from core block time

---

packages/rs-drive-proof-verifier/src/proof.rs
packages/rs-sdk/Cargo.toml
packages/rs-sdk/README.md
packages/rs-sdk/examples/read_contract.rs
packages/rs-sdk/src/error.rs
packages/rs-sdk/src/mock/provider.rs
packages/rs-sdk/src/mock/sdk.rs
packages/rs-sdk/src/platform/block_info_from_metadata.rs
packages/rs-sdk/src/platform/delegate.rs
packages/rs-sdk/src/platform/document_query.rs
packages/rs-sdk/src/platform/fetch.rs
packages/rs-sdk/src/platform/fetch_many.rs
packages/rs-sdk/src/platform/query.rs
packages/rs-sdk/src/platform/transition/broadcast_identity.rs
packages/rs-sdk/src/platform/transition/broadcast_request.rs
packages/rs-sdk/src/platform/types/epoch.rs
packages/rs-sdk/src/platform/types/version_votes.rs
packages/rs-sdk/src/sdk.rs
packages/rs-sdk/tests/fetch/config.rs
packages/rs-sdk/tests/fetch/epoch.rs

Clients might want to actually see the proof.
In this PR we add a method to give back proofs to clients if they are requested. Clients can then print out the proof to help developers debug.
Not breaking.

feat: sdk to return proofs if requested

---

packages/dashmate/src/listr/tasks/setup/regular/registerMasternode/registerMasternodeWithCoreWallet.js

`dashmate setup` command for new masternodes displays an instructions to register it in the network. This is usually done from the Dash Core GUI wallet and `dash-cli` prefix is obsolete, as well as slashes.
Roved dash-cli and slashes from the `dashmate setup`
Locally
No

fix(dashmate): remove `dash-cli` from protx registration instructions

---

.github/workflows/release.yml
packages/dashmate/configs/defaults/getBaseConfigFactory.js
packages/dashmate/configs/defaults/getLocalConfigFactory.js
packages/dashmate/configs/defaults/getMainnetConfigFactory.js
packages/dashmate/configs/defaults/getTestnetConfigFactory.js
packages/dashmate/configs/getConfigFileMigrationsFactory.js
packages/dashmate/src/listr/tasks/setup/setupRegularPresetTaskFactory.js

We need to update mainnet settings for v1 release
- Updated config for mainnet
- Enabled platform for mainnet
- Removed migrations
None
None

chore(dashmate): configure mainnet

---

packages/dashmate/src/commands/reset.js
packages/dashmate/src/docker/DockerCompose.js
packages/dashmate/src/listr/tasks/resetNodeTaskFactory.js

We should be able to reset node but keep docker volumes so we don't need to resync Core or Platform again.
This is useful during dashmate upgrade when existing dashmate had outdated docker containers.
Also haveing this you can sync a fullnode and then convert it to masternode.
- Added `--keep-data` flag to keep docker containers to the reset command
Locally
None

feat(dashmate): a flag to keep data on reset

---

Cargo.lock
packages/dashmate/configs/defaults/getBaseConfigFactory.js
packages/dashmate/configs/defaults/getMainnetConfigFactory.js
packages/dashmate/configs/getConfigFileMigrationsFactory.js
packages/dashmate/src/config/configJsonSchema.js
packages/dashmate/src/listr/tasks/setup/regular/importCoreDataTaskFactory.js
packages/dashmate/src/listr/tasks/setup/setupLocalPresetTaskFactory.js
packages/dashmate/templates/core/dash.conf.dot
packages/rs-drive-abci/Cargo.toml
packages/rs-sdk/Cargo.toml
packages/simple-signer/Cargo.toml

Local and testnet nodes enable unnecessary Core indexes.
Importing existing Core data requires unnecessary Core indexes.
We also should be able to specify particular indexes to enable.
- Changed `core.indexes` to accept array of required Core indexes
- Import Core Data requires only txindex or being a masternode
- Fixed migration on dapi and drive images
- Set dapi and drive images version to major
Locally
None

fix(dashmate): unnecessary core indexes are required

---

packages/dashmate/README.md
packages/dashmate/src/commands/status/platform.js
packages/dashmate/src/status/colors.js
packages/dashmate/src/status/determineStatus.js
packages/dashmate/src/status/enums/serviceStatus.js
packages/dashmate/src/status/scopes/platform.js
packages/dashmate/test/unit/status/scopes/platform.spec.js

Tenderdash RPC is only available after a platform activation, which will happen in 3 weeks from now. Since TD RPC is used to perform healthcheck on the service, we need to an additional check for softfork activation for the mainnet network configs.
Added a `getblockchaininfo` core rpc request in the `status platform` command
It will only query tenderdash if the mn_rr softfork is already active. 
An additional status line about platform activation time was also added.
Locally
No

fix(dashmate): status command shows tenderdash error before activation

---

packages/rs-drive-abci/src/abci/app/execution_result.rs
packages/rs-drive-abci/src/abci/config.rs
packages/rs-drive-abci/src/abci/handler/prepare_proposal.rs
packages/rs-drive-abci/src/abci/handler/process_proposal.rs
packages/rs-drive-abci/src/execution/check_tx/v0/mod.rs
packages/rs-drive-abci/src/execution/engine/run_block_proposal/mod.rs
packages/rs-drive-abci/src/execution/engine/run_block_proposal/v0/mod.rs
packages/rs-drive-abci/src/execution/platform_events/state_transition_processing/process_raw_state_transitions/mod.rs
packages/rs-drive-abci/src/execution/platform_events/state_transition_processing/process_raw_state_transitions/v0/mod.rs
packages/rs-drive-abci/src/execution/validation/state_transition/state_transitions/data_contract_create/mod.rs
packages/rs-drive-abci/src/execution/validation/state_transition/state_transitions/data_contract_update/mod.rs
packages/rs-drive-abci/src/execution/validation/state_transition/state_transitions/documents_batch/mod.rs
packages/rs-drive-abci/src/execution/validation/state_transition/state_transitions/identity_create/mod.rs
packages/rs-drive-abci/src/execution/validation/state_transition/state_transitions/identity_credit_withdrawal/mod.rs
packages/rs-drive-abci/src/execution/validation/state_transition/state_transitions/identity_top_up/mod.rs
packages/rs-drive-abci/src/execution/validation/state_transition/state_transitions/mod.rs
packages/rs-drive-abci/src/platform_types/state_transitions_processing_result/mod.rs
packages/rs-drive/src/drive/initialization/genesis_core_height/mod.rs

- When a node is preparing a block proposal, it will skip and mark as not executed remaining state transitions txs when a time limit is reached.
- Added in Abci config the value of the limit with a default value of 8 seconds. 

feat(drive-abci): skip state transition txs if time limit is reached on prepare_proposal

---

packages/dashmate/src/templates/renderServiceTemplatesFactory.js
packages/dashmate/src/templates/renderTemplateFactory.js

Reindex command is not working properly in the dashmate, it breaks the whole dash config by trimming \n characters. As a result, node begins to sync mainnet with all default options.
This PR fixes `dashmate core reindex` command
Moved `dots.templateSettings.strip = false` from renderServiceTemplatesFactory to renderTemplateFactory
Locally
No

fix(dashmate): core reindex command not working

---

packages/rs-sdk/src/sdk.rs

Calling `request.execute(&&Sdk)` causes overflow error.
Removed affected code.
Now, the compiler will show error when trying to use double-ref.
GHA
Use of double-ref to `Sdk` in `DapiRequestExecutor::execute()` is not possible anymore.
You must deref or clone `Sdk`.

fix(sdk)!: overflow when using &&sdk in DapiRequestExecutor

---

Cargo.lock
packages/rs-drive-abci/src/execution/platform_events/initialization/create_genesis_state/v0/mod.rs
packages/rs-drive-abci/tests/strategy_tests/main.rs
packages/rs-drive-abci/tests/strategy_tests/strategy.rs
packages/rs-drive/Cargo.toml
packages/rs-drive/src/query/mod.rs
packages/rs-platform-version/Cargo.toml

We were experiencing a few issues with an empty string being present as a tree in the domain table, this caused the contract based translation of the drive document queries to path queries to go a bit haywire which led to the result that an item that was expected would not be inserted due to a limit going down by 1 because of an empty tree.
Fixed the dash tld.
Not very well tested, however this is most likely the issue. I checked a strategy test to make sure things worked well after this change, however since the original issue was very hard to reproduce, we will only really be able to see if the fix works when it goes to Testnet.
This fix is a breaking change.

fix(drive-abci)!: fix wrong fields in dash top level domain 

---

packages/dashmate/docker-compose.build.base.yml
packages/dashmate/docker-compose.build.dapi_api.yml
packages/dashmate/docker-compose.build.dapi_core_streams.yml
packages/dashmate/docker-compose.build.dashmate_helper.yml
packages/dashmate/docker-compose.build.drive_abci.yml
packages/dashmate/docker-compose.insight_api.yml
packages/dashmate/docker-compose.insight_ui.yml
packages/dashmate/docker-compose.rate_limiter.metrics.yml
packages/dashmate/docker-compose.rate_limiter.yml
packages/dashmate/docker-compose.yml
packages/dashmate/templates/dynamic-compose.yml.dot

When running the Platform, we can see warning `docker-compose version is obsolete`
Replaced `version` in docker-compose files with `---` which is a start sequence for yaml files.
GHA
None

fix(dashmate): docker-compose version is obsolete

---

.github/actions/rust/action.yaml
Cargo.toml
Dockerfile
README.md
packages/dapi-grpc/Cargo.toml
packages/dashpay-contract/Cargo.toml
packages/data-contracts/Cargo.toml
packages/dpns-contract/Cargo.toml
packages/feature-flags-contract/Cargo.toml
packages/masternode-reward-shares-contract/Cargo.toml
packages/rs-dpp/Cargo.toml
packages/rs-drive-abci/Cargo.toml
packages/rs-drive-proof-verifier/Cargo.toml
packages/rs-drive-verify-c-binding/Cargo.toml
packages/rs-drive/Cargo.toml
packages/rs-json-schema-compatibility-validator/Cargo.toml
packages/rs-platform-serialization-derive/Cargo.toml
packages/rs-platform-serialization/Cargo.toml
packages/rs-platform-value-convertible/Cargo.toml
packages/rs-platform-value/Cargo.toml
packages/rs-platform-version/Cargo.toml
packages/rs-platform-versioning/Cargo.toml
packages/simple-signer/Cargo.toml
packages/strategy-tests/Cargo.toml
packages/wasm-dpp/Cargo.toml
packages/withdrawals-contract/Cargo.toml
rust-toolchain.toml
scripts/update_rust_version.sh

1. Updated Rust to most recent stable version (1.80).
2. Crates inherit package-level rust version.
3. Added `scripts/update_rust_version.sh` script to quickly update rust version.
4. Dockerfile and github pipelines detect rust version automatically, based on rust-toolchain.toml file
Github Actions workflow must pass.
None

build: update rust to 1.80

---

packages/dashmate/src/listr/tasks/setup/regular/configureSSLCertificateTaskFactory.js

It appeared as a common problem that people do not include server certificates in certificate chain file
- Added explanation to include server certificate in certificate chain file
- Validate that certificate chain file corresponds to private key 
Passing valid and invalid cert files to `dashmate setup`.
None

feat(dashmate): validate SSL certificate files

---

packages/dapi-grpc/protos/platform/v0/platform.proto
packages/rs-drive-abci/src/query/identity_based_queries/balances/v0/mod.rs
packages/rs-drive-proof-verifier/src/proof.rs
packages/rs-sdk/src/platform/types/identity.rs

The previous API requires to pass a double structured list, this PR simplifies things.
Changed the API to make it more friendly.
Not breaking compared to previous version.

style(dapi): better api for identities balances

---

packages/rs-drive-abci/src/execution/engine/run_block_proposal/v0/mod.rs
packages/rs-drive-abci/src/execution/platform_events/block_fee_processing/add_process_epoch_change_operations/v0/mod.rs
packages/rs-drive-abci/src/execution/platform_events/block_fee_processing/process_block_fees/v0/mod.rs
packages/rs-drive-abci/src/execution/platform_events/protocol_upgrade/check_for_desired_protocol_upgrade/v0/mod.rs
packages/rs-drive-abci/src/execution/platform_events/protocol_upgrade/upgrade_protocol_version/v0/mod.rs
packages/rs-drive-abci/src/execution/types/block_execution_context/mod.rs
packages/rs-drive-abci/src/execution/types/block_execution_context/v0/mod.rs
packages/rs-drive-abci/src/execution/validation/state_transition/state_transitions/mod.rs
packages/rs-drive-abci/src/platform_types/platform_state/mod.rs
packages/rs-drive-abci/src/platform_types/platform_state/v0/mod.rs
packages/rs-drive-abci/src/test/helpers/fast_forward_to_block.rs

fix(drive-abci): require 75 percent of active, not total hpmns

---

packages/dashmate/docker-compose.insight_api.yml
packages/dashmate/docker-compose.insight_ui.yml
packages/dashmate/docker-compose.rate_limiter.metrics.yml
packages/dashmate/docker-compose.rate_limiter.yml
packages/dashmate/docker-compose.yml

Dashmate docker logs grows infinitely and could lead to a node downtime due to lack of disk space. 
- Configured log compression and rotation for dashmate docker services
- Switch to more efficient in our case the "local" logging driver. 
None
Previously, dashmate docker services write json file logs on disk using the `json-file` driver. Not it uses more efficient internal binary format for logs. This will affect you only if you work directly with log files. The `docker logs`  works as before.

chore(dashmate)!: docker logs rotation

---

packages/js-dash-sdk/README.md
packages/wallet-lib/README.md

Since this SDK doesn't support proofs we need a warning to make sure that is obvious
Replaces #2106 which couldn't complete CI
Add warning to top of README
N/A
N/A

docs: add warning about js-sdk security

---

packages/dashmate/configs/defaults/getBaseConfigFactory.js
packages/dashmate/configs/getConfigFileMigrationsFactory.js

We need to text next release candidate image of Tenderdash, tagged `dashpay/tenderdash:fix-wrong-proposer-at-round`, on testnet
Updated  dashmate configs
Not tested
New image introduces new proposer selection algorithm, to be activated by Drive.
Before activation, it will behave as previously.

build(dashmate): update tenderdash image to fix-wrong-proposer-at-round

---

packages/rs-drive-abci/src/execution/platform_events/protocol_upgrade/check_for_desired_protocol_upgrade/v0/mod.rs
packages/rs-drive-abci/tests/strategy_tests/upgrade_fork_tests.rs

A few tests were broken just because they hadn't been properly updated, now they are fixed.

fix(tests): fix upgrade tests because of 51% limit on v1

---

packages/js-dapi-client/lib/DAPIClient.js
packages/js-dapi-client/lib/networkConfigs.js
packages/js-dapi-client/test/unit/DAPIClient.spec.js

JS DAPI Client connects to testnet by default
- Connect to mainnet by default.
- Configure seeds for mainnet
None
DAPI client connected to testnet by default previously. Now it connects to mainnet.

chore(dapi)!: connect to mainnet by default

---

.github/workflows/release.yml

We are attempting to build on MacOS 14 as 12 is outdated and occasionally hangs when doing a release
Changed GitHub actions to use MacOS 14 instead of 12
Has not, will be tested during a dev release
None

ci: fix releasing dashmate package for macos

---

packages/dashmate/src/docker/DockerCompose.js
packages/dashmate/src/listr/tasks/doctor/collectSamplesTaskFactory.js

The dashmate doctor command fails to collect big logs (> 900 MB). I am not sure if it's a good idea to send more than 100 MB logs per service. In this case, a sample archive file will be too big and inconvenient to send.
- Limitted collected service log to 300,000 lines (approximately 100 MB of text).
Running doctor locally
None

fix(dashmate): doctor fails collecting to big logs

---

packages/dapi/lib/externalApis/tenderdash/BlockchainListener.js
packages/dapi/lib/grpcServer/handlers/platform/getStatusHandlerFactory.js
packages/dapi/test/integration/externalApis/tenderdash/BlockchainListener.spec.js
packages/dashmate/src/docker/DockerCompose.js
packages/dashmate/src/doctor/analyse/analyseConfigFactory.js
packages/dashmate/src/listr/tasks/doctor/collectSamplesTaskFactory.js
packages/dashmate/src/listr/tasks/ssl/zerossl/obtainZeroSSLCertificateTaskFactory.js
packages/dashmate/src/ssl/zerossl/validateZeroSslCertificateFactory.js
packages/dashmate/src/status/providers.js
packages/dashmate/src/update/updateNodeFactory.js
packages/dashmate/test/e2e/testnetFullnode.spec.js
packages/js-dapi-client/lib/networkConfigs.js

Backport fixes from 1.4 to 1.3 to release a patch version 1.3.1
- Backported multiple fixes without breaking changes
None
None

chore: 1.4 backports (not squash)

---

packages/rs-drive-abci/src/execution/platform_events/voting/remove_votes_for_removed_masternodes/mod.rs
packages/rs-drive-abci/src/execution/platform_events/voting/remove_votes_for_removed_masternodes/v0/mod.rs
packages/rs-drive-abci/src/execution/platform_events/voting/run_dao_platform_events/v0/mod.rs
packages/rs-drive-abci/src/execution/validation/state_transition/state_transitions/masternode_vote/mod.rs
packages/rs-drive/src/drive/votes/cleanup/remove_all_votes_given_by_identities/mod.rs
packages/rs-drive/src/drive/votes/cleanup/remove_all_votes_given_by_identities/v0/mod.rs

We had a sequence of errors on the mainnet started since block 32326. We got RocksDB's "transaction is busy" error because we removed votes without using a database transaction. Due to another bug in Tenderdash (https://github.com/dashpay/tenderdash/pull/966), validators just proceeded to the next block partially committing the state and updating the cache. Full nodes are stuck and proceeded after re-sync.
- Remove votes using database transaction
Syncing testnet and mainnet
None

fix(drive): apply batch is not using transaction in `remove_all_votes_given_by_identities`

---

packages/rs-drive-abci/tests/strategy_tests/main.rs
packages/rs-drive-abci/tests/strategy_tests/strategy.rs
packages/rs-drive-abci/tests/strategy_tests/voting_tests.rs
packages/strategy-tests/src/lib.rs
packages/strategy-tests/src/operations.rs
packages/strategy-tests/src/transitions.rs

Original PR can be found here: https://github.com/dashpay/platform/pull/2312

feat: hardcoded identity transfers in strategy tests

---

.github/workflows/release-docker-image.yml
.github/workflows/release.yml

actions/upload-artifact@v3 is deprecated
replaced with actions/upload-artifact@v4
GHA
None

ci: replace actions/upload-artifact@v3 with actions/upload-artifact@v4

---

Dockerfile

In #2318, we compile librocksdb with CPU optimizations that require Haswell CPU instruction set. 
Unfortunately, some users use older CPUs like Ivy Bridge.
Build librocksdb on docker in `PORTALBLE=1` mode.
Local user-mode qemu instance, using `Nehalem` cpu.
* reproduced issue with drive 1.6.1
* tested with image dashpay/drive:1.6.2-pr.2363.1 - issue cannot be reproduced anymore
None

build: enable drive image for Ivy Bridge CPU

---

packages/rs-dpp/src/state_transition/state_transitions/document/batch_transition/batched_transition/token_transition.rs
packages/rs-dpp/src/tokens/token_event.rs
packages/rs-drive-abci/tests/strategy_tests/verify_state_transitions.rs
packages/rs-drive/src/drive/tokens/add_transaction_history_operations/v0/mod.rs
packages/rs-drive/src/state_transition_action/batch/batched_transition/token_transition/mod.rs
packages/rs-drive/src/verify/state_transition/verify_state_transition_was_executed_with_proof/v0/mod.rs
packages/wasm-dpp/src/document/state_transition/batch_transition/token_transition/mod.rs

Historical documents for token events were using the same document ids based on the token history contract, and identity contract nonce for the token contract, but this meant that if a user would send token A, then send token B the second transaction would use the same document id to try to store info on the transaction.
Historical document id now looks like:
`    fn historical_document_id(&self, owner_id: Identifier) -> Identifier {
let token_id = self.token_id();
let name = self.historical_document_type_name();
let owner_nonce = self.identity_contract_nonce();
Document::generate_document_id_v0(
&token_id,
&owner_id,
format!("history_{}", name).as_str(),
owner_nonce.to_be_bytes().as_slice(),
)
}`
Not tested, but tests still pass.
Breaking, (but previous was failing). It's shouldn't be …

fix(platform): unique token keeps history documents

---

packages/rs-dpp/src/data_contract/associated_token/token_perpetual_distribution/distribution_function/evaluate.rs
packages/rs-dpp/src/data_contract/associated_token/token_perpetual_distribution/distribution_function/mod.rs
packages/rs-dpp/src/data_contract/associated_token/token_perpetual_distribution/distribution_function/validation.rs
packages/rs-dpp/src/errors/consensus/basic/data_contract/invalid_token_distribution_function_incoherence_error.rs
packages/rs-drive-abci/src/execution/validation/state_transition/state_transitions/batch/tests/token/distribution/perpetual/block_based.rs
packages/rs-platform-version/src/version/v9.rs

Added inverted log distribution tests and made minor fixes and performance improvements.
None

test(platform): distribution inverted log tests

---

packages/keyword-search-contract/schema/v1/keyword-search-contract-documents.json
packages/rs-drive-abci/src/execution/platform_events/initialization/create_genesis_state/test/tokens.rs
packages/rs-drive-abci/src/execution/validation/state_transition/state_transitions/data_contract_create/basic_structure/v0/mod.rs
packages/rs-drive-abci/src/execution/validation/state_transition/state_transitions/data_contract_update/mod.rs
packages/rs-drive-abci/src/execution/validation/state_transition/state_transitions/mod.rs
packages/rs-drive/src/drive/contract/insert/add_description/mod.rs
packages/rs-drive/src/drive/contract/insert/add_description/v0/mod.rs
packages/rs-drive/src/drive/contract/insert/add_new_keywords/mod.rs
packages/rs-drive/src/drive/contract/insert/add_new_keywords/v0/mod.rs
packages/rs-drive/src/drive/contract/update/mod.rs
packages/rs-drive/src/drive/contract/update/update_contract/v1/mod.rs
packages/rs-drive/src/drive/contract/update/update_description/mod.rs
packages/rs-drive/src/drive/contract/update/update_description/v0/mod.rs
packages/rs-drive/src/drive/contract/update/update_keywords/mod.rs
packages/rs-drive/src/drive/contract/update/update_keywords/v0/mod.rs
packages/rs-drive/src/drive/document/delete/delete_document_for_contract_operations/mod.rs
packages/rs-drive/src/drive/document/delete/delete_document_for_contract_operations/v0/mod.rs
packages/rs-platform-version/src/version/drive_versions/drive_contract_method_versions/mod.rs
packages/rs-platform-version/src/version/drive_versions/drive_contract_method_versions/v1.rs
packages/rs-platform-version/src/version/drive_versions/drive_contract_method_versions/v2.rs

fix(platform): sam's fixes for token search

---

Cargo.lock
packages/rs-dpp/src/data_contract/associated_token/token_perpetual_distribution/distribution_function/evaluate.rs
packages/rs-dpp/src/data_contract/associated_token/token_perpetual_distribution/distribution_function/mod.rs
packages/rs-dpp/src/data_contract/associated_token/token_perpetual_distribution/distribution_function/validation.rs
packages/rs-drive-abci/Cargo.toml
packages/rs-drive-abci/src/execution/validation/state_transition/state_transitions/batch/tests/token/distribution/perpetual/block_based.rs
packages/rs-drive-abci/src/execution/validation/state_transition/state_transitions/batch/tests/token/distribution/perpetual/time_based.rs
packages/rs-drive-abci/src/logging/logger.rs
packages/rs-drive-abci/src/logging/mod.rs

Added exponential and polynomial distribution tests and made minor fixes and performance improvements.
None

test(platform): tests for exp and polynomial distributions

---

.gitignore

This update adds the `.gitaipconfig` file to the `.gitignore` list to prevent it from being tracked by Git.
- Added `.gitaipconfig` to the `.gitignore` file to ensure it is not included in version control.
No specific tests are required for this change as it only affects the `.gitignore` file.
None

chore: add .gitaipconfig to .gitignore

---

package.json

The package `token-search-contract` was renamed to `keyword-search-contract` to better reflect its functionality and improve clarity.
The `token-search-contract` package in the `package.json` file has been renamed to `keyword-search-contract`. This change aims to provide a more descriptive name that aligns with the package's purpose.
The change was tested by ensuring that all references to the package name within the codebase were updated accordingly, and the application was run to verify that it functions as expected without any issues.
None

refactor: rename token-search-contract to keyword-search-contract

---

CLAUDE.md

Added documentation to provide guidance for developers working with the code repository.
Created a new file `CLAUDE.md` that includes commands for build and development, testing, Rust development, and an overview of the architecture and technology stack.
N/A
None

docs: add CLAUDE.md for development guidance

---

.pnp.cjs
package.json
packages/wasm-drive-verify/Cargo.toml
packages/wasm-drive-verify/build.sh
packages/wasm-drive-verify/package.json
yarn.lock

This PR contains a fix for a build process that results in an unoptimized js package
Current size of build: 3 Mb
- Fixed Сargo.toml, because build profiles outside the parent Cargo.toml in workspace are not taken into account during build. Profile has also been slightly modified
- Fixed build script. Added wasm-opt, wasm-snip and also updated to set individual profile parameters for build.
- Fixed package.json. Before this PR package.json was generated when building from sh script, which is maximum not convenient and wrong. Now the root package.json for a module is the only and the main one for everything  
build by `yarn build` and then test in this [project](https://github.com/owl352/bls-verify)

feat(sdk): wasm drive verify optimization
